Repository googleforgames/agones, pull requests merged in 2018-09, with the labels that each got.

#342 Release 0.4.0
  CHANGELOG.md
  docs/access_api.md
  docs/create_fleet.md
  docs/create_gameserver.md
  docs/fleet_spec.md
  docs/gameserver_spec.md
  docs/sdk_rest_api.md
  install/README.md
  install/helm/README.md
  sdks/README.md
  sdks/cpp/README.md
Labels: kind/release

#343 Prepare for next release - 0.5.0.rc
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
Labels: kind/cleanup

#338 Forces restart when using tls generation.
  build/Makefile
  install/helm/README.md
  install/helm/agones/templates/NOTES.txt
  install/helm/agones/templates/controller.yaml
Labels: area/build-tools, kind/feature, merge-after-release

#347 Allocation is broken when using the generated go client
  pkg/apis/stable/v1alpha1/fleetallocation.go
  pkg/fleetallocation/controller.go
  pkg/fleetallocation/controller_test.go
  test/e2e/fleet_test.go
  test/e2e/framework/framework.go
  test/e2e/gameserver_test.go
  test/e2e/main_test.go
Labels: area/user-experience, kind/bug

#346 Switch to golangci-lint
  .gitignore
  .golangci.yml
  build/Makefile
  build/build-image/Dockerfile
  build/build-image/gen-lint-exclude.sh
  examples/simple-udp/main.go
  pkg/fleets/controller.go
  pkg/fleets/controller_test.go
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  pkg/gameservers/localsdk_test.go
  pkg/gameservers/portallocator_test.go
  pkg/gameservers/sdkserver_test.go
  sdks/go/sdk.go
  sdks/go/sdk_test.go
  test/e2e/framework/framework.go
  test/e2e/gameserver_test.go
Labels: area/build-tools

#352 Adding goimports back into the build shell.
  build/build-image/Dockerfile
Labels: area/build-tools

#351 e2e tests for Fleet Scaling and Updates
  build/Makefile
  examples/simple-udp/Makefile
  examples/simple-udp/fleet.yaml
  examples/simple-udp/gameserver.yaml
  examples/simple-udp/gameserverset.yaml
  examples/simple-udp/main.go
  test/e2e/fleet_test.go
  test/e2e/framework/framework.go
  test/e2e/main_test.go
Labels: area/build-tools

#359 Add ReadTimeout for e2e tests, otherwise this can hang forever.
  test/e2e/framework/framework.go
Labels: area/build-tools, kind/bug

#357 Fixes race condition bug with Pod not being scheduled before Ready()
  pkg/apis/stable/v1alpha1/gameserver.go
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
Labels: kind/bug

#349 Improve support for custom dev environments
  build/Makefile
  build/README.md
  install/helm/README.md
  install/helm/agones/templates/controller.yaml
  test/e2e/README.md
  test/e2e/framework/framework.go
  test/e2e/gameserver_test.go
  test/e2e/main_test.go
Labels: area/build-tools, kind/documentation, kind/feature

#360 Upgrade GKE version and increase test cluster size
  build/gke-test-cluster/cluster-e2e.yml
  build/gke-test-cluster/cluster.yml.jinja
Labels: area/build-tools, kind/cleanup

#363 Map level to severity for stackdriver
  pkg/util/runtime/runtime.go
Labels: area/user-experience, kind/bug

#361 Agones stable helm repository
  build/Makefile
  docs/governance/templates/release.md
  docs/governance/templates/release_issue.md
  install/helm/README.md
Labels: area/user-experience, kind/documentation, kind/feature

#364 Update Alpine version to 3.8.1
  cmd/controller/Dockerfile
  cmd/sdk-server/Dockerfile
  examples/simple-udp/Dockerfile
Labels: area/security

#367 Fix for race condition: Allocation of Deleting GameServers Possible
  cmd/controller/main.go
  pkg/fleetallocation/controller.go
  pkg/fleetallocation/controller_test.go
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  pkg/gameserversets/controller.go
  pkg/gameserversets/controller_test.go
  test/e2e/fleet_test.go
  test/e2e/gameserver_test.go
Labels: area/user-experience, kind/bug
