Repository googleforgames/agones, pull requests merged in 2018-06, with the labels that each got.

#233 Revert install configuration back to 0.2.0
  install/helm/agones/values.yaml
  install/yaml/install.yaml
Labels: kind/release

#235 Updates to release process
  README.md
  docs/governance/release_process.md
  docs/governance/templates/release.md
  docs/governance/templates/release_issue.md
Labels: area/meta, kind/documentation

#239 Adding my streaming development to contributing
  CONTRIBUTING.md
Labels: kind/documentation

#243 Release 0.2.0
  CHANGELOG.md
  build/Makefile
  docs/create_fleet.md
  docs/fleet_spec.md
  docs/governance/templates/release_issue.md
  install/README.md
  install/helm/README.md
Labels: kind/release

#244 Increment base version
  build/Makefile
  install/helm/agones/values.yaml
  install/yaml/install.yaml
Labels: kind/release

#241 Lock protoc-gen-go to 1.0 release
  build/build-image/Dockerfile
Labels: area/build-tools

#230 Support Rust SDK by gRPC-rs
  build/Makefile
  build/build-image/Dockerfile
  build/build-image/gen-grpc-rust.sh
  examples/rust-simple/.gitignore
  examples/rust-simple/Cargo.toml
  examples/rust-simple/Dockerfile
  examples/rust-simple/Makefile
  examples/rust-simple/README.md
  examples/rust-simple/gameserver.yaml
  examples/rust-simple/src/main.rs
  sdks/rust/.gitignore
  sdks/rust/Cargo.toml
  sdks/rust/README.md
  sdks/rust/src/errors.rs
  sdks/rust/src/grpc/mod.rs
  sdks/rust/src/grpc/sdk.rs
  sdks/rust/src/grpc/sdk_grpc.rs
  sdks/rust/src/lib.rs
  sdks/rust/src/sdk.rs
Labels: area/user-experience, kind/feature

#251 Rust SDK Doc additions
  sdks/README.md
  sdks/rust/README.md
Labels: kind/documentation

#252 Clearer Helm installation instructions
  install/helm/README.md
Labels: kind/cleanup, kind/documentation

#253 Add Licences to Rust SDK & Examples
  build/build-image/gen-grpc-rust.sh
  examples/rust-simple/Cargo.toml
  examples/rust-simple/Dockerfile
  examples/rust-simple/Makefile
  examples/rust-simple/gameserver.yaml
  examples/rust-simple/src/main.rs
  sdks/rust/Cargo.toml
  sdks/rust/src/errors.rs
  sdks/rust/src/grpc/mod.rs
  sdks/rust/src/grpc/sdk.rs
  sdks/rust/src/grpc/sdk_grpc.rs
  sdks/rust/src/lib.rs
  sdks/rust/src/sdk.rs
Labels: kind/cleanup

#260 Flaky test fix: TestWorkQueueHealthCheck
  pkg/util/workerqueue/workerqueue_test.go
Labels: kind/cleanup

#257 Flakey test fix: TestControllerUpdateFleetStatus
  pkg/fleets/controller_test.go
Labels: kind/cleanup

#262 Upgrade Helm for build tools
  build/build-image/Dockerfile
Labels: area/build-tools, kind/cleanup

#263 Upgrade to Go 1.10.3
  build/build-image/Dockerfile
Labels: area/build-tools, kind/cleanup

#264 Give linter 15 minutes.
  build/Makefile
Labels: area/build-tools

#266 Fix Xonotic example race condition
  examples/xonotic/Makefile
  examples/xonotic/fleet.yaml
  examples/xonotic/gameserver.yaml
  examples/xonotic/main.go
Labels: area/examples, kind/bug

#268 Fixing Flaky test TestControllerSyncFleet
  pkg/fleets/controller_test.go
Labels: kind/cleanup

#267 Update Helm App Version
  install/helm/agones/Chart.yaml
  install/yaml/install.yaml
Labels: area/user-experience

#270 More Docker and Kubernetes Getting Started Resources
  README.md
Labels: kind/documentation

#250 use the helm --namespace convention
  build/Makefile
  install/helm/README.md
  install/helm/agones/templates/NOTES.txt
  install/helm/agones/templates/admissionregistration.yaml
  install/helm/agones/templates/controller.yaml
  install/helm/agones/templates/namespace.yaml
  install/helm/agones/templates/service.yaml
  install/helm/agones/templates/serviceaccounts/controller.yaml
  install/helm/agones/templates/serviceaccounts/sdk.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
Labels: area/build-tools, area/user-experience, kind/documentation

#271 Move cluster node addition/removal out of "experimental"
  pkg/gameservers/controller.go
  pkg/gameservers/portallocator.go
  pkg/gameservers/portallocator_test.go
Labels: kind/feature

#273 Update minikube instructions to 0.28.0
  build/Makefile
  build/README.md
  install/README.md
Labels: area/build-tools, kind/documentation

#274 Remove line
  sdks/README.md
Labels: kind/cleanup, kind/documentation
