Repository googleforgames/agones, pull requests merged in 2018-10, with the labels that each got.

#373 Update instructions for Minikube 0.29.0
  build/Makefile
  build/README.md
  install/README.md
Labels: area/build-tools, kind/cleanup, kind/documentation

#376 Fix for flaky test TestControllerAddress
  pkg/gameservers/controller_test.go
Labels: area/build-tools, kind/cleanup

#353 Add allocator service example and documentation
  README.md
  docs/access_api.md
  docs/create_allocator_service.md
  docs/create_fleet.md
  docs/edit_first_game_server.md
  examples/allocator-service/README.md
  examples/allocator-service/allocator-ingress.yaml
  examples/allocator-service/allocator-service.yaml
  examples/allocator-service/dockerfile
  examples/allocator-service/main.go
  examples/allocator-service/service-account.yaml
Labels: area/examples, kind/documentation

#377 Make WaitForFleetCondition take up to 5 minutes
  test/e2e/framework/framework.go
Labels: area/build-tools, kind/cleanup

#379 Release 0.5.0.rc changes
  CHANGELOG.md
  build/Makefile
  docs/create_fleetautoscaler.md
Labels: kind/release

#380 Post 0.5.0-rc updates
  CHANGELOG.md
  docs/governance/templates/release.md
  docs/governance/templates/release_issue.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
Labels: area/build-tools, area/meta, kind/cleanup

#381 Spec docs for FleetAutoscaler
  README.md
  docs/fleetautoscaler_spec.md
Labels: kind/documentation

#384 Troubleshooting guide for issues with Agones.
  README.md
  docs/troubleshooting.md
Labels: area/user-experience, kind/documentation

#386 Hotfix for wrong image tag.
  CHANGELOG.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
Labels: kind/bug

#388 Change for the 0.5.0 release.
  CHANGELOG.md
  docs/access_api.md
  docs/create_fleet.md
  docs/create_fleetautoscaler.md
  docs/create_gameserver.md
  docs/fleetautoscaler_spec.md
  docs/gameserver_spec.md
  install/README.md
  install/helm/agones/templates/NOTES.txt
Labels: kind/release

#389 Post 0.5.0 Updates
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
Labels: kind/cleanup

#385 Update to Go 1.11.1
  build/build-image/Dockerfile
Labels: area/build-tools, kind/cleanup

#370 Prioritise Allocation from Nodes with Allocated/Ready GameServers
  README.md
  docs/create_fleetautoscaler.md
  docs/fleet_spec.md
  docs/scheduling_autoscaling.md
  examples/fleet.yaml
  pkg/apis/stable/v1alpha1/fleet.go
  pkg/apis/stable/v1alpha1/fleet_test.go
  pkg/fleetallocation/controller.go
  pkg/fleetallocation/controller_test.go
  pkg/fleetallocation/find.go
  pkg/fleetallocation/find_test.go
  test/e2e/fleet_test.go
Labels: area/user-experience, kind/feature

#390 Specify CPU Request for the SDK Server Sidecar
  README.md
  cmd/controller/main.go
  docs/limiting_resources.md
  install/helm/README.md
  install/helm/agones/templates/controller.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  pkg/testing/controller.go
  pkg/util/webhooks/webhooks_test.go
  pkg/util/workerqueue/workerqueue_test.go
Labels: area/user-experience, kind/feature

#391 Set test clusters to base version. GKE will work out the rest.
  build/gke-test-cluster/cluster-e2e.yml
  build/gke-test-cluster/cluster.yml.jinja
Labels: area/build-tools, kind/cleanup

#393 Adding third part videos and presentations.
  README.md
  docs/videos_presentations.md
Labels: kind/documentation

#394 Make sure do-release always uses the release_registry
  build/Makefile
Labels: area/build-tools, kind/cleanup

#397 Packed: PreferredDuringSchedulingIgnoredDuringExecution PodAffinity with a HostName topology
  docs/scheduling_autoscaling.md
  pkg/apis/stable/v1alpha1/fleet.go
  pkg/apis/stable/v1alpha1/fleet_test.go
  pkg/apis/stable/v1alpha1/gameserver.go
  pkg/apis/stable/v1alpha1/gameserver_test.go
  pkg/apis/stable/v1alpha1/gameserverset.go
  pkg/apis/stable/v1alpha1/scheduling.go
  pkg/gameservers/portallocator.go
Labels: area/user-experience, kind/feature

#402 Apparently patching events is a thing.
  install/helm/agones/templates/serviceaccounts/controller.yaml
  install/yaml/install.yaml
Labels: kind/bug, kind/cleanup

#401 Packed: Fleet scaled down removes GameServers from least used Nodes
  docs/scheduling_autoscaling.md
  examples/simple-udp/fleet.yaml
  install/helm/agones/templates/crds/_gameserverspecvalidation.yaml
  install/helm/agones/templates/crds/fleet.yaml
  install/helm/agones/templates/crds/fleetautoscaler.yaml
  install/helm/agones/templates/crds/gameserverset.yaml
  install/yaml/install.yaml
  pkg/apis/stable/v1alpha1/gameserver.go
  pkg/apis/stable/v1alpha1/gameserverset.go
  pkg/gameserversets/controller.go
  pkg/gameserversets/controller_test.go
  pkg/gameserversets/gameserversets.go
  pkg/gameserversets/gameserversets_test.go
Labels: area/user-experience, kind/feature

#396 Update Helm to 2.11.0
  build/Makefile
  build/build-image/Dockerfile
  build/e2e-image/Dockerfile
  build/e2e-image/entrypoint.sh
  build/gke-test-cluster/cluster-e2e.yml
Labels: area/build-tools, kind/cleanup

#399 Process to become an reviewer/approver on Agones.
  CONTRIBUTING.md
  docs/governance/community_membership.md
  docs/governance/templates/membership.md
Labels: area/meta
