Repository googleforgames/agones, pull requests merged in 2018-03, with the labels that each got.

#122 Add cluster creation Quickstart.
  README.md
  docs/cloud-shell.png
  docs/installing_agones.md
Labels: area/examples, area/user-experience, kind/documentation

#131 Godoc badge!
  README.md
Labels: kind/documentation

#133 Update base version to 0.2
  build/Makefile
Labels: area/build-tools

#136 Cleanup of grpc go generation code
  build/build-image/Dockerfile
  build/build-image/gen-grpc-go.sh
  sdks/go/sdk.go
  sdks/go/sdk.pb.go
  sdks/go/sdk_test.go
Labels: kind/cleanup

#137 Update Go version to 1.10
  build/build-image/Dockerfile
Labels: area/build-tools

#139 go vet: 3 warnings, 2 of them are easy.
  examples/simple-udp/server/main.go
  pkg/gameservers/helper_test.go
Labels: kind/cleanup

#140 Handle stop signal in the SDK Server
  cmd/sdk-server/main.go
Labels: kind/cleanup

#147 Move GameServer validation to a ValidatingAdmissionWebhook
  README.md
  build/install.yaml
  install.yaml
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
Labels: area/user-experience, kind/cleanup

#152 Documentation on the CI build system.
  CONTRIBUTING.md
  cloudbuild.yaml
Labels: kind/documentation
