Repository googleforgames/agones, pull requests merged in 2018-11, with the labels that each got.

#405 Cluster Autoscaling: safe-to-evict=false annotations for GameServer Pods
  docs/scheduling_autoscaling.md
  install/helm/agones/templates/controller.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  pkg/apis/stable/v1alpha1/gameserver.go
  pkg/apis/stable/v1alpha1/gameserver_test.go
Labels: area/user-experience, kind/feature

#413 Changes to the GameServer configuration are reflected in the local sdk server
  cmd/sdk-server/main.go
  examples/simple-udp/gameserver.yaml
  pkg/gameservers/localsdk.go
  pkg/gameservers/localsdk_test.go
  sdks/README.md
Labels: area/user-experience, kind/feature

#375 Add crd-install helm hook to crds templates
  install/helm/agones/templates/crds/fleet.yaml
  install/helm/agones/templates/crds/fleetallocation.yaml
  install/helm/agones/templates/crds/fleetautoscaler.yaml
  install/helm/agones/templates/crds/gameserver.yaml
  install/helm/agones/templates/crds/gameserverset.yaml
  install/yaml/install.yaml
Labels: area/user-experience, kind/feature

#415 Ports should always be allocated to a GameServer
  pkg/gameservers/controller.go
  pkg/gameservers/portallocator.go
  pkg/gameservers/portallocator_test.go
Labels: area/user-experience, kind/bug

#417 More stringent linting rules (and update linter)
  .golangci.yml
  build/build-image/Dockerfile
  pkg/apis/stable/v1alpha1/fleet.go
  pkg/apis/stable/v1alpha1/fleetautoscaler.go
  pkg/apis/stable/v1alpha1/scheduling.go
  pkg/gameservers/localsdk.go
  test/e2e/framework/framework.go
Labels: kind/cleanup

#422 Development tools to enable pprof
  build/Makefile
  build/README.md
  build/build-image/Dockerfile
  cmd/controller/pprof.go
Labels: area/build-tools, kind/feature

#416 FleetAutoscaler can be targeted at Non Existent Fleets
  install/helm/agones/templates/admissionregistration.yaml
  install/yaml/install.yaml
  pkg/apis/stable/v1alpha1/fleetautoscaler.go
  pkg/apis/stable/v1alpha1/fleetautoscaler_test.go
  pkg/fleetautoscalers/controller.go
  pkg/fleetautoscalers/controller_test.go
  pkg/gameservers/localsdk.go
Labels: area/user-experience, kind/cleanup

#429 Release 0.6.0 updates.
  CHANGELOG.md
  docs/fleet_spec.md
  docs/gameserver_spec.md
  docs/governance/templates/release_issue.md
  docs/limiting_resources.md
  docs/scheduling_autoscaling.md
  install/README.md
  install/helm/README.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
Labels: kind/release

#427 add fleet name to gameservers labels
  pkg/apis/stable/v1alpha1/fleet.go
  pkg/apis/stable/v1alpha1/fleet_test.go
  pkg/apis/stable/v1alpha1/gameserverset.go
  pkg/apis/stable/v1alpha1/gameserverset_test.go
  pkg/fleetallocation/controller.go
  pkg/fleets/fleets.go
  pkg/fleets/fleets_test.go
  test/e2e/framework/framework.go
Labels: area/performance, kind/cleanup

#430 Post 0.6.0 updates
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
Labels: kind/cleanup

#432 README: Autoscaler example link
  README.md
Labels: kind/cleanup, kind/documentation
