Repository googleforgames/agones, pull requests merged in 2018-12, with the labels that each got.

#434 Pinger service for Multiple Cluster Latency Measurement.
  README.md
  build/Makefile
  build/README.md
  cloudbuild.yaml
  cmd/controller/pprof.go
  cmd/ping/Dockerfile
  cmd/ping/main.go
  cmd/ping/udp.go
  cmd/ping/udp_test.go
  docs/ping_service.md
  install/helm/README.md
  install/helm/agones/templates/ping.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  test/e2e/ping_test.go
Labels: area/user-experience, kind/feature

#441 Remove crd-install hook, as it break CRD updates
  build/Makefile
  install/helm/README.md
  install/helm/agones/scripts/delete_crds.sh
  install/helm/agones/templates/crds/fleet.yaml
  install/helm/agones/templates/crds/fleetallocation.yaml
  install/helm/agones/templates/crds/fleetautoscaler.yaml
  install/helm/agones/templates/crds/gameserver.yaml
  install/helm/agones/templates/crds/gameserverset.yaml
  install/helm/agones/templates/hooks/post_delete_hook.yaml
  install/helm/agones/templates/hooks/pre_delete_hook.yaml
  install/helm/agones/templates/hooks/sa.yaml
  install/helm/agones/templates/hooks/scripts.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
Labels: area/user-experience, kind/bug

#442 GameServerSets: DeleteFunc could receive a DeletedFinalStateUnknown
  pkg/gameserversets/controller.go
Labels: kind/bug, kind/cleanup

#444 CRD: added additionalPrinterColumns to GameServer for kubectl
  install/helm/agones/templates/crds/fleet.yaml
  install/helm/agones/templates/crds/fleetallocation.yaml
  install/helm/agones/templates/crds/gameserver.yaml
  install/helm/agones/templates/crds/gameserverset.yaml
  install/yaml/install.yaml
Labels: area/user-experience, kind/feature

#461 Apply fix for goroutines leak
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  vendor/k8s.io/apimachinery/pkg/util/wait/wait_test.go
Labels: area/performance, kind/bug

#458 Adds Kind local cluster support with documentation
  build/Makefile
  build/README.md
Labels: area/build-tools, kind/feature

#462 This should fail e2e in any command fails
  build/e2e-image/e2e.sh
Labels: area/build-tools, kind/bug

#459 Upgrade minikube to K8s 1.11
  build/Makefile
Labels: area/build-tools, kind/cleanup

#460 Add webhook functionality into FleetAutoscaler
  Gopkg.lock
  README.md
  docs/create_webhook_fleetautoscaler.md
  docs/fleetautoscaler_spec.md
  examples/autoscaler-webhook/Dockerfile
  examples/autoscaler-webhook/Makefile
  examples/autoscaler-webhook/README.md
  examples/autoscaler-webhook/autoscaler-service.yaml
  examples/autoscaler-webhook/main.go
  examples/fleet.yaml
  examples/webhookfleetautoscaler.yaml
  install/helm/agones/templates/crds/fleetautoscaler.yaml
  install/yaml/install.yaml
  pkg/apis/stable/v1alpha1/fleetautoscaler.go
  pkg/apis/stable/v1alpha1/fleetautoscaler_test.go
  pkg/apis/stable/v1alpha1/zz_generated.deepcopy.go
  pkg/fleetautoscalers/controller_test.go
  pkg/fleetautoscalers/fleetautoscalers.go
  pkg/fleetautoscalers/fleetautoscalers_test.go
  test/e2e/fleetautoscaler_test.go
Labels: area/user-experience, kind/feature
