Repository googleforgames/agones, pull requests merged in 2018-05, with the labels that each got.

#190 Update initialClusterVersion to 1.9.6.gke.1
  build/gke-test-cluster/cluster.yml.jinja
Labels: area/build-tools, kind/bug

#195 Install docs: minikube 0.25.2 and k8s 1.9.4
  docs/installing_agones.md
Labels: kind/documentation

#194 `minikube-test-cluster` needed the `ensure-build-image` dependency
  build/Makefile
Labels: area/build-tools, kind/bug

#197 Fixes for GKE issues with install/quickstart
  docs/create_gameserver.md
  docs/installing_agones.md
Labels: kind/bug, kind/documentation

#198 Don't allow allocation of Deleted GameServers
  pkg/fleetallocation/controller.go
  pkg/fleetallocation/controller_test.go
Labels: kind/bug

#200 Typo in GameServer json
  pkg/apis/stable/v1alpha1/gameserver.go
Labels: kind/cleanup

#202 RBAC: controller doesn't need fleet create
  install/helm/agones/templates/serviceaccounts/controller.yaml
  install/yaml/install.yaml
Labels: kind/cleanup, security

#201 Release version, and twitter badges.
  README.md
Labels: kind/documentation

#199 Fleet update strategy: Replace
  cmd/controller/main.go
  docs/create_fleet.md
  docs/fleet_spec.md
  examples/fleet.yaml
  examples/xonotic/fleet.yaml
  install/helm/agones/templates/crds/fleet.yaml
  install/helm/agones/templates/mutatingwebhook.yaml
  install/yaml/install.yaml
  pkg/apis/stable/v1alpha1/fleet.go
  pkg/apis/stable/v1alpha1/fleet_test.go
  pkg/apis/stable/v1alpha1/zz_generated.deepcopy.go
  pkg/fleetallocation/controller.go
  pkg/fleetallocation/controller_test.go
  pkg/fleets/controller.go
  pkg/fleets/controller_test.go
Labels: kind/documentation, kind/feature

#204 Fleet docs: Some missing pieces.
  README.md
  docs/fleet_spec.md
Labels: kind/cleanup, kind/documentation

#206 Clearer docs on developing and building from source
  README.md
Labels: kind/cleanup, kind/documentation

#208 Testing functions for resource events
  pkg/fleets/controller_test.go
  pkg/gameservers/health_test.go
  pkg/gameservers/sdkserver_test.go
  pkg/gameserversets/controller_test.go
  pkg/testing/controller.go
Labels: area/build-tools, kind/cleanup

#215 Release process documentation
  docs/governance/release_process.md
  docs/governance/templates/release.md
  docs/governance/templates/release_issue.md
Labels: area/meta

#216 Some more Extending Kubernetes resources
  CONTRIBUTING.md
Labels: kind/documentation

#214 Generate Certs for Mutation/Validatiion Webhooks
  build/Makefile
  cmd/controller/Dockerfile
  docs/installing_agones.md
  install/helm/README.md
  install/helm/agones/certs/cert.sh
  install/helm/agones/certs/server.crt
  install/helm/agones/certs/server.key
  install/helm/agones/templates/admissionregistration.yaml
  install/helm/agones/templates/controller.yaml
  install/helm/agones/templates/mutatingwebhook.yaml
  install/helm/agones/templates/validatingwebhook.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
Labels: kind/feature

#217 Target for generating a CHANGELOG from GitHub Milestones.
  build/Makefile
Labels: area/build-tools, area/meta, kind/feature

#218 Intercept Xonotic stdout for SDK Integration
  examples/xonotic/Dockerfile
  examples/xonotic/Makefile
  examples/xonotic/README.md
  examples/xonotic/fleet.yaml
  examples/xonotic/fleetallocation.yaml
  examples/xonotic/gameserver.yaml
  examples/xonotic/main.go
  examples/xonotic/run.sh
Labels: area/examples

#221 Lint timeout increase, and make configurable
  build/Makefile
  build/README.md
Labels: area/build-tools, kind/feature

#222 Update tools - vetshadow is more aggressive
  build/build-image/Dockerfile
  cmd/sdk-server/main.go
  pkg/gameservers/controller.go
  pkg/gameservers/portallocator.go
  pkg/gameservers/sdkserver.go
  pkg/util/workerqueue/workerqueue.go
Labels: area/build-tools, kind/cleanup

#223 Move to proper semver
  build/Makefile
  docs/governance/release_process.md
  install/helm/README.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
Labels: kind/cleanup

#225 Update installing_agones.md
  docs/installing_agones.md
Labels: kind/cleanup, kind/documentation

#226 Release steps of archiving installation resources and documentation
  README.md
  build/Makefile
  docs/create_fleet.md
  docs/create_gameserver.md
  install/README.md
  install/helm/README.md
Labels: area/build-tools, kind/documentation, kind/feature

#228 do-release release registry and upstream push
  build/Makefile
Labels: area/build-tools, kind/cleanup

#227 Archive C++ src on build and release
  build/Makefile
  cloudbuild.yaml
  sdks/cpp/Makefile
Labels: area/build-tools, area/user-experience

#220 add the ability to turn off RBAC in helm and customize gcp test-cluster
  build/Makefile
  build/README.md
  build/gke-test-cluster/cluster.yml.jinja
  build/gke-test-cluster/deployment.yml
  install/helm/README.md
  install/helm/agones/templates/serviceaccounts/controller.yaml
  install/helm/agones/templates/serviceaccounts/sdk.yaml
  install/helm/agones/values.yaml
Labels: area/user-experience, kind/feature

#232 Release v0.2.0.rc
  CHANGELOG.md
  build/Makefile
  docs/create_fleet.md
  docs/fleet_spec.md
  install/README.md
  install/helm/README.md
  install/helm/agones/values.yaml
  install/yaml/install.yaml
Labels: kind/release

#234 Adding a README.md file for the simple-udp to help developer to get start
  README.md
  docs/edit_first_game_server.md
  examples/simple-udp/server/README.md
Labels: kind/documentation
