Repository googleforgames/agones, pull requests merged in 2018-04, with the labels that each got.

#159 Why does this project exist?
  README.md
Labels: kind/documentation

#158 Add GKE Comic to explain Kubernetes to newcomers
  README.md
Labels: kind/documentation

#157 Adding a Go Report Card
  README.md
Labels: kind/documentation

#164 Refactor of workerqueue health testing
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  pkg/gameservers/helper_test.go
  pkg/util/workerqueue/workerqueue_test.go
Labels: kind/cleanup

#166 Fixed missing links in documentation.
  docs/installing_agones.md
  install/helm/README.md
Labels: kind/bug, kind/documentation

#172 Centralise utilities for testing controllers
  pkg/gameservers/controller_test.go
  pkg/gameservers/health_test.go
  pkg/gameservers/helper_test.go
  pkg/gameservers/portallocator_test.go
  pkg/gameservers/sdkserver_test.go
  pkg/gameserversets/controller.go
  pkg/gameserversets/controller_test.go
  pkg/testing/controller.go
  pkg/testing/doc.go
Labels: kind/cleanup

#175 Missed a couple of small things in last PR
  pkg/apis/stable/v1alpha1/register.go
  pkg/fleets/controller_test.go
Labels: kind/cleanup

#185 Solve rare flakiness on TestWorkerQueueHealthy
  pkg/util/workerqueue/workerqueue_test.go
Labels: area/build-tools, kind/cleanup

#184 Adding additional resources for CRDs and Controllers
  CONTRIBUTING.md
Labels: kind/documentation

#189 Point the install.yaml to the release-0.1 branch
  docs/installing_agones.md
Labels: kind/bug, kind/documentation

#188 Make the development release warning more visible.
  install/helm/README.md
Labels: kind/documentation
