Repository googleforgames/agones, pull requests merged in 2019-11, with the labels that each got.

#1166 Add Spec and Health data to default local sdk GameServer
  pkg/sdkserver/localsdk.go
Labels: approved, area/user-experience, kind/feature, size/XS

#1116 Move Googlers no longer actively reviewing code to emeritus owners
  OWNERS
Labels: approved, lgtm, size/XS

#1099 GameServer container restart before Ready, move to Unhealthy state After (v2)
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/agones/v1/gameserver_test.go
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  pkg/gameservers/health.go
  pkg/gameservers/health_test.go
  pkg/sdk/sdk.pb.go
  test/e2e/gameserver_test.go
Labels: approved, area/user-experience, kind/bug, lgtm, size/L

#1171 Mitigate panic when no ports allocated in E2E tests
  examples/gameserver.yaml
  site/content/en/docs/Reference/gameserver.md
  test/e2e/framework/framework.go
Labels: approved, lgtm, size/S

#1172 Extra debugging for TestGameServerRestartBeforeReadyCrash
  test/e2e/gameserver_test.go
Labels: approved, area/tests, kind/cleanup, lgtm, size/XS

#1165 Docs: Fix using GOPATH in the guides, added shortcode ghrelease
  site/content/en/docs/Getting Started/create-webhook-fleetautoscaler.md
  site/content/en/docs/Guides/Client SDKs/local.md
  site/htmltest.yaml
  site/layouts/shortcodes/ghrelease.html
Labels: approved, lgtm, size/M

#1176 Update the prow cluster to use Kubernetes 1.13
  build/gke-test-cluster/cluster-prow.yml
Labels: approved, lgtm, size/XS

#1175 Update GKE development tooling to Kubernetes 1.13
  build/README.md
  build/build-image/Dockerfile
  build/gke-test-cluster/cluster-e2e.yml
  build/gke-test-cluster/cluster.yml.jinja
Labels: approved, size/XS

#1145 Refresh client CA certificate if changed
  cmd/allocator/main.go
  go.mod
  go.sum
  test/e2e/allocator_test.go
  vendor/gopkg.in/fsnotify.v1/.gitignore
  vendor/gopkg.in/fsnotify.v1/AUTHORS
  vendor/gopkg.in/fsnotify.v1/CHANGELOG.md
  vendor/gopkg.in/fsnotify.v1/CONTRIBUTING.md
  vendor/gopkg.in/fsnotify.v1/LICENSE
  vendor/gopkg.in/fsnotify.v1/README.md
  vendor/gopkg.in/fsnotify.v1/fen.go
  vendor/gopkg.in/fsnotify.v1/fsnotify.go
  vendor/gopkg.in/fsnotify.v1/inotify.go
  vendor/gopkg.in/fsnotify.v1/inotify_poller.go
  vendor/gopkg.in/fsnotify.v1/kqueue.go
  vendor/gopkg.in/fsnotify.v1/open_mode_bsd.go
  vendor/gopkg.in/fsnotify.v1/open_mode_darwin.go
  vendor/gopkg.in/fsnotify.v1/windows.go
Labels: approved, area/operations, kind/feature, lgtm, size/XXL

#1174 Flaky: TestGameServerRestartBeforeReadyCrash
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  pkg/gameservers/health.go
  test/e2e/gameserver_test.go
Labels: approved, kind/bug, size/M

#1169 Implementation of GameServer() for Unity
  examples/unity-simple/.gitignore
  examples/unity-simple/Assets/Scripts/Agones/model.meta
  examples/unity-simple/Assets/Scripts/Agones/model/GameServer.cs
  examples/unity-simple/Assets/Scripts/Agones/model/GameServer.cs.meta
  examples/unity-simple/Assets/Scripts/Agones/model/GameServerObjectMeta.cs
  examples/unity-simple/Assets/Scripts/Agones/model/GameServerObjectMeta.cs.meta
  examples/unity-simple/Assets/Scripts/Agones/model/GameServerSpec.cs
  examples/unity-simple/Assets/Scripts/Agones/model/GameServerSpec.cs.meta
  examples/unity-simple/Assets/Scripts/Agones/model/GameServerStatus.cs
  examples/unity-simple/Assets/Scripts/Agones/model/GameServerStatus.cs.meta
  examples/unity-simple/Assets/Scripts/Agones/model/SpecHealth.cs
  examples/unity-simple/Assets/Scripts/Agones/model/SpecHealth.cs.meta
  examples/unity-simple/Assets/Scripts/Agones/model/StatusPort.cs
  examples/unity-simple/Assets/Scripts/Agones/model/StatusPort.cs.meta
  examples/unity-simple/Assets/Scripts/Agones/third_party.meta
  examples/unity-simple/Assets/Scripts/Agones/third_party/MiniJSON.cs
  examples/unity-simple/Assets/Scripts/Agones/third_party/MiniJSON.cs.meta
  examples/unity-simple/Assets/Scripts/UdpEchoServer.cs
  examples/unity-simple/Packages/manifest.json
  examples/unity-simple/ProjectSettings/EditorSettings.asset
  examples/unity-simple/ProjectSettings/ProjectVersion.txt
  examples/unity-simple/README.md
  pkg/sdk/sdk.pb.go
  sdks/unity/AgonesSdk.cs
  sdks/unity/model/GameServer.cs
  sdks/unity/model/GameServerObjectMeta.cs
  sdks/unity/model/GameServerSpec.cs
  sdks/unity/model/GameServerStatus.cs
  sdks/unity/model/SpecHealth.cs
  sdks/unity/model/StatusPort.cs
  sdks/unity/third_party/MiniJSON.cs
  site/content/en/docs/Examples/_index.md
  site/content/en/docs/Guides/Client SDKs/unity.md
Labels: approved, area/user-experience, kind/feature, lgtm, size/XXL

#1179 Update terraform configs to use Kubernetes 1.13
  build/modules/aks/aks.tf
  build/modules/gke/cluster.tf
  examples/terraform-submodules/aks/module.tf
  examples/terraform-submodules/gke-local/main.tf
Labels: approved, do-not-merge/hold, size/S

#1177 Update minikube and KIND developer tooling to Kubernetes 1.13
  build/includes/kind.mk
  build/includes/minikube.mk
Labels: approved, area/operations, kind/cleanup, size/XS

#1186 Change the "Read more ..." links to better text on the home page.
  site/content/en/_index.html
Labels: approved, lgtm, size/XS

#1187 Point Helm Upgrade link to v2 documentation
  site/content/en/docs/Installation/upgrading.md
Labels: approved, area/operations, kind/cleanup, kind/documentation, lgtm, size/XS

#1181 Implementation of Unity SDK.Connect()
  examples/unity-simple/Assets/Scripts/UdpEchoServer.cs
  sdks/unity/AgonesSdk.cs
  site/content/en/docs/Guides/Client SDKs/unity.md
Labels: approved, area/user-experience, kind/feature, size/M

#1180 Update the default gRPC and HTTP ports for the sdkserver for the 1.2.0 release
  build/includes/sdk.mk
  cmd/sdk-server/main.go
  examples/gameserver.yaml
  install/helm/agones/templates/crds/_gameserverspecvalidation.yaml
  install/yaml/install.yaml
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/agones/v1/gameserver_test.go
  sdks/cpp/src/agones/sdk.cc
  sdks/go/sdk.go
  sdks/nodejs/spec/agonesSDK.spec.js
  sdks/nodejs/src/agonesSDK.js
  sdks/rust/src/sdk.rs
  sdks/unity/AgonesSdk.cs
  sdks/unreal/Agones/Source/Agones/AgonesHook.cpp
  site/content/en/docs/Guides/Client SDKs/local.md
  site/content/en/docs/Reference/gameserver.md
Labels: approved, kind/breaking, size/L

#1190 Add ImagePullSecrets for Allocator and Ping (helm)
  install/helm/agones/templates/ping.yaml
  install/helm/agones/templates/service/allocation.yaml
  site/content/en/docs/Installation/helm.md
Labels: approved, lgtm, size/S

#1191 Fix MD files in the repo
  build/README.md
  site/content/en/docs/Advanced/multi-cluster-allocation.md
  site/content/en/docs/Guides/metrics.md
  site/content/en/docs/Guides/ping-service.md
  site/content/en/docs/Installation/helm.md
  site/content/en/docs/Installation/terraform.md
  site/content/en/docs/Installation/upgrading.md
Labels: approved, lgtm, size/M

#1168 Allow fleet with empty Replicas
  examples/fleet.yaml
  install/helm/agones/templates/crds/fleet.yaml
  install/yaml/install.yaml
  pkg/apis/agones/v1/fleet.go
  pkg/apis/agones/v1/fleet_test.go
  pkg/apis/agones/v1/zz_generated.deepcopy.go
  site/content/en/docs/Getting Started/create-fleetautoscaler.md
  site/content/en/docs/Reference/agones_crd_api_reference.html
  site/content/en/docs/Reference/fleet.md
  test/e2e/fleet_test.go
  test/e2e/fleetautoscaler_test.go
Labels: approved, area/operations, kind/bug, size/L

#1188 Fix infinite creation of GameServerSets when 1000m CPU limit was used
  pkg/apis/agones/v1/gameserverset.go
  pkg/fleets/controller.go
  pkg/fleets/controller_test.go
  test/e2e/fleet_test.go
Labels: approved, lgtm, size/L
