Repository googleforgames/agones, pull requests merged in 2019-01, with the labels that each got.

#468 Release 0.7.0-rc
  CHANGELOG.md
  docs/create_webhook_fleetautoscaler.md
  docs/metrics.md
  docs/ping_service.md
  install/helm/agones/README.md
Labels: kind/release

#470 Preparation for 0.7.0
  docs/governance/templates/release_issue.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
Labels: kind/release

#478 Release 0.7.0
  CHANGELOG.md
  docs/create_webhook_fleetautoscaler.md
  docs/gameserver_spec.md
  docs/metrics.md
  docs/ping_service.md
  install/README.md
  install/helm/agones/README.md
Labels: kind/release

#479 Post 0.7.0 changes
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
Labels: kind/release

#475 docs: added game server state diagram
  build/Makefile
  docs/gameserver-states.dot
  docs/gameserver-states.png
  docs/gameserver_spec.md
Labels: kind/documentation

#486 Fix for the controller panic issue on metrics.enabled is false
  cmd/controller/main.go
Labels: kind/bug, kind/cleanup

#488 Remove reflect from controller.
  cmd/controller/main.go
Labels: kind/cleanup

#494 Go download link has changed
  build/build-image/Dockerfile
  build/e2e-image/Dockerfile
Labels: area/build-tools, kind/bug

#496 added resource limits to gameserver.yaml and changed to generateName:
  examples/simple-udp/gameserver.yaml
Labels: area/examples, kind/cleanup

#504 Fixes for flaky e2e tests.
  test/e2e/fleetautoscaler_test.go
  test/e2e/framework/framework.go
Labels: kind/cleanup

#503 Fix for Flaky TestControllerCreationMutationHandler
  pkg/fleetallocation/controller_test.go
Labels: kind/cleanup

#501 Prometheus and grafana improvements based on load testing experience
  build/Makefile
  build/gke-test-cluster/cluster.yml.jinja
  build/grafana.yaml
  build/prometheus.yaml
  site/content/en/docs/Guides/metrics.md
Labels: area/operations, kind/feature

#498 Add Agones version into Gameserver Annotation
  pkg/apis/stable/register.go
  pkg/apis/stable/v1alpha1/fleet.go
  pkg/apis/stable/v1alpha1/gameserver.go
  test/e2e/gameserver_test.go
Labels: area/operations, kind/feature

#507 Extend e2e lock to 30m
  build/e2e-image/entrypoint.sh
Labels: area/build-tools, kind/cleanup

#508 Add e2e test for updating gameserver configurations in fleet
  test/e2e/fleet_test.go
Labels: area/tests

#505 add client-go metrics and grafana dashboards
  build/grafana/dashboard-goclient-caches.yaml
  build/grafana/dashboard-goclient-requests.yaml
  build/grafana/dashboard-goclient-workqueues.yaml
  pkg/metrics/controller.go
  pkg/metrics/controller_metrics.go
  pkg/metrics/controller_test.go
  pkg/metrics/gameservers_count.go
  pkg/metrics/kubernetes_client.go
  pkg/metrics/metrics.go
  pkg/metrics/util.go
  pkg/metrics/util_test.go
  site/content/en/docs/Guides/metrics.md
Labels: area/operations, kind/feature

#515 minkube-setup-grafana => minikube-setup-grafana
  build/Makefile
Labels: area/build-tools, kind/cleanup

#516 Fix for flaky TestSDKSetAnnotation
  test/e2e/gameserver_test.go
Labels: area/tests, kind/cleanup

#518 Extend consul -try to 30m
  build/e2e-image/entrypoint.sh
Labels: area/build-tools, kind/cleanup

#497 controller: made QPS, burst QPS and number of workers externally configurable
  cmd/controller/main.go
  install/helm/agones/templates/controller.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  site/content/en/docs/Installation/helm.md
  test/e2e/fleet_test.go
Labels: area/performance, kind/feature

#510 Prometheus installation docs tweak.
  site/content/en/docs/Guides/metrics.md
Labels: kind/cleanup, kind/documentation

#513 Restructure cloudbuild.yaml
  build/Makefile
  build/e2e-image/e2e.sh
  cloudbuild.yaml
Labels: area/tests, kind/cleanup

#519 Remove TOC from metrics page
  site/content/en/docs/Guides/metrics.md
Labels: kind/cleanup, kind/documentation

#527 Continuous Deployment of Agones.dev
  site/cloudbuild.yaml
Labels: area/site, kind/feature

#525 Fix potential data race in allocation counter
  pkg/gameserverallocations/allocationcounter.go
  pkg/gameserverallocations/allocationcounter_test.go
  pkg/gameserverallocations/controller.go
  pkg/gameserverallocations/find.go
Labels: kind/bug

#528 [SECURITY] Update Go to 1.11.5
  build/build-image/Dockerfile
  examples/autoscaler-webhook/Dockerfile
  examples/simple-udp/Dockerfile
Labels: area/build-tools, area/security

#524 Put CI buiild logs in a public bucket.
  cloudbuild.yaml
Labels: area/build-tools, area/tests

#529 Move SDK local tooling into its own section
  site/content/en/blog/news/new-agones-site.md
  site/content/en/docs/Guides/Client SDKs/_index.md
  site/content/en/docs/Guides/Client SDKs/local.md
Labels: area/site, kind/documentation

#531 PortAllocator.Run() is no longer blocking.
  pkg/gameservers/controller.go
Labels: kind/cleanup

#534 This is how you write shortcode in hugo
  site/content/en/docs/Contribute/_index.md
Labels: kind/cleanup, kind/documentation

#537 Adding tags to cloudbuilds
  cloudbuild.yaml
  site/cloudbuild.yaml
Labels: area/build-tools, area/site
