Repository googleforgames/agones, pull requests merged in 2019-06, with the labels that each got.

#766 Add Reserved GameServer State
  pkg/apis/stable/v1alpha1/fleet.go
  pkg/apis/stable/v1alpha1/gameserver.go
  pkg/apis/stable/v1alpha1/gameserver_test.go
  pkg/apis/stable/v1alpha1/gameserverset.go
  pkg/fleetautoscalers/controller_test.go
  pkg/fleets/controller.go
  pkg/fleets/controller_test.go
  pkg/gameserversets/controller.go
  pkg/gameserversets/controller_test.go
  site/content/en/docs/Reference/agones_crd_api_reference.html
  test/e2e/fleet_test.go
Labels: area/user-experience, kind/feature

#802 Fix Down Scale on RollingUpdate
  pkg/fleets/controller.go
  test/e2e/fleet_test.go
Labels: area/user-experience, kind/bug

#806 Correcting the reference to the service account role binding. #805
  install/helm/agones/templates/serviceaccounts/controller.yaml
  install/yaml/install.yaml
Labels: area/operations, kind/cleanup

#810 Add ShutdownReplicas count
  pkg/apis/stable/v1alpha1/gameserverset.go
  pkg/fleets/controller.go
  pkg/gameserversets/controller.go
  site/content/en/docs/Reference/agones_crd_api_reference.html
  test/e2e/fleet_test.go
Labels: area/user-experience, kind/bug

#812 Flaky: TestAutoscalerWebhook
  test/e2e/fleetautoscaler_test.go
Labels: area/tests, kind/cleanup

#814 Remove env namespace dependency from allocator service.
  cmd/allocator/main.go
  cmd/allocator/main_test.go
  install/helm/agones/templates/service/allocation.yaml
  install/yaml/install.yaml
  test/e2e/allocator_test.go
Labels: area/user-experience, kind/cleanup

#815 Handle delete events when caching Ready GameServers for Allocation
  pkg/gameserverallocations/controller.go
  pkg/gameserverallocations/controller_test.go
Labels: kind/cleanup

#807 Update Locust to 0.9 image and set cpu requests/limits
  test/load/locust-files/gameserver_allocation.py
Labels: area/performance, area/tests

#823 Move lifecycle diagram to use GameServerAllocation
  site/content/en/docs/Guides/gameserver-lifecycle.md
  site/static/diagrams/gameserver-lifecycle.puml
  site/static/diagrams/gameserver-lifecycle.puml.png
Labels: kind/cleanup, kind/documentation

#821 Fix header alignment on Fleet Reference
  site/content/en/docs/Reference/fleet.md
Labels: kind/cleanup, kind/documentation

#819 --promote on development site
  cloudbuild.yaml
Labels: area/site, kind/cleanup

#816 Flaky: TestHealthControllerRun
  pkg/gameservers/controller.go
  pkg/gameservers/health.go
  pkg/gameservers/health_test.go
Labels: area/tests, kind/cleanup

#822 Fix instructions for getting pprof information from controller
  build/README.md
Labels: area/build-tools, kind/cleanup, kind/documentation

#824 Rewrite Agones Overview
  site/content/en/docs/Installation/_index.md
  site/content/en/docs/Overview/_index.md
Labels: kind/documentation, kind/feature

#804 Batched Packed and Distributed Allocations
  pkg/gameserverallocations/cache.go
  pkg/gameserverallocations/controller.go
  pkg/gameserverallocations/controller_test.go
  pkg/gameserverallocations/find.go
  pkg/gameserverallocations/find_test.go
Labels: area/performance, kind/feature

#776 Fixing SDK proto file according to style guide
  pkg/sdk/sdk.pb.go
  sdk.proto
  sdk.swagger.json
  sdks/cpp/include/agones/sdk.pb.h
  sdks/cpp/src/agones/sdk.pb.cc
  sdks/nodejs/lib/sdk_pb.js
  sdks/rust/src/grpc/sdk.rs
Labels: kind/breaking, kind/cleanup

#828 fix: check if NodeExternalIP is empty to fallback to NodeInternalIP
  pkg/gameservers/controller.go
Labels: area/user-experience, kind/feature

#827 Flaky: TestControllerSyncFleetAutoscaler
  pkg/fleetautoscalers/controller.go
  pkg/fleetautoscalers/controller_test.go
Labels: area/tests, kind/cleanup

#832 More Google Inc. -> Google LLC Licence changes.
  build/build-sdk-images/cpp/Dockerfile
  build/build-sdk-images/cpp/build.sh
  build/build-sdk-images/cpp/gen.sh
  build/build-sdk-images/go/Dockerfile
  build/build-sdk-images/go/gen.sh
  build/build-sdk-images/go/test.sh
  build/build-sdk-images/node/Dockerfile
  build/build-sdk-images/node/gen.sh
  build/build-sdk-images/node/test.sh
  build/build-sdk-images/rust/Dockerfile
  build/build-sdk-images/tool/base/entrypoint.sh
  build/build-sdk-images/tool/template/Dockerfile
  build/build-sdk-images/tool/template/build.sh
  build/build-sdk-images/tool/template/gen.sh
  build/build-sdk-images/tool/template/test.sh
  build/includes/sdk.mk
  pkg/apis/allocation/v1alpha1/doc.go
  pkg/apis/allocation/v1alpha1/register.go
  pkg/gameserverallocations/cache.go
  pkg/gameserverallocations/cache_test.go
  pkg/gameserverallocations/find_test.go
  sdks/rust/src/types.rs
  sdks/unreal/Agones/Source/Agones/Agones.Build.cs
  sdks/unreal/Agones/Source/Agones/Agones.cpp
  sdks/unreal/Agones/Source/Agones/AgonesHook.cpp
  sdks/unreal/Agones/Source/Agones/AgonesHook.h
  sdks/unreal/Agones/Source/Agones/AgonesSettings.cpp
  sdks/unreal/Agones/Source/Agones/Public/Agones.h
  sdks/unreal/Agones/Source/Agones/Public/AgonesSettings.h
Labels: kind/cleanup

#818 Add Unity SDK
  sdks/unity/AgonesSdk.cs
  site/content/en/docs/Guides/Client SDKs/unity.md
Labels: area/user-experience, kind/feature

#830 Changed AllocationEndpoint to array of endpoints
  install/helm/agones/templates/crds/gameserverallocationpolicy.yaml
  install/yaml/install.yaml
  pkg/apis/multicluster/v1alpha1/gameserverallocationpolicy.go
  pkg/apis/multicluster/v1alpha1/gameserverallocationpolicy_test.go
  pkg/gameserverallocations/controller.go
  pkg/gameserverallocations/controller_test.go
  test/e2e/gameserverallocation_test.go
Labels: area/user-experience, kind/feature

#833 Remove GSA Experimental warnings.
  examples/gameserverallocation.yaml
  examples/simple-udp/gameserverallocation.yaml
  examples/xonotic/gameserverallocation.yaml
Labels: area/examples, kind/cleanup

#834 E2E test for Ready->Allocated->Ready
  build/Makefile
  examples/fleet.yaml
  examples/simple-udp/Makefile
  examples/simple-udp/fleet-distributed.yaml
  examples/simple-udp/fleet.yaml
  examples/simple-udp/gameserver-passthrough.yaml
  examples/simple-udp/gameserver.yaml
  examples/simple-udp/gameserverset.yaml
  examples/simple-udp/main.go
  install/helm/agones/templates/NOTES.txt
  site/content/en/docs/Advanced/limiting-resources.md
  site/content/en/docs/Advanced/scheduling-and-autoscaling.md
  site/content/en/docs/Advanced/service-accounts.md
  site/content/en/docs/Getting Started/create-fleet.md
  site/content/en/docs/Getting Started/create-gameserver.md
  site/content/en/docs/Guides/access-api.md
  test/e2e/framework/framework.go
  test/e2e/gameserver_test.go
  test/e2e/gameserverallocation_test.go
  test/e2e/main_test.go
  test/e2e/ping_test.go
Labels: area/tests

#836 Move all to https://github.com/googleforgames/agones
  README.md
  build/Makefile
  build/README.md
  docs/governance/templates/release.md
  docs/governance/templates/release_issue.md
  examples/allocator-service/dockerfile
  examples/fleet.yaml
  examples/terraform-submodules/aks/module.tf
  examples/terraform-submodules/gke/module.tf
  install/helm/agones/Chart.yaml
  install/helm/agones/templates/NOTES.txt
  pkg/util/apiserver/apiserver.go
  sdks/cpp/CMakeLists.txt
  sdks/nodejs/package.json
  sdks/unreal/Agones/Agones.uplugin
  site/config.toml
  site/content/en/_index.html
  site/content/en/docs/Contribute/_index.md
  site/content/en/docs/Getting Started/create-fleet.md
  site/content/en/docs/Getting Started/create-fleetautoscaler.md
  site/content/en/docs/Getting Started/create-gameserver.md
  site/content/en/docs/Getting Started/create-webhook-fleetautoscaler.md
  site/content/en/docs/Guides/Client SDKs/_index.md
  site/content/en/docs/Guides/Client SDKs/cpp.md
  site/content/en/docs/Guides/Client SDKs/local.md
  site/content/en/docs/Guides/Client SDKs/unreal.md
  site/content/en/docs/Installation/_index.md
  site/content/en/docs/Reference/fleet.md
  site/vanity.yaml
Labels: area/examples, kind/cleanup, kind/documentation

#838 Flaky: TestFleetRollingUpdate
  test/e2e/fleet_test.go
Labels: area/tests, kind/cleanup

#837 Flaky: TestSDKSetAnnotation
  pkg/apis/stable/v1alpha1/gameserver.go
  pkg/apis/stable/v1alpha1/gameserver_test.go
  test/e2e/gameserver_test.go
Labels: area/tests, kind/cleanup

#839 Flaky: TestAllocator
  test/e2e/allocator_test.go
Labels: area/tests, kind/cleanup

#840 Flaky: TestFleetRecreateGameServers
  test/e2e/fleet_test.go
Labels: area/tests, kind/cleanup

#835 Implement EnqueueAfter on WorkerQueue
  pkg/util/workerqueue/workerqueue.go
  pkg/util/workerqueue/workerqueue_test.go
Labels: kind/feature

#842 Release 0.11.0-rc
  CHANGELOG.md
  build/includes/release.mk
  docs/governance/release_process.md
  docs/governance/templates/release_issue.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  site/content/en/blog/releases/0.10.0.md
  site/content/en/blog/releases/0.11.0-rc.md
Labels: kind/release

#843 Set secret namespace to agones-system for allocator service
  install/helm/agones/certs/allocator/client-ca/ca.crt
  install/helm/agones/certs/allocator/server.crt
  install/helm/agones/certs/allocator/server.key
  install/helm/agones/templates/service/allocation.yaml
  install/yaml/install.yaml
Labels: area/user-experience, kind/bug

#844 Flaky: TestAutoscalerWebhook
  test/e2e/fleetautoscaler_test.go
Labels: area/tests, kind/cleanup

#852 Preparation for 0.12.0 sprint
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
Labels: kind/cleanup
