Repository googleforgames/agones, pull requests merged in 2019-07, with the labels that each got.

#862 Fix for podtemplatespec link
  site/content/en/docs/Reference/gameserver.md
Labels: kind/cleanup, kind/documentation

#856 Remove FleetAllocation.
  cmd/controller/main.go
  examples/allocator-service/Dockerfile
  examples/allocator-service/README.md
  examples/allocator-service/main.go
  examples/allocator-service/service-account.yaml
  examples/fleet.yaml
  examples/fleetallocation.yaml
  examples/simple-udp/fleetallocation.yaml
  examples/xonotic/fleetallocation.yaml
  install/helm/agones/scripts/delete_agones_resources.sh
  install/helm/agones/templates/crds/fleetallocation.yaml
  install/helm/agones/templates/extensions.yaml
  install/helm/agones/templates/hooks/sa.yaml
  install/helm/agones/templates/serviceaccounts/controller.yaml
  install/yaml/install.yaml
  pkg/apis/stable/v1alpha1/fleetallocation.go
  pkg/apis/stable/v1alpha1/fleetallocation_test.go
  pkg/apis/stable/v1alpha1/register.go
  pkg/apis/stable/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/stable/v1alpha1/fake/fake_fleetallocation.go
  pkg/client/clientset/versioned/typed/stable/v1alpha1/fake/fake_stable_client.go
  pkg/client/clientset/versioned/typed/stable/v1alpha1/fleetallocation.go
  pkg/client/clientset/versioned/typed/stable/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/stable/v1alpha1/stable_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/stable/v1alpha1/fleetallocation.go
  pkg/client/informers/externalversions/stable/v1alpha1/interface.go
  pkg/client/listers/stable/v1alpha1/expansion_generated.go
  pkg/client/listers/stable/v1alpha1/fleetallocation.go
  pkg/fleetallocation/controller.go
  pkg/fleetallocation/controller_test.go
  pkg/fleetallocation/doc.go
  pkg/fleetallocation/find.go
  pkg/fleetallocation/find_test.go
  pkg/metrics/controller.go
  pkg/metrics/controller_metrics.go
  pkg/metrics/controller_test.go
  pkg/metrics/util_test.go
  pkg/util/logfields/logfields.go
  site/content/en/docs/Reference/agones_crd_api_reference.html
  test/e2e/fleet_test.go
  test/e2e/fleetautoscaler_test.go
  test/e2e/framework/framework.go
Labels: area/user-experience, kind/cleanup

#820 Reserve proto definition and generated code
  pkg/sdk/sdk.pb.go
  pkg/sdk/sdk.pb.gw.go
  pkg/sdkserver/localsdk.go
  pkg/sdkserver/sdkserver.go
  sdk.proto
  sdk.swagger.json
  sdks/cpp/include/agones/sdk.grpc.pb.h
  sdks/cpp/include/agones/sdk.pb.h
  sdks/cpp/src/agones/sdk.grpc.pb.cc
  sdks/cpp/src/agones/sdk.pb.cc
  sdks/go/sdk_test.go
  sdks/nodejs/lib/sdk_grpc_pb.js
  sdks/nodejs/lib/sdk_pb.js
  sdks/rust/src/grpc/sdk.rs
  sdks/rust/src/grpc/sdk_grpc.rs
Labels: area/user-experience, kind/feature

#847 Update CPP Example Readme and yaml files
  examples/cpp-simple/README.md
  examples/cpp-simple/fleet.yaml
  examples/cpp-simple/gameserver.yaml
Labels: area/examples, kind/cleanup

#846 Add Unity to the SDK page.
  site/content/en/docs/Guides/Client SDKs/_index.md
  site/content/en/docs/Guides/Client SDKs/cpp.md
  site/content/en/docs/Guides/Client SDKs/unity.md
Labels: kind/cleanup, kind/documentation

#864 Unreal Engine plugin - Health Ping Enabled to true by default
  sdks/unreal/Agones/Source/Agones/AgonesSettings.cpp
Labels: area/user-experience, kind/cleanup

#866 Add events to SDK state change operations
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  pkg/sdkserver/sdkserver.go
  pkg/sdkserver/sdkserver_test.go
Labels: area/user-experience, kind/feature

#863 Flaky: TestGameServerPassthroughPort
  pkg/sdkserver/sdkserver.go
  pkg/sdkserver/sdkserver_test.go
Labels: area/user-experience, kind/bug

#867 Remove / Expire FleetAllocation from documentation.
  site/content/en/docs/Examples/_index.md
  site/content/en/docs/Getting Started/create-fleet.md
  site/content/en/docs/Getting Started/create-fleetautoscaler.md
  site/content/en/docs/Getting Started/create-webhook-fleetautoscaler.md
  site/content/en/docs/Guides/Client SDKs/_index.md
  site/content/en/docs/Guides/access-api.md
  site/content/en/docs/Reference/fleet.md
  site/content/en/docs/Tutorials/allocator-service-go.md
Labels: kind/cleanup, kind/documentation

#869 Docs: Centralise udp-server tag
  site/config.toml
  site/content/en/docs/Advanced/limiting-resources.md
  site/content/en/docs/Advanced/scheduling-and-autoscaling.md
  site/content/en/docs/Advanced/service-accounts.md
  site/content/en/docs/Getting Started/create-fleet.md
  site/content/en/docs/Getting Started/create-gameserver.md
  site/content/en/docs/Guides/access-api.md
  site/layouts/shortcodes/example-image.html
Labels: area/site, kind/cleanup

#877 Fix for CRD API docs generator
  pkg/apis/stable/v1alpha1/gameserver.go
  pkg/apis/stable/v1alpha1/gameserverset.go
  site/content/en/docs/Reference/agones_crd_api_reference.html
  site/gen-api-docs.sh
Labels: kind/cleanup, kind/documentation

#874 Promote autoscaling to v1
  build/build-image/Dockerfile
  build/build-image/gen-crd-client.sh
  examples/autoscaler-webhook/main.go
  examples/fleetautoscaler.yaml
  examples/simple-udp/fleetautoscaler.yaml
  examples/webhookfleetautoscaler.yaml
  examples/webhookfleetautoscalertls.yaml
  examples/xonotic/fleetautoscaler.yaml
  install/helm/agones/templates/crds/fleetautoscaler.yaml
  install/helm/agones/templates/extensions.yaml
  install/yaml/install.yaml
  pkg/apis/autoscaling/v1/doc.go
  pkg/apis/autoscaling/v1/fleetautoscaler.go
  pkg/apis/autoscaling/v1/fleetautoscaler_test.go
  pkg/apis/autoscaling/v1/register.go
  pkg/apis/autoscaling/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/autoscaling/v1/autoscaling_client.go
  pkg/client/clientset/versioned/typed/autoscaling/v1/doc.go
  pkg/client/clientset/versioned/typed/autoscaling/v1/fake/doc.go
  pkg/client/clientset/versioned/typed/autoscaling/v1/fake/fake_autoscaling_client.go
  pkg/client/clientset/versioned/typed/autoscaling/v1/fake/fake_fleetautoscaler.go
  pkg/client/clientset/versioned/typed/autoscaling/v1/fleetautoscaler.go
  pkg/client/clientset/versioned/typed/autoscaling/v1/generated_expansion.go
  pkg/client/informers/externalversions/autoscaling/interface.go
  pkg/client/informers/externalversions/autoscaling/v1/fleetautoscaler.go
  pkg/client/informers/externalversions/autoscaling/v1/interface.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/autoscaling/v1/expansion_generated.go
  pkg/client/listers/autoscaling/v1/fleetautoscaler.go
  pkg/fleetautoscalers/controller.go
  pkg/fleetautoscalers/controller_test.go
  pkg/fleetautoscalers/fleetautoscalers.go
  pkg/fleetautoscalers/fleetautoscalers_test.go
  pkg/metrics/controller.go
  pkg/metrics/util_test.go
  site/content/en/docs/Getting Started/create-fleetautoscaler.md
  site/content/en/docs/Getting Started/create-webhook-fleetautoscaler.md
  site/content/en/docs/Reference/agones_crd_api_reference.html
  site/content/en/docs/Reference/fleetautoscaler.md
  test/e2e/fleetautoscaler_test.go
  test/e2e/framework/framework.go
Labels: area/user-experience, kind/feature

#873 Update gen-sdk-grpc make target name.
  build/README.md
Labels: area/build-tools, kind/cleanup, kind/documentation

#848 SDK Conformance testing
  build/Makefile
  build/README.md
  build/build-sdk-images/go/sdktest.sh
  build/build-sdk-images/node/build.sh
  build/build-sdk-images/node/clean.sh
  build/build-sdk-images/node/sdktest.sh
  build/includes/build-image.mk
  build/includes/sdk.mk
  cloudbuild.yaml
  cmd/sdk-server/main.go
  examples/nodejs-simple/src/index.js
  pkg/sdkserver/localsdk.go
  pkg/sdkserver/localsdk_test.go
  sdks/nodejs/spec/agonesSDK.spec.js
  sdks/nodejs/src/agonesSDK.js
  sdks/nodejs/src/index.js
  site/content/en/docs/Guides/Client SDKs/_index.md
  test/sdk/go/sdk-client-test.go
  test/sdk/nodejs/package.json
  test/sdk/nodejs/testSDKClient.js
Labels: area/tests, kind/feature

#882 Last touches to the install guide regarding taints and tolerations
  site/content/en/docs/Installation/_index.md
Labels: kind/cleanup, kind/documentation

#886 Document SDK - Allocated->Ready()
  site/content/en/docs/Guides/Client SDKs/_index.md
Labels: kind/cleanup, kind/documentation

#880 Make GameServerAllocation reference document
  site/content/en/docs/Getting Started/create-fleet.md
  site/content/en/docs/Guides/Client SDKs/_index.md
  site/content/en/docs/Guides/Client SDKs/rest.md
  site/content/en/docs/Guides/metrics.md
  site/content/en/docs/Reference/fleet.md
  site/content/en/docs/Reference/gameserverallocation.md
Labels: kind/cleanup, kind/documentation

#885 Small improvements to create-fleet quickstart
  site/content/en/docs/Getting Started/create-fleet.md
Labels: kind/cleanup, kind/documentation

#865 Add ReserveUntil to GameServer.Status
  pkg/apis/stable/v1alpha1/gameserver.go
  pkg/apis/stable/v1alpha1/zz_generated.deepcopy.go
  site/content/en/docs/Reference/agones_crd_api_reference.html
Labels: area/user-experience, kind/feature

#887 Update GKE development tooling to 1.12
  build/README.md
  build/build-image/Dockerfile
  build/gke-test-cluster/cluster-e2e.yml
  build/gke-test-cluster/cluster.yml.jinja
  build/includes/google-cloud.mk
Labels: area/build-tools, kind/feature

#888 Explicitly disable creation of the client certificate on GKE
  build/cluster.tf
  build/modules/gke/cluster.tf
  build/modules/gke/outputs.tf
Labels: area/operations, kind/cleanup

#881 Promote allocation to v1
  build/build-image/Dockerfile
  build/build-image/gen-crd-client.sh
  cmd/allocator/main.go
  cmd/allocator/main_test.go
  examples/allocator-service/main.go
  examples/gameserverallocation.yaml
  examples/simple-udp/gameserverallocation.yaml
  examples/xonotic/gameserverallocation.yaml
  install/helm/agones/templates/extensions.yaml
  install/yaml/install.yaml
  pkg/apis/allocation/v1/doc.go
  pkg/apis/allocation/v1/gameserverallocation.go
  pkg/apis/allocation/v1/gameserverallocation_test.go
  pkg/apis/allocation/v1/register.go
  pkg/apis/allocation/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/allocation/v1/allocation_client.go
  pkg/client/clientset/versioned/typed/allocation/v1/doc.go
  pkg/client/clientset/versioned/typed/allocation/v1/fake/doc.go
  pkg/client/clientset/versioned/typed/allocation/v1/fake/fake_allocation_client.go
  pkg/client/clientset/versioned/typed/allocation/v1/fake/fake_gameserverallocation.go
  pkg/client/clientset/versioned/typed/allocation/v1/gameserverallocation.go
  pkg/client/clientset/versioned/typed/allocation/v1/generated_expansion.go
  pkg/gameserverallocations/controller.go
  pkg/gameserverallocations/controller_test.go
  pkg/gameserverallocations/find.go
  pkg/gameserverallocations/find_test.go
  pkg/util/apiserver/apiserver_test.go
  site/content/en/docs/Getting Started/create-fleet.md
  site/content/en/docs/Guides/access-api.md
  site/content/en/docs/Reference/agones_crd_api_reference.html
  test/e2e/allocator_test.go
  test/e2e/fleet_test.go
  test/e2e/framework/framework.go
  test/e2e/gameserverallocation_test.go
  test/load/locust-files/gameserver_allocation.py
Labels: area/user-experience, kind/breaking, kind/feature

#890 Fix timeout on Terraform Helm install agones step
  build/helm.tf
Labels: area/operations, kind/bug

#879 Fix Rust SDK, add allocate, add conformance test
  build/build-sdk-images/rust/Dockerfile
  build/build-sdk-images/rust/build.sh
  build/build-sdk-images/rust/clean.sh
  build/build-sdk-images/rust/sdktest.sh
  build/includes/sdk.mk
  sdks/rust/src/sdk.rs
  sdks/rust/src/types.rs
  test/sdk/rust/Cargo.toml
  test/sdk/rust/src/main.rs
Labels: area/user-experience, kind/feature

#897 Update GKE documentation to 1.12
  build/includes/google-cloud.mk
  site/content/en/docs/Installation/_index.md
Labels: kind/documentation, kind/feature

#895 Update minikube documentation and dev tooling to 1.12
  build/includes/minikube.mk
  site/content/en/docs/Guides/troubleshooting.md
  site/content/en/docs/Installation/_index.md
Labels: area/build-tools, kind/cleanup

#803 Cpp prerequisities cmake
  sdks/cpp/CMakeLists.txt
  sdks/cpp/build_scripts/msvs_2017_x64_release.bat
  sdks/cpp/cmake/agonesConfig.cmake.in
  sdks/cpp/cmake/prerequisites.cmake
  site/content/en/docs/Guides/Client SDKs/cpp.md
Labels: area/user-experience, kind/cleanup

#898 Fix minikube developer experience
  build/includes/minikube.mk
Labels: area/build-tools, kind/bug

#896 Update kind dev tooling to 1.12
  build/README.md
  build/includes/kind.mk
Labels: area/build-tools, kind/cleanup, kind/documentation

#904 fix: Fix gRCP context leaks.
  sdks/cpp/include/agones/sdk.h
  sdks/cpp/src/agones/sdk.cc
Labels: area/performance, kind/bug, kind/cleanup

#891 Reserve() SDK implementation
  pkg/sdkserver/sdkserver.go
  pkg/sdkserver/sdkserver_test.go
  sdks/go/sdk.go
  sdks/go/sdk_test.go
  site/content/en/docs/Guides/Client SDKs/_index.md
Labels: area/user-experience, kind/breaking, kind/feature

#916 Fix the command to teardown the test cluster in the GKE developer instructions.
  build/README.md
Labels: area/build-tools, kind/cleanup

#919 Flaky - e2e cp: cannot stat
  build/e2e-image/entrypoint.sh
Labels: area/tests, kind/bug

#921 Fixup the formatting on Fleet Getting Started Guide
  site/content/en/docs/Getting Started/create-fleet.md
Labels: area/site, kind/cleanup

#913 Fix Rust SDK conformance flakiness, add clean step
  build/README.md
  build/build-sdk-images/node/build-sdk-test.sh
  build/build-sdk-images/rust/build-sdk-test.sh
  build/build-sdk-images/rust/clean.sh
  build/includes/sdk.mk
  test/sdk/rust/src/main.rs
Labels: area/tests, kind/cleanup

#923 Fix a small typo.
  build/build-sdk-images/tool/template/build.sh
Labels: area/build-tools

#926 Flaky: Make preview --no-promote to avoid promotion race conditions
  cloudbuild.yaml
Labels: area/tests, kind/cleanup

#928 Update K8s Code Generation Tooling to 1.12
  build/Makefile
  build/build-image/Dockerfile
  examples/fleet.yaml
  examples/simple-udp/Makefile
  examples/simple-udp/dev-gameserver.yaml
  examples/simple-udp/fleet-distributed.yaml
  examples/simple-udp/fleet.yaml
  examples/simple-udp/gameserver-passthrough.yaml
  examples/simple-udp/gameserver.yaml
  examples/simple-udp/gameserverset.yaml
  install/helm/agones/templates/NOTES.txt
  pkg/apis/agones/v1/zz_generated.deepcopy.go
  pkg/apis/allocation/v1/zz_generated.deepcopy.go
  pkg/apis/autoscaling/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/agones/v1/fake/fake_fleet.go
  pkg/client/clientset/versioned/typed/agones/v1/fake/fake_gameserver.go
  pkg/client/clientset/versioned/typed/agones/v1/fake/fake_gameserverset.go
  pkg/client/clientset/versioned/typed/agones/v1/fleet.go
  pkg/client/clientset/versioned/typed/agones/v1/gameserver.go
  pkg/client/clientset/versioned/typed/agones/v1/gameserverset.go
  pkg/client/clientset/versioned/typed/autoscaling/v1/fake/fake_fleetautoscaler.go
  pkg/client/clientset/versioned/typed/autoscaling/v1/fleetautoscaler.go
  pkg/client/informers/externalversions/agones/v1/fleet.go
  pkg/client/informers/externalversions/agones/v1/gameserver.go
  pkg/client/informers/externalversions/agones/v1/gameserverset.go
  pkg/client/informers/externalversions/autoscaling/v1/fleetautoscaler.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/multicluster/v1alpha1/gameserverallocationpolicy.go
  site/config.toml
  test/e2e/main_test.go
Labels: area/operations, kind/cleanup

#929 Update the dev-gameserver example to use the current udp-server container image.
  site/content/en/docs/Guides/local-game-server.md
Labels: area/examples, kind/cleanup

#930 Updates to the allocator service tutorial.
  examples/allocator-service/Dockerfile
  site/content/en/docs/Tutorials/allocator-service-go.md
Labels: area/examples, kind/cleanup, kind/documentation

#920 Compliance tests for Reserve(seconds).
  build/includes/sdk.mk
  pkg/sdkserver/localsdk.go
  test/sdk/go/sdk-client-test.go
  test/sdk/nodejs/.gitignore
Labels: area/tests, kind/feature

#922 Add new GameServer lifecycle diagrams for Reserved
  build/Makefile
  build/README.md
  build/includes/website.mk
  site/content/en/docs/Contribute/_index.md
  site/content/en/docs/Guides/gameserver-lifecycle.md
  site/static/diagrams/gameserver-reserved.puml
  site/static/diagrams/gameserver-reserved.puml.png
Labels: kind/documentation, kind/feature

#932 With the extra whitespace the rendered output has undesirable new paragraphs.
  site/content/en/docs/Tutorials/allocator-service-go.md
Labels: area/examples, kind/cleanup, kind/documentation

#933 Update GameServer state diagram with Reserved
  site/content/en/docs/Reference/gameserver.md
  site/static/diagrams/gameserver-states.dot
  site/static/diagrams/gameserver-states.dot-0.11.png
  site/static/diagrams/gameserver-states.dot.png
Labels: kind/documentation, kind/feature

#944 Fix indentation of two of the build targets.
  build/README.md
Labels: area/build-tools, kind/cleanup, kind/documentation

#945 Update the nodejs example to build in a docker image
  examples/cpp-simple/README.md
  examples/nodejs-simple/Dockerfile
  examples/nodejs-simple/Makefile
  examples/nodejs-simple/README.md
  examples/nodejs-simple/gameserver.yaml
  examples/nodejs-simple/package-lock.json
  examples/nodejs-simple/src/index.js
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  site/content/en/docs/Tutorials/simple-gameserver-cpp.md
  site/content/en/docs/Tutorials/simple-gameserver-nodejs.md
Labels: area/examples, area/security, area/user-experience, kind/feature

#952 Update the container image version for the simple unity sdk.
  examples/unity-simple/Makefile
  examples/unity-simple/gameserver.yaml
Labels: area/examples, kind/cleanup

#954 Update node.js coverage, dependencies and potential issue
  examples/nodejs-simple/src/index.js
  sdks/nodejs/.eslintrc.json
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/nodejs/spec/agonesSDK.spec.js
  sdks/nodejs/src/agonesSDK.js
Labels: area/security, area/tests, area/user-experience, kind/cleanup

#960 Fix the capitalization for 'publishVersion' in the website docs.
  site/content/en/docs/Advanced/limiting-resources.md
  site/content/en/docs/Advanced/scheduling-and-autoscaling.md
  site/content/en/docs/Advanced/service-accounts.md
  site/content/en/docs/Examples/_index.md
  site/content/en/docs/Getting Started/create-fleet.md
  site/content/en/docs/Getting Started/create-fleetautoscaler.md
  site/content/en/docs/Getting Started/create-gameserver.md
  site/content/en/docs/Guides/Client SDKs/_index.md
  site/content/en/docs/Guides/Client SDKs/rest.md
  site/content/en/docs/Guides/access-api.md
  site/content/en/docs/Guides/local-game-server.md
  site/content/en/docs/Guides/metrics.md
  site/content/en/docs/Installation/_index.md
  site/content/en/docs/Installation/helm.md
  site/content/en/docs/Reference/fleet.md
  site/content/en/docs/Reference/fleetautoscaler.md
  site/content/en/docs/Reference/gameserverallocation.md
Labels: kind/cleanup, kind/documentation

#961 [Fix Breaking CI] Site test failure due to 404s
  site/content/en/blog/releases/0.10.0-rc.md
  site/content/en/blog/releases/0.10.0.md
  site/content/en/blog/releases/0.7.0.md
  site/content/en/blog/releases/0.8.0-rc.md
  site/content/en/blog/releases/0.8.0.md
  site/content/en/docs/Tutorials/allocator-service-go.md
Labels: kind/cleanup, kind/documentation

#953 Implement block on connect with Rust+Node.js SDK
  build/includes/sdk.mk
  sdks/nodejs/spec/agonesSDK.spec.js
  sdks/nodejs/src/agonesSDK.js
  sdks/rust/src/sdk.rs
  site/content/en/docs/Guides/Client SDKs/nodejs.md
  site/content/en/docs/Guides/Client SDKs/rust.md
  test/sdk/nodejs/testSDKClient.js
  test/sdk/rust/.gitignore
  test/sdk/rust/src/main.rs
Labels: area/tests, area/user-experience, kind/bug

#959 Remove GameServer UpdateStatus() since its not being used.
  pkg/apis/agones/v1/gameserver.go
  pkg/client/clientset/versioned/typed/agones/v1/fake/fake_gameserver.go
  pkg/client/clientset/versioned/typed/agones/v1/gameserver.go
  site/content/en/docs/Reference/agones_crd_api_reference.html
Labels: area/user-experience, kind/cleanup

#937 Updates to the rust simple example.
  examples/rust-simple/Makefile
  examples/rust-simple/README.md
  examples/rust-simple/gameserver.yaml
  site/content/en/docs/Tutorials/simple-gameserver-cpp.md
  site/content/en/docs/Tutorials/simple-gameserver-nodejs.md
  site/content/en/docs/Tutorials/simple-gameserver-rust.md
Labels: area/examples, kind/cleanup
