Repository googleforgames/agones, pull requests merged in 2019-02, with the labels that each got.

#544 Changed kubeInformation to kubeInformer.
  cmd/controller/main.go
Labels: kind/cleanup

#550 e2e: improved logging and simplified waiting for fleet conditions
  test/e2e/fleet_test.go
  test/e2e/fleetautoscaler_test.go
  test/e2e/framework/framework.go
  test/e2e/gameserveralloction_test.go
Labels: kind/cleanup

#549 Typo: Docsy -> Agones Blog.
  site/content/en/blog/_index.md
Labels: area/site, kind/cleanup

#539 Add Scale Subresource into Fleet and Gameserverset CRDs
  build/Makefile
  install/helm/agones/templates/crds/fleet.yaml
  install/helm/agones/templates/crds/gameserverset.yaml
  install/yaml/install.yaml
  pkg/apis/stable/v1alpha1/fleet.go
  pkg/apis/stable/v1alpha1/gameserverset.go
  pkg/client/clientset/versioned/typed/stable/v1alpha1/fake/fake_fleet.go
  pkg/client/clientset/versioned/typed/stable/v1alpha1/fake/fake_gameserverset.go
  pkg/client/clientset/versioned/typed/stable/v1alpha1/fleet.go
  pkg/client/clientset/versioned/typed/stable/v1alpha1/gameserverset.go
  site/content/en/docs/Getting Started/create-fleet.md
  site/content/en/docs/Reference/fleet.md
  test/e2e/fleet_test.go
  test/e2e/gameserverallocation_test.go
Labels: area/user-experience, kind/feature

#542 Speed up creation/deletion of game servers in a set
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  pkg/gameserversets/controller.go
  pkg/gameserversets/controller_test.go
  pkg/gameserversets/gameserver_state_cache.go
  pkg/gameserversets/gameserver_state_cache_test.go
  pkg/util/workerqueue/workerqueue.go
Labels: area/performance

#561 Fix prometheous installation on minikube
  build/Makefile
Labels: area/build-tools, kind/cleanup

#548 GameServer Creation, Allocation and Shutdown Lifecycle
  build/Makefile
  build/build-image/Dockerfile
  site/content/en/docs/Getting Started/create-fleet.md
  site/content/en/docs/Guides/gameserver-lifecycle.md
  site/content/en/docs/Reference/gameserver.md
  site/static/diagrams/gameserver-lifecycle.puml
  site/static/diagrams/gameserver-lifecycle.puml.png
  site/static/diagrams/gameserver-states.dot.png
Labels: kind/documentation

#565 Changed how GameServer POD names are generated
  pkg/apis/stable/v1alpha1/gameserver.go
  pkg/apis/stable/v1alpha1/gameserver_test.go
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
Labels: kind/bug

#560 CloudBuild for a "development" subdomain
  site/cloudbuild.yaml
Labels: area/site, kind/documentation

#564 simple-udp: added support for customizing labels and annotations by the caller
  build/Makefile
  examples/fleet.yaml
  examples/simple-udp/Makefile
  examples/simple-udp/fleet.yaml
  examples/simple-udp/gameserver.yaml
  examples/simple-udp/gameserverset.yaml
  examples/simple-udp/main.go
  install/helm/agones/templates/NOTES.txt
  site/content/en/docs/Advanced/limiting-resources.md
  site/content/en/docs/Advanced/scheduling-and-autoscaling.md
  site/content/en/docs/Getting Started/create-fleet.md
  site/content/en/docs/Getting Started/create-gameserver.md
  site/content/en/docs/Guides/access-api.md
  test/e2e/main_test.go
Labels: area/examples, kind/feature

#566 Adding Github link and version dropdown to the navigation bar
  site/layouts/partials/navbar.html
Labels: area/site, kind/feature

#562 added fleet-loadtest.yaml for use in load testing
  examples/simple-udp/fleet-distributed.yaml
Labels: area/examples

#558 Add support to create a development gameserver.
  examples/simple-udp/dev-gameserver.yaml
  pkg/apis/stable/v1alpha1/gameserver.go
  pkg/apis/stable/v1alpha1/gameserver_test.go
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  site/content/en/docs/Guides/local-game-server.md
  test/e2e/gameserver_test.go
Labels: area/user-experience, kind/feature

#579 Removal of allocationMutex from controllers that don't need it.
  cmd/controller/main.go
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  pkg/gameserversets/controller.go
  pkg/gameserversets/controller_test.go
Labels: kind/cleanup

#556 Remove the custom kubectl commands from quickstarts
  site/content/en/docs/Getting Started/create-fleet.md
  site/content/en/docs/Getting Started/create-fleetautoscaler.md
  site/content/en/docs/Getting Started/create-gameserver.md
  site/content/en/docs/Getting Started/create-webhook-fleetautoscaler.md
  site/content/en/docs/Tutorials/allocator-service-go.md
Labels: kind/cleanup, kind/documentation

#576 fix setAnnotation for simple-udp to use customized key & value
  build/Makefile
  examples/fleet.yaml
  examples/simple-udp/Makefile
  examples/simple-udp/fleet-distributed.yaml
  examples/simple-udp/fleet.yaml
  examples/simple-udp/gameserver.yaml
  examples/simple-udp/gameserverset.yaml
  examples/simple-udp/main.go
  install/helm/agones/templates/NOTES.txt
  site/content/en/docs/Advanced/limiting-resources.md
  site/content/en/docs/Advanced/scheduling-and-autoscaling.md
  site/content/en/docs/Getting Started/create-fleet.md
  site/content/en/docs/Getting Started/create-gameserver.md
  site/content/en/docs/Guides/access-api.md
  test/e2e/main_test.go
Labels: area/examples, kind/feature

#580 Update godoc command to enable search
  build/Makefile
Labels: area/build-tools, kind/cleanup

#591 Release 0.8.0-rc
  CHANGELOG.md
  docs/governance/templates/release.md
  docs/governance/templates/release_issue.md
  site/content/en/blog/releases/0.8.0-rc.md
Labels: kind/release

#595 Remove -v from Go testing - becomes too noisy
  build/Makefile
Labels: area/tests, kind/cleanup

#594 Switch to htmltest link checker -- and fix issues
  build/build-image/Dockerfile
  build/includes/website.mk
  docs/governance/templates/release_issue.md
  site/content/en/docs/Contribute/_index.md
  site/content/en/docs/Examples/_index.md
  site/content/en/docs/Getting Started/create-fleet.md
  site/content/en/docs/Guides/Client SDKs/cpp.md
  site/content/en/docs/Guides/Client SDKs/rest.md
  site/content/en/docs/Guides/gameserver-lifecycle.md
  site/content/en/docs/Guides/metrics.md
  site/content/en/docs/Installation/helm.md
  site/content/en/docs/Reference/fleet.md
  site/htmltest.yaml
  site/layouts/partials/page-meta-lastmod.html
  site/layouts/partials/page-meta-links.html
  site/layouts/partials/pager.html
  site/layouts/shortcodes/ghlink.html
  site/layouts/shortcodes/release-branch.html
  site/static/favicons/_head.html
  site/themes/docsy/layouts/partials/pager.html
Labels: area/site, area/tests, kind/bug

#592 Minor tweaks to release process.
  docs/governance/templates/release.md
  docs/governance/templates/release_issue.md
Labels: area/meta, kind/cleanup

#603 Remove deprecation from FleetAllocation
  examples/fleetallocation.yaml
  examples/gameserverallocation.yaml
  examples/simple-udp/fleetallocation.yaml
  examples/simple-udp/gameserverallocation.yaml
  examples/xonotic/fleetallocation.yaml
  examples/xonotic/gameserverallocation.yaml
  pkg/apis/stable/v1alpha1/fleetallocation.go
  site/content/en/docs/Getting Started/create-fleet.md
  site/content/en/docs/Reference/fleet.md
Labels: kind/documentation

#605 Release 0.8.0
  CHANGELOG.md
  docs/governance/templates/release_issue.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  site/config.toml
  site/content/en/blog/releases/0.8.0.md
  site/content/en/docs/Getting Started/create-fleet.md
  site/content/en/docs/Getting Started/create-webhook-fleetautoscaler.md
  site/content/en/docs/Guides/metrics.md
  site/content/en/docs/Installation/helm.md
  site/content/en/docs/Reference/fleet.md
  site/content/en/docs/Reference/fleetautoscaler.md
  site/layouts/partials/navbar.html
  site/layouts/partials/page-meta-links.html
Labels: kind/release

#598 Add Fleet and Gameserverset Validation handler
  install/helm/agones/templates/admissionregistration.yaml
  install/yaml/install.yaml
  pkg/apis/stable/v1alpha1/fleet.go
  pkg/apis/stable/v1alpha1/fleet_test.go
  pkg/apis/stable/v1alpha1/gameserverset.go
  pkg/apis/stable/v1alpha1/gameserverset_test.go
  pkg/fleets/controller.go
  pkg/gameserversets/controller.go
  site/content/en/docs/Reference/fleet.md
  test/e2e/fleet_test.go
Labels: area/user-experience, kind/cleanup

#610 Moving to 0.9.0!
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  site/content/en/blog/releases/0.8.0.md
Labels: kind/release

#582 Update GameServerSet scheduling when Fleet scheduling is changed.
  pkg/fleets/controller.go
  pkg/fleets/controller_test.go
  test/e2e/fleet_test.go
  test/e2e/framework/framework.go
Labels: area/user-experience, kind/bug

#615 Organising Makefile into includes
  build/Makefile
  build/includes/google-cloud.mk
  build/includes/kind.mk
  build/includes/minikube.mk
  build/includes/release.mk
Labels: area/build-tools, kind/cleanup

#612 Upgraed go-lint tooling.
  build/build-image/Dockerfile
  pkg/gameserversets/gameserver_state_cache.go
Labels: area/build-tools, kind/cleanup

#618 New logo for the website!
  README.md
  docs/agones.png
  docs/logos/print/CMYK.ai
  docs/logos/web/RGB.ai
  docs/logos/web/jpeg/high/Full-Color.jpg
  docs/logos/web/jpeg/high/Negative-DarkBlue.jpg
  docs/logos/web/jpeg/high/Negative-LightBlue.jpg
  docs/logos/web/jpeg/low/Full-Color.jpg
  docs/logos/web/jpeg/low/Negative-DarkBlue.jpg
  docs/logos/web/jpeg/low/Negative-LightBlue.jpg
  docs/logos/web/png/high/Full-Color.png
  docs/logos/web/png/high/LightBlue.png
  docs/logos/web/png/high/Negative-DarkBlue.png
  docs/logos/web/png/low/Full-Color.png
  docs/logos/web/png/low/Negative-DarkBlue.png
  docs/logos/web/png/low/Negative-LightBlue.png
  site/assets/icons/logo.svg
  site/layouts/partials/favicons.html
  site/static/favicons/apple-touch-icon-180x180.png
  site/static/favicons/browserconfig.xml
  site/static/favicons/favicon-16x16.png
  site/static/favicons/favicon-32x32.png
  site/static/favicons/favicon.ico
  site/static/favicons/pwa-192x192.png
  site/static/favicons/pwa-512x512.png
  site/static/favicons/tile150x150.png
  site/static/favicons/tile310x150.png
  site/static/favicons/tile310x310.png
  site/static/favicons/tile70x70.png
Labels: area/meta, area/site

#617 Consistency: Portpolicy static=>Static & dynamic=>Dynamic
  examples/cpp-simple/fleet.yaml
  examples/cpp-simple/gameserver.yaml
  examples/fleet.yaml
  examples/gameserver.yaml
  examples/rust-simple/gameserver.yaml
  examples/simple-udp/dev-gameserver.yaml
  examples/simple-udp/gameserver.yaml
  examples/simple-udp/gameserverset.yaml
  examples/xonotic/fleet.yaml
  examples/xonotic/gameserver.yaml
  install/helm/agones/templates/crds/_gameserverspecvalidation.yaml
  install/yaml/install.yaml
  pkg/apis/stable/v1alpha1/gameserver.go
  site/content/en/docs/Advanced/limiting-resources.md
  site/content/en/docs/Getting Started/create-fleet.md
  site/content/en/docs/Getting Started/create-gameserver.md
  site/content/en/docs/Guides/access-api.md
  site/content/en/docs/Guides/local-game-server.md
  site/content/en/docs/Reference/fleet.md
  site/content/en/docs/Reference/gameserver.md
Labels: kind/breaking, kind/cleanup

#575 Add status subresource to fleet and Gameserverset
  install/helm/agones/templates/crds/fleet.yaml
  install/helm/agones/templates/crds/gameserverset.yaml
  install/helm/agones/templates/serviceaccounts/controller.yaml
  install/yaml/install.yaml
  pkg/fleets/controller.go
  pkg/fleets/controller_test.go
  pkg/gameserversets/controller.go
Labels: kind/cleanup

#616 Unified logging of resource identifiers so that we can reliably get entire history of a resource in stack driver.
  pkg/fleetautoscalers/controller.go
  pkg/fleets/controller.go
  pkg/gameserverallocations/controller.go
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  pkg/gameservers/health.go
  pkg/gameserversets/controller.go
  pkg/sdkserver/sdkserver.go
  pkg/util/logfields/logfields.go
  pkg/util/workerqueue/workerqueue.go
  pkg/util/workerqueue/workerqueue_test.go
Labels: kind/cleanup

#583 Improve allocation performance
  build/Makefile
  build/gke-test-cluster/cluster.yml.jinja
  cmd/controller/main.go
  pkg/apis/stable/v1alpha1/gameserverallocation.go
  pkg/gameserverallocations/controller.go
  pkg/gameserverallocations/controller_test.go
  site/content/en/docs/Getting Started/create-fleet.md
  test/e2e/gameserver_test.go
  test/e2e/gameserverallocation_test.go
Labels: area/performance, area/user-experience

#627 Update docs Create Gameserver with current state
  site/content/en/docs/Getting Started/create-gameserver.md
Labels: kind/cleanup
