Repository googleforgames/agones, pull requests merged in 2019-10, with the labels that each got.

#1019 Build examples make target
  build/README.md
  build/includes/sdk.mk
  examples/cpp-simple/Dockerfile
  examples/xonotic/Dockerfile
Labels: area/examples, area/tests, size/M

#1077 Fixes, more e2e tests and logging for multi-cluster allocation
  cmd/allocator/main.go
  install/helm/agones/templates/crds/gameserverallocationpolicy.yaml
  install/yaml/install.yaml
  pkg/apis/multicluster/v1alpha1/gameserverallocationpolicy.go
  pkg/gameserverallocations/allocator.go
  pkg/gameserverallocations/controller_test.go
  test/e2e/allocator_test.go
  test/e2e/fleet_test.go
  test/e2e/fleetautoscaler_test.go
  test/e2e/framework/framework.go
  test/e2e/gameserver_test.go
  test/e2e/gameserverallocation_test.go
Labels: size/XL

#1065 Add func to wait for fleet condition without Fatalf
  test/e2e/allocator_test.go
  test/e2e/fleet_test.go
  test/e2e/fleetautoscaler_test.go
  test/e2e/framework/framework.go
  test/e2e/gameserverallocation_test.go
Labels: area/tests, kind/cleanup, size/L

#1086 Use environment variables to dynamically set the grpc port in the golang sdk.
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  sdks/go/sdk.go
  site/content/en/docs/Guides/Client SDKs/_index.md
  site/content/en/docs/Guides/Client SDKs/rest.md
  site/content/en/docs/Guides/Client SDKs/unreal.md
Labels: area/user-experience, kind/feature, lgtm, size/L

#1094 Fix install.yaml
  install/helm/agones/templates/crds/_gameserverspecvalidation.yaml
  install/yaml/install.yaml
Labels: lgtm, size/L

#1096 Fix the log output when starting the grpc gateway in the sdkserver
  cmd/sdk-server/main.go
Labels: kind/cleanup, lgtm, size/XS

#1101 Fix metrics bug for when a gameserver is not retrievable
  pkg/gameserverallocations/metrics.go
Labels: lgtm, size/XS

#1097 Ran `npm audit fix` to update package dependencies.
  sdks/nodejs/package-lock.json
Labels: lgtm, size/S

#1095 Use non-ephemeral port for Go SDK conformance test
  build/includes/sdk.mk
  cmd/sdk-server/Dockerfile
Labels: lgtm, size/S

#1103 Add AltaVR logo to companies using Agones
  site/content/en/_index.html
  site/static/images/altavr-logo.png
Labels: lgtm, size/XS

#1108 Improve fleet controller response times in busy clusters.
  pkg/fleetautoscalers/controller.go
  pkg/fleets/controller.go
  pkg/gameserversets/controller.go
  pkg/util/workerqueue/workerqueue.go
Labels: lgtm, size/S

#1093 Use an environment variable to dynamically set the grpc port in the nodejs sdk
  sdks/nodejs/spec/agonesSDK.spec.js
  sdks/nodejs/src/agonesSDK.js
Labels: lgtm, size/M

#1110 Move allocation proto to root level proto
  proto/allocation/v1alpha1/allocation.proto
Labels: lgtm, size/XS

#1100 Remove required multi-cluster allocation policy fields that are not required
  install/helm/agones/templates/crds/gameserverallocationpolicy.yaml
  install/yaml/install.yaml
Labels: size/XS

#1041 Adding make file to generate allocation go from proto
  build/Makefile
  build/build-allocation-images/go/Dockerfile
  build/build-allocation-images/go/gen.sh
  build/includes/allocation.mk
  pkg/allocation/go/allocation.gw.pb.go
  pkg/allocation/go/allocation.pb.go
  pkg/allocation/go/allocation.swagger.json
Labels: lgtm, size/XXL

#1113 Move the owners file to the root of the repository.
  OWNERS
Labels: lgtm, size/XS

#1118 Add owners files for the C++ code
  examples/cpp-simple/OWNERS
  sdks/cpp/OWNERS
Labels: approved, do-not-merge/invalid-owners-file, lgtm, size/XS

#1092 Set the port to connect to the sdkserver based on the AGONES_SDK_GRPC_PORT environment variable
  examples/cpp-simple/server.cc
  sdks/cpp/src/agones/sdk.cc
Labels: approved, size/S

#1117 Implement converters between the GameServerAllocation API and allocation.proto
  build/build-allocation-images/go/gen.sh
  pkg/allocation/converters/converter.go
  pkg/allocation/converters/converter_test.go
  pkg/allocation/go/v1alpha1/allocation.gw.pb.go
  pkg/allocation/go/v1alpha1/allocation.pb.go
  pkg/allocation/go/v1alpha1/allocation.swagger.json
Labels: approved, lgtm, size/XL

#1123 Change the API for allocator to allocation.proto
  cmd/allocator/main.go
  cmd/allocator/main_test.go
  pkg/gameserverallocations/allocator.go
  pkg/gameserverallocations/controller_test.go
  test/e2e/allocator_test.go
Labels: approved, kind/breaking, lgtm, size/L

#1111 Run all SDK conformance tests in parallel
  build/build-sdk-images/rust/build-sdk-test.sh
  build/build-sdk-images/rust/sdktest.sh
  build/includes/sdk.mk
  cloudbuild.yaml
  test/sdk/nodejs/testSDKClient.js
Labels: lgtm, size/M

#1122 Faster subsequent Rust SDK conformance builds
  build/build-sdk-images/rust/build-sdk-test.sh
  build/build-sdk-images/rust/clean.sh
  build/build-sdk-images/rust/sdktest.sh
  cloudbuild.yaml
  test/sdk/rust/.gitignore
  test/sdk/rust/Cargo.toml
Labels: approved, lgtm, size/M

#1121 Added dynamic configuration of http port in the unity sdk
  sdks/unity/AgonesSdk.cs
Labels: approved, size/XS

#1124 Drop the Extension API Server reference from agones-allocator
  cmd/allocator/main.go
  cmd/allocator/main_test.go
  install/helm/agones/templates/service/allocation.yaml
  install/yaml/install.yaml
Labels: approved, size/L

#1079 Add SDK server HTTP API test
  build/build-sdk-images/restapi/Dockerfile
  build/build-sdk-images/restapi/build-sdk-test.sh
  build/build-sdk-images/restapi/clean.sh
  build/build-sdk-images/restapi/sdktest.sh
  build/includes/sdk.mk
  cloudbuild.yaml
  test/sdk/restapi/http-api-test.go.nolint
Labels: approved, size/L

#1125 Added dynamic configuration of http port in the rust sdk
  sdks/rust/src/sdk.rs
Labels: approved, lgtm, size/XS

#1128 Simplify the selection of the dynamic port in the nodejs sdk.
  sdks/nodejs/spec/agonesSDK.spec.js
  sdks/nodejs/src/agonesSDK.js
Labels: approved, lgtm, size/M

#1127 Simplify the selection of the dynamic port in the Go sdk.
  sdks/go/sdk.go
Labels: approved, size/M

#1130 Retry on failures for multi-cluster allocation
  pkg/gameserverallocations/allocator.go
  pkg/gameserverallocations/controller_test.go
Labels: approved, lgtm, size/L

#1129 Style fixes.
  sdks/nodejs/src/agonesSDK.js
Labels: approved, lgtm, size/XS

#1131 Add dynamic configuration of the sidecar http port to the unreal sdk.
  sdks/unreal/Agones/Agones.uplugin
  sdks/unreal/Agones/Source/Agones/AgonesHook.cpp
  sdks/unreal/Agones/Source/Agones/AgonesHook.h
  sdks/unreal/Agones/Source/Agones/AgonesSettings.cpp
  sdks/unreal/Agones/Source/Agones/Public/AgonesSettings.h
  site/content/en/docs/Guides/Client SDKs/unreal.md
Labels: approved, lgtm, size/M

#1134 Release 1.1.0-rc
  CHANGELOG.md
  docs/governance/templates/release.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  site/content/en/blog/releases/1.1.0-rc.md
Labels: approved, kind/release, lgtm, size/L

#1138 Remove the svg version of the old logo.
  agones-logo.svg
Labels: approved, kind/cleanup, lgtm, size/M

#1139 Replace tabs with spaces in the svg file so that it renders more nicely.
  site/assets/icons/logo.svg
Labels: approved, kind/cleanup, lgtm, size/S

#1143 Disable Auto Upgrade for Deployment Manager
  build/gke-test-cluster/cluster.yml.jinja
Labels: approved, lgtm, size/XS

#1140 Update the instructions for manually creating a GKE cluster to disable automatic node upgrades
  site/content/en/docs/Installation/_index.md
Labels: approved, area/operations, kind/documentation, lgtm, size/XS

#1147 Fixed a typo
  site/content/en/docs/Advanced/service-accounts.md
Labels: approved, kind/cleanup, kind/documentation, lgtm, size/XS

#1141 Update the instructions for installing a GKE cluster with terraform to disable automatic node upgrades
  build/cluster.tf
  examples/terraform-submodules/gke/module.tf
  site/content/en/docs/Installation/terraform.md
Labels: approved, area/operations, kind/documentation, kind/feature, lgtm, size/L

#1135 CI: Update Rust SDK conformance test cache version
  site/content/en/docs/Guides/Client SDKs/_index.md
  test/sdk/rust/Cargo.toml
Labels: approved, area/tests, kind/cleanup, size/XS

#1152 Replace `>` quoted text with alert shortcodes
  site/content/en/docs/Advanced/scheduling-and-autoscaling.md
  site/content/en/docs/Contribute/_index.md
  site/content/en/docs/Getting Started/create-fleet.md
  site/content/en/docs/Getting Started/create-gameserver.md
  site/content/en/docs/Getting Started/edit-first-gameserver-go.md
  site/content/en/docs/Guides/Client SDKs/_index.md
  site/content/en/docs/Guides/Client SDKs/local.md
  site/content/en/docs/Guides/Client SDKs/rest.md
  site/content/en/docs/Guides/Client SDKs/unity.md
  site/content/en/docs/Guides/fleet-updates.md
  site/content/en/docs/Guides/gameserver-lifecycle.md
  site/content/en/docs/Guides/metrics.md
  site/content/en/docs/Installation/_index.md
  site/content/en/docs/Installation/helm.md
Labels: approved, kind/cleanup, kind/documentation, lgtm, size/L

#1119 Add owners files for the nodejs code
  examples/nodejs-simple/OWNERS
  sdks/nodejs/OWNERS
Labels: approved, area/meta, size/XS

#1149 Add SDK.GameServer() to Matchmaking Registration Diagram
  site/static/diagrams/gameserver-reserved.puml
  site/static/diagrams/gameserver-reserved.puml.png
Labels: approved, kind/documentation, kind/feature, size/S

#1153 Update the images for all examples to use the 1.1 SDKs
  build/Makefile
  examples/cpp-simple/Makefile
  examples/cpp-simple/fleet.yaml
  examples/cpp-simple/gameserver.yaml
  examples/fleet.yaml
  examples/gameserver.yaml
  examples/nodejs-simple/Makefile
  examples/nodejs-simple/gameserver.yaml
  examples/rust-simple/Makefile
  examples/rust-simple/gameserver.yaml
  examples/simple-tcp/Dockerfile
  examples/simple-tcp/Makefile
  examples/simple-tcp/gameserver.yaml
  examples/simple-udp/Dockerfile
  examples/simple-udp/Makefile
  examples/simple-udp/dev-gameserver.yaml
  examples/simple-udp/fleet-distributed.yaml
  examples/simple-udp/fleet.yaml
  examples/simple-udp/gameserver-passthrough.yaml
  examples/simple-udp/gameserver.yaml
  examples/simple-udp/gameserverset.yaml
  examples/unity-simple/Makefile
  examples/unity-simple/gameserver.yaml
  examples/xonotic/Makefile
  examples/xonotic/fleet.yaml
  examples/xonotic/gameserver.yaml
  pkg/util/webhooks/webhooks_test.go
  site/config.toml
  site/content/en/docs/Guides/local-game-server.md
  site/content/en/docs/Guides/troubleshooting.md
  site/content/en/docs/Reference/fleet.md
  site/content/en/docs/Reference/gameserver.md
  test/e2e/main_test.go
Labels: approved, size/L

#1157 Cloud Build: Add --output-sync=target to run-sdk-conformance-tests
  cloudbuild.yaml
Labels: approved, area/tests, kind/cleanup, size/XS

#1158 Broke Allocator Status in Grafana Dashboard
  build/Makefile
  build/grafana/dashboard-status.yaml
Labels: approved, area/operations, kind/bug, lgtm, size/L

#1155 Document agones-allocator and multi-cluster allocation
  site/content/en/docs/Advanced/allocator-service.md
  site/content/en/docs/Advanced/multi-cluster-allocation.md
Labels: approved, lgtm, size/L

#1159 Update "Local Development" documents
  site/content/en/docs/Guides/Client SDKs/local.md
Labels: approved, kind/cleanup, kind/documentation, lgtm, size/M

#1162 Preperation for 1.2.0 sprint
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
Labels: approved, kind/release, lgtm, size/M

#1164 Add top level notes on functionalitity on Unity & Unreal docs
  site/content/en/docs/Guides/Client SDKs/unity.md
  site/content/en/docs/Guides/Client SDKs/unreal.md
Labels: approved, kind/cleanup, kind/documentation, lgtm, size/S

#1142 Fix CPP SDK archive path - created separate one
  .dockerignore
  build/includes/release.mk
  cloudbuild.yaml
  sdks/cpp/Makefile
Labels: approved, area/build-tools, kind/cleanup, size/XS
