Repository googleforgames/agones, pull requests merged in 2019-05, with the labels that each got.

#750 Deprecate Fleet Allocation.
  examples/fleetallocation.yaml
  examples/simple-udp/fleetallocation.yaml
  examples/xonotic/fleetallocation.yaml
  pkg/apis/stable/v1alpha1/fleetallocation.go
  site/content/en/docs/Getting Started/create-fleet.md
  site/content/en/docs/Reference/agones_crd_api_reference.html
  site/content/en/docs/Reference/fleet.md
Labels: kind/cleanup

#739 We don't need CMake in the base build image
  build/build-image/Dockerfile
Labels: area/build-tools, kind/cleanup

#754 Add tests for gameServerCacheEntry in GameServerAllocation controller
  pkg/gameserverallocations/cache.go
  pkg/gameserverallocations/cache_test.go
  pkg/gameserverallocations/controller.go
Labels: kind/cleanup

#747 Cleanup - no longer need to list Pods for GameServers
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  pkg/sdkserver/sdkserver.go
  test/e2e/gameserver_test.go
Labels: area/performance, kind/cleanup

#758 Flaky: Fix test for TestGameServerUnhealthyAfterDeletingPod
  test/e2e/framework/framework.go
  test/e2e/gameserver_test.go
Labels: area/tests, kind/bug

#746 Convert C++ Example to Docker Build Pattern
  .dockerignore
  examples/cpp-simple/CMakeLists.txt
  examples/cpp-simple/Dockerfile
  examples/cpp-simple/Makefile
Labels: area/examples, kind/cleanup

#760 Release 0.10.0-rc
  CHANGELOG.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  site/content/en/blog/releases/0.10.0-rc.md
  site/content/en/blog/releases/0.9.0.md
Labels: kind/release

#762 Add secret list and watch permissions to RBAC rules
  install/helm/agones/templates/serviceaccounts/controller.yaml
  install/yaml/install.yaml
  pkg/gameserverallocations/controller.go
  pkg/gameserverallocations/controller_test.go
  site/content/en/docs/Reference/agones_crd_api_reference.html
Labels: area/operations, kind/bug

#761 Bad copy paste on 0.10.0 rc release page
  site/content/en/blog/releases/0.10.0-rc.md
Labels: area/site, kind/cleanup

#764 Update Fleet autoscaling documentation
  site/content/en/docs/Advanced/scheduling-and-autoscaling.md
Labels: kind/cleanup, kind/documentation

#767 Update examples list
  site/content/en/docs/Examples/_index.md
Labels: kind/cleanup, kind/documentation

#763 Revert UnHealthy standalone GameServers to not be deleted
  build/Makefile
  examples/fleet.yaml
  examples/simple-udp/Makefile
  examples/simple-udp/fleet-distributed.yaml
  examples/simple-udp/fleet.yaml
  examples/simple-udp/gameserver.yaml
  examples/simple-udp/gameserverset.yaml
  examples/simple-udp/main.go
  install/helm/agones/templates/NOTES.txt
  pkg/gameservers/controller.go
  pkg/gameservers/health.go
  pkg/gameserversets/controller.go
  pkg/gameserversets/controller_test.go
  pkg/sdkserver/sdkserver.go
  pkg/sdkserver/sdkserver_test.go
  site/content/en/docs/Advanced/limiting-resources.md
  site/content/en/docs/Advanced/scheduling-and-autoscaling.md
  site/content/en/docs/Advanced/service-accounts.md
  site/content/en/docs/Getting Started/create-fleet.md
  site/content/en/docs/Getting Started/create-gameserver.md
  site/content/en/docs/Guides/access-api.md
  test/e2e/fleet_test.go
  test/e2e/framework/framework.go
  test/e2e/gameserver_test.go
  test/e2e/main_test.go
Labels: area/tests, kind/cleanup

#756 Add AKS, GKE and Helm terraform modules
  build/modules/aks/aks.tf
  build/modules/aks/outputs.tf
  build/modules/aks/variables.tf
  build/modules/gke/cluster.tf
  build/modules/gke/outputs.tf
  build/modules/gke/variables.tf
  build/modules/helm/helm.tf
  build/modules/helm/variables.tf
  examples/terraform-submodules/aks/module.tf
  examples/terraform-submodules/gke-local/main.tf
  examples/terraform-submodules/gke/module.tf
  site/content/en/docs/Installation/terraform.md
Labels: area/operations, kind/feature

#748 Add close method to node client
  examples/nodejs-simple/src/index.js
  sdks/nodejs/spec/agonesSDK.spec.js
  sdks/nodejs/src/agonesSDK.js
Labels: area/user-experience, kind/feature

#774 Expose allocate method in node sdk
  sdks/nodejs/spec/agonesSDK.spec.js
  sdks/nodejs/src/agonesSDK.js
Labels: area/user-experience, kind/feature

#782 Prevent race conditions by syncing node cache on GameServer controller
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
Labels: area/tests, kind/bug

#768 Adding an allocator service that acts as a reverse proxy.
  build/Makefile
  build/build-required-src-dist.sh
  build/extract-licenses.sh
  build/helm.tf
  cmd/allocator/Dockerfile
  cmd/allocator/main.go
  cmd/allocator/main_test.go
  install/helm/agones/certs/allocator/client-ca/ca.crt
  install/helm/agones/certs/allocator/server.crt
  install/helm/agones/certs/allocator/server.key
  install/helm/agones/templates/service/allocation.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  pkg/gameserverallocations/controller.go
  pkg/gameserverallocations/controller_test.go
  site/content/en/docs/Installation/helm.md
  test/e2e/allocator_test.go
Labels: area/user-experience, kind/feature

#780 Prevent race conditions by syncing cache on new Allocation elements
  pkg/gameserverallocations/controller.go
  pkg/gameserverallocations/controller_test.go
Labels: area/tests, kind/bug

#775 Preparation for 0.11.0 release!
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
Labels: kind/release

#779 Flaky: Race condition in TestControllerSyncGameServerStartingState
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
Labels: area/tests, kind/cleanup

#781 Flakey: TestControllerSyncGameServerDeletionTimestamp
  pkg/gameservers/controller_test.go
Labels: area/tests, kind/cleanup

#785 Fix spelling in docs and comments
  build/build-sdk-images/README.md
  docs/governance/templates/release_issue.md
  examples/autoscaler-webhook/README.md
  pkg/gameserversets/controller_test.go
  site/content/en/_index.html
  site/content/en/docs/Getting Started/create-fleet.md
  site/content/en/docs/Getting Started/create-fleetautoscaler.md
  site/content/en/docs/Getting Started/create-gameserver.md
  site/content/en/docs/Getting Started/create-webhook-fleetautoscaler.md
  site/content/en/docs/Guides/Client SDKs/cpp.md
  site/content/en/docs/Guides/ping-service.md
  site/content/en/docs/Reference/fleetautoscaler.md
  site/content/en/docs/Tutorials/allocator-service-go.md
Labels: kind/cleanup, kind/documentation

#789 Flaky: TestAllocator
  build/Makefile
  build/e2e-image/e2e.sh
  build/e2e-image/entrypoint.sh
  test/e2e/allocator_test.go
Labels: area/tests, kind/bug

#772 Fix for front link. Not sure what happened?
  site/content/en/_index.html
Labels: area/site, kind/bug

#777 Fix spelling mistake in grafana dashboard.
  build/grafana/dashboard-gameservers.yaml
Labels: area/operations, kind/cleanup

#778 Update SDK page with full list of current SDKs.
  site/content/en/docs/Guides/Client SDKs/_index.md
  site/content/en/docs/Guides/Client SDKs/go.md
Labels: kind/cleanup, kind/documentation

#791 Add missing validation for GameServerSet, refactor
  pkg/apis/stable/v1alpha1/common.go
  pkg/apis/stable/v1alpha1/fleet.go
  pkg/apis/stable/v1alpha1/gameserver.go
  pkg/apis/stable/v1alpha1/gameserver_test.go
  pkg/apis/stable/v1alpha1/gameserverset.go
  pkg/apis/stable/v1alpha1/gameserverset_test.go
  test/e2e/fleet_test.go
Labels: kind/cleanup

#788 Docs: FleetAllocation example fix
  site/content/en/docs/Getting Started/create-webhook-fleetautoscaler.md
Labels: kind/cleanup, kind/documentation

#793 Fix publishDate on unreal docs
  site/content/en/docs/Guides/Client SDKs/unreal.md
Labels: area/site, kind/bug

#795 Fleetautoscaler: Add check to have minReplicas>0 when use percents bufferSize
  pkg/apis/stable/v1alpha1/fleetautoscaler.go
  pkg/apis/stable/v1alpha1/fleetautoscaler_test.go
  site/content/en/docs/Reference/fleetautoscaler.md
Labels: area/user-experience, kind/cleanup
