Repository googleforgames/agones, pull requests merged in 2019-12, with the labels that each got.

#1198 FleetAutoScaler add reserved into consideration
  examples/fleetautoscaler.yaml
  site/content/en/docs/Guides/Client SDKs/_index.md
  site/content/en/docs/Reference/fleetautoscaler.md
Labels: approved, lgtm, size/S

#1193 Implement Reserve for Unity
  examples/unity-simple/Assets/Scripts/UdpEchoServer.cs
  sdks/unity/AgonesSdk.cs
  site/content/en/docs/Guides/Client SDKs/unity.md
Labels: approved, area/user-experience, kind/feature, size/M

#1178 Update documentation for the 1.2 release to use Kubernetes 1.13.
  examples/fleet.yaml
  examples/fleetautoscaler.yaml
  examples/gameserver.yaml
  site/content/en/docs/Installation/_index.md
  site/content/en/docs/Installation/helm.md
  site/content/en/docs/Reference/fleet.md
  site/content/en/docs/Reference/fleetautoscaler.md
  site/content/en/docs/Reference/gameserver.md
Labels: approved, kind/documentation, kind/feature, lgtm, size/L

#1192 Flaky: TestGameServerUnhealthyAfterReadyCrash
  test/e2e/gameserver_test.go
Labels: approved, area/tests, kind/cleanup, lgtm, size/S

#1167 Move terraform modules from ./build to ./install
  build/cluster.tf
  build/helm.tf
  build/includes/terraform.mk
  examples/terraform-submodules/aks/module.tf
  examples/terraform-submodules/gke-local/main.tf
  examples/terraform-submodules/gke/module.tf
  install/terraform/cluster.tf
  install/terraform/helm.tf
  install/terraform/modules/aks/aks.tf
  install/terraform/modules/aks/outputs.tf
  install/terraform/modules/aks/variables.tf
  install/terraform/modules/gke/cluster.tf
  install/terraform/modules/gke/outputs.tf
  install/terraform/modules/gke/variables.tf
  install/terraform/modules/helm/helm.tf
  install/terraform/modules/helm/variables.tf
Labels: approved, area/operations, kind/cleanup, size/XL

#1204 Whoops - spelling mistake in feature tag.
  site/content/en/docs/Guides/Client SDKs/local.md
  site/content/en/docs/Installation/_index.md
  site/content/en/docs/Installation/helm.md
  site/content/en/docs/Reference/fleet.md
  site/content/en/docs/Reference/fleetautoscaler.md
  site/content/en/docs/Reference/gameserver.md
Labels: approved, kind/bug, kind/documentation, lgtm, size/S

#1200 Fix sdk-server image make target
  build/Makefile
  build/includes/kind.mk
Labels: approved, area/build-tools, kind/cleanup, lgtm, size/XS

#1205 Error checking of attributes on feature shortcode
  site/layouts/shortcodes/feature.html
Labels: approved, area/site, kind/feature, size/XS

#1206 Release 1.2.0-rc
  CHANGELOG.md
  docs/governance/templates/release.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  site/content/en/blog/releases/1.2.0-rc.md
Labels: approved, kind/release, lgtm, size/L

#1208 Wrong date on 1.2.0-rc blog post
  site/content/en/blog/releases/1.2.0-rc.md
Labels: approved, kind/cleanup, kind/documentation, lgtm, size/XS

#1209 Setting Unreal plugin version to 3
  sdks/unreal/Agones/Agones.uplugin
Labels: approved, area/user-experience, kind/bug, lgtm, size/XS

#1210 Document the default ports used by the sdkserver sidecar on the website
  site/content/en/docs/Guides/Client SDKs/_index.md
Labels: approved, kind/documentation, kind/feature, lgtm, size/XS

#1219 Add missing license headers
  examples/allocator-service/Dockerfile
  examples/allocator-service/allocator-ingress.yaml
  examples/allocator-service/allocator-service.yaml
  examples/allocator-service/main.go
  examples/allocator-service/service-account.yaml
  pkg/util/logfields/logfields.go
  tools.go
Labels: approved, lgtm, size/M

#1221 Fix documentation for allocator helm args
  install/helm/agones/values.yaml
  site/content/en/docs/Installation/helm.md
Labels: approved, kind/bug, kind/documentation, lgtm, size/XS

#1224 Docs: allocator service should have save-config
  install/helm/agones/values.yaml
  site/content/en/docs/Advanced/allocator-service.md
Labels: approved, lgtm, size/XS

#1226 Revert: Make it possible to create a Fleet with 0 replicas
  examples/fleet.yaml
  pkg/apis/agones/v1/fleet.go
  pkg/apis/agones/v1/fleet_test.go
  site/content/en/docs/Reference/agones_crd_api_reference.html
  site/content/en/docs/Reference/fleet.md
  test/e2e/fleet_test.go
Labels: approved, area/user-experience, kind/bug, lgtm, size/M

#1231 Preparation for 1.3.0
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
Labels: approved, kind/release, lgtm, size/M

#1080 Feature Stages Documentation
  CONTRIBUTING.md
  site/content/en/docs/Guides/feature-stages.md
Labels: approved, area/meta, kind/documentation, kind/feature, size/L

#1232 Move conflict messaged to Debug Logging
  pkg/util/workerqueue/workerqueue.go
Labels: approved, area/operations, kind/cleanup, size/XS

#1220 Configurable Log Level for Agones Controller
  build/Makefile
  cmd/controller/main.go
  install/helm/agones/templates/controller.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  pkg/util/runtime/runtime.go
  site/content/en/docs/Installation/helm.md
Labels: approved, area/operations, kind/feature, lgtm, size/S

#1237 Add Embark logo to Agones site
  site/content/en/_index.html
  site/static/images/embark.png
Labels: approved, lgtm, size/XS

#1235 Fix documentation for multi-cluster allocation
  site/content/en/docs/Advanced/multi-cluster-allocation.md
Labels: approved, size/S

#1236 Changed the LabelSelector reference of allocator gRPC api
  pkg/allocation/converters/converter.go
  pkg/allocation/converters/converter_test.go
  pkg/allocation/go/v1alpha1/allocation.pb.go
  pkg/allocation/go/v1alpha1/allocation.swagger.json
  proto/allocation/v1alpha1/allocation.proto
  test/e2e/allocator_test.go
Labels: approved, kind/cleanup, size/L

#1242 Half the width of the Embark Logo
  site/content/en/_index.html
Labels: approved, area/site, kind/cleanup, lgtm, size/XS

#1240 Fix cleanup Agones resources script
  install/helm/agones/scripts/delete_agones_resources.sh
Labels: approved, area/operations, kind/bug, size/XS

#1243 Adding retry on GameServerAllocations.Create for multi-cluster testing
  test/e2e/gameserverallocation_test.go
Labels: approved, area/tests, kind/cleanup, lgtm, size/S

#1241 Remove syncGameServerSet logging.
  pkg/gameserversets/controller.go
Labels: approved, area/operations, kind/cleanup, size/XS

#1132 improve stackdriver metric type
  cmd/allocator/main.go
  cmd/controller/main.go
  go.mod
  go.sum
  install/helm/agones/templates/controller.yaml
  install/helm/agones/templates/service/allocation.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  pkg/metrics/exporter.go
  pkg/metrics/util.go
  pkg/metrics/util_test.go
  site/content/en/docs/Installation/helm.md
Labels: approved, area/operations, kind/feature, size/L

#1222 Better error message for Health Check Failure
  pkg/sdkserver/sdkserver.go
  pkg/sdkserver/sdkserver_test.go
  test/e2e/gameserver_test.go
Labels: approved, area/operations, kind/feature, size/M

#1211 Split installation guide into separate sections
  site/content/en/docs/Advanced/limiting-resources.md
  site/content/en/docs/Getting Started/edit-first-gameserver-go.md
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Guides/metrics.md
  site/content/en/docs/Guides/ping-service.md
  site/content/en/docs/Installation/Creating Cluster/_index.md
  site/content/en/docs/Installation/Creating Cluster/aks.md
  site/content/en/docs/Installation/Creating Cluster/eks.md
  site/content/en/docs/Installation/Creating Cluster/gke.md
  site/content/en/docs/Installation/Creating Cluster/minikube.md
  site/content/en/docs/Installation/Install Agones/_index.md
  site/content/en/docs/Installation/Install Agones/helm.md
  site/content/en/docs/Installation/Install Agones/yaml.md
  site/content/en/docs/Installation/Terraform/_index.md
  site/content/en/docs/Installation/Terraform/aks.md
  site/content/en/docs/Installation/Terraform/gke.md
  site/content/en/docs/Installation/_index.md
  site/content/en/docs/Installation/confirm.md
  site/content/en/docs/Installation/terraform.md
  site/content/en/docs/Installation/upgrading.md
  site/content/en/docs/Reference/gameserver.md
  site/content/en/docs/Tutorials/allocator-service-go.md
  site/content/en/docs/Tutorials/simple-gameserver-cpp.md
  site/content/en/docs/Tutorials/simple-gameserver-nodejs.md
  site/content/en/docs/Tutorials/simple-gameserver-rust.md
  site/static/images/cloud-shell.png
Labels: approved, kind/cleanup, kind/documentation, lgtm, size/XXL

#1233 Health Checking: Fix doc errors and expand
  site/content/en/docs/Guides/health-checking.md
Labels: approved, kind/bug, kind/cleanup, kind/documentation, lgtm, size/M
