Repository googleforgames/agones, pull requests merged in 2020-11, with the labels that each got.

#1876 Fix kind on GameServerAllocation converter
  pkg/allocation/converters/converter.go
  pkg/allocation/converters/converter_test.go
Labels: approved, cla: yes, lgtm, size/S

#1882 Add new projects to Third Party section of the site
  site/content/en/docs/Third Party Content/libraries-tools.md
Labels: approved, cla: yes, size/XS

#1874 Add allocator resources
  install/helm/agones/templates/service/allocation.yaml
  install/helm/agones/values.yaml
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: approved, area/operations, cla: yes, kind/feature, size/S

#1877 Move the loadBalancerIP to helm installation as best effort
  build/Makefile
Labels: approved, area/build-tools, cla: yes, kind/cleanup, size/XS

#1881 Update helm installation to include a step to update helm repo
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: approved, cla: yes, size/XS

#1880 Add log level setting in allocator
  cmd/allocator/main.go
  cmd/allocator/metrics.go
  install/helm/agones/templates/service/allocation.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: approved, cla: yes, lgtm, size/S

#1878 Add troubleshooting for allocation gRPC request
  site/content/en/docs/Advanced/allocator-service.md
  site/content/en/docs/Advanced/multi-cluster-allocation.md
Labels: approved, cla: yes, lgtm, size/L

#1885 Release 1.10.0-rc
  CHANGELOG.md
  docs/governance/templates/release_issue.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package.json
  site/content/en/blog/releases/1.10.0-rc.md
  site/content/en/blog/releases/1.9.0.md
Labels: approved, cla: yes, kind/release, lgtm, size/L

#1887 Updates to the release template
  docs/governance/templates/release.md
  site/content/en/blog/releases/1.10.0-rc.md
Labels: approved, cla: yes, kind/bug, kind/release, lgtm, size/S

#1889 Fix formatting on the 1.10 blog post.
  site/content/en/blog/releases/1.10.0-rc.md
Labels: approved, cla: yes, kind/bug, kind/documentation, lgtm, size/XS

#1888 Fix GameServer count per type graph back to pie
  build/grafana/dashboard-gameservers.yaml
Labels: approved, area/operations, cla: yes, kind/bug, lgtm, size/XXL

#1896 csharp SDK: exposes the Alpha SDK via the main interface
  sdks/csharp/sdk/IAgonesSDK.cs
Labels: approved, cla: yes, kind/cleanup, lgtm, size/XS

#1895 Preparation for 1.11.0
  build/Makefile
  docs/governance/templates/release_issue.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package.json
Labels: approved, cla: yes, kind/release, lgtm, size/M

#1901 Upgrade terraform and test clusters to 1.17
  build/build-image/Dockerfile
  build/e2e-image/Dockerfile
  install/terraform/modules/gke/cluster.tf
Labels: approved, area/build-tools, area/operations, cla: yes, kind/breaking, kind/cleanup, lgtm, size/XS

#1900 Updated Go to 1.14.12
  build/build-image/Dockerfile
  build/build-sdk-images/go/Dockerfile
  build/build-sdk-images/restapi/Dockerfile
  build/e2e-image/Dockerfile
  examples/autoscaler-webhook/Dockerfile
  examples/crd-client/Dockerfile
  examples/simple-game-server/Dockerfile
  examples/simple-tcp/Dockerfile
  examples/simple-udp/Dockerfile
  examples/supertuxkart/Dockerfile
  examples/xonotic/Dockerfile
Labels: approved, area/build-tools, area/security, cla: yes, kind/cleanup, size/S

#1908 Merge allocation service annotation metadata
  install/helm/agones/templates/service/allocation.yaml
  install/yaml/install.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1906 Update minikube dev tooling
  build/README.md
  build/includes/linux.mk
  build/includes/macos.mk
  build/includes/minikube.mk
  build/includes/windows.mk
Labels: approved, area/build-tools, cla: yes, kind/cleanup, size/L

#1910 Adding SAN to fleet autoscaler certs and updating documentation
  site/content/en/docs/Getting Started/create-webhook-fleetautoscaler.md
  test/e2e/fleetautoscaler_test.go
Labels: approved, cla: yes, kind/breaking, kind/cleanup, kind/documentation, size/L
