Repository googleforgames/agones, pull requests merged in 2020-06, with the labels that each got.

#1604 Flaky: TestAllocatorCrossNamespace
  test/e2e/allocator_test.go
Labels: approved, area/tests, kind/bug, kind/cleanup, lgtm, size/XS

#1606 Flaky: TestFleetAggregatedPlayerStatus
  test/e2e/fleet_test.go
Labels: approved, area/tests, kind/bug, lgtm, size/S

#1602 Adding parallel to more tests.
  pkg/gameserversets/controller_test.go
Labels: approved, area/tests, kind/cleanup, lgtm, size/S

#1546 CI: Add one more E2E tests run with all feature gates disabled
  build/e2e-image/e2e.sh
  build/e2e-image/entrypoint.sh
  cloudbuild.yaml
Labels: approved, area/build-tools, area/tests, size/S

#1607 Added some missing helm vars documentation for Agones intall with helm.
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: approved, area/site, lgtm, size/XS

#1608 Update the build image to buster
  build/build-image/Dockerfile
Labels: approved, area/build-tools, kind/cleanup, lgtm, size/XS

#1597 Grafana - add namespace to distinguish fleets with the same name
  build/grafana/dashboard-gameservers.yaml
Labels: approved, size/M

#1601 Additional commands for prometheus and grafana
  build/Makefile
Labels: lgtm, size/XS

#1612 Update all images to Go 1.14.4
  build/build-image/Dockerfile
  build/build-sdk-images/go/Dockerfile
  build/build-sdk-images/restapi/Dockerfile
  build/e2e-image/Dockerfile
  examples/allocator-service/Dockerfile
  examples/autoscaler-webhook/Dockerfile
  examples/crd-client/Dockerfile
  examples/simple-tcp/Dockerfile
  examples/simple-udp/Dockerfile
  examples/supertuxkart/Dockerfile
  examples/xonotic/Dockerfile
  pkg/apis/agones/v1/common.go
Labels: approved, area/build-tools, area/examples, kind/cleanup, lgtm, size/S

#1609 Update Debian version for CPP example
  examples/cpp-simple/Dockerfile
  examples/cpp-simple/Makefile
Labels: approved, area/build-tools, kind/cleanup, size/XS

#1610 Update Rust Debian image version
  examples/rust-simple/Dockerfile
  examples/rust-simple/Makefile
Labels: approved, area/examples, kind/cleanup, size/S

#1577 Move ContainerPortAllocation to beta
  build/Makefile
  build/includes/terraform.mk
  examples/gameserver.yaml
  pkg/apis/agones/v1/gameserver.go
  pkg/util/runtime/features.go
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Reference/agones_crd_api_reference.html
  site/content/en/docs/Reference/gameserver.md
Labels: approved, lgtm, size/L

#1613 Update AccelByte logo
  site/static/images/accelbyte.png
Labels: approved, area/site, kind/cleanup, size/XS

#1616 Site: fix minor issues, obsolete helm parameters
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: approved, kind/documentation, lgtm, size/XS

#1511 Update Debian image version for SDK base
  build/build-sdk-images/restapi/Dockerfile
  build/build-sdk-images/tool/base/Dockerfile
  cloudbuild.yaml
Labels: approved, size/S

#1596 C# SDK Cleanup & Nuget Package
  sdks/csharp/sdk/.gitignore
  sdks/csharp/sdk/AgonesSDK.cs
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/IAgonesSDK.cs
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/csharp/test/csharp-sdk-test.csproj
  site/content/en/docs/Guides/Client SDKs/csharp.md
Labels: approved, area/user-experience, kind/feature, size/L

#1619 Update docs to explicitly allow specifying ca.crt in client secret instead of serverCa field for multi-cluster allocation
  pkg/gameserverallocations/allocator.go
  site/content/en/docs/Advanced/multi-cluster-allocation.md
Labels: approved, lgtm, size/XS

#1615 Grafana - add namespace to autoscalers dashboard
  build/grafana/dashboard-autoscalers.yaml
Labels: area/operations, kind/feature, lgtm, size/L

#1618 Add port flag to example allocator-client
  examples/allocator-client/main.go
  site/content/en/docs/Advanced/allocator-service.md
Labels: approved, size/XS

#1547 Improved Fleets - controller tests
  pkg/fleets/controller.go
  pkg/fleets/controller_test.go
Labels: size/XL

#1591 Remove redundant "helm test" pod from "install.yaml"
  install/helm/agones/templates/tests/test-runner.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: approved, area/operations, size/M

#1622 Fix replacement bug in gen-api-docs.sh
  site/gen-api-docs.sh
Labels: approved, area/build-tools, cla: yes, kind/bug, kind/documentation, lgtm, size/XS

#1620 Remove obsolete example of FleetAllocator service
  examples/allocator-service/Dockerfile
  examples/allocator-service/README.md
  examples/allocator-service/allocator-ingress.yaml
  examples/allocator-service/allocator-service.yaml
  examples/allocator-service/main.go
  examples/allocator-service/service-account.yaml
  site/content/en/docs/Examples/_index.md
  site/content/en/docs/Getting Started/create-fleet.md
  site/content/en/docs/Guides/access-api.md
Labels: approved, cla: yes, kind/cleanup, kind/documentation, size/L

#1624 Removed obsolete allocator-service-go.md
  site/content/en/docs/Tutorials/allocator-service-go.md
Labels: approved, cla: yes, lgtm, size/L

#1468 New metric - state duration
  go.mod
  pkg/metrics/controller.go
  pkg/metrics/controller_metrics.go
  pkg/metrics/controller_test.go
  pkg/metrics/gameservers_count.go
  pkg/metrics/util_test.go
  site/content/en/docs/Guides/metrics.md
Labels: approved, area/operations, cla: yes, size/L

#1633 Fixed broken link to pass tests.
  site/content/en/docs/Guides/access-api.md
Labels: approved, area/tests, cla: yes, kind/cleanup, kind/documentation, lgtm, size/XS

#1634 Load test: Fix example yaml config
  test/load/allocation/fleet.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1637 Add a note to the contributing docs that joining the mailing list gives access to build logs
  CONTRIBUTING.md
Labels: approved, cla: yes, size/XS

#1632 CreateNamespace: delete dangling namespaces
  test/e2e/framework/framework.go
Labels: approved, area/tests, cla: yes, kind/cleanup, size/S

#1611 CI: Adding E2E cluster name as a parameter for CloudBuild
  build/e2e-image/entrypoint.sh
  build/includes/google-cloud.mk
  cloudbuild.yaml
Labels: approved, area/tests, cla: yes, kind/breaking, size/S

#1638 Adding support for refreshing TLS certs in the allocator
  cmd/allocator/main.go
  cmd/allocator/main_test.go
  site/content/en/docs/Advanced/allocator-service.md
  test/e2e/allocator_test.go
Labels: approved, cla: yes, lgtm, size/L

#1635 Fixed GameServer State Diagram
  site/static/diagrams/gameserver-states.dot
  site/static/diagrams/gameserver-states.dot.png
Labels: approved, cla: yes, size/XS

#1643 Fixed some formatting issues in the allocator code.
  cmd/allocator/main.go
Labels: approved, cla: yes, lgtm, size/S

#1644 Website: Change to relative reference
  site/content/en/docs/Advanced/allocator-service.md
Labels: approved, cla: yes, lgtm, size/XS

#1627 Helm 3 Install Documentation
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: approved, cla: yes, kind/documentation, kind/feature, size/L

#1646 Update Terraform to Helm 3
  examples/terraform-submodules/aks/module.tf
  examples/terraform-submodules/eks/module.tf
  examples/terraform-submodules/gke/module.tf
  install/terraform/modules/helm/helm.tf
  install/terraform/modules/helm3/helm.tf
  install/terraform/modules/helm3/variables.tf
  site/content/en/docs/Installation/Terraform/_index.md
  site/content/en/docs/Installation/Terraform/gke.md
Labels: approved, area/operations, cla: yes, kind/documentation, kind/feature, lgtm, size/L

#1629 test-e2e - Added several Fatal calls
  test/e2e/gameserver_test.go
Labels: approved, cla: yes, lgtm, size/L

#1647 Update developer tooling to Helm 3
  build/Makefile
  build/README.md
  build/build-image/Dockerfile
  build/e2e-image/Dockerfile
  build/helm.yaml
  build/includes/build-image.mk
  build/includes/google-cloud.mk
  build/includes/kind.mk
  build/includes/minikube.mk
  install/yaml/install.yaml
Labels: approved, area/build-tools, cla: yes, kind/feature, lgtm, size/XXL

#1651 Flaky: Csharp SDK Test
  cloudbuild.yaml
Labels: approved, area/tests, cla: yes, kind/bug, lgtm, size/XS

#1652 E2E: Invert ContainerPortAllocation FeatureGate
  cloudbuild.yaml
Labels: approved, area/tests, cla: yes, lgtm, size/XS

#1655 Cleanup e2e namespaces before test start
  test/e2e/framework/framework.go
  test/e2e/main_test.go
Labels: approved, area/tests, cla: yes, kind/cleanup, lgtm, size/M

#1645 Conditionally enable mtls for the allocator.
  cmd/allocator/main.go
  cmd/allocator/metrics.go
  install/helm/agones/templates/service/allocation.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  pkg/gameserverallocations/allocator.go
Labels: approved, cla: yes, lgtm, size/L

#1642 New feature: SDK cached gameserver
  build/Makefile
  cloudbuild.yaml
  pkg/sdkserver/sdkserver.go
  pkg/sdkserver/sdkserver_test.go
  pkg/util/runtime/features.go
  site/content/en/docs/Guides/Client SDKs/_index.md
  site/content/en/docs/Guides/feature-stages.md
Labels: approved, cla: yes, size/M

#1657 Update Node.js dependencies in sdk and example
  examples/nodejs-simple/Makefile
  examples/nodejs-simple/README.md
  examples/nodejs-simple/gameserver.yaml
  examples/nodejs-simple/package-lock.json
  examples/nodejs-simple/package.json
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
Labels: approved, cla: yes, size/XXL

#1656 Update Agones developer guide to point at faster targets
  build/README.md
Labels: approved, area/build-tools, cla: yes, kind/cleanup, kind/documentation, lgtm, size/S

#1662 Release 1.7.0-rc
  CHANGELOG.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/nodejs/package.json
  site/content/en/blog/releases/1.6.0.md
  site/content/en/blog/releases/1.7.0-rc.md
Labels: approved, cla: yes, kind/release, lgtm, size/L

#1665 Flaky TestLocal
  pkg/sdkserver/localsdk_test.go
Labels: approved, area/tests, cla: yes, kind/cleanup, size/S

#1664 Add ensure-build-image to test-go Make target
  build/Makefile
Labels: approved, area/build-tools, cla: yes, kind/cleanup, size/XS
