Repository googleforgames/agones, pull requests merged in 2020-12, with the labels that each got.

#1902 Adding rest to allocation endpoint
  cmd/allocator/main.go
  site/content/en/docs/Advanced/allocator-service.md
  site/content/en/docs/Advanced/multi-cluster-allocation.md
  test/e2e/allocator_test.go
  vendor/modules.txt
Labels: approved, area/user-experience, cla: yes, kind/feature, size/L

#1894 #54 Preliminary Windows Image Support
  build/Makefile
  build/README.md
  cmd/sdk-server/Dockerfile.windows
  examples/simple-tcp/.dockerignore
  examples/simple-tcp/Dockerfile.windows
  examples/simple-tcp/Makefile
  examples/simple-tcp/README.md
  examples/simple-tcp/gameserver-windows.yaml
  examples/simple-udp/.dockerignore
  examples/simple-udp/Dockerfile.windows
  examples/simple-udp/Makefile
  examples/simple-udp/gameserver-windows.yaml
  examples/xonotic/Dockerfile.windows
  examples/xonotic/main.go
  site/content/en/docs/Examples/_index.md
Labels: approved, cla: yes, size/XL

#1912 Issue #1854: Fix getplayercount() description on index
  site/content/en/docs/Guides/Client SDKs/_index.md
Labels: approved, cla: yes, size/XS

#1916 Updated terraform scripts to 1.17
  install/terraform/modules/aks/aks.tf
  install/terraform/modules/eks/eks.tf
  install/terraform/modules/gke/variables.tf
Labels: approved, area/operations, cla: yes, kind/breaking, kind/cleanup, lgtm, size/XS

#1909 Move CRDs from v1beta1 to v1
  install/helm/agones/templates/crds/_gameserverspecschema.yaml
  install/helm/agones/templates/crds/_gameserverstatus.yaml
  install/helm/agones/templates/crds/fleet.yaml
  install/helm/agones/templates/crds/fleetautoscaler.yaml
  install/helm/agones/templates/crds/gameserver.yaml
  install/helm/agones/templates/crds/gameserverallocationpolicy.yaml
  install/helm/agones/templates/crds/gameserverset.yaml
  install/yaml/install.yaml
  test/e2e/fleet_test.go
Labels: approved, area/operations, cla: yes, kind/breaking, kind/cleanup, lgtm, size/XXL

#1915 Update Kind dev tooling to 1.17.3
  build/includes/kind.mk
Labels: approved, cla: yes, kind/cleanup, lgtm, size/XS

#1917 Move supported site K8s version to shortcodes
  docs/governance/templates/release_issue.md
  site/config.toml
  site/content/en/docs/Advanced/limiting-resources.md
  site/content/en/docs/Installation/Creating Cluster/aks.md
  site/content/en/docs/Installation/Creating Cluster/eks.md
  site/content/en/docs/Installation/Creating Cluster/gke.md
  site/content/en/docs/Installation/Creating Cluster/minikube.md
  site/content/en/docs/Installation/_index.md
  site/content/en/docs/Reference/fleet.md
  site/content/en/docs/Reference/fleetautoscaler.md
  site/content/en/docs/Reference/gameserver.md
  site/layouts/shortcodes/aks-k8s-minor-version.html
  site/layouts/shortcodes/feature.html
  site/layouts/shortcodes/k8s-api.html
  site/layouts/shortcodes/k8s-version.html
  site/layouts/shortcodes/minikube-k8s-minor-version.html
Labels: approved, area/build-tools, cla: yes, kind/documentation, kind/feature, lgtm, size/M

#1920 Move Scaling resource to v1betav1 to v1
  pkg/apis/agones/v1/fleet.go
  pkg/apis/agones/v1/gameserverset.go
  pkg/client/clientset/versioned/typed/agones/v1/fake/fake_fleet.go
  pkg/client/clientset/versioned/typed/agones/v1/fake/fake_gameserverset.go
  pkg/client/clientset/versioned/typed/agones/v1/fleet.go
  pkg/client/clientset/versioned/typed/agones/v1/gameserverset.go
  pkg/fleets/controller_test.go
  test/e2e/fleet_test.go
Labels: approved, cla: yes, kind/cleanup, lgtm, size/M

#1918 Move apiregistration & admissionregistration to v1
  install/helm/agones/templates/extensions.yaml
  install/yaml/install.yaml
  pkg/fleetautoscalers/controller.go
  pkg/fleetautoscalers/controller_test.go
  pkg/fleets/controller.go
  pkg/fleets/controller_test.go
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  pkg/gameserversets/controller.go
  pkg/gameserversets/controller_test.go
  pkg/util/webhooks/webhooks.go
  pkg/util/webhooks/webhooks_test.go
  vendor/k8s.io/api/admission/v1/doc.go
  vendor/k8s.io/api/admission/v1/generated.pb.go
  vendor/k8s.io/api/admission/v1/generated.proto
  vendor/k8s.io/api/admission/v1/register.go
  vendor/k8s.io/api/admission/v1/types.go
  vendor/k8s.io/api/admission/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/admission/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, area/operations, cla: yes, kind/breaking, kind/cleanup, size/L

#1919 Move admissionregistration to v1
  pkg/apis/autoscaling/v1/fleetautoscaler.go
  pkg/apis/autoscaling/v1/fleetautoscaler_test.go
  pkg/apis/autoscaling/v1/zz_generated.deepcopy.go
  pkg/fleetautoscalers/controller_test.go
  pkg/fleetautoscalers/fleetautoscalers_test.go
  site/content/en/docs/Reference/agones_crd_api_reference.html
  test/e2e/fleetautoscaler_test.go
Labels: approved, cla: yes, kind/cleanup, size/XXL

#1922 Updated CRD libraries to v1
  pkg/fleetautoscalers/controller.go
  pkg/fleets/controller.go
  pkg/gameservers/controller.go
  pkg/gameserversets/controller.go
  pkg/testing/controller.go
  pkg/util/crd/crd.go
  pkg/util/crd/crd_test.go
Labels: approved, cla: yes, kind/cleanup, lgtm, size/M

#1924 Oops, k8s-api shortcode only pointed at one URL
  site/layouts/shortcodes/k8s-api.html
Labels: approved, cla: yes, kind/bug, kind/documentation, size/XS

#1923 Remove K8s API reference links from yaml examples
  examples/fleet.yaml
  examples/fleetautoscaler.yaml
  examples/gameserver.yaml
  examples/gameserverallocation.yaml
  examples/webhookfleetautoscaler.yaml
  examples/webhookfleetautoscalertls.yaml
Labels: approved, area/examples, cla: yes, kind/cleanup, size/M

#1925 Update crd-doc-config.json to Kubernetes 1.17
  site/assets/templates/crd-doc-config.json
  site/content/en/docs/Reference/agones_crd_api_reference.html
Labels: approved, cla: yes, kind/cleanup, kind/documentation, lgtm, size/M

#1926 Upgrade prow to 1.17
  build/terraform/prow/module.tf
Labels: approved, area/build-tools, cla: yes, kind/cleanup, size/XS

#1927 Tooling to review pprof heaps
  build/Makefile
  build/README.md
Labels: approved, area/build-tools, cla: yes, kind/feature, lgtm, size/S

#1930 Pin the postcss-cli version
  build/includes/website.mk
Labels: approved, area/build-tools, area/site, cla: yes, kind/bug, lgtm, size/XS

#1929 Add some logging to help determine which game server / namespace is causing this particular error
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
Labels: approved, cla: yes, size/XS

#1933 1.11.0 Release Candidate
  CHANGELOG.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package.json
  site/content/en/blog/releases/1.10.0.md
  site/content/en/blog/releases/1.11.0-rc.md
Labels: approved, cla: yes, kind/release, lgtm, size/L

#1938 Preparation for 1.12.0 release
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package.json
Labels: approved, cla: yes, kind/release, lgtm, size/M
