Repository googleforgames/agones, pull requests merged in 2020-01, with the labels that each got.

#1248 Workerqueue: Enqueuing & processing logs to Debug
  pkg/util/workerqueue/workerqueue.go
Labels: approved, area/operations, kind/cleanup, lgtm, size/XS

#1249 Webhooks: Move "running" logging to Debug
  pkg/gameservers/controller.go
  pkg/util/webhooks/webhooks.go
Labels: approved, area/operations, kind/cleanup, size/XS

#1250 Events: Move logging to Debug
  pkg/fleetautoscalers/controller.go
  pkg/fleets/controller.go
  pkg/gameserverallocations/allocator.go
  pkg/gameserverallocations/controller.go
  pkg/gameservers/controller.go
  pkg/gameservers/health.go
  pkg/gameserversets/controller.go
  pkg/sdkserver/sdkserver.go
Labels: approved, area/operations, kind/cleanup, size/S

#1252 Update e2e Kubectl to 1.13.12
  build/e2e-image/Dockerfile
Labels: approved, area/tests, kind/cleanup, size/XS

#1255 Fixup Helm Configuration table
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: approved, kind/bug, kind/documentation, size/XS

#1253 Update Alpine image to 3.11
  cmd/allocator/Dockerfile
  cmd/controller/Dockerfile
  cmd/ping/Dockerfile
  cmd/sdk-server/Dockerfile
Labels: approved, area/build-tools, area/security, kind/cleanup, lgtm, size/XS

#1251 Update to Go 1.13
  build/build-allocation-images/go/Dockerfile
  build/build-image/Dockerfile
  build/build-sdk-images/go/Dockerfile
  build/build-sdk-images/restapi/Dockerfile
  build/e2e-image/Dockerfile
  go.mod
  pkg/util/webhooks/webhooks_test.go
Labels: approved, area/build-tools, kind/cleanup, size/S

#1234 Unity SDK - Watch GameServer Functionality
  examples/unity-simple/Assets/Scripts/UdpEchoServer.cs
  sdks/unity/AgonesSdk.cs
  site/content/en/docs/Guides/Client SDKs/unity.md
Labels: approved, area/user-experience, kind/feature, size/M

#1257 Add validation for Labels on Fleet and GS Template
  pkg/apis/agones/v1/common.go
  pkg/apis/agones/v1/fleet.go
  pkg/apis/agones/v1/fleet_test.go
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/agones/v1/gameserver_test.go
  pkg/apis/agones/v1/gameserverset.go
  pkg/apis/agones/v1/gameserverset_test.go
  test/e2e/fleet_test.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation_test.go
Labels: approved, area/user-experience, kind/feature, lgtm, size/L

#1254 Handling of PVM shutdown/maintenance events
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  pkg/gameservers/gameservers.go
  pkg/gameservers/gameservers_test.go
  pkg/gameservers/health.go
  pkg/gameservers/migration.go
  pkg/gameservers/migration_test.go
  pkg/util/logfields/logfields.go
Labels: approved, area/user-experience, kind/bug, lgtm, size/XL

#1265 Fix a minor typo in the unity example's README
  examples/unity-simple/README.md
Labels: approved, area/examples, kind/cleanup, kind/documentation, lgtm, size/XS

#1228 Docs Fleet add section about RollingUpdate fields
  site/content/en/docs/Getting Started/create-fleetautoscaler.md
  site/content/en/docs/Guides/fleet-updates.md
Labels: approved, kind/cleanup, kind/documentation, size/S

#1256 Feature Gate implementation
  cmd/allocator/main.go
  cmd/controller/main.go
  cmd/ping/main.go
  cmd/sdk-server/main.go
  install/helm/agones/templates/controller.yaml
  install/helm/agones/templates/ping.yaml
  install/helm/agones/templates/service/allocation.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  pkg/util/runtime/features.go
  pkg/util/runtime/features_test.go
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: approved, kind/feature, size/L

#986 Initial version of EKS terraform config
  examples/terraform-submodules/eks/module.tf
  install/terraform/modules/eks/eks.tf
  install/terraform/modules/eks/outputs.tf
  install/terraform/modules/eks/variables.tf
  install/terraform/modules/helm/helm.tf
  install/terraform/modules/helm/variables.tf
  site/content/en/docs/Installation/Terraform/_index.md
  site/content/en/docs/Installation/Terraform/aks.md
  site/content/en/docs/Installation/Terraform/eks.md
  site/content/en/docs/Installation/Terraform/gke.md
Labels: approved, area/operations, kind/feature, lgtm, size/L

#1266 Add Annotations validation for Template ObjectMeta
  pkg/apis/agones/v1/common.go
  pkg/apis/agones/v1/fleet_test.go
  pkg/apis/agones/v1/gameserver_test.go
  pkg/apis/agones/v1/gameserverset_test.go
  test/e2e/fleet_test.go
  vendor/k8s.io/apimachinery/pkg/api/validation/doc.go
  vendor/k8s.io/apimachinery/pkg/api/validation/generic.go
  vendor/k8s.io/apimachinery/pkg/api/validation/objectmeta.go
  vendor/k8s.io/apimachinery/pkg/api/validation/objectmeta_test.go
  vendor/k8s.io/apimachinery/pkg/api/validation/path/name.go
  vendor/k8s.io/apimachinery/pkg/api/validation/path/name_test.go
Labels: approved, area/user-experience, kind/feature, lgtm, size/XXL

#1267 Update golangci-lint, add more linters
  .golangci.yml
  build/Makefile
  build/build-image/Dockerfile
  cmd/allocator/main.go
  cmd/controller/main.go
  cmd/ping/udp_test.go
  cmd/sdk-server/main.go
  pkg/allocation/converters/converter.go
  pkg/apis/agones/v1/common.go
  pkg/apis/agones/v1/fleet.go
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/agones/v1/gameserverset.go
  pkg/apis/agones/v1/register.go
  pkg/apis/allocation/v1/gameserverallocation.go
  pkg/apis/allocation/v1/register.go
  pkg/apis/autoscaling/v1/register.go
  pkg/apis/multicluster/v1alpha1/gameserverallocationpolicy.go
  pkg/apis/multicluster/v1alpha1/register.go
  pkg/fleets/controller.go
  pkg/fleets/controller_test.go
  pkg/gameserverallocations/allocator.go
  pkg/gameserverallocations/cache_test.go
  pkg/gameserverallocations/controller_test.go
  pkg/gameserverallocations/ready_cache.go
  pkg/gameservers/controller.go
  pkg/gameservers/pernodecounter_test.go
  pkg/gameservers/portallocator.go
  pkg/gameservers/portallocator_test.go
  pkg/gameserversets/controller.go
  pkg/gameserversets/controller_test.go
  pkg/metrics/controller.go
  pkg/metrics/exporter.go
  pkg/sdkserver/localsdk.go
  pkg/util/apiserver/apiserver.go
  pkg/util/crd/crd.go
  pkg/util/runtime/runtime_test.go
  sdks/go/sdk_test.go
  site/handler.go
  test/e2e/allocator_test.go
  test/e2e/fleet_test.go
  test/e2e/framework/framework.go
Labels: approved, lgtm, size/L

#1264 Node packaging
  build/build-sdk-images/node/publish.sh
  examples/nodejs-simple/package.json
  examples/nodejs-simple/src/index.js
  sdks/nodejs/.npmrc
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  site/content/en/docs/Guides/Client SDKs/nodejs.md
  test/sdk/nodejs/package.json
  test/sdk/nodejs/testSDKClient.js
Labels: approved, area/user-experience, kind/breaking, kind/feature, size/M

#1270 Fix broken link to Helm installation
  install/helm/agones/README.md
Labels: approved, kind/cleanup, kind/documentation, size/XS

#1269 Fuzz Roundtrip test for v1 Agones schemas
  pkg/apis/agones/v1/fuzz_test/roundtrip_test.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/codec.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/fuzzer/fuzzer.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/fuzzer/valuefuzz.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/fuzzer/valuefuzz_test.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/roundtrip/roundtrip.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/fuzzer/fuzzer.go
Labels: lgtm, size/XXL

#1271 Added Community Meetings to the community pages
  README.md
  site/config.toml
Labels: approved, area/community, area/site, kind/documentation, kind/feature, lgtm, size/S

#1275 Release 1.3.0-rc
  CHANGELOG.md
  docs/governance/templates/release_issue.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/nodejs/package.json
  site/content/en/blog/releases/1.2.0.md
  site/content/en/blog/releases/1.3.0-rc.md
Labels: approved, kind/release, lgtm, size/L

#1274 Fix list formatting on the terraform install page.
  site/content/en/docs/Installation/Terraform/_index.md
Labels: approved, size/XS

#1278 Need to change to https url on swagger-codegen download
  build/build-sdk-images/restapi/build-sdk-test.sh
Labels: approved, area/tests, kind/cleanup, lgtm, size/XS

#1277 Release publishing of NPM module
  build/build-sdk-images/node/publish.sh
  build/includes/release.mk
Labels: approved, area/build-tools, size/S

#1281 Site: Add video & podcasts to third party section
  site/content/en/docs/Third Party Content/podcasts.md
  site/content/en/docs/Third Party Content/videos-and-presentations.md
Labels: approved, kind/documentation, kind/feature, lgtm, size/S

#1284 Nodejs docs: require for npm should switch on 1.3.0
  site/content/en/docs/Guides/Client SDKs/nodejs.md
Labels: approved, kind/cleanup, kind/documentation, lgtm, size/XS

#1291 Preparation for 1.4.0 Sprint
  build/Makefile
  docs/governance/templates/release_issue.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/nodejs/package.json
Labels: approved, kind/release, lgtm, size/M

#1294 Adding a "Major Feature" to overview page
  site/content/en/docs/Overview/_index.md
Labels: approved, kind/cleanup, kind/documentation, lgtm, size/XS

#1292 Show GameServer name in TestGameServerReserve flakiness fail
  test/e2e/gameserver_test.go
Labels: approved, area/tests, lgtm, size/XS

#1297 Fix broken agones.dev link
  CONTRIBUTING.md
Labels: kind/cleanup, kind/documentation, lgtm, size/XS

#1302 Super Tux Kart Example
  build/includes/examples.mk
  examples/supertuxkart/Dockerfile
  examples/supertuxkart/Makefile
  examples/supertuxkart/README.md
  examples/supertuxkart/entrypoint.sh
  examples/supertuxkart/fleet.yaml
  examples/supertuxkart/gameserver.yaml
  examples/supertuxkart/gameserverallocation.yaml
  examples/supertuxkart/main.go
  examples/supertuxkart/server_config.xml
Labels: approved, area/examples, kind/feature, lgtm, size/L

#1293 Use a numeric User ID for the "agones" user in the SDK sidecar
  cmd/allocator/Dockerfile
  cmd/controller/Dockerfile
  cmd/ping/Dockerfile
  cmd/sdk-server/Dockerfile
  examples/allocator-service/Dockerfile
  examples/autoscaler-webhook/Dockerfile
  examples/autoscaler-webhook/Makefile
  examples/cpp-simple/Dockerfile
  examples/cpp-simple/Makefile
  examples/crd-client/Dockerfile
  examples/crd-client/Makefile
  examples/nodejs-simple/Dockerfile
  examples/nodejs-simple/Makefile
  examples/rust-simple/Dockerfile
  examples/rust-simple/Makefile
  examples/simple-tcp/Dockerfile
  examples/simple-tcp/Makefile
  examples/simple-udp/Dockerfile
  examples/simple-udp/Makefile
  examples/xonotic/Dockerfile
  examples/xonotic/Makefile
Labels: approved, area/operations, kind/bug, lgtm, size/M

#1306 Add fuzz tests missing vendor changes
  vendor_fixes/k8s.io/apimachinery/pkg/api/apitesting/codec.go
  vendor_fixes/k8s.io/apimachinery/pkg/api/apitesting/fuzzer/fuzzer.go
  vendor_fixes/k8s.io/apimachinery/pkg/api/apitesting/fuzzer/valuefuzz.go
  vendor_fixes/k8s.io/apimachinery/pkg/api/apitesting/fuzzer/valuefuzz_test.go
  vendor_fixes/k8s.io/apimachinery/pkg/api/apitesting/roundtrip/roundtrip.go
  vendor_fixes/k8s.io/apimachinery/pkg/api/validation/doc.go
  vendor_fixes/k8s.io/apimachinery/pkg/api/validation/generic.go
  vendor_fixes/k8s.io/apimachinery/pkg/api/validation/objectmeta.go
  vendor_fixes/k8s.io/apimachinery/pkg/api/validation/objectmeta_test.go
  vendor_fixes/k8s.io/apimachinery/pkg/api/validation/path/name.go
  vendor_fixes/k8s.io/apimachinery/pkg/api/validation/path/name_test.go
  vendor_fixes/k8s.io/apimachinery/pkg/apis/meta/fuzzer/fuzzer.go
  vendor_fixes/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
  vendor_fixes/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation_test.go
Labels: approved, lgtm, size/XXL
