Repository googleforgames/agones, pull requests merged in 2020-09, with the labels that each got.

#1775 Make Unreal lambda bindings on the AgonesComponent safe
  sdks/unreal/Agones/Source/Agones/Private/AgonesComponent.cpp
Labels: approved, area/user-experience, cla: yes, kind/bug, lgtm, size/M

#1777 Added a new 'disableTLS' flag and changed 'disableMTLS' to only disab…
  cmd/allocator/main.go
  cmd/allocator/metrics.go
  install/helm/agones/templates/service/allocation.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
Labels: approved, cla: yes, lgtm, size/L

#1787 Examples: update Kubernetes version
  examples/fleetautoscaler.yaml
  examples/gameserver.yaml
  site/content/en/docs/Reference/fleet.md
  site/content/en/docs/Reference/fleetautoscaler.md
  site/content/en/docs/Reference/gameserver.md
Labels: approved, area/examples, area/site, cla: yes, lgtm, size/S

#1788 Adding aLekSer to approvers list
  OWNERS
Labels: approved, area/meta, cla: yes, lgtm, size/XS

#1785 GolangCI-lint updating version to 1.30
  .golangci.yml
  build/build-image/Dockerfile
  cmd/controller/main.go
  test/e2e/framework/framework.go
  test/load/allocation/allocationload.go
Labels: approved, area/build-tools, cla: yes, size/S

#1784 Doc changes for TLS and loadBalancerIP changes
  site/content/en/docs/Advanced/allocator-service.md
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: approved, area/site, cla: yes, size/S

#1789 Docs: updated advised version of Kubernetes to use
  site/content/en/docs/Installation/_index.md
Labels: approved, area/site, cla: yes, lgtm, size/S

#1786 Docs: updating Minikube kubernetes version to 1.16
  build/includes/kind.mk
  build/includes/minikube.mk
  site/content/en/docs/Installation/Creating Cluster/minikube.md
Labels: approved, area/site, cla: yes, size/S

#1793 Add load balancer configuration for Helm options
  install/helm/agones/templates/ping.yaml
  install/helm/agones/templates/service/allocation.yaml
  install/helm/agones/values.yaml
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: approved, area/operations, cla: yes, kind/feature, lgtm, size/M

#1783 Add Uninstall instructions when using install.yaml
  site/content/en/docs/Installation/Install Agones/yaml.md
Labels: approved, area/site, cla: yes, size/S

#1801 Add lock to to sdk-conformance compare()
  pkg/sdkserver/localsdk.go
Labels: approved, cla: yes, kind/cleanup, lgtm, size/XS

#1771 Added game-server example
  build/Makefile
  examples/simple-game-server/Dockerfile
  examples/simple-game-server/Makefile
  examples/simple-game-server/README.md
  examples/simple-game-server/dev-gameserver.yaml
  examples/simple-game-server/fleet-distributed.yaml
  examples/simple-game-server/fleet-tcp.yaml
  examples/simple-game-server/fleet.yaml
  examples/simple-game-server/fleetautoscaler.yaml
  examples/simple-game-server/gameserver-passthrough.yaml
  examples/simple-game-server/gameserver.yaml
  examples/simple-game-server/gameserverallocation.yaml
  examples/simple-game-server/main.go
  site/content/en/docs/Examples/_index.md
  test/e2e/framework/framework.go
Labels: approved, area/examples, area/tests, cla: yes, lgtm, size/XL

#1792 UE4 small nit about float to float comparison
  sdks/unreal/Agones/Source/Agones/Private/AgonesComponent.cpp
Labels: approved, area/user-experience, cla: yes, kind/cleanup, size/XS

#1795 Troubleshooting - namespace stuck terminating
  site/content/en/docs/Guides/troubleshooting.md
Labels: approved, cla: yes, size/M

#1803 Flaky: TestControllerSyncUnhealthyGameServers
  pkg/gameserversets/controller_test.go
Labels: approved, area/tests, cla: yes, kind/bug, size/XS

#1804 DriveBy - fix link
  examples/allocator-client/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1805 Flaky: TestControllerGameServersNodeState
  pkg/metrics/controller_test.go
  pkg/metrics/util_test.go
Labels: approved, area/tests, cla: yes, kind/bug, lgtm, size/M

#1806 Upgrade Kubectl to 1.16.15
  build/build-image/Dockerfile
  build/e2e-image/Dockerfile
Labels: approved, area/build-tools, cla: yes, kind/breaking, lgtm, size/XS

#1791 Docs: updating GKE and AKS Kubernetes versions
  install/terraform/modules/aks/aks.tf
  site/content/en/docs/Installation/Creating Cluster/aks.md
  site/content/en/docs/Installation/Creating Cluster/gke.md
  site/content/en/docs/Installation/Terraform/aks.md
Labels: approved, cla: yes, lgtm, size/M

#1812 Add logging for the client certificate verification
  cmd/allocator/main.go
Labels: approved, cla: yes, lgtm, size/XS

#1807 Rerun Agones CRD client generation
  pkg/client/clientset/versioned/clientset.go
Labels: approved, cla: yes, kind/cleanup, size/XS

#1808 CI: Wait for tests step before sdk-conformance
  cloudbuild.yaml
Labels: approved, cla: yes, size/XS

#1811 Docs: Fix rest `GetPlayerCount` description
  site/content/en/docs/Guides/Client SDKs/rest.md
Labels: approved, cla: yes, kind/bug, kind/documentation, lgtm, size/XS

#1814 Website: Update API docs to Kubernetes 1.16
  site/assets/templates/crd-doc-config.json
  site/content/en/docs/Reference/agones_crd_api_reference.html
Labels: approved, cla: yes, lgtm, size/XXL

#1817 Remove the warning about the unity SDK not being feature complete.
  site/content/en/docs/Guides/Client SDKs/unity.md
Labels: approved, cla: yes, lgtm, size/XS

#1818 Pin npm autoprefixer package for site generation
  build/includes/website.mk
Labels: approved, area/site, cla: yes, kind/bug, lgtm, size/XS

#1820 Fix 404 in AWS/EKS documentation
  site/content/en/docs/Installation/Creating Cluster/eks.md
Labels: approved, cla: yes, kind/bug, kind/documentation, lgtm, size/XS

#1790 Docs and TF: Update EKS Kubernetes version to use 1.16
  install/terraform/modules/eks/eks.tf
  site/content/en/docs/Installation/Creating Cluster/eks.md
Labels: approved, area/operations, area/site, cla: yes, size/S

#1802 [Doc] Update allocator service & multi-cluster allocation documentation
  site/content/en/docs/Advanced/allocator-service.md
  site/content/en/docs/Advanced/multi-cluster-allocation.md
Labels: approved, cla: yes, size/M

#1813 Website: Update properly to Kubernetes 1.16
  examples/fleet.yaml
  site/content/en/docs/Advanced/limiting-resources.md
  site/content/en/docs/Reference/fleet.md
  site/content/en/docs/Reference/fleetautoscaler.md
  site/content/en/docs/Reference/gameserver.md
Labels: approved, cla: yes, size/L

#1826 Corrected gke docs 'release-release' typo
  site/content/en/docs/Installation/Terraform/gke.md
Labels: approved, cla: yes, lgtm, size/XS

#1626 Fix Fleets RollingUpdate
  build/Makefile
  cloudbuild.yaml
  go.mod
  pkg/apis/agones/v1/fleet.go
  pkg/apis/agones/v1/fleet_test.go
  pkg/fleets/controller.go
  pkg/fleets/controller_test.go
  pkg/util/runtime/features.go
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Guides/fleet-updates.md
  test/e2e/fleet_test.go
Labels: approved, cla: yes, kind/feature, lgtm, size/L

#1764 Add TCPUDP protocol
  build/terraform/e2e/module.tf
  examples/gameserver.yaml
  install/helm/agones/templates/crds/_gameserverspecvalidation.yaml
  install/terraform/modules/gke/cluster.tf
  install/yaml/install.yaml
  pkg/apis/agones/v1/gameserver.go
  pkg/gameservers/portallocator.go
  pkg/gameservers/portallocator_test.go
  site/content/en/docs/Reference/agones_crd_api_reference.html
  site/content/en/docs/Reference/gameserver.md
  test/e2e/framework/framework.go
  test/e2e/gameserver_test.go
Labels: approved, area/user-experience, cla: yes, kind/feature, size/L

#1825 Add player tracking and shutdown to the supertuxkart example server
  examples/supertuxkart/Dockerfile
  examples/supertuxkart/Makefile
  examples/supertuxkart/entrypoint.sh
  examples/supertuxkart/gameserver.yaml
  examples/supertuxkart/go.mod
  examples/supertuxkart/go.sum
  examples/supertuxkart/main.go
  examples/supertuxkart/main_test.go
Labels: approved, area/examples, cla: yes, kind/feature, size/L

#1828 Release 1.9.0-rc
  CHANGELOG.md
  build/includes/examples.mk
  docs/governance/templates/release.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package.json
  site/content/en/blog/releases/1.8.0.md
  site/content/en/blog/releases/1.9.0-rc.md
Labels: approved, cla: yes, kind/release, lgtm, size/L

#1836 Preparation for 1.10.0
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package.json
Labels: approved, cla: yes, kind/release, lgtm, size/M
