Repository googleforgames/agones, pull requests merged in 2020-04, with the labels that each got.

#1440 Alpha GameServer attributes added to SDK
  build/build-sdk-images/csharp/gen.sh
  pkg/sdk/sdk.pb.go
  pkg/sdkserver/sdk.go
  pkg/sdkserver/sdk_test.go
  proto/sdk/sdk.proto
  sdks/cpp/include/agones/sdk.pb.h
  sdks/cpp/src/agones/sdk.pb.cc
  sdks/csharp/sdk/generated/Sdk.cs
  sdks/csharp/sdk/generated/SdkGrpc.cs
  sdks/go/alpha.go
  sdks/nodejs/lib/sdk_pb.js
  sdks/rust/src/grpc/sdk.rs
  sdks/swagger/sdk.swagger.json
Labels: approved, area/user-experience, kind/feature, lgtm, size/XXL

#1443 Revert local sdk logging from Debug->Info
  pkg/sdkserver/localsdk.go
Labels: approved, area/user-experience, kind/bug, lgtm, size/M

#1442 Fix wrong function usage
  cmd/controller/main.go
Labels: approved, size/XS

#1433 Added version to stress tests files
  build/Makefile
  test/e2e/fleet_test.go
  test/e2e/framework/framework.go
  test/e2e/framework/perf.go
Labels: lgtm, size/M

#1431 Terraform: Add FeatureGates into helm release
  build/includes/terraform.mk
  build/terraform/gke/module.tf
  examples/terraform-submodules/aks/module.tf
  examples/terraform-submodules/eks/module.tf
  examples/terraform-submodules/gke/module.tf
  install/terraform/modules/helm/helm.tf
  install/terraform/modules/helm/variables.tf
  site/content/en/docs/Installation/Terraform/aks.md
  site/content/en/docs/Installation/Terraform/eks.md
  site/content/en/docs/Installation/Terraform/gke.md
Labels: approved, size/M

#1444 Local implementation of Set/GetPlayerCapacity
  build/includes/sdk.mk
  pkg/sdkserver/localsdk.go
  pkg/sdkserver/localsdk_test.go
  test/sdk/go/sdk-client-test.go
Labels: approved, area/user-experience, kind/feature, lgtm, size/L

#1448 Feature Gates: EnableAllFeatures
  pkg/util/runtime/features.go
  pkg/util/runtime/features_test.go
Labels: approved, area/user-experience, kind/feature, size/M

#1451 Flaky: TestLocalSDKServerPlayerCapacity
  pkg/sdkserver/localsdk_test.go
Labels: approved, area/tests, kind/bug, size/S

#1455 Release 1.5.0-rc
  CHANGELOG.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/nodejs/package.json
  site/content/en/blog/releases/1.4.0.md
  site/content/en/blog/releases/1.5.0-rc.md
Labels: approved, kind/release, lgtm, size/L

#1457 Use go modules for a website and update go version
  build/includes/website.mk
  cloudbuild.yaml
  site/app.yaml
  site/cloudbuild.yaml
  site/go.mod
  site/go.sum
Labels: approved, area/site, kind/cleanup, lgtm, size/M

#1462 Website: Fix path in swagger command
  site/content/en/docs/Guides/Client SDKs/rest.md
Labels: approved, kind/cleanup, kind/documentation, lgtm, size/XS

#1458 Fixed flaky TestGameServerWithPortsMappedToMultipleContainers
  test/e2e/gameserver_test.go
Labels: approved, area/tests, kind/bug, lgtm, size/M

#1460 FAQ for Agones
  site/content/en/docs/FAQ/_index.md
Labels: approved, kind/documentation, kind/feature, lgtm, size/L

#1470 e2e image needs 1.14.10 kubectl
  build/e2e-image/Dockerfile
Labels: approved, area/build-tools, area/tests, kind/bug, lgtm, size/XS

#1466 Website: A number of corrections in the docs
  examples/autoscaler-webhook/README.md
  site/content/en/docs/Advanced/allocator-service.md
  site/content/en/docs/Advanced/limiting-resources.md
  site/content/en/docs/Advanced/multi-cluster-allocation.md
  site/content/en/docs/Advanced/scheduling-and-autoscaling.md
  site/content/en/docs/Advanced/service-accounts.md
  site/content/en/docs/Getting Started/create-fleet.md
  site/content/en/docs/Getting Started/create-fleetautoscaler.md
  site/content/en/docs/Getting Started/create-gameserver.md
  site/content/en/docs/Getting Started/create-webhook-fleetautoscaler.md
  site/content/en/docs/Getting Started/edit-first-gameserver-go.md
  site/content/en/docs/Guides/Client SDKs/_index.md
  site/content/en/docs/Guides/Client SDKs/cpp.md
  site/content/en/docs/Guides/metrics.md
  site/content/en/docs/Installation/Creating Cluster/aks.md
  site/content/en/docs/Installation/Creating Cluster/eks.md
  site/content/en/docs/Installation/Install Agones/helm.md
  site/content/en/docs/Installation/Terraform/aks.md
  site/content/en/docs/Installation/Terraform/gke.md
  site/content/en/docs/Installation/upgrading.md
  site/content/en/docs/Reference/fleetautoscaler.md
  site/content/en/docs/Reference/gameserver.md
Labels: approved, kind/cleanup, kind/documentation, lgtm, size/L

#1469 Working Node.js example gameserver.yaml
  examples/nodejs-simple/gameserver.yaml
Labels: approved, area/examples, kind/bug, lgtm, size/XS

#1474 Preparation for 1.6.0 Release.
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/nodejs/package.json
Labels: approved, kind/release, lgtm, size/M

#1456 SDK Conformance test - fix parallel recordRequests
  pkg/sdkserver/localsdk.go
  pkg/sdkserver/localsdk_test.go
Labels: approved, size/M

#1423 Add validation for CPU and Memory Resources for GameServers, Fleets and GameServerSets
  pkg/apis/agones/v1/gameserver.go
  test/e2e/fleet_test.go
  test/e2e/gameserver_test.go
Labels: approved, area/user-experience, kind/feature, size/L

#1453 Enhance Logs readability of SDK Conformance Tests
  build/build-sdk-images/node/build-sdk-test.sh
  build/build-sdk-images/restapi/Dockerfile
  build/includes/sdk.mk
  cmd/sdk-server/main.go
  cmd/sdk-server/main_test.go
  pkg/sdkserver/localsdk.go
  pkg/sdkserver/localsdk_test.go
Labels: approved, area/tests, kind/cleanup, size/L

#1465 Update Grafana to the 6.7 release.
  build/Makefile
  build/build-image/Dockerfile
  build/grafana/dashboard-gameservers.yaml
Labels: approved, area/build-tools, area/operations, size/XXL

#1459 Update the agones-allocator doc to recommend using cert-manager
  site/content/en/docs/Advanced/allocator-service.md
  site/content/en/docs/Advanced/multi-cluster-allocation.md
Labels: approved, kind/documentation, kind/feature, lgtm, size/M

#1464 Refactor of localsdk tests
  pkg/sdkserver/localsdk_test.go
Labels: approved, area/tests, kind/cleanup, size/M

#1477 Update documentation describing when we will change the version of Kubernetes that we support.
  site/content/en/docs/Installation/_index.md
Labels: approved, lgtm, size/XS

#1476 GameServer CRD with Updated Player Tracking
  install/helm/agones/templates/crds/_gameserverspecvalidation.yaml
  install/yaml/install.yaml
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/agones/v1/zz_generated.deepcopy.go
  site/content/en/docs/Reference/agones_crd_api_reference.html
Labels: approved, area/user-experience, kind/feature, lgtm, size/L

#1480 Fix for flaky e2e: TestUnhealthyGameServersWithoutFreePorts
  test/e2e/gameserver_test.go
Labels: approved, area/tests, kind/bug, size/S

#1471 Added a pull request template
  .github/pull_request_template.md
Labels: approved, area/meta, kind/feature, size/S

#1484 Allocator client tutorial: add steps for MacOS
  site/content/en/docs/Advanced/allocator-service.md
Labels: approved, kind/cleanup, kind/documentation, lgtm, size/XS

#1445 Pass FEATURE_GATES flag to e2e tests
  build/Makefile
  pkg/util/runtime/features.go
  test/e2e/controller/main_test.go
  test/e2e/fleet_test.go
  test/e2e/framework/framework.go
  test/e2e/gameserver_test.go
  test/e2e/main_test.go
Labels: approved, area/build-tools, area/tests, kind/feature, size/L

#1481 Changes in proto for Player Tracking design update
  proto/sdk/alpha/alpha.proto
  proto/sdk/sdk.proto
Labels: approved, area/user-experience, kind/feature, size/M

#1486 Update developer tooling to Kubernetes 1.15
  build/build-image/Dockerfile
  build/gke-test-cluster/cluster-e2e.yml
  build/gke-test-cluster/cluster-prow.yml
  build/gke-test-cluster/cluster.yml.jinja
  build/includes/kind.mk
  build/includes/minikube.mk
Labels: approved, area/build-tools, kind/breaking, lgtm, size/S

#1492 Update testify package in gomod
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/testutil/testutil.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/modules.txt
Labels: lgtm, size/XL

#1487 Docs: add Grafana version explicitly
  build/Makefile
  build/README.md
  build/grafana.yaml
  site/content/en/docs/Guides/metrics.md
Labels: approved, size/S

#1493 Code Gen and Stubs for updated Player Tracking
  pkg/sdk/alpha/alpha.pb.go
  pkg/sdk/alpha/alpha.pb.gw.go
  pkg/sdk/sdk.pb.go
  pkg/sdkserver/localsdk.go
  pkg/sdkserver/sdkserver.go
  sdks/cpp/include/agones/sdk.pb.h
  sdks/cpp/src/agones/sdk.pb.cc
  sdks/csharp/sdk/generated/Sdk.cs
  sdks/go/alpha_test.go
  sdks/nodejs/lib/sdk_pb.js
  sdks/rust/src/grpc/sdk.rs
  sdks/swagger/alpha.swagger.json
  sdks/swagger/sdk.swagger.json
Labels: approved, area/user-experience, kind/feature, lgtm, size/XXL

#1479 Monitoring: fix error on Stackdriver exporter
  pkg/metrics/kubernetes_client.go
Labels: approved, area/operations, kind/bug, lgtm, size/S

#1485 Improved gameserver unit tests
  pkg/apis/agones/v1/common.go
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/agones/v1/gameserver_test.go
  test/e2e/fleet_test.go
Labels: approved, area/tests, kind/cleanup, lgtm, size/XXL

#1497 Add Event to Player Capacity update
  pkg/sdkserver/sdkserver.go
  pkg/sdkserver/sdkserver_test.go
Labels: approved, area/user-experience, kind/feature, lgtm, size/S

#1499 Refactor err check in GS controller a bit. Add event if Pod was not created
  pkg/gameservers/controller.go
Labels: approved, lgtm, size/S

#1500 Fix link to client SDK documentation
  sdks/rust/README.md
Labels: approved, kind/cleanup, kind/documentation, size/XS

#1498 Add PlayerTracking IDs to SDK Convert function
  pkg/sdkserver/sdk.go
  pkg/sdkserver/sdk_test.go
Labels: approved, area/user-experience, kind/feature, lgtm, size/XS

#1502 FeatureFlag:PlayerTesting ➡ FeatureFlag:PlayerTracking
  pkg/apis/agones/v1/gameserver.go
  pkg/sdk/sdk.pb.go
  pkg/sdkserver/localsdk.go
  pkg/sdkserver/sdkserver.go
  proto/sdk/sdk.proto
  sdks/csharp/sdk/generated/Sdk.cs
  sdks/rust/src/grpc/sdk.rs
  sdks/swagger/sdk.swagger.json
  site/content/en/docs/Reference/agones_crd_api_reference.html
Labels: approved, kind/cleanup, lgtm, size/M

#1503 Added a couple of tests to gameserverallocationpolicy
  pkg/apis/multicluster/v1/gameserverallocationpolicy_test.go
Labels: approved, lgtm, size/M

#1496 Implementation of Local SDK Server Player Tracking
  pkg/sdkserver/localsdk.go
  pkg/sdkserver/localsdk_test.go
Labels: approved, area/user-experience, kind/feature, size/L

#1505 fix a typo in README.md
  README.md
Labels: approved, kind/cleanup, kind/documentation, lgtm, size/XS
