Repository googleforgames/agones, pull requests merged in 2020-08, with the labels that each got.

#1730 Build Terraform: Use docker image project default
  build/includes/terraform.mk
Labels: approved, area/build-tools, cla: yes, kind/bug, lgtm, size/S

#1658 Alpha SDK and example for Node.js (Player tracking)
  build/build-sdk-images/node/gen.sh
  examples/nodejs-simple/Makefile
  examples/nodejs-simple/README.md
  examples/nodejs-simple/package-lock.json
  examples/nodejs-simple/package.json
  examples/nodejs-simple/src/index.js
  sdks/nodejs/.eslintrc.json
  sdks/nodejs/lib/alpha/alpha_grpc_pb.js
  sdks/nodejs/lib/alpha/alpha_pb.js
  sdks/nodejs/lib/alpha/google/api/annotations_pb.js
  sdks/nodejs/lib/alpha/google/api/http_pb.js
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/nodejs/spec/agonesSDK.spec.js
  sdks/nodejs/spec/alphaAgonesSDK.spec.js
  sdks/nodejs/src/agonesSDK.js
  sdks/nodejs/src/alpha.js
  sdks/nodejs/src/index.js
Labels: approved, cla: yes, lgtm, size/XXL

#1727 Tests update: gameserversets-controllers added missing test cases
  pkg/gameserversets/controller.go
  pkg/gameserversets/controller_test.go
  pkg/gameserversets/gameserversets_test.go
Labels: approved, area/tests, cla: yes, kind/cleanup, size/L

#1723 Tests update: portallocator_test
  pkg/gameservers/portallocator.go
  pkg/gameservers/portallocator_test.go
Labels: approved, cla: yes, size/L

#1737 Terraform Helm enforcing string for set values
  install/terraform/modules/helm3/helm.tf
  install/terraform/modules/helm3/variables.tf
Labels: approved, area/operations, cla: yes, kind/bug, lgtm, size/XS

#1738 Switch gcloud-test-cluster to Terraform
  build/gke-test-cluster/cluster.yml.jinja
  build/includes/google-cloud.mk
Labels: approved, area/operations, cla: yes, kind/cleanup, size/L

#1733 Add Rust SDK async/await syntax support and minor improvements
  build/build-sdk-images/rust/Dockerfile
  build/includes/sdk.mk
  sdks/rust/Cargo.toml
  sdks/rust/src/alpha.rs
  sdks/rust/src/grpc/alpha.rs
  sdks/rust/src/grpc/alpha_grpc.rs
  sdks/rust/src/grpc/sdk.rs
  sdks/rust/src/grpc/sdk_grpc.rs
  sdks/rust/src/lib.rs
  sdks/rust/src/sdk.rs
  sdks/rust/src/types.rs
  test/sdk/rust/Cargo.toml
  test/sdk/rust/src/main.rs
Labels: approved, cla: yes, size/XXL

#1725 Fix findOpenPorts portAllocator function
  pkg/gameservers/portallocator.go
  pkg/gameservers/portallocator_test.go
Labels: approved, cla: yes, lgtm, size/S

#1714 Use the scheduling.k8s.io/v1 API since the beta API will no longer be served by default starting with Kubernetes 1.16
  install/helm/agones/templates/priority-class.yaml
  install/yaml/install.yaml
  pkg/util/apiserver/apiserver.go
Labels: approved, area/operations, cla: yes, kind/cleanup, size/XS

#1736 Fix fleetautoscalers webhook TLS policy
  pkg/fleetautoscalers/fleetautoscalers.go
Labels: approved, area/user-experience, cla: yes, kind/bug, size/S

#1739 move Netspeak Unreal SDK into Agones Unreal SDK
  sdks/unreal/Agones/Agones.uplugin
  sdks/unreal/Agones/README.md
  sdks/unreal/Agones/Resources/Icon128.png
  sdks/unreal/Agones/Source/Agones/Agones.Build.cs
  sdks/unreal/Agones/Source/Agones/Classes/Classes.h
  sdks/unreal/Agones/Source/Agones/Private/Agones.cpp
  sdks/unreal/Agones/Source/Agones/Private/AgonesComponent.cpp
  sdks/unreal/Agones/Source/Agones/Private/AgonesHook.cpp
  sdks/unreal/Agones/Source/Agones/Private/AgonesSettings.cpp
  sdks/unreal/Agones/Source/Agones/Public/Agones.h
  sdks/unreal/Agones/Source/Agones/Public/AgonesComponent.h
  sdks/unreal/Agones/Source/Agones/Public/AgonesHook.h
  sdks/unreal/Agones/Source/Agones/Public/AgonesSettings.h
  sdks/unreal/Agones/Source/Agones/Public/Model/Duration.h
  sdks/unreal/Agones/Source/Agones/Public/Model/GameServer.h
  sdks/unreal/Agones/Source/Agones/Public/Model/GameServerObjectMeta.h
  sdks/unreal/Agones/Source/Agones/Public/Model/GameServerSpec.h
  sdks/unreal/Agones/Source/Agones/Public/Model/GameServerStatus.h
  sdks/unreal/Agones/Source/Agones/Public/Model/KeyValuePair.h
  sdks/unreal/Agones/Source/Agones/Public/Model/SpecHealth.h
  sdks/unreal/Agones/Source/Agones/Public/Model/StatusPort.h
  site/content/en/docs/Guides/Client SDKs/unreal.md
  site/static/images/unreal_bp_actions.png
  site/static/images/unreal_bp_component.png
Labels: approved, area/user-experience, cla: yes, kind/breaking, kind/feature, lgtm, size/XXL

#1735 Added several tests for metrics package
  pkg/metrics/controller_test.go
  pkg/metrics/util.go
  pkg/metrics/util_test.go
Labels: approved, cla: yes, size/L

#1743 Add note on GKE cluster versions
  site/content/en/docs/Installation/Creating Cluster/gke.md
Labels: approved, cla: yes, kind/cleanup, kind/documentation, size/S

#1741 Add firewall name variable to GKE Terraform
  install/terraform/modules/gke/cluster.tf
  install/terraform/modules/gke/variables.tf
Labels: approved, area/operations, cla: yes, kind/feature, size/S

#1746 Release 1.8.0 Release Candidate
  CHANGELOG.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/nodejs/package.json
  site/content/en/blog/releases/1.7.0.md
  site/content/en/blog/releases/1.8.0-rc.md
Labels: approved, cla: yes, kind/release, lgtm, size/L

#1749 Fix parsing the media type in GameServerAllocation
  pkg/gameserverallocations/controller.go
Labels: area/user-experience, cla: yes, kind/bug, lgtm, size/XS

#1750 Remove Deployment Manager from build/
  build/README.md
  build/gke-test-cluster/cluster-e2e.yml
  build/gke-test-cluster/cluster-prow.yml
  build/includes/google-cloud.mk
  build/includes/terraform.mk
  build/terraform/e2e/module.tf
  build/terraform/prow/module.tf
Labels: approved, area/build-tools, cla: yes, kind/cleanup, lgtm, size/L

#1755 Helm default values in docs (related to controller limits) match chart default values
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: cla: yes, lgtm, size/XS

#1752 Best practices for game server shutdown
  site/content/en/docs/Guides/Client SDKs/_index.md
Labels: approved, cla: yes, kind/cleanup, kind/documentation, size/S

#1762 Preparation for 1.9.0
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/nodejs/package.json
Labels: approved, cla: yes, kind/release, lgtm, size/M

#1766 Added option to hardcode load balancer IP for allocator.
  install/helm/agones/templates/service/allocation.yaml
  install/helm/agones/values.yaml
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: approved, cla: yes, lgtm, size/S

#1753 Publish to NuGet for Csharp SDK
  build/build-sdk-images/csharp/publish.sh
  build/build-sdk-images/csharp/shell.sh
  build/includes/sdk.mk
  docs/governance/templates/release_issue.md
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
Labels: approved, area/build-tools, cla: yes, kind/feature, lgtm, size/M

#1772 Update GKE Terraform clusters to 1.16
  build/terraform/gke/module.tf
  build/terraform/prow/module.tf
  install/terraform/modules/gke/cluster.tf
  install/terraform/modules/gke/variables.tf
Labels: approved, area/operations, cla: yes, kind/breaking, lgtm, size/S

#1765 Pass port into autoscaler url from webhook policy
  pkg/fleetautoscalers/fleetautoscalers.go
  pkg/fleetautoscalers/fleetautoscalers_test.go
  site/content/en/docs/Reference/fleetautoscaler.md
Labels: cla: yes, size/S

#1774 The footnote shouldn't be part of the table.
  site/content/en/docs/Guides/feature-stages.md
Labels: approved, cla: yes, kind/cleanup, kind/documentation, lgtm, size/XS

#1697 Add Terraform example for GKE custom VPC deployment
  examples/terraform-submodules/gke/module.tf
  site/content/en/docs/Installation/Terraform/gke.md
Labels: approved, cla: yes, lgtm, size/M
