Repository googleforgames/agones, pull requests merged in 2020-02, with the labels that each got.

#1311 Move all "Synchronising" logs to debug
  pkg/fleetautoscalers/controller.go
  pkg/fleets/controller.go
  pkg/gameservers/controller.go
  pkg/gameservers/health.go
Labels: approved, area/operations, kind/cleanup, lgtm, size/XS

#1310 Workerqueue IsConflict needed to check error Cause
  pkg/util/workerqueue/workerqueue.go
Labels: approved, area/operations, kind/bug, size/XS

#1282 Conformance test for CPP SDK
  build/build-sdk-images/cpp/build-sdk-test.sh
  build/build-sdk-images/cpp/clean.sh
  build/build-sdk-images/cpp/sdktest.sh
  build/includes/sdk.mk
  cloudbuild.yaml
  test/sdk/cpp/CMakeLists.txt
  test/sdk/cpp/server.cc
Labels: approved, area/tests, area/user-experience, lgtm, size/L

#1316 Fleet: Add validation for Strategy Type
  pkg/apis/agones/v1/fleet.go
  pkg/apis/agones/v1/fleet_test.go
  test/e2e/fleet_test.go
Labels: approved, size/M

#1317 Removing Interpolation-only expressions
  install/terraform/cluster.tf
  install/terraform/helm.tf
  install/terraform/modules/gke/cluster.tf
  install/terraform/modules/gke/outputs.tf
Labels: approved, size/L

#1321 Adding missing dependency to a vendor_fixes
  go.sum
  vendor/k8s.io/apimachinery/pkg/util/httpstream/doc.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/httpstream.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/httpstream_test.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/connection.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/connection_test.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper_test.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/upgrade.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/upgrade_test.go
  vendor_fixes/k8s.io/apimachinery/pkg/util/httpstream/doc.go
  vendor_fixes/k8s.io/apimachinery/pkg/util/httpstream/httpstream.go
  vendor_fixes/k8s.io/apimachinery/pkg/util/httpstream/httpstream_test.go
  vendor_fixes/k8s.io/apimachinery/pkg/util/httpstream/spdy/connection.go
  vendor_fixes/k8s.io/apimachinery/pkg/util/httpstream/spdy/connection_test.go
  vendor_fixes/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper.go
  vendor_fixes/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper_test.go
  vendor_fixes/k8s.io/apimachinery/pkg/util/httpstream/spdy/upgrade.go
  vendor_fixes/k8s.io/apimachinery/pkg/util/httpstream/spdy/upgrade_test.go
Labels: area/build-tools, kind/cleanup, lgtm, size/XXL

#1322 Fix for `go mod vendor` command
  vendor/github.com/google/btree/btree_mem.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/golang.org/x/tools/go/gcexportdata/main.go
  vendor/golang.org/x/tools/imports/mkindex.go
  vendor/golang.org/x/tools/imports/mkstdlib.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/fuzzer/valuefuzz_test.go
  vendor/k8s.io/apimachinery/pkg/api/validation/objectmeta_test.go
  vendor/k8s.io/apimachinery/pkg/api/validation/path/name.go
  vendor/k8s.io/apimachinery/pkg/api/validation/path/name_test.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation_test.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#1319 Support UE4 BuildSettingsVersion.V2
  sdks/unreal/Agones/Source/Agones/AgonesHook.cpp
  sdks/unreal/Agones/Source/Agones/Model/GameServer.h
  sdks/unreal/Agones/Source/Agones/Model/GameServerObjectMeta.h
  sdks/unreal/Agones/Source/Agones/Model/GameServerSpec.h
  sdks/unreal/Agones/Source/Agones/Model/GameServerStatus.h
  sdks/unreal/Agones/Source/Agones/Model/SpecHealth.h
  sdks/unreal/Agones/Source/Agones/Model/StatusPort.h
  sdks/unreal/Agones/Source/Agones/Public/Agones.h
Labels: approved, area/user-experience, kind/bug, size/S

#1305 Do not remove replica field if set to zero
  pkg/apis/agones/v1/fleet.go
Labels: approved, kind/cleanup, size/XS

#1283 CPP SDK example code: join threads
  examples/cpp-simple/server.cc
Labels: approved, area/examples, kind/cleanup, size/S

#1323 Remove the provider blocks from the gke submodules
  examples/terraform-submodules/gke-local/main.tf
  examples/terraform-submodules/gke/module.tf
  install/terraform/cluster.tf
  install/terraform/modules/gke/cluster.tf
Labels: approved, lgtm, size/M

#1279 Fix for Pod deletion during unavailable controller
  pkg/apis/agones/v1/gameserver_test.go
  pkg/gameservers/controller.go
  pkg/gameservers/gameservers.go
  pkg/gameservers/gameservers_test.go
  pkg/gameservers/missing.go
  pkg/gameservers/missing_test.go
  test/e2e/controller_test.go
Labels: approved, area/user-experience, kind/bug, lgtm, size/XL

#1314 Changing the allocator API to gRPC
  cmd/allocator/main.go
  cmd/allocator/main_test.go
  go.sum
  pkg/gameserverallocations/allocator.go
  pkg/gameserverallocations/controller_test.go
  test/e2e/allocator_test.go
  vendor_fixes/k8s.io/apimachinery/go.mod
Labels: approved, area/user-experience, kind/breaking, kind/feature, size/XL

#1336 Adding SuperTuxKart to the examples page
  site/content/en/docs/Examples/_index.md
Labels: approved, kind/documentation, kind/feature, lgtm, size/XS

#1332 Change the GameServerAllocationPolicy version to stable.
  build/build-image/gen-crd-client.sh
  cmd/allocator/main.go
  install/helm/agones/templates/crds/gameserverallocationpolicy.yaml
  install/yaml/install.yaml
  pkg/apis/agones/v1/fuzz_test/roundtrip_test.go
  pkg/apis/multicluster/v1/doc.go
  pkg/apis/multicluster/v1/gameserverallocationpolicy.go
  pkg/apis/multicluster/v1/gameserverallocationpolicy_test.go
  pkg/apis/multicluster/v1/register.go
  pkg/apis/multicluster/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/multicluster/v1/doc.go
  pkg/client/clientset/versioned/typed/multicluster/v1/fake/doc.go
  pkg/client/clientset/versioned/typed/multicluster/v1/fake/fake_gameserverallocationpolicy.go
  pkg/client/clientset/versioned/typed/multicluster/v1/fake/fake_multicluster_client.go
  pkg/client/clientset/versioned/typed/multicluster/v1/gameserverallocationpolicy.go
  pkg/client/clientset/versioned/typed/multicluster/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/multicluster/v1/multicluster_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/multicluster/interface.go
  pkg/client/informers/externalversions/multicluster/v1/gameserverallocationpolicy.go
  pkg/client/informers/externalversions/multicluster/v1/interface.go
  pkg/client/listers/multicluster/v1/expansion_generated.go
  pkg/client/listers/multicluster/v1/gameserverallocationpolicy.go
  pkg/gameserverallocations/allocator.go
  pkg/gameserverallocations/controller.go
  pkg/gameserverallocations/controller_test.go
  site/content/en/docs/Reference/agones_crd_api_reference.html
  test/e2e/allocator_test.go
  test/e2e/gameserverallocation_test.go
Labels: approved, lgtm, size/L

#1337 Use official github-changelog-generator in release
  build/includes/release.mk
Labels: approved, area/build-tools, kind/cleanup, lgtm, size/XS

#1338 Unity SDK - Initialize in Awake()
  sdks/unity/AgonesSdk.cs
Labels: approved, lgtm, size/XS

#1339 Add missing CABundle field for FleetAutoScaler CRD
  install/helm/agones/templates/crds/fleetautoscaler.yaml
  install/yaml/install.yaml
  site/content/en/docs/Getting Started/create-webhook-fleetautoscaler.md
Labels: approved, lgtm, size/S

#1312 Player Tracking Proto and Go stubs
  pkg/sdk/alpha/alpha.pb.go
  pkg/sdk/alpha/alpha.pb.gw.go
  pkg/sdkserver/alpha/localsdk.go
  pkg/sdkserver/alpha/sdkserver.go
  proto/sdk/alpha/alpha.proto
  sdks/cpp/include/agones/sdk.grpc.pb.h
  sdks/cpp/include/agones/sdk.pb.h
  sdks/cpp/include/google/api/annotations.pb.h
  sdks/cpp/include/google/api/http.pb.h
  sdks/cpp/src/agones/sdk.grpc.pb.cc
  sdks/cpp/src/agones/sdk.pb.cc
  sdks/cpp/src/google/annotations.pb.cc
  sdks/cpp/src/google/http.pb.cc
  sdks/nodejs/lib/google/api/annotations_pb.js
  sdks/nodejs/lib/google/api/http_pb.js
  sdks/nodejs/lib/sdk_pb.js
  sdks/rust/src/grpc/sdk.rs
  sdks/rust/src/grpc/sdk_grpc.rs
  sdks/swagger/alpha.swagger.json
Labels: approved, area/user-experience, kind/feature, lgtm, size/XXL

#1324 CRD implementation of alpha player tracking
  install/helm/agones/templates/crds/_gameserverspecvalidation.yaml
  install/yaml/install.yaml
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/agones/v1/gameserver_test.go
  pkg/apis/agones/v1/zz_generated.deepcopy.go
  pkg/util/runtime/features.go
  pkg/util/runtime/features_test.go
  site/content/en/docs/Reference/agones_crd_api_reference.html
Labels: approved, area/user-experience, kind/feature, lgtm, size/L

#1346 Add more details on Allocate() behaviour
  site/content/en/docs/Guides/Client SDKs/_index.md
Labels: lgtm, size/S

#1341 Update developer tooling to Kubernetes 1.14
  build/build-image/Dockerfile
  build/gke-test-cluster/cluster-e2e.yml
  build/gke-test-cluster/cluster-prow.yml
  build/gke-test-cluster/cluster.yml.jinja
  build/includes/kind.mk
  build/includes/minikube.mk
Labels: approved, size/S

#1342 Update terraform configs to use Kubernetes 1.14
  examples/terraform-submodules/aks/module.tf
  examples/terraform-submodules/gke-local/main.tf
  install/terraform/modules/aks/aks.tf
  install/terraform/modules/gke/cluster.tf
Labels: approved, size/XS

#1349 Update the kind make targets to work with kind 0.6.0 and later.
  build/includes/kind.mk
Labels: lgtm

#1352 Save UE4 Plugin settings to per-project config file
  sdks/unreal/Agones/Source/Agones/Public/AgonesSettings.h
Labels: approved, area/user-experience, kind/bug, size/XS

#1335 Stackdriver - fix getMonitoredResource
  pkg/metrics/exporter.go
  site/content/en/docs/Guides/metrics.md
Labels: approved, size/S

#1353 Fix Kubernetes terraform provider version
  examples/terraform-submodules/aks/module.tf
  install/terraform/helm.tf
  install/terraform/modules/aks/aks.tf
  install/terraform/modules/aks/variables.tf
  install/terraform/modules/helm/helm.tf
Labels: approved, size/M

#1348 Implement Alpha field best practices
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/agones/v1/gameserver_test.go
  pkg/apis/agones/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/util/runtime/features.go
  site/content/en/docs/Reference/agones_crd_api_reference.html
Labels: approved, kind/cleanup, lgtm, size/L

#1355 Update Feature Stage: New CRD attributes section
  site/content/en/docs/Guides/feature-stages.md
Labels: approved, area/meta, kind/cleanup, kind/documentation, size/M

#1358 Fix UE4 plugin compilation error in AgonesHook.h.
  sdks/unreal/Agones/Source/Agones/Private/Agones.cpp
  sdks/unreal/Agones/Source/Agones/Private/AgonesHook.cpp
  sdks/unreal/Agones/Source/Agones/Private/AgonesSettings.cpp
  sdks/unreal/Agones/Source/Agones/Public/AgonesHook.h
  sdks/unreal/Agones/Source/Agones/Public/Model/Duration.h
  sdks/unreal/Agones/Source/Agones/Public/Model/GameServer.h
  sdks/unreal/Agones/Source/Agones/Public/Model/GameServerObjectMeta.h
  sdks/unreal/Agones/Source/Agones/Public/Model/GameServerSpec.h
  sdks/unreal/Agones/Source/Agones/Public/Model/GameServerStatus.h
  sdks/unreal/Agones/Source/Agones/Public/Model/KeyValuePair.h
  sdks/unreal/Agones/Source/Agones/Public/Model/SpecHealth.h
  sdks/unreal/Agones/Source/Agones/Public/Model/StatusPort.h
Labels: approved, lgtm, size/XS

#1361 Fix test failure due to v1alpha becoming v1.
  site/content/en/docs/Advanced/multi-cluster-allocation.md
Labels: approved, lgtm, size/XS

#1344 Update images with latest everything #1261
  build/Makefile
  examples/allocator-service/Dockerfile
  examples/autoscaler-webhook/Dockerfile
  examples/autoscaler-webhook/autoscaler-service-tls.yaml
  examples/autoscaler-webhook/autoscaler-service.yaml
  examples/cpp-simple/Dockerfile
  examples/cpp-simple/fleet.yaml
  examples/cpp-simple/gameserver.yaml
  examples/crd-client/Dockerfile
  examples/crd-client/create-gs.yaml
  examples/crd-client/main.go
  examples/fleet.yaml
  examples/gameserver.yaml
  examples/rust-simple/Dockerfile
  examples/rust-simple/README.md
  examples/rust-simple/gameserver.yaml
  examples/simple-tcp/Dockerfile
  examples/simple-tcp/gameserver.yaml
  examples/simple-udp/Dockerfile
  examples/simple-udp/dev-gameserver.yaml
  examples/simple-udp/fleet-distributed.yaml
  examples/simple-udp/fleet.yaml
  examples/simple-udp/gameserver-passthrough.yaml
  examples/simple-udp/gameserver.yaml
  examples/simple-udp/gameserverset.yaml
  examples/xonotic/Dockerfile
  examples/xonotic/fleet.yaml
  examples/xonotic/gameserver.yaml
  pkg/util/webhooks/webhooks_test.go
  site/config.toml
  site/content/en/docs/Guides/local-game-server.md
  site/content/en/docs/Guides/troubleshooting.md
  site/content/en/docs/Reference/fleet.md
  site/content/en/docs/Reference/gameserver.md
  test/e2e/fleetautoscaler_test.go
  test/e2e/framework/framework.go
Labels: area/examples, kind/cleanup, size/M

#1356 Release NPM package, and Node update
  build/build-sdk-images/node/Dockerfile
  build/build-sdk-images/node/shell.sh
  build/includes/release.mk
  build/includes/sdk.mk
  docs/governance/templates/release_issue.md
  examples/nodejs-simple/Dockerfile
  examples/nodejs-simple/package.json
  examples/nodejs-simple/src/index.js
  sdks/nodejs/.npmrc
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  site/content/en/docs/Guides/Client SDKs/nodejs.md
  test/sdk/nodejs/package.json
  test/sdk/nodejs/testSDKClient.js
Labels: approved, area/operations, area/user-experience, kind/feature, size/L

#1364 Update documentation (examples and website) to use Kubernetes 1.14
  examples/fleet.yaml
  examples/fleetautoscaler.yaml
  examples/gameserver.yaml
  site/content/en/docs/Installation/Creating Cluster/aks.md
  site/content/en/docs/Installation/Creating Cluster/eks.md
  site/content/en/docs/Installation/Creating Cluster/gke.md
  site/content/en/docs/Installation/Creating Cluster/minikube.md
  site/content/en/docs/Installation/_index.md
  site/content/en/docs/Reference/fleet.md
  site/content/en/docs/Reference/fleetautoscaler.md
  site/content/en/docs/Reference/gameserver.md
Labels: approved, kind/documentation, kind/feature, size/L

#1367 Release 1.4.0 Release Candidate
  CHANGELOG.md
  docs/governance/templates/release.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/nodejs/package.json
  site/content/en/blog/releases/1.3.0.md
  site/content/en/blog/releases/1.4.0-rc.md
Labels: approved, kind/release, lgtm, size/L

#1369 Main page, gameserver lifecycle page - typos
  site/content/en/_index.html
  site/content/en/docs/Guides/gameserver-lifecycle.md
Labels: approved, lgtm, size/XS

#1374 Fix for 404 in OpenSSL Install link
  site/content/en/docs/Guides/Client SDKs/cpp.md
Labels: approved, kind/cleanup, kind/documentation, lgtm, size/XS

#1378 Add crd-client image to release template
  docs/governance/templates/release.md
Labels: approved, lgtm, size/XS
