Repository googleforgames/agones, pull requests merged in 2020-05, with the labels that each got.

#1506 Be able to run individual e2e tests in Intellij
  go.mod
  go.sum
  test/e2e/framework/framework.go
  vendor/github.com/spf13/pflag/README.md
  vendor/github.com/spf13/pflag/bool_slice.go
  vendor/github.com/spf13/pflag/count.go
  vendor/github.com/spf13/pflag/duration_slice.go
  vendor/github.com/spf13/pflag/flag.go
  vendor/github.com/spf13/pflag/float32_slice.go
  vendor/github.com/spf13/pflag/float64_slice.go
  vendor/github.com/spf13/pflag/go.mod
  vendor/github.com/spf13/pflag/go.sum
  vendor/github.com/spf13/pflag/int32_slice.go
  vendor/github.com/spf13/pflag/int64_slice.go
  vendor/github.com/spf13/pflag/int_slice.go
  vendor/github.com/spf13/pflag/ip_slice.go
  vendor/github.com/spf13/pflag/string_array.go
  vendor/github.com/spf13/pflag/string_slice.go
  vendor/github.com/spf13/pflag/string_to_int64.go
  vendor/github.com/spf13/pflag/uint_slice.go
  vendor/modules.txt
Labels: approved, area/tests, kind/bug, lgtm, size/XXL

#1509 Local SDK wasn't loading referenced file
  cmd/sdk-server/main.go
Labels: approved, area/user-experience, kind/bug, lgtm, size/XS

#1510 Unity SDK: Fix SpecHealth parsing
  sdks/unity/model/SpecHealth.cs
Labels: approved, size/S

#1512 factored metrics logic out of the allocator main file
  cmd/allocator/main.go
  cmd/allocator/metrics.go
Labels: approved, lgtm, size/L

#1513 Change rpc method from PostAllocate to Allocate
  cmd/allocator/main.go
  cmd/allocator/main_test.go
  examples/allocator-client/main.go
  pkg/allocation/go/v1alpha1/allocation.gw.pb.go
  pkg/allocation/go/v1alpha1/allocation.pb.go
  pkg/allocation/go/v1alpha1/allocation.swagger.json
  pkg/gameserverallocations/allocator.go
  proto/allocation/v1alpha1/allocation.proto
  test/e2e/allocator_test.go
Labels: approved, lgtm, size/L

#1507 SDKServer Player Tracking implementation
  pkg/sdkserver/sdkserver.go
  pkg/sdkserver/sdkserver_test.go
Labels: approved, area/user-experience, kind/feature, size/L

#1515 Improved fleetautoscalers - controller unit tests
  pkg/fleetautoscalers/controller_test.go
Labels: approved, area/tests, lgtm, size/L

#1518 Cleanup Feature Gate Errors
  pkg/sdkserver/localsdk.go
  pkg/sdkserver/sdkserver.go
Labels: approved, kind/cleanup, lgtm, size/S

#1516 Change allocator gRPC response state to gRPC error status
  cmd/allocator/main.go
  cmd/allocator/main_test.go
  pkg/allocation/converters/converter.go
  pkg/allocation/converters/converter_test.go
  pkg/allocation/go/v1alpha1/allocation.pb.go
  pkg/allocation/go/v1alpha1/allocation.swagger.json
  pkg/gameserverallocations/allocator.go
  pkg/gameserverallocations/controller_test.go
  proto/allocation/v1alpha1/allocation.proto
  test/e2e/allocator_test.go
Labels: approved, size/L

#1514 Fix allocator service tls auth for C# client and add a C# sample
  cmd/allocator/main.go
  cmd/allocator/main_test.go
  examples/allocator-client-csharp/Program.cs
  examples/allocator-client-csharp/README.md
  examples/allocator-client-csharp/allocator-client-csharp.csproj
  examples/allocator-client/main.go
  site/content/en/docs/Advanced/allocator-service.md
Labels: approved, area/user-experience, kind/bug, lgtm, size/L

#1519 PlayerConnect/Disconnect & related Go SDK functions
  sdks/go/alpha.go
  sdks/go/alpha_test.go
Labels: approved, area/user-experience, kind/feature, size/M

#1521 Add tolerations for delete hook script
  install/helm/agones/templates/hooks/pre_delete_hook.yaml
Labels: approved, area/operations, kind/cleanup, lgtm, size/XS

#1525 Fix typo in workerqueue
  pkg/util/workerqueue/workerqueue.go
Labels: approved, kind/cleanup, size/XS

#1530 Fix broken Fuzz Roundtrip tests in 1.15
  pkg/apis/agones/v1/fuzz_test/roundtrip_test.go
Labels: approved, lgtm, size/S

#1528 Fixed a small typo spotted while reading documentation.
  site/content/en/docs/Advanced/limiting-resources.md
Labels: approved, area/site, size/XS

#1526 Small typo in test
  pkg/apis/agones/v1/gameserver_test.go
Labels: approved, size/XS

#1533 Flaky: TestControllerSyncGameServerCreatingState
  pkg/gameservers/controller_test.go
Labels: approved, area/tests, kind/cleanup, size/XS

#1527 Player Tracking Go SDK Conformance Tests
  build/includes/sdk.mk
  test/sdk/go/sdk-client-test.go
Labels: approved, area/tests, kind/feature, lgtm, size/M

#1520 Helm: add ping HTTP and UDP annotations into chart
  install/helm/agones/templates/ping.yaml
  install/helm/agones/templates/service/allocation.yaml
  install/helm/agones/values.yaml
Labels: area/operations, kind/feature, lgtm, size/S

#1522 Update EKS Kubernetes version to 1.15
  install/terraform/modules/eks/eks.tf
  site/content/en/docs/Installation/Creating Cluster/eks.md
Labels: area/operations, kind/feature, lgtm, size/XS

#1537 REST SDK Conformance Tests
  build/build-sdk-images/restapi/build-sdk-test.sh
  build/build-sdk-images/restapi/clean.sh
  build/includes/sdk.mk
  cmd/sdk-server/main.go
  test/sdk/restapi/http-api-test.go.nolint
Labels: approved, area/user-experience, kind/feature, lgtm, size/M

#1529 Switch Node.js SDK grpc dependency to grpc-js
  build/build-sdk-images/node/Dockerfile
  build/build-sdk-images/node/gen.sh
  examples/nodejs-simple/package-lock.json
  examples/nodejs-simple/package.json
  sdks/nodejs/lib/google/api/http_pb.js
  sdks/nodejs/lib/sdk_grpc_pb.js
  sdks/nodejs/lib/sdk_pb.js
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/nodejs/spec/agonesSDK.spec.js
  sdks/nodejs/src/agonesSDK.js
Labels: approved, area/user-experience, kind/breaking, lgtm, size/XXL

#1542 Fix: SDK conformance test. Update Rust version to fix cargo build
  build/build-sdk-images/rust/Dockerfile
Labels: approved, size/XS

#1541 E2E Tests for GameServer Player Tracking
  build/Makefile
  examples/simple-udp/Makefile
  examples/simple-udp/main.go
  test/e2e/framework/framework.go
  test/e2e/gameserver_test.go
Labels: approved, area/examples, area/tests, kind/feature, lgtm, size/L

#1548 Fix small typo in comments
  build/Makefile
  pkg/apis/agones/v1/gameserverset.go
  pkg/gameserverallocations/allocator.go
  pkg/gameservers/controller.go
  pkg/gameservers/health.go
  site/content/en/docs/FAQ/_index.md
  site/content/en/docs/Guides/Client SDKs/rest.md
Labels: approved, size/S

#1549 Faq links point to wrong place
  site/content/en/docs/FAQ/_index.md
Labels: approved, kind/bug, kind/documentation, lgtm, size/S

#1550 Upgrade kubectl for e2e tests
  build/e2e-image/Dockerfile
Labels: approved, area/tests, kind/feature, size/XS

#1482 Terraform: update GKE cluster version, use locals and `lookup` to set default values
  build/includes/terraform.mk
  build/terraform/gke/module.tf
  examples/terraform-submodules/gke/module.tf
  install/terraform/modules/gke/cluster.tf
  install/terraform/modules/gke/variables.tf
  site/content/en/docs/Installation/Terraform/gke.md
Labels: approved, area/operations, kind/feature, size/M

#1556 Terraform: update AKS version
  install/terraform/modules/aks/aks.tf
Labels: approved, area/operations, lgtm, size/XS

#1554 Update documentation links in examples and website pages
  examples/fleet.yaml
  examples/fleetautoscaler.yaml
  examples/gameserver.yaml
  site/content/en/docs/Reference/fleet.md
  site/content/en/docs/Reference/fleetautoscaler.md
  site/content/en/docs/Reference/gameserver.md
Labels: approved, area/examples, kind/documentation, size/S

#1551 CRD values for Aggregate Player Tracking
  pkg/apis/agones/v1/common.go
  pkg/apis/agones/v1/fleet.go
  pkg/apis/agones/v1/gameserverset.go
  pkg/apis/agones/v1/zz_generated.deepcopy.go
  pkg/apis/autoscaling/v1/zz_generated.deepcopy.go
  site/content/en/docs/Reference/agones_crd_api_reference.html
Labels: approved, area/user-experience, kind/feature, lgtm, size/L

#1552 Player Tracking: Json "IDs" => "ids"
  pkg/apis/agones/v1/gameserver.go
  site/content/en/docs/Reference/agones_crd_api_reference.html
Labels: approved, kind/cleanup, size/XS

#1555 Website: update documents to use Kubernetes 1.15
  site/content/en/docs/Installation/Creating Cluster/aks.md
  site/content/en/docs/Installation/Creating Cluster/gke.md
  site/content/en/docs/Installation/Creating Cluster/minikube.md
  site/content/en/docs/Installation/_index.md
Labels: approved, kind/documentation, size/S

#1559 Player Tracking Proto: IDs => ids
  pkg/sdk/sdk.pb.go
  pkg/sdkserver/localsdk.go
  pkg/sdkserver/localsdk_test.go
  pkg/sdkserver/sdk.go
  pkg/sdkserver/sdk_test.go
  proto/sdk/sdk.proto
  sdks/cpp/include/agones/sdk.pb.h
  sdks/cpp/src/agones/sdk.pb.cc
  sdks/csharp/sdk/generated/Sdk.cs
  sdks/nodejs/lib/sdk_pb.js
  sdks/rust/src/grpc/sdk.rs
  sdks/swagger/sdk.swagger.json
Labels: approved, kind/cleanup, size/L

#1545 Use ServerCA from GameServerAllocationPolicy instead of client secret ca.crt
  install/helm/agones/templates/crds/gameserverallocationpolicy.yaml
  install/yaml/install.yaml
  pkg/apis/multicluster/v1/gameserverallocationpolicy.go
  pkg/apis/multicluster/v1/gameserverallocationpolicy_test.go
  pkg/apis/multicluster/v1/zz_generated.deepcopy.go
  pkg/gameserverallocations/allocator.go
  pkg/gameserverallocations/controller_test.go
  site/content/en/docs/Advanced/multi-cluster-allocation.md
  site/content/en/docs/Reference/agones_crd_api_reference.html
  test/e2e/allocator_test.go
Labels: approved, size/L

#1544 fixed Agones.Build.cs for #1303
  sdks/unreal/Agones/Source/Agones/Agones.Build.cs
Labels: approved, area/user-experience, kind/bug, size/XS

#1558 Add Third Party > Libraries and Tools section
  site/content/en/docs/Third Party Content/libraries-tools.md
Labels: approved, kind/documentation, kind/feature, size/S

#1540 Change the multi-cluster allocation API version to stable
  build/build-allocation-images/go/gen.sh
  cmd/allocator/main.go
  cmd/allocator/main_test.go
  examples/allocator-client-csharp/Program.cs
  examples/allocator-client-csharp/allocator-client-csharp.csproj
  examples/allocator-client/main.go
  pkg/allocation/converters/converter.go
  pkg/allocation/converters/converter_test.go
  pkg/allocation/go/allocation.gw.pb.go
  pkg/allocation/go/allocation.pb.go
  pkg/allocation/go/allocation.swagger.json
  pkg/gameserverallocations/allocator.go
  pkg/gameserverallocations/controller_test.go
  proto/allocation/allocation.proto
  site/content/en/docs/Advanced/allocator-service.md
  site/content/en/docs/Advanced/multi-cluster-allocation.md
  test/e2e/allocator_test.go
Labels: approved, size/L

#1560 Player Tracking Proto: Players => players
  pkg/sdk/sdk.pb.go
  proto/sdk/sdk.proto
  sdks/cpp/include/agones/sdk.pb.h
  sdks/cpp/src/agones/sdk.pb.cc
  sdks/csharp/sdk/generated/Sdk.cs
  sdks/nodejs/lib/sdk_pb.js
  sdks/rust/src/grpc/sdk.rs
  sdks/swagger/sdk.swagger.json
Labels: approved, kind/cleanup, size/L

#1565 Flaky: TestGameServerReserve
  build/Makefile
  examples/simple-udp/Makefile
  examples/simple-udp/main.go
  test/e2e/fleetautoscaler_test.go
  test/e2e/framework/framework.go
  test/e2e/gameserver_test.go
Labels: approved, area/tests, kind/bug, lgtm, size/L

#1567 Fixed a typo sercerCA -> serverCa
  site/content/en/docs/Advanced/multi-cluster-allocation.md
Labels: approved, size/XS

#1564 Player Tracking SDK Reference
  site/content/en/docs/Guides/Client SDKs/_index.md
  site/layouts/shortcodes/alpha.html
Labels: approved, kind/documentation, kind/feature, size/L

#1568 Site: Fix publish issue with date update
  site/content/en/docs/Advanced/allocator-service.md
Labels: approved, area/site, kind/bug, lgtm, size/XS

#1561 Fleet Aggregate Player Tracking Logic
  pkg/fleets/controller.go
  pkg/fleets/controller_test.go
  pkg/gameserversets/controller.go
  pkg/gameserversets/controller_test.go
  test/e2e/fleet_test.go
Labels: approved, area/tests, kind/feature, size/L

#1569 Player Tracking guide, and GameServer reference.
  examples/gameserver.yaml
  pkg/apis/agones/v1/gameserver.go
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Guides/player-tracking.md
  site/content/en/docs/Reference/agones_crd_api_reference.html
  site/content/en/docs/Reference/gameserver.md
Labels: approved, kind/documentation, kind/feature, lgtm, size/L

#1570 Player Tracking: REST SDK Reference
  site/content/en/docs/Guides/Client SDKs/rest.md
Labels: approved, kind/documentation, kind/feature, lgtm, size/L

#1572 Fix Local SDK nil Players with test
  build/includes/sdk.mk
  pkg/sdkserver/localsdk.go
  pkg/sdkserver/localsdk_test.go
Labels: approved, area/tests, lgtm, size/L

#1574 Release 1.6.0-rc
  CHANGELOG.md
  build/includes/website.mk
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/nodejs/package.json
  site/content/en/blog/releases/1.6.0-rc.md
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Reference/gameserver.md
Labels: approved, kind/release, lgtm, size/L

#1580 Warning to release checklist.
  docs/governance/templates/release_issue.md
Labels: approved, kind/cleanup, lgtm, size/XS

#1581 Fix the Unreal Plugin's GetGameServer
  sdks/unreal/Agones/Source/Agones/Private/AgonesHook.cpp
  sdks/unreal/Agones/Source/Agones/Public/AgonesHook.h
Labels: approved, lgtm, size/M

#1586 Fix flaky Local SDK test
  pkg/sdkserver/localsdk_test.go
Labels: approved, area/tests, lgtm, size/S

#1566 Allow env var overrides for e2e tests
  test/e2e/framework/framework.go
Labels: approved, area/tests, kind/bug, lgtm, size/S

#1589 Preparation for 1.7.0
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/nodejs/package.json
Labels: approved, kind/release, size/M

#1595 Update edit-first-gameserver-go.md
  site/content/en/docs/Getting Started/edit-first-gameserver-go.md
Labels: approved, lgtm, size/XS

#1593 Adding AccelByte in Companies using Agones list
  site/content/en/_index.html
  site/static/images/accelbyte.png
Labels: approved, size/XS

#1585 Metrics: add namespace to distinguish fleets with the same name
  pkg/metrics/controller.go
  pkg/metrics/controller_metrics.go
  pkg/metrics/controller_test.go
  pkg/metrics/gameservers_count.go
  pkg/metrics/util.go
Labels: area/operations, kind/feature, size/L
