Repository googleforgames/agones, pull requests merged in 2021-06, with the labels that each got.

#2111 Update our community membership guidelines to add a Releaser role.
  docs/governance/community_membership.md
Labels: approved, cla: yes, lgtm, size/M

#2118 Update link to contributing guide from the membership template.
  docs/governance/templates/membership.md
Labels: approved, cla: yes, lgtm, size/XS

#2080 Minor updates to the release checklist.
  docs/governance/templates/release_issue.md
Labels: approved, cla: yes, kind/cleanup, size/XS

#2121 Release 1.15.0-rc
  CHANGELOG.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package.json
  site/content/en/blog/releases/1.14.0.md
  site/content/en/blog/releases/1.15.0-rc.md
Labels: approved, cla: yes, kind/release, lgtm, size/L

#2130 Prep for the 1.16.0 release
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package.json
Labels: approved, cla: yes, lgtm, size/M

#2122 Adds the Missing TCP protocol spec to the example fleet
  examples/simple-game-server/fleet-tcp.yaml
Labels: approved, area/examples, cla: yes, kind/cleanup, lgtm, size/XS

#2120 Change the way we generate new version numbers for nodejs
  docs/governance/templates/release_issue.md
Labels: approved, area/meta, cla: yes, lgtm, size/XS

#2137 Updated Minikube documentation
  site/content/en/docs/Getting Started/create-gameserver.md
  site/content/en/docs/Installation/Creating Cluster/minikube.md
Labels: approved, cla: yes, lgtm, size/M

#2135 Fix a typo in the documentation.
  site/content/en/docs/Advanced/limiting-resources.md
Labels: approved, cla: yes, kind/cleanup, kind/documentation, size/XS

#2134 Update helm configuration to allow annotations to be added to service accounts
  install/helm/agones/templates/controller.yaml
  install/helm/agones/templates/service/allocation.yaml
  install/helm/agones/templates/serviceaccounts/controller.yaml
  install/helm/agones/templates/serviceaccounts/sdk.yaml
  install/helm/agones/values.yaml
  site/content/en/docs/Guides/metrics.md
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: approved, area/operations, cla: yes, kind/breaking, kind/feature, lgtm, size/M

#2144 Removal of getRandomlySelectedGS
  pkg/gameserverallocations/allocator.go
  pkg/gameserverallocations/controller_test.go
Labels: approved, cla: yes, kind/cleanup, lgtm, size/M

#2143 Feature gates for advanced Allocation filtering
  pkg/util/runtime/features.go
Labels: approved, cla: yes, kind/feature, size/S

#2138 Upgrade terraform to Kubernetes 1.19.
  build/terraform/prow/module.tf
  install/terraform/modules/aks/aks.tf
  install/terraform/modules/eks/eks.tf
  install/terraform/modules/gke/cluster.tf
  install/terraform/modules/gke/variables.tf
Labels: approved, cla: yes, lgtm, size/S

#2147 Upgrade kubectl to 1.19 in dev tooling.
  build/build-image/Dockerfile
  build/e2e-image/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2124 Fix Network Security Group Gameserver rule not applied on AKS cluster
  examples/terraform-submodules/aks/module.tf
  install/terraform/modules/aks/aks.tf
  install/terraform/modules/aks/variables.tf
  site/content/en/docs/Installation/Creating Cluster/aks.md
Labels: approved, area/operations, cla: yes, kind/cleanup, lgtm, size/L

#2149 add copy to clipboard function to code on website
  site/config.toml
  site/content/en/docs/Advanced/allocator-service.md
  site/content/en/docs/Advanced/multi-cluster-allocation.md
  site/content/en/docs/Getting Started/create-fleet.md
  site/content/en/docs/Getting Started/create-fleetautoscaler.md
  site/content/en/docs/Getting Started/create-gameserver.md
  site/content/en/docs/Getting Started/create-webhook-fleetautoscaler.md
  site/content/en/docs/Getting Started/edit-first-gameserver-go.md
  site/content/en/docs/Guides/Client SDKs/cpp.md
  site/content/en/docs/Guides/Client SDKs/local.md
  site/content/en/docs/Guides/Client SDKs/nodejs.md
  site/content/en/docs/Guides/Client SDKs/rest.md
  site/content/en/docs/Guides/Client SDKs/unreal.md
  site/content/en/docs/Guides/access-api.md
  site/content/en/docs/Guides/metrics.md
  site/content/en/docs/Guides/troubleshooting.md
  site/content/en/docs/Guides/windows-gameservers.md
  site/content/en/docs/Installation/Creating Cluster/aks.md
  site/content/en/docs/Installation/Creating Cluster/eks.md
  site/content/en/docs/Installation/Install Agones/helm.md
  site/content/en/docs/Installation/Install Agones/yaml.md
  site/content/en/docs/Installation/Terraform/aks.md
  site/content/en/docs/Installation/Terraform/eks.md
  site/content/en/docs/Installation/Terraform/gke.md
  site/content/en/docs/Installation/confirm.md
  site/content/en/docs/Reference/fleet.md
  site/content/en/docs/Tutorials/simple-gameserver-cpp.md
  site/content/en/docs/Tutorials/simple-gameserver-nodejs.md
  site/content/en/docs/Tutorials/simple-gameserver-rust.md
  site/layouts/partials/head.html
Labels: approved, cla: yes, lgtm, size/XL

#2150 Update the consul helm chart to use HashiCorp's Official Helm Chart.
  build/e2e-image/entrypoint.sh
  build/terraform/e2e/module.tf
Labels: approved, area/tests, cla: yes, kind/cleanup, size/XS

#2152 Update Minikube and Kind dev tooling to Kubernetes 1.19
  build/includes/kind.mk
  build/includes/minikube.mk
Labels: approved, area/operations, cla: yes, kind/cleanup, size/XS

#2151 Update the dev version of Kubernetes in the website to 1.19.
  site/config.toml
Labels: approved, cla: yes, size/XS

#2141 Fix shutdown problems in ping application.
  cmd/ping/main.go
  cmd/ping/udp.go
Labels: approved, cla: yes, size/M

#2161 terraform-init on gcloud-terraform-destroy-cluster
  build/includes/terraform.mk
Labels: approved, area/build-tools, cla: yes, kind/cleanup, lgtm, size/XS

#2158 Update CRD API reference and regenerate CRD Kubernetes client libraries for Kubernetes 1.19.
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/listers/agones/v1/fleet.go
  pkg/client/listers/agones/v1/gameserver.go
  pkg/client/listers/agones/v1/gameserverset.go
  pkg/client/listers/autoscaling/v1/fleetautoscaler.go
  pkg/client/listers/multicluster/v1/gameserverallocationpolicy.go
  site/assets/templates/crd-doc-config.json
  site/content/en/docs/Reference/agones_crd_api_reference.html
Labels: approved, cla: yes, lgtm, size/XXL

#2160 Fix for failing export-openapi.sh on K8s 1.19
  build/README.md
  build/export-openapi.sh
  install/helm/agones/templates/crds/k8s/_io.k8s.api.core.v1.PodTemplateSpec.yaml
  install/helm/agones/templates/crds/k8s/_io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta.yaml
  install/yaml/install.yaml
Labels: approved, area/build-tools, cla: yes, kind/bug, size/XXL

#2157 Remove links to the pre-1.0 versions of the website from the navbar.
  site/layouts/partials/navbar.html
Labels: approved, cla: yes, size/XS

#2148 Refactor ReadyGameServerCache to AllocationCache
  cmd/allocator/main.go
  pkg/gameserverallocations/allocation_cache.go
  pkg/gameserverallocations/allocation_cache_test.go
  pkg/gameserverallocations/allocator.go
  pkg/gameserverallocations/allocator_test.go
  pkg/gameserverallocations/controller.go
  pkg/gameserverallocations/controller_test.go
  pkg/gameserverallocations/find.go
  pkg/gameserverallocations/find_test.go
Labels: approved, cla: yes, kind/feature, size/XL
