Repository googleforgames/agones, pull requests merged in 2021-09, with the labels that each got.

#2247 Release/1.17.0
  CHANGELOG.md
Labels: kind/release, lgtm, size/S, approved, cla: yes

#2250 Preparation for 1.18.0
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
Labels: kind/release, size/M, lgtm, cla: yes

#2254 [docs] fix create gameserver args
  site/content/en/docs/Guides/access-api.md
Labels: lgtm, size/XS, cla: yes

#2251 Docs: Integration Pattern - Reusing GameServers
  build/includes/website.mk
  site/content/en/docs/FAQ/_index.md
  site/content/en/docs/Integration Patterns/reusing-gameservers.md
  site/static/diagrams/reusing-gameservers.puml
  site/static/diagrams/reusing-gameservers.puml.png
Labels: kind/feature, kind/documentation, lgtm, size/L, approved, cla: yes

#2257 Explain how namespaces work with allocations
  site/content/en/docs/Reference/gameserverallocation.md
Labels: lgtm, size/XS, approved, cla: yes

#2259 Remove GOPATH from development guide
  build/README.md
Labels: kind/cleanup, area/build-tools, lgtm, size/S, approved, cla: yes

#2258 Create examples.md
  site/content/en/docs/Third Party Content/examples.md
Labels: lgtm, size/S, cla: yes

#2260 Fix typo
  site/content/en/docs/Third Party Content/examples.md
Labels: lgtm, size/XS, approved, cla: yes

#2269 Unblock CI: Ignore rolltable link for testing
  site/content/en/_index.html
Labels: kind/bug, area/site, lgtm, size/XS, approved, cla: yes

#2268 Separate the Helm value for the allocator service name from its service account name
  install/helm/agones/templates/service/allocation.yaml
  install/helm/agones/values.yaml
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: lgtm, size/XS, approved, cla: yes

#2265 Update the helm template command to match what is used in `make gen-install`.
  site/content/en/docs/Installation/Install Agones/yaml.md
Labels: kind/documentation, size/XS, approved, cla: yes

#2275 Fix a link on the FAQ that was pointed at localhost
  site/content/en/docs/FAQ/_index.md
Labels: lgtm, size/XS, approved, cla: yes

#2272 Allow the ports for gRPC and REST to be configured for the allocator service
  build/Makefile
  cmd/allocator/main.go
  cmd/allocator/metrics.go
  install/helm/agones/templates/service/allocation.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  site/content/en/docs/Advanced/allocator-service.md
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: kind/feature, kind/breaking, area/operations, lgtm, size/L, approved, cla: yes

#2270 Docs: High Density Integration Pattern
  build/includes/website.mk
  site/content/en/docs/Integration Patterns/high-density-gameservers.md
  site/static/diagrams/high-density.puml
  site/static/diagrams/high-density.puml.png
  site/static/diagrams/reusing-gameservers.puml.png
Labels: kind/feature, kind/documentation, lgtm, size/L, approved, cla: yes

#2281 Minor cleanup on reserved diagram
  site/static/diagrams/gameserver-reserved.puml
  site/static/diagrams/gameserver-reserved.puml.png
Labels: kind/documentation, kind/cleanup, lgtm, size/XS, approved, cla: yes

#2277 Skip the secrets and volume mounts in the allocator pod when they aren't needed
  install/helm/agones/templates/service/allocation.yaml
Labels: kind/feature, lgtm, size/XS, approved, cla: yes

#2205 Support graceful termination
  cmd/sdk-server/main.go
  pkg/sdkserver/sdkserver.go
  pkg/sdkserver/sdkserver_test.go
  pkg/util/runtime/features.go
  site/content/en/docs/Guides/Client SDKs/_index.md
  site/content/en/docs/Guides/feature-stages.md
Labels: size/L, approved, cla: yes

#2284 Ignore SDK CPP build directory
  .gitignore
Labels: kind/cleanup, area/build-tools, size/XS, approved, cla: yes

#2283 Test for extended allocation metadata characters
  test/e2e/allocator_test.go
Labels: kind/cleanup, area/tests, size/S, approved, cla: yes
