Repository googleforgames/agones, pull requests merged in 2021-12, with the labels that each got.

#2386 Fix webhook image, and e2e.AssertFleetCondition
  test/e2e/fleetautoscaler_test.go
  test/e2e/framework/framework.go
Labels: kind/bug, area/tests, size/M, approved, cla: yes

#2392 Update allocator-service.md
  site/content/en/docs/Advanced/allocator-service.md
Labels: lgtm, size/S, approved

#2393 pretty print pre-formatted code to "bash"
  site/content/en/docs/Advanced/allocator-service.md
Labels: kind/cleanup, lgtm, size/XS, approved

#2405 Fix broken links in the website.
  site/content/en/docs/FAQ/_index.md
  site/content/en/docs/Installation/Terraform/aks.md
Labels: kind/cleanup, lgtm, size/XS, approved

#2399 Update the minikube driver flag name (--vm-driver is deprecated)
  site/content/en/docs/Installation/Creating Cluster/minikube.md
Labels: kind/cleanup, size/M, approved

#2407 Add a flag to simple-game-server to shutdown after a specified number of seconds
  examples/simple-game-server/main.go
Labels: kind/feature, lgtm, size/S, approved

#2409 Update the simple game server to move itself back to the Ready state after allocation
  examples/simple-game-server/Makefile
  examples/simple-game-server/README.md
  examples/simple-game-server/main.go
Labels: kind/feature, size/M, approved

#2414 Upgrade-gRPC-version-2
  pkg/allocation/go/allocation.pb.go
  pkg/sdk/alpha/alpha.pb.go
  pkg/sdk/sdk.pb.go
Labels: size/M, lgtm, approved

#2413 Update the simple game server version to 0.6.
  build/Makefile
  examples/crd-client/create-gs.yaml
  examples/fleet.yaml
  examples/gameserver.yaml
  examples/simple-game-server/dev-gameserver.yaml
  examples/simple-game-server/fleet-distributed.yaml
  examples/simple-game-server/fleet-tcp.yaml
  examples/simple-game-server/fleet.yaml
  examples/simple-game-server/gameserver-passthrough.yaml
  examples/simple-game-server/gameserver-windows.yaml
  examples/simple-game-server/gameserver.yaml
  install/helm/agones/templates/tests/test-runner.yaml
  pkg/util/webhooks/webhooks_test.go
  site/config.toml
  test/e2e/framework/framework.go
  test/e2e/gameserver_test.go
  test/load/allocation/README.md
  test/load/allocation/fleet.yaml
  test/load/allocation/grpc/README.md
  test/load/allocation/grpc/fleet.yaml
Labels: kind/cleanup, size/M, lgtm, approved

#2415 Fixed missing "const" parameter for SetAnnotation & SetLabels.
  sdks/unreal/Agones/Source/Agones/Private/AgonesComponent.cpp
  sdks/unreal/Agones/Source/Agones/Public/AgonesComponent.h
Labels: lgtm, size/XS
