Repository googleforgames/agones, pull requests merged in 2021-05, with the labels that each got.

#2085 Upgrade to Hugo 0.82.1
  build/build-image/Dockerfile
Labels: approved, area/site, cla: yes, kind/cleanup, lgtm, size/XS

#2089 Clone Kubernetes objects in API Server before encoding them
  pkg/util/apiserver/apiserver.go
  pkg/util/apiserver/apiserver_test.go
Labels: approved, cla: yes, lgtm, size/M

#2092 Add Afterverse logo
  site/content/en/_index.html
  site/static/images/afterverse.svg
Labels: approved, cla: yes, lgtm, size/XS

#2094 Link Client SDK page to Third Party SDKs
  site/content/en/docs/Guides/Client SDKs/_index.md
Labels: approved, cla: yes, kind/documentation, lgtm, size/XS

#2095 e2e test: Update Fleet replicas 0 with Spec change
  test/e2e/fleet_test.go
Labels: approved, area/tests, cla: yes, lgtm, size/M

#2070 Rename MetaPatch to Metadata for AllocationRequest
  pkg/allocation/converters/converter.go
  pkg/allocation/converters/converter_test.go
  pkg/allocation/go/allocation.pb.go
  pkg/allocation/go/allocation.swagger.json
  proto/allocation/allocation.proto
  site/content/en/docs/Advanced/allocator-service.md
  test/e2e/allocator_test.go
Labels: approved, cla: yes, lgtm, size/L

#2099 Update and audit fix Node.js dependencies
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
Labels: approved, cla: yes, lgtm, size/L

#2091 [docs] hugo fails to server link without /
  examples/allocator-client-csharp/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2103 aks setup improvements
  install/terraform/modules/aks/aks.tf
  install/terraform/modules/aks/variables.tf
  site/content/en/docs/Installation/Creating Cluster/aks.md
Labels: area/operations, cla: yes, kind/cleanup, lgtm, size/M

#2107 Respectful code cleanup No.1
  CONTRIBUTING.md
  build/README.md
  build/prometheus.yaml
  examples/xonotic/server.cfg
  site/content/en/docs/FAQ/_index.md
  site/content/en/docs/Guides/metrics.md
  site/content/en/docs/Installation/upgrading.md
  site/handler.go
  site/handler_test.go
  site/themes/docsy/config.toml
Labels: approved, cla: yes, kind/cleanup, lgtm, size/M

#2109 Respectful code cleanup No.2
  .github/pull_request_template.md
  build/README.md
  cmd/sdk-server/main.go
  examples/unity-simple/README.md
  site/content/en/_index.html
  site/content/en/docs/Guides/Client SDKs/local.md
Labels: approved, cla: yes, kind/cleanup, lgtm, size/S

#2110 Return HTTP 201 on GameServerAllocation
  pkg/gameserverallocations/controller.go
  pkg/gameserverallocations/controller_test.go
  test/e2e/gameserverallocation_test.go
Labels: approved, area/user-experience, cla: yes, kind/bug, lgtm, size/S
