Repository googleforgames/agones, pull requests merged in 2021-01, with the labels that each got.

#1947 Fix Twitter linkcheck failure.
  build/build-image/Dockerfile
  site/htmltest.yaml
Labels: approved, area/tests, cla: yes, kind/bug, lgtm, size/XS

#1946 Add nodeSelector property to Agones helm chart for Allocator
  install/helm/agones/templates/service/allocation.yaml
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: approved, area/operations, cla: yes, kind/feature, lgtm, size/XS

#1935 Update documentation to note there is no GameServer update support
  site/content/en/docs/Reference/gameserver.md
Labels: approved, cla: yes, kind/cleanup, kind/documentation, size/XS

#1952 nullable lastScaleTime on FleetAutoScaler CRD
  install/helm/agones/templates/crds/fleetautoscaler.yaml
  install/yaml/install.yaml
Labels: approved, area/operations, cla: yes, kind/bug, lgtm, size/XS

#1953 Add a "why" section for the Allocator Service documentation
  site/content/en/docs/Advanced/allocator-service.md
Labels: approved, cla: yes, kind/documentation, kind/feature, size/S

#1949 ObjectMeta should use additionalProperties
  install/helm/agones/templates/crds/_gameserverspecschema.yaml
  install/yaml/install.yaml
Labels: approved, area/user-experience, cla: yes, kind/cleanup, size/S

#1948 Add Windows note for netcat in getting started
  site/content/en/docs/Getting Started/create-gameserver.md
Labels: approved, cla: yes, kind/cleanup, kind/documentation, lgtm, size/XS

#1961 Move ContainerPortAllocation to Stable
  cloudbuild.yaml
  examples/gameserver.yaml
  install/helm/agones/templates/crds/_gameserverspecschema.yaml
  install/yaml/install.yaml
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/agones/v1/gameserver_test.go
  pkg/util/runtime/features.go
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Reference/agones_crd_api_reference.html
  site/content/en/docs/Reference/gameserver.md
  test/e2e/fleet_test.go
  test/e2e/gameserver_test.go
Labels: approved, area/user-experience, cla: yes, kind/feature, lgtm, size/XXL

#1956 CRD OpenAPI Spec for ObjectMeta & PodTemplateSpec
  build/Makefile
  build/README.md
  build/boilerplate.yaml.txt
  build/build-image/Dockerfile
  build/e2e-image/Dockerfile
  build/export-openapi.sh
  install/helm/agones/templates/crds/_gameserverspecschema.yaml
  install/helm/agones/templates/crds/fleet.yaml
  install/helm/agones/templates/crds/gameserver.yaml
  install/helm/agones/templates/crds/gameserverset.yaml
  install/helm/agones/templates/crds/k8s/_io.k8s.api.core.v1.PodTemplateSpec.yaml
  install/helm/agones/templates/crds/k8s/_io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  pkg/fleets/controller.go
  site/content/en/docs/Installation/Install Agones/helm.md
  test/e2e/fleet_test.go
  test/e2e/gameserver_test.go
Labels: approved, area/build-tools, area/operations, area/user-experience, cla: yes, kind/feature, size/XXL

#1960 Move `SDKWatchSendOnExecute` to Beta stage.
  build/Makefile
  cloudbuild.yaml
  pkg/util/runtime/features.go
  site/content/en/docs/Guides/Client SDKs/_index.md
  site/content/en/docs/Guides/feature-stages.md
Labels: approved, cla: yes, kind/breaking, kind/feature, lgtm, size/S

#1958 Refactored sdk functions to always return &alpha.Bool{} instead of nil
  pkg/sdkserver/localsdk.go
  pkg/sdkserver/localsdk_test.go
  pkg/sdkserver/sdkserver.go
  pkg/sdkserver/sdkserver_test.go
Labels: approved, cla: yes, kind/bug, size/L

#1965 Fix data race in sdkserver.go
  pkg/sdkserver/sdkserver.go
Labels: approved, cla: yes, kind/bug, lgtm, size/XS

#1928 Utilize ExternalDNS as well as ExternalIP
  build/Makefile
  cloudbuild.yaml
  pkg/gameservers/gameservers.go
  pkg/gameservers/gameservers_test.go
  pkg/util/runtime/features.go
  site/content/en/docs/FAQ/_index.md
  site/content/en/docs/Guides/feature-stages.md
Labels: approved, cla: yes, kind/breaking, kind/feature, size/M

#1967 Release 1.12.0-rc
  CHANGELOG.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package.json
  site/content/en/blog/releases/1.11.0.md
  site/content/en/blog/releases/1.12.0-rc.md
Labels: approved, cla: yes, kind/release, lgtm, size/L

#1968 Limit the disableTLS to only gRPC API
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: approved, cla: yes, kind/cleanup, kind/documentation, lgtm, size/XS
