Repository googleforgames/agones, pull requests merged in 2021-02, with the labels that each got.

#1975 Fix badly formatted feature tags in GameServer specification docs
  site/content/en/docs/Reference/gameserver.md
Labels: approved, cla: yes, lgtm, size/XS

#1974 Fix Minikube #1973
  site/content/en/docs/Installation/Creating Cluster/minikube.md
Labels: approved, cla: yes, size/S

#1969 Fixed getting latency metrics
  pkg/gameserverallocations/allocator.go
  pkg/gameserverallocations/controller.go
Labels: approved, cla: yes, kind/bug, size/M

#1979 Preparation for 1.13.0
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package.json
Labels: approved, cla: yes, kind/release, lgtm, size/M

#1980 Move build tooling to helm upgrade --atomic
  build/Makefile
Labels: approved, area/build-tools, area/tests, cla: yes, kind/bug, lgtm, size/XS

#1983 Update all reference of `master` to `main`
  .github/ISSUE_TEMPLATE/become-a-repo-collaborator.md
  .github/pull_request_template.md
  build/README.md
  build/includes/release.mk
  build/includes/website.mk
  docs/governance/release_process.md
  docs/governance/templates/release_issue.md
  examples/terraform-submodules/aks/module.tf
  examples/terraform-submodules/eks/module.tf
  examples/terraform-submodules/gke/module.tf
  install/helm/agones/Chart.yaml
  pkg/util/apiserver/apiserver.go
  site/cloudbuild.yaml
  site/content/en/docs/Contribute/_index.md
  site/content/en/docs/Guides/Client SDKs/_index.md
  site/content/en/docs/Installation/Terraform/gke.md
  site/content/en/docs/Overview/_index.md
  site/layouts/partials/page-meta-links.html
  site/themes/docsy/layouts/partials/page-meta-links.html
Labels: approved, cla: yes, kind/cleanup, lgtm, size/M

#1984 Fixed: Multi namespace support for client secrets in helm template service/allocation.yaml
  install/helm/agones/templates/service/allocation.yaml
  install/yaml/install.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1986 Upgrade crd-client example
  examples/crd-client/Dockerfile
  examples/crd-client/Makefile
  examples/crd-client/create-gs.yaml
  examples/crd-client/go.mod
  examples/crd-client/go.sum
Labels: approved, area/examples, cla: yes, kind/cleanup, lgtm, size/L

#1988 Upgrade Terraform to 1.18
  build/terraform/prow/module.tf
  install/terraform/modules/aks/aks.tf
  install/terraform/modules/eks/eks.tf
  install/terraform/modules/gke/cluster.tf
  install/terraform/modules/gke/variables.tf
Labels: approved, cla: yes, kind/breaking, kind/feature, size/S

#1985 Ignore Rust SDK Target folder
  test/sdk/rust/.gitignore
Labels: approved, cla: yes, kind/cleanup, size/XS

#1989 Upgrade dev tooling kubectl to 1.18
  build/build-image/Dockerfile
  build/e2e-image/Dockerfile
Labels: approved, area/build-tools, cla: yes, kind/breaking, lgtm, size/XS

#1991 Add "gke" prefix to TCP e2e firewall
  build/terraform/e2e/module.tf
Labels: approved, area/operations, area/tests, cla: yes, kind/cleanup, size/XS

#1994 Terraform helm module fix deprecated version declaration
  install/terraform/modules/helm3/helm.tf
Labels: approved, cla: yes, lgtm, size/S

#1995 Minor grammar fix
  site/content/en/docs/Getting Started/create-fleet.md
Labels: approved, cla: yes, kind/cleanup, kind/documentation, lgtm, size/XS

#1996 Fix bug in webhook docs after example switch
  site/content/en/docs/Getting Started/create-webhook-fleetautoscaler.md
Labels: approved, cla: yes, kind/bug, kind/documentation, lgtm, size/S

#2000 Add Space Game logo to Agones site
  site/content/en/_index.html
  site/static/images/spacegame.png
Labels: approved, area/site, cla: yes, lgtm, size/XS

#2002 Add RollTable to Companies that use Agones
  site/content/en/_index.html
  site/static/images/rolltable.png
Labels: cla: yes, lgtm, size/XS

#2003 add Vela Games to companies that use Agones
  site/content/en/_index.html
  site/static/images/velagames.png
Labels: area/site, cla: yes, kind/feature, size/XS

#1944 [UrealSDK] Creating requests should work in all versions of UE4
  sdks/unreal/Agones/Source/Agones/Private/AgonesComponent.cpp
  sdks/unreal/Agones/Source/Agones/Public/AgonesComponent.h
Labels: approved, area/user-experience, cla: yes, kind/bug, size/M

#1999 Add WebSocket capability to WatchGameServer REST API
  build/build-sdk-images/restapi/sdktest.sh
  cmd/sdk-server/main.go
  go.mod
  go.sum
  site/content/en/docs/Guides/Client SDKs/rest.md
  test/sdk/websocket-watch/ws-watch-test.go
  vendor/github.com/gorilla/websocket/.gitignore
  vendor/github.com/gorilla/websocket/AUTHORS
  vendor/github.com/gorilla/websocket/LICENSE
  vendor/github.com/gorilla/websocket/README.md
  vendor/github.com/gorilla/websocket/client.go
  vendor/github.com/gorilla/websocket/client_clone.go
  vendor/github.com/gorilla/websocket/client_clone_legacy.go
  vendor/github.com/gorilla/websocket/compression.go
  vendor/github.com/gorilla/websocket/conn.go
  vendor/github.com/gorilla/websocket/conn_write.go
  vendor/github.com/gorilla/websocket/conn_write_legacy.go
  vendor/github.com/gorilla/websocket/doc.go
  vendor/github.com/gorilla/websocket/json.go
  vendor/github.com/gorilla/websocket/mask.go
  vendor/github.com/gorilla/websocket/mask_safe.go
  vendor/github.com/gorilla/websocket/prepared.go
  vendor/github.com/gorilla/websocket/proxy.go
  vendor/github.com/gorilla/websocket/server.go
  vendor/github.com/gorilla/websocket/trace.go
  vendor/github.com/gorilla/websocket/trace_17.go
  vendor/github.com/gorilla/websocket/util.go
  vendor/github.com/gorilla/websocket/x_net_proxy.go
  vendor/github.com/tmc/grpc-websocket-proxy/LICENSE
  vendor/github.com/tmc/grpc-websocket-proxy/wsproxy/doc.go
  vendor/github.com/tmc/grpc-websocket-proxy/wsproxy/websocket_proxy.go
  vendor/modules.txt
Labels: approved, area/user-experience, cla: yes, kind/feature, lgtm, size/XXL

#2010 Update Dev Kind & Minikube to 1.18
  build/includes/kind.mk
  build/includes/minikube.mk
Labels: approved, area/build-tools, cla: yes, lgtm, size/XS

#2009 Update CRD API reference to Kubernetes 1.18
  site/assets/templates/crd-doc-config.json
  site/content/en/docs/Reference/agones_crd_api_reference.html
Labels: approved, cla: yes, kind/cleanup, kind/documentation, lgtm, size/XXL

#2004 Add extra resource to DGS prereq knowledge section
  site/content/en/docs/Prerequisite Knowledge/_index.md
Labels: approved, cla: yes, kind/cleanup, kind/documentation, size/XS

#2008 Update website supported Kubernetes
  site/config.toml
Labels: approved, cla: yes, kind/breaking, kind/documentation, size/XS
