Repository googleforgames/agones, pull requests merged in 2021-08, with the labels that each got.

#2211 [docs] examples allocator fixed link (without / it did no resolved)
  examples/allocator-client-csharp/README.md
Labels: lgtm, size/XS, approved, cla: yes

#2212 Add a missing word to clarify our policy for when to upgrade Kubernetes versions
  site/content/en/docs/Installation/_index.md
Labels: kind/cleanup, lgtm, size/XS, approved, cla: yes

#2171 Custom fleet autoscaler resync interval
  build/Makefile
  cloudbuild.yaml
  examples/fleetautoscaler.yaml
  install/helm/agones/templates/crds/fleetautoscaler.yaml
  install/yaml/install.yaml
  pkg/apis/autoscaling/v1/fleetautoscaler.go
  pkg/apis/autoscaling/v1/fleetautoscaler_test.go
  pkg/apis/autoscaling/v1/zz_generated.deepcopy.go
  pkg/fleetautoscalers/controller.go
  pkg/fleetautoscalers/controller_test.go
  pkg/metrics/util_test.go
  pkg/util/runtime/features.go
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Reference/agones_crd_api_reference.html
  site/content/en/docs/Reference/fleetautoscaler.md
  test/e2e/fleetautoscaler_test.go
Labels: size/XL, cla: yes

#2225 Workaround for bullseye release CI blockage
  build/build-sdk-images/cpp/Dockerfile
  build/build-sdk-images/csharp/Dockerfile
  build/build-sdk-images/go/Dockerfile
  build/build-sdk-images/node/Dockerfile
  build/build-sdk-images/restapi/Dockerfile
  build/build-sdk-images/rust/Dockerfile
  site/content/en/_index.html
  site/htmltest.yaml
Labels: kind/bug, area/build-tools, size/S, approved, cla: yes

#2215 Create "Integration Patterns" section in docs
  site/content/en/docs/FAQ/_index.md
  site/content/en/docs/Getting Started/create-fleet.md
  site/content/en/docs/Guides/gameserver-lifecycle.md
  site/content/en/docs/Integration Patterns/_index.md
  site/content/en/docs/Integration Patterns/allocation-from-fleet.md
  site/content/en/docs/Integration Patterns/matchmaker-registration.md
Labels: kind/feature, kind/documentation, lgtm, size/L, approved, cla: yes

#2228 Fix for tabbing in gameserverallocation.md
  site/content/en/docs/Reference/gameserverallocation.md
Labels: kind/documentation, kind/cleanup, lgtm, size/S, approved, cla: yes

#2227 Docs: Canary Testing Integration Pattern
  build/includes/website.mk
  site/content/en/docs/Integration Patterns/canary-testing.md
  site/static/diagrams/canary-testing.puml
  site/static/diagrams/canary-testing.puml.png
Labels: kind/feature, kind/documentation, size/M, lgtm, approved, cla: yes

#2230 remove allocated 2 times from dot file
  site/static/diagrams/gameserver-states.dot
Labels: lgtm, size/XS, cla: yes

#2233 Update dev dependencies and audit fix security warning
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
Labels: area/security, lgtm, size/L, approved, cla: yes

#2229 Docs: Player Capacity Integration Pattern
  build/includes/website.mk
  site/content/en/docs/Integration Patterns/player-capacity.md
  site/layouts/shortcodes/alpha.html
  site/static/diagrams/allocation-player-capacity.puml
  site/static/diagrams/allocation-player-capacity.puml.png
Labels: kind/feature, kind/documentation, lgtm, size/L, approved, cla: yes

#2234 Unlock mutex before returning on error in SDKServer.updateState
  pkg/sdkserver/sdkserver.go
Labels: kind/bug, lgtm, size/XS, approved, cla: yes

#2242 Fix validation bug in FleetAutoscaler
  install/helm/agones/templates/extensions.yaml
  install/yaml/install.yaml
  pkg/apis/autoscaling/v1/fleetautoscaler.go
  pkg/apis/autoscaling/v1/fleetautoscaler_test.go
  pkg/fleetautoscalers/controller.go
  pkg/fleetautoscalers/controller_test.go
  test/e2e/fleetautoscaler_test.go
Labels: kind/bug, lgtm, size/L, approved, cla: yes

#2246 Add nil check to fleet autoscaler validation for sync field
  pkg/apis/autoscaling/v1/fleetautoscaler.go
Labels: kind/bug, size/XS, approved, cla: yes
