Repository googleforgames/agones, pull requests merged in 2022-04, with the labels that each got.

#2534 UE4 docs broke links with UE5 release
  site/content/en/docs/Guides/Client SDKs/unreal.md
Labels: kind/documentation, kind/cleanup, lgtm, size/S, approved

#2533 updates for the upcoming release
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/unity/package.json
Labels: kind/release, size/M, lgtm, approved

#2535 Fix for flaky TestFleetRecreateGameServers
  test/e2e/fleet_test.go
Labels: kind/cleanup, area/tests, lgtm, size/XS, approved

#2527 Use source sdk in simple-game-server
  examples/simple-game-server/Dockerfile
  examples/simple-game-server/Makefile
  examples/simple-game-server/go.mod
  examples/simple-game-server/go.sum
Labels: kind/bug, area/examples, lgtm, size/XL, approved

#2526 Check for DeletionTimestamp of fleet and gameserverset before scaling
  pkg/fleetautoscalers/controller.go
  pkg/fleetautoscalers/controller_test.go
  pkg/fleets/controller.go
  pkg/fleets/controller_test.go
  pkg/gameserversets/controller.go
  pkg/gameserversets/controller_test.go
Labels: size/L, approved

#2537 Update unreal.md to fix #2523
  site/content/en/docs/Guides/Client SDKs/unreal.md
Labels: size/XS, approved

#2539 v2: Flaky TestFleetRecreateGameServers fix.
  test/e2e/fleet_test.go
Labels: kind/cleanup, area/tests, lgtm, size/XS, approved

#2541 Update fleetautoscaler e2e certs
  test/e2e/fleetautoscaler_test.go
Labels: kind/cleanup, area/tests, lgtm, size/L, approved

#2540 Update everything to simple-gameserver:0.12
  build/Makefile
  examples/crd-client/create-gs.yaml
  examples/fleet.yaml
  examples/gameserver.yaml
  examples/simple-game-server/dev-gameserver.yaml
  examples/simple-game-server/fleet-distributed.yaml
  examples/simple-game-server/fleet-tcp.yaml
  examples/simple-game-server/fleet.yaml
  examples/simple-game-server/gameserver-passthrough.yaml
  examples/simple-game-server/gameserver-windows.yaml
  examples/simple-game-server/gameserver.yaml
  install/helm/agones/templates/tests/test-runner.yaml
  pkg/util/webhooks/webhooks_test.go
  site/config.toml
  test/e2e/framework/framework.go
  test/e2e/gameserver_test.go
  test/load/allocation/fleet.yaml
  test/load/allocation/grpc/README.md
  test/load/allocation/grpc/fleet.yaml
  test/load/locust-files/fleet_autoscaling.py
  test/load/locust-files/gameserver_allocation.py
Labels: kind/cleanup, area/tests, size/M, approved

#2542 Initial step for M1 with (make build-images WITH_WINDOWS=0 and make s…
  build/Makefile
Labels: kind/bug, area/build-tools, lgtm, size/XS, approved

#2503 Add e2e test for PlayerConnectWithCapacityZero
  test/e2e/gameserver_test.go
Labels: size/S, approved

#2547 Move some Info logging to Debug
  cmd/allocator/main.go
  pkg/gameservers/controller.go
  pkg/gameservers/portallocator.go
  pkg/gameserversets/controller.go
  pkg/metrics/controller.go
  pkg/util/crd/crd.go
  pkg/util/webhooks/webhooks.go
Labels: kind/cleanup, area/operations, lgtm, size/S, approved

#2548 Unblock CI: Remove EKS Autoscaler terraform link
  site/content/en/docs/Advanced/scheduling-and-autoscaling.md
  site/htmltest.yaml
Labels: kind/documentation, kind/cleanup, lgtm, size/XS, approved

#2545 Don't move Dev GameServer back to Ready always
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  test/e2e/gameserver_test.go
Labels: kind/bug, area/user-experience, size/M, lgtm, approved

#2550 Queue updated GameServers with DeletionTimestamp
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
Labels: kind/bug, area/user-experience, lgtm, size/XS, approved

#2551 Upgrade terraform to Kubernetes 1.22
  build/terraform/prow/module.tf
  install/terraform/modules/aks/variables.tf
  install/terraform/modules/eks/eks.tf
  install/terraform/modules/gke/cluster.tf
  install/terraform/modules/gke/variables.tf
Labels: kind/breaking, lgtm, size/S, approved

#2555 Upgrade kubectl to 1.22 in dev tooling
  build/build-image/Dockerfile
  build/e2e-image/Dockerfile
Labels: lgtm, size/XS, approved

#2556 Update the dev version of Kubernetes in the website to 1.22
  site/config.toml
Labels: lgtm, size/XS, approved

#2557 Increase the e2e cluster size to match what was observed
  build/terraform/e2e/module.tf
Labels: lgtm, size/XS, approved

#2558 Update Minikube and Kind dev tooling to Kubernetes 1.22
  build/includes/kind.mk
  build/includes/minikube.mk
Labels: lgtm, size/XS, approved

#2561 Add the new gke-gcloud-auth-plugin binary to the build image
  build/build-image/Dockerfile
Labels: lgtm, size/XS, approved

#2562 Regenerate Kubernetes resource includes (ObjectMeta, PodTemplateSpec) for Kubernetes 1.22
  install/helm/agones/templates/crds/k8s/_io.k8s.api.core.v1.PodTemplateSpec.yaml
  install/helm/agones/templates/crds/k8s/_io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta.yaml
  install/yaml/install.yaml
Labels: lgtm, size/XL, approved

#2563 Update the go runtime environment version for the website from 1.13 to 1.16
  site/app.yaml
Labels: lgtm, size/XS, approved

#2554 Fix for health controller race condition marking healthy pods as unhealthy
  pkg/gameservers/health.go
  pkg/gameservers/health_test.go
Labels: kind/bug, size/M, lgtm, approved

#2521 sdk arm64 images
  build/Makefile
  build/includes/build-image.mk
  cloudbuild.yaml
  cmd/sdk-server/Dockerfile
Labels: size/M, lgtm, approved
