Repository googleforgames/agones, pull requests merged in 2022-01, with the labels that each got.

#2421 Release v1.20.0-rc
  CHANGELOG.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package.json
  sdks/unity/package.json
  site/content/en/blog/releases/1.19.0.md
  site/content/en/blog/releases/1.20.0-rc.md
  site/content/en/docs/Advanced/scheduling-and-autoscaling.md
Labels: size/L, approved

#2425 Upgrade terraform test dependencies.
  test/terraform/go.mod
  test/terraform/go.sum
Labels: area/security, area/tests, size/XXL, lgtm, approved

#2434 Next release updates
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/unity/package.json
Labels: kind/release, size/M, lgtm, approved

#2419 Add a new prerequisite to the release checklist
  docs/governance/templates/release_issue.md
Labels: kind/cleanup, size/XS, approved

#2422 Fleet Autoscaler custom sync: Race condition fix
  pkg/fleetautoscalers/controller.go
  pkg/fleetautoscalers/controller_test.go
  test/e2e/fleetautoscaler_test.go
Labels: kind/bug, lgtm, size/XL, approved

#2435 Update the node-forge dependency to address GHSA-5rrq-pxf6-6jx5
  sdks/nodejs/package-lock.json
Labels: kind/cleanup, area/security, lgtm, size/S, approved

#2412 Adding AcceleratXR to companies using agones
  site/content/en/_index.html
  site/static/images/acceleratxr.png
Labels: size/XS, approved

#2426 CI: Uninstall Helm release if stuck
  build/Makefile
Labels: area/build-tools, area/tests, size/XS, approved

#2429 docs: typo grep command
  site/content/en/docs/Getting Started/create-fleet.md
Labels: kind/documentation, kind/cleanup, size/XS, approved

#2439 Unit test for an Allocation empty selector.
  pkg/gameserverallocations/find_test.go
Labels: area/tests, lgtm, size/S, approved

#2427 Simple Game Server: Don't panic on UNHEALTHY x 2
  .dockerignore
  examples/simple-game-server/Makefile
  examples/simple-game-server/main.go
Labels: kind/bug, area/examples, area/tests, size/M, approved

#2423 Fix "kubectl explain" output for Agones CRDs
  install/helm/agones/templates/crds/_gameserverspecschema.yaml
  install/helm/agones/templates/crds/_gameserverstatus.yaml
  install/helm/agones/templates/crds/fleet.yaml
  install/helm/agones/templates/crds/fleetautoscaler.yaml
  install/helm/agones/templates/crds/gameserverallocationpolicy.yaml
  install/helm/agones/templates/crds/gameserverset.yaml
  install/yaml/install.yaml
Labels: size/M, lgtm, approved

#2440 Get the initial game server state before marking the simple game server ready
  examples/simple-game-server/Makefile
  examples/simple-game-server/main.go
Labels: kind/cleanup, size/S, approved

#2441 Move Allocator unit tests to better test module
  pkg/gameserverallocations/allocator_test.go
  pkg/gameserverallocations/controller_test.go
Labels: kind/cleanup, area/tests, size/XXL, approved

#2444 Fix connection timeout on Rust SDK.
  examples/rust-simple/Makefile
  sdks/rust/Cargo.toml
  sdks/rust/src/sdk.rs
Labels: kind/bug, area/user-experience, area/tests, lgtm, size/S, approved

#2438 Remove curl|bash from dockerfile to address vulnerability issues
  build/build-image/Dockerfile
  build/build-sdk-images/node/Dockerfile
  build/build-sdk-images/restapi/Dockerfile
  examples/nodejs-simple/Dockerfile
  examples/nodejs-simple/Makefile
  examples/nodejs-simple/README.md
  examples/nodejs-simple/gameserver.yaml
  pkg/fleetautoscalers/fleetautoscalers_test.go
  pkg/util/apiserver/apiserver.go
  pkg/util/https/https.go
  test/e2e/fleetautoscaler_test.go
  test/e2e/framework/perf.go
  test/e2e/gameserver_test.go
Labels: lgtm, size/L, approved

#2442 Send initial GameServer update in WatchGameServer
  pkg/sdkserver/localsdk.go
  pkg/sdkserver/localsdk_test.go
Labels: kind/bug, area/user-experience, size/S, approved

#2448 Remove trailing space in logging statement.
  pkg/gameserverallocations/allocator.go
Labels: kind/cleanup, lgtm, size/XS, approved

#2447 Regenerate package-lock.json for the two node.js projects
  examples/nodejs-simple/package-lock.json
  sdks/nodejs/package-lock.json
Labels: size/XXL, approved

#2449 Validate GameServerAllocation metadata
  pkg/apis/allocation/v1/gameserverallocation.go
  pkg/apis/allocation/v1/gameserverallocation_test.go
  test/e2e/gameserverallocation_test.go
Labels: kind/bug, area/user-experience, size/L, approved

#2451 Update the simple game server to avoid a race condition when transitioning from ready to allocated
  examples/simple-game-server/Makefile
  examples/simple-game-server/main.go
Labels: kind/bug, lgtm, size/S, approved

#2446 update on scaler limited to Max
  pkg/fleetautoscalers/controller.go
  pkg/fleetautoscalers/controller_test.go
Labels: kind/bug, lgtm, size/S

#2433 Remove node_name label from allocation metrics
  build/grafana/dashboard-allocations.yaml
  pkg/gameserverallocations/metrics.go
Labels: kind/breaking, area/operations, size/M, lgtm, approved
