Repository googleforgames/agones, pull requests merged in 2022-07, with the labels that each got.

#2649 Health check error message
  sdks/nodejs/spec/agonesSDK.spec.js
  sdks/nodejs/src/agonesSDK.js
  site/content/en/docs/Guides/Client SDKs/nodejs.md
Labels: kind/cleanup, size/M, lgtm

#2662 Fix minikube dev tooling
  build/includes/minikube.mk
Labels: kind/bug, area/build-tools, lgtm, size/S, approved

#2656 Add agones4j to 3rd party libraries.
  site/content/en/docs/Third Party Content/libraries-tools.md
Labels: kind/documentation, size/XS, approved

#2663 Specify the OS architecture tested for known working drivers for minikube.
  site/content/en/docs/Installation/Creating Cluster/minikube.md
Labels: kind/cleanup, size/XS, approved

#2660 NodeExternalDNS/stable
  cloudbuild.yaml
  pkg/gameservers/gameservers.go
  pkg/gameservers/gameservers_test.go
  pkg/util/runtime/features.go
  site/content/en/docs/Guides/feature-stages.md
Labels: kind/feature, size/M, approved

#2667 Minikube: Fixes for Makefile, dev & usage docs
  build/Makefile
  build/README.md
  site/content/en/docs/Installation/Creating Cluster/minikube.md
Labels: kind/bug, kind/documentation, kind/cleanup, area/build-tools, lgtm, size/S, approved

#2600 Support for Unity Alpha SDK
  sdks/unity/AgonesAlphaSdk.cs
  sdks/unity/AgonesAlphaSdk.cs.meta
  sdks/unity/AgonesSdk.cs
  site/content/en/docs/Guides/Client SDKs/unity.md
  site/layouts/shortcodes/alpha.html
Labels: size/L, approved

#2668 update grpc package version for arm64 Linux
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/csharp/test/csharp-sdk-test.csproj
Labels: kind/bug, size/S, approved

#2672 Bug: `make install` uses local helm and jq
  build/Makefile
Labels: kind/bug, area/build-tools, lgtm, size/XS, approved

#2654 Move CustomFasSyncInterval to Beta
  build/Makefile
  cloudbuild.yaml
  examples/fleetautoscaler.yaml
  pkg/apis/autoscaling/v1/fleetautoscaler.go
  pkg/util/runtime/features.go
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Reference/agones_crd_api_reference.html
  site/content/en/docs/Reference/fleetautoscaler.md
Labels: kind/feature, size/XXL, approved

#2608 supertuxcart version update-1.3
  examples/supertuxkart/Dockerfile
  examples/supertuxkart/Makefile
  examples/supertuxkart/entrypoint.sh
  examples/supertuxkart/server_config.xml
Labels: kind/cleanup, area/examples, size/M, lgtm

#2666 Building and pushing ARM64 images
  build/Makefile
Labels: kind/bug, area/build-tools, size/M, lgtm

#2676 Update `Contribute` docs feature code version
  site/content/en/docs/Contribute/_index.md
Labels: kind/documentation, kind/cleanup, lgtm, size/S, approved

#2678 Docs: Note that Feature Gate changes are upgrades
  site/content/en/docs/Installation/upgrading.md
Labels: kind/documentation, kind/cleanup, lgtm, size/S, approved

#2669 upgrade xonotic version
  examples/xonotic/Dockerfile
  examples/xonotic/Dockerfile.windows
  examples/xonotic/Makefile
  examples/xonotic/go.mod
  examples/xonotic/go.sum
Labels: kind/feature, area/examples, size/L, approved

#2679 Add Feature Flag section to troubleshooting
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Guides/troubleshooting.md
Labels: kind/documentation, kind/cleanup, lgtm, size/S, approved

#2677 Docs: How to do local container with sdk
  site/content/en/docs/Guides/Client SDKs/local.md
Labels: kind/feature, kind/documentation, size/M, lgtm, approved

#2685 release-v1.25.0-rc
  CHANGELOG.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/unity/package.json
  site/content/en/blog/releases/1.24.0.md
  site/content/en/blog/releases/1.25.0-rc.md
Labels: kind/release, lgtm, size/L, approved

#2686 Fix typo in release 1.25.0-rc blog post
  site/content/en/blog/releases/1.25.0-rc.md
Labels: kind/bug, kind/documentation, lgtm, size/S, approved

#2689 Fix feature flags on "High Density" documentation
  site/content/en/docs/Integration Patterns/high-density-gameservers.md
  site/layouts/shortcodes/alpha.html
Labels: lgtm, size/XS, approved
