Repository googleforgames/agones, pull requests merged in 2022-10, with the labels that each got.

#2756 Enable image streaming everywhere by default
  build/README.md
  build/includes/google-cloud.mk
  build/includes/terraform.mk
  build/terraform/gke/module.tf
  examples/terraform-submodules/gke/module.tf
  install/terraform/modules/gke/cluster.tf
  site/content/en/docs/Installation/Creating Cluster/gke.md
  site/content/en/docs/Installation/Terraform/gke.md
Labels: size/M, lgtm, approved

#2759 Add an example of setting autoscaler behavior in a Fleet.
  site/content/en/docs/Advanced/scheduling-and-autoscaling.md
Labels: kind/cleanup, lgtm, size/S, approved

#2760 Fix case of HTTP module reference
  sdks/unreal/Agones/Source/Agones/Agones.Build.cs
Labels: lgtm, size/XS

#2763 2665 Log cleanup: Verbose error log on pod not yet running
  pkg/gameservers/controller.go
Labels: kind/cleanup, lgtm, size/XS, approved

#2762 Enable image streaming for e2e test cluster
  build/includes/terraform.mk
  build/terraform/e2e/module.tf
Labels: lgtm, size/S

#2764 Add repository for hashicorp/consul, and disable the consul-consul-client
  build/includes/google-cloud.mk
  build/terraform/e2e/module.tf
Labels: lgtm, size/S

#2768 Release 1.27.0-rc
  CHANGELOG.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/unity/package.json
  site/content/en/blog/releases/1.26.0.md
  site/content/en/blog/releases/1.27.0-rc.md
Labels: kind/release, lgtm, size/L, approved

#2773 Update FAQ on ExternalDNS
  site/content/en/docs/FAQ/_index.md
Labels: kind/documentation, kind/cleanup, lgtm, size/XS, approved

#2772 Updates to release checklist.
  docs/governance/templates/release_issue.md
Labels: kind/cleanup, area/meta, lgtm, size/S, approved

#2778 Version updates
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/unity/package.json
Labels: kind/release, size/M, lgtm, approved

#2765 Players in-game metric for when PlayerTracking is enabled
  pkg/metrics/controller.go
  pkg/metrics/controller_metrics.go
  pkg/metrics/controller_test.go
  site/content/en/docs/Guides/metrics.md
Labels: size/L, approved

#2757 Remove generation for swagger Go code and Add static swagger codes for test
  .golangci.yml
  build/README.md
  build/build-sdk-images/restapi/build-sdk-test.sh
  build/build-sdk-images/restapi/clean.sh
  build/build-sdk-images/restapi/gen.sh
  test/sdk/restapi/alpha/swagger/api_sdk.go
  test/sdk/restapi/alpha/swagger/client.go
  test/sdk/restapi/alpha/swagger/configuration.go
  test/sdk/restapi/alpha/swagger/model_alpha_bool.go
  test/sdk/restapi/alpha/swagger/model_alpha_count.go
  test/sdk/restapi/alpha/swagger/model_alpha_empty.go
  test/sdk/restapi/alpha/swagger/model_alpha_player_id.go
  test/sdk/restapi/alpha/swagger/model_alpha_player_id_list.go
  test/sdk/restapi/alpha/swagger/response.go
  test/sdk/restapi/swagger/api_sdk.go
  test/sdk/restapi/swagger/client.go
  test/sdk/restapi/swagger/configuration.go
  test/sdk/restapi/swagger/model_game_server_object_meta.go
  test/sdk/restapi/swagger/model_game_server_spec.go
  test/sdk/restapi/swagger/model_game_server_status.go
  test/sdk/restapi/swagger/model_protobuf_any.go
  test/sdk/restapi/swagger/model_runtime_stream_error.go
  test/sdk/restapi/swagger/model_sdk_duration.go
  test/sdk/restapi/swagger/model_sdk_empty.go
  test/sdk/restapi/swagger/model_sdk_game_server.go
  test/sdk/restapi/swagger/model_sdk_key_value.go
  test/sdk/restapi/swagger/model_spec_health.go
  test/sdk/restapi/swagger/model_status_player_status.go
  test/sdk/restapi/swagger/model_status_port.go
  test/sdk/restapi/swagger/model_xstreamdefinitionssdkgameserver.go
  test/sdk/restapi/swagger/response.go
Labels: size/XXL, approved

#2780 Show how to set graceful termination in a game server that is safe to evict
  site/content/en/docs/Advanced/scheduling-and-autoscaling.md
Labels: kind/documentation, lgtm, size/XS, approved

#2783 Avoid retry from allocateFromLocalCluster under context kill.
  pkg/gameserverallocations/allocator.go
Labels: kind/bug, size/XS, approved

#2769 Bring SDK base image to debian:bullseye
  build/build-sdk-images/cpp/shell.sh
  build/build-sdk-images/tool/base/Dockerfile
  sdks/cpp/src/agones/sdk.cc
Labels: kind/cleanup, area/build-tools, lgtm, size/S, approved
