Repository googleforgames/agones, pull requests merged in 2022-09, with the labels that each got.

#2723 Add the agones prefix to the cleanupOnDelete variable name.
  install/terraform/modules/helm3/helm.tf
Labels: kind/bug, lgtm, size/XS, approved

#2712 Exposes metrics ports on pods in order to enable GCP Managed Prometheus
  install/helm/agones/templates/service/allocation.yaml
  install/yaml/install.yaml
  site/content/en/docs/Guides/metrics.md
Labels: kind/feature, size/S, approved

#2724 Docs/Helm: Formatted table, fix typo
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: kind/bug, kind/documentation, size/L, approved

#2701 Clear metric labels on Fleet/Autoscaler delete
  build/Makefile
  cloudbuild.yaml
  pkg/metrics/controller.go
  pkg/metrics/controller_metrics.go
  pkg/metrics/controller_test.go
  pkg/metrics/util_test.go
  pkg/util/runtime/features.go
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Guides/metrics.md
Labels: kind/bug, area/operations, size/L, approved

#2725 Update gRPC SDK tooling to 1.36.1
  build/build-sdk-images/tool/base/Dockerfile
  build/includes/sdk.mk
  pkg/allocation/go/allocation.gw.pb.go
  pkg/allocation/go/allocation.pb.go
  pkg/sdk/alpha/alpha.pb.go
  pkg/sdk/alpha/alpha.pb.gw.go
  pkg/sdk/beta/beta.pb.go
  pkg/sdk/sdk.pb.go
  pkg/sdk/sdk.pb.gw.go
  sdks/cpp/CMakeLists.txt
Labels: kind/cleanup, size/M, lgtm, approved

#2727 Regenerate gRPC clients for all SDKs.
  sdks/cpp/cmake/prerequisites.cmake
  sdks/cpp/include/agones/sdk.grpc.pb.h
  sdks/cpp/include/agones/sdk.pb.h
  sdks/cpp/include/google/api/annotations.pb.h
  sdks/cpp/include/google/api/http.pb.h
  sdks/cpp/src/agones/sdk.grpc.pb.cc
  sdks/cpp/src/agones/sdk.pb.cc
  sdks/cpp/src/google/annotations.pb.cc
  sdks/cpp/src/google/http.pb.cc
  sdks/csharp/sdk/generated/Alpha.cs
  sdks/csharp/sdk/generated/AlphaGrpc.cs
  sdks/csharp/sdk/generated/Sdk.cs
  sdks/csharp/sdk/generated/SdkGrpc.cs
  sdks/nodejs/lib/alpha/alpha_pb.js
  sdks/nodejs/lib/alpha/google/api/annotations_pb.js
  sdks/nodejs/lib/alpha/google/api/http_pb.js
  sdks/nodejs/lib/google/api/annotations_pb.js
  sdks/nodejs/lib/google/api/http_pb.js
  sdks/nodejs/lib/sdk_pb.js
  sdks/rust/proto/allocation/allocation.proto
Labels: kind/cleanup, area/user-experience, size/XXL, lgtm, approved

#2728 Added missing env to flag mapping
  cmd/allocator/main.go
  cmd/controller/main.go
Labels: lgtm, size/XS, approved

#2733 relase v1.26.0-rc
  CHANGELOG.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/unity/package.json
  site/content/en/blog/releases/1.25.0.md
  site/content/en/blog/releases/1.26.0-rc.md
Labels: kind/release, lgtm, size/L, approved

#2741 updates for upcoming release
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/unity/package.json
Labels: kind/release, size/M, lgtm

#2742 Added a title to the 1.26.0 release
  site/content/en/blog/releases/1.26.0.md
Labels: kind/documentation, kind/cleanup, lgtm, size/XS, approved

#2731 Allocator Informer Event optimize updateFunc
  pkg/gameserverallocations/allocation_cache.go
Labels: size/S, approved

#2743 Upgrade Go version to 1.19.1
  .golangci.yml
  build/build-image/Dockerfile
  build/build-sdk-images/go/Dockerfile
  build/build-sdk-images/restapi/Dockerfile
  build/e2e-image/Dockerfile
  cmd/allocator/main.go
  cmd/allocator/main_test.go
  cmd/allocator/metrics.go
  examples/allocation-endpoint/Makefile
  examples/allocation-endpoint/client/go.mod
  examples/allocation-endpoint/server/Dockerfile
  examples/allocation-endpoint/server/go.mod
  examples/autoscaler-webhook/Dockerfile
  examples/autoscaler-webhook/Makefile
  examples/crd-client/Dockerfile
  examples/crd-client/Makefile
  examples/simple-game-server/Dockerfile
  examples/simple-game-server/Makefile
  examples/simple-game-server/go.mod
  examples/simple-game-server/go.sum
  examples/supertuxkart/Dockerfile
  examples/supertuxkart/Makefile
  examples/supertuxkart/go.mod
  examples/xonotic/Dockerfile
  examples/xonotic/Dockerfile.windows
  examples/xonotic/Makefile
  examples/xonotic/go.mod
  go.mod
  go.sum
  site/go.mod
  test/e2e/allocator_test.go
  test/e2e/fleet_test.go
  test/e2e/gameserver_test.go
  test/terraform/go.mod
  test/terraform/go.sum
Labels: size/XXL, lgtm, approved

#2751 bump the example images version
  build/Makefile
  examples/autoscaler-webhook/autoscaler-service-tls.yaml
  examples/autoscaler-webhook/autoscaler-service.yaml
  examples/crd-client/create-gs.yaml
  examples/fleet.yaml
  examples/gameserver.yaml
  examples/simple-game-server/dev-gameserver.yaml
  examples/simple-game-server/fleet-distributed.yaml
  examples/simple-game-server/fleet-tcp.yaml
  examples/simple-game-server/fleet.yaml
  examples/simple-game-server/gameserver-passthrough.yaml
  examples/simple-game-server/gameserver-windows.yaml
  examples/simple-game-server/gameserver.yaml
  examples/supertuxkart/fleet.yaml
  examples/supertuxkart/gameserver.yaml
  examples/xonotic/fleet.yaml
  examples/xonotic/gameserver.yaml
  install/helm/agones/templates/tests/test-runner.yaml
  pkg/util/webhooks/webhooks_test.go
  site/config.toml
  test/e2e/fleetautoscaler_test.go
  test/e2e/framework/framework.go
  test/e2e/gameserver_test.go
  test/load/allocation/fleet.yaml
  test/load/allocation/grpc/README.md
  test/load/allocation/grpc/fleet.yaml
Labels: size/M, lgtm, approved

#2752 Replace uses of the io/ioutil package
  .golangci.yml
  cmd/allocator/main.go
  examples/allocator-client/main.go
  examples/autoscaler-webhook/main.go
  pkg/fleetautoscalers/fleetautoscalers.go
  pkg/fleetautoscalers/fleetautoscalers_test.go
  pkg/gameserverallocations/controller.go
  pkg/sdkserver/helper_test.go
  pkg/sdkserver/localsdk_test.go
  pkg/util/apiserver/apiserver_test.go
  pkg/util/https/https.go
  pkg/util/webhooks/webhooks_test.go
  pkg/util/workerqueue/workerqueue_test.go
  site/handler_test.go
  site/main.go
  test/e2e/allocator_test.go
  test/e2e/gameserver_test.go
  test/e2e/ping_test.go
  test/load/allocation/grpc/allocationload.go
  test/load/allocation/grpc/runscenario.go
Labels: size/M, lgtm

#2754 If the user has specified cluster autoscaling behavior for their gameserver then don't overwrite it
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/agones/v1/gameserver_test.go
  site/content/en/docs/Advanced/scheduling-and-autoscaling.md
Labels: kind/cleanup, lgtm, size/L, approved
