Repository googleforgames/agones, pull requests merged in 2022-05, with the labels that each got.

#2564 Update dependency for the `push-agones-sdk-linux-image-amd64` target
  build/Makefile
Labels: lgtm, size/XS, approved

#2565 Allocator controller arm64 img
  build/Makefile
  cmd/allocator/Dockerfile
  cmd/controller/Dockerfile
Labels: size/M, lgtm, approved

#2573 Remove broken links to unblock CI
  site/content/en/blog/releases/1.1.0-rc.md
  site/content/en/blog/releases/1.1.0.md
  site/content/en/blog/releases/1.12.0-rc.md
  site/content/en/blog/releases/1.12.0.md
  site/content/en/docs/Installation/Creating Cluster/eks.md
  site/content/en/docs/Installation/Creating Cluster/minikube.md
Labels: kind/cleanup, lgtm, size/S, approved

#2569 ensure context is set before spawning goroutines using it
  pkg/sdkserver/sdkserver.go
Labels: kind/bug, lgtm, size/XS

#2576 Preparation for the 1.24.0 release
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/unity/package.json
Labels: kind/release, size/M, lgtm, approved

#2577 Change deprecated preferred & required to selectors in Player Capacity docs
  site/content/en/docs/Integration Patterns/player-capacity.md
Labels: lgtm, size/S

#2581 Fix controller arm64 tag
  build/Makefile
Labels: lgtm, size/XS

#2587 Added Agones Category to all UPROPERTY macro
  sdks/unreal/Agones/Source/Agones/Classes/Classes.h
Labels: kind/feature, area/user-experience, size/M, lgtm

#2584 updateing debian image to bullseye/Part-1
  build/build-image/Dockerfile
Labels: kind/bug, area/build-tools, size/XS, approved

#2588 Fix local-includes WITH_ARM64=0 or WITH_WINDOWS=0
  build/Makefile
Labels: kind/bug, area/build-tools, lgtm, size/S, approved

#2590 Fix typo in allocator.yaml
  install/helm/agones/templates/service/allocation.yaml
Labels: lgtm, size/XS, approved

#2589 Make Allocator batchWaitTime configurable
  cmd/allocator/main.go
  cmd/allocator/metrics.go
  cmd/controller/main.go
  install/helm/agones/templates/controller.yaml
  install/helm/agones/templates/service/allocation.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  pkg/gameserverallocations/allocator.go
  pkg/gameserverallocations/allocator_test.go
  pkg/gameserverallocations/controller.go
  pkg/gameserverallocations/controller_test.go
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: lgtm, size/L, approved

#2579 Add Document about Informers and Listers
  site/content/en/docs/Guides/access-api.md
Labels: size/L, approved

#2605 Fix intermediate certificate handling (#2602)
  cmd/allocator/main.go
Labels: lgtm, size/XS

#2603 Fix build command: build-agones-sdk-image
  build/includes/build-image.mk
Labels: lgtm, size/XS, approved

#2591 Ping arm img
  build/Makefile
  cmd/ping/Dockerfile
Labels: size/M, lgtm, approved

#2604 e2e tests for arm64 simple game server
  examples/simple-game-server/Makefile
Labels: size/M, lgtm, approved
