Repository googleforgames/agones, pull requests merged in 2022-03, with the labels that each got.

#2472 docs: Support gRPC without TLS
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: lgtm, size/XS, approved

#2477 Fix allocator service document
  site/content/en/docs/Advanced/allocator-service.md
Labels: kind/documentation, kind/cleanup, size/XS, approved

#2489 Fix panic when playertracking is false
  sdks/go/alpha.go
Labels: size/S, approved

#2476 Add NodePort to the helm template for agones-allocator service
  install/helm/agones/templates/service/allocation.yaml
  install/helm/agones/values.yaml
Labels: size/S, approved

#2500 Update CPP gRPC to v1.27.1
  examples/cpp-simple/CMakeLists.txt
  examples/cpp-simple/Makefile
  sdks/cpp/CMakeLists.txt
  sdks/cpp/cmake/prerequisites.cmake
  sdks/cpp/include/agones/sdk.grpc.pb.h
  sdks/cpp/include/agones/sdk.pb.h
  sdks/cpp/include/google/api/annotations.pb.h
  sdks/cpp/include/google/api/http.pb.h
  sdks/cpp/src/agones/sdk.grpc.pb.cc
  sdks/cpp/src/agones/sdk.pb.cc
  sdks/cpp/src/google/annotations.pb.cc
  sdks/cpp/src/google/http.pb.cc
  test/sdk/cpp/CMakeLists.txt
Labels: size/XXL, lgtm, approved

#2502 Added a Development Tools section as requested
  site/content/en/docs/Third Party Content/libraries-tools.md
Labels: lgtm, size/XS, approved

#2506 Update simple-game-server to 0.11 everywhere
  build/Makefile
  examples/crd-client/create-gs.yaml
  examples/fleet.yaml
  examples/gameserver.yaml
  examples/simple-game-server/Makefile
  examples/simple-game-server/dev-gameserver.yaml
  examples/simple-game-server/fleet-distributed.yaml
  examples/simple-game-server/fleet-tcp.yaml
  examples/simple-game-server/fleet.yaml
  examples/simple-game-server/gameserver-passthrough.yaml
  examples/simple-game-server/gameserver-windows.yaml
  examples/simple-game-server/gameserver.yaml
  install/helm/agones/templates/tests/test-runner.yaml
  pkg/util/webhooks/webhooks_test.go
  site/config.toml
  test/e2e/framework/framework.go
  test/e2e/gameserver_test.go
  test/load/allocation/fleet.yaml
  test/load/allocation/grpc/README.md
  test/load/allocation/grpc/fleet.yaml
Labels: kind/cleanup, area/examples, area/tests, size/M, lgtm, approved

#2508 Update the version of the simple game server in the load test samples to the current version
  test/load/allocation/grpc/README.md
  test/load/locust-files/fleet_autoscaling.py
  test/load/locust-files/gameserver_allocation.py
Labels: kind/cleanup, lgtm, size/S, approved

#2513 Remove google-private
  examples/allocation-endpoint/terraform/main.tf
Labels: lgtm, size/XS, approved

#2516 e2e flow for High Density GameServers
  site/content/en/docs/Integration Patterns/high-density-gameservers.md
  test/e2e/gameserverallocation_test.go
Labels: kind/documentation, area/tests, size/M, lgtm, approved

#2420 Fix Rolling Update with Allocated GameServers
  pkg/fleets/controller.go
  test/e2e/fleet_test.go
  test/e2e/framework/framework.go
Labels: lgtm, size/L, approved

#2453 Support cert-manager for controller tls
  install/helm/agones/templates/extensions.yaml
  install/helm/agones/values.yaml
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: size/L

#2510 C# Health and WatchGameServer fixes
  build/build-sdk-images/csharp/Dockerfile
  sdks/csharp/sdk/AgonesSDK.cs
  sdks/csharp/sdk/Alpha.cs
  sdks/csharp/test/AgonesSDKClientTests.cs
  sdks/csharp/test/csharp-sdk-test.csproj
Labels: size/L, approved

#2520 Add multi-cluster allocation demo to third party doc
  site/content/en/docs/Third Party Content/libraries-tools.md
Labels: lgtm, size/XS, approved

#2519 Release v1.22.0 rc
  CHANGELOG.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/unity/package.json
  site/content/en/blog/releases/1.21.0.md
  site/content/en/blog/releases/1.22.0-rc.md
Labels: kind/release, lgtm, size/L, approved
