Repository googleforgames/agones, pull requests merged in 2023-02, with the labels that each got.

#2914 Adds snapshot Hugo env to separate from default env
  build/includes/release.mk
  build/includes/website.mk
  site/layouts/shortcodes/aks-k8s-minor-version.html
  site/layouts/shortcodes/k8s-api.html
  site/layouts/shortcodes/k8s-version.html
  site/layouts/shortcodes/minikube-k8s-minor-version.html
Labels: lgtm, size/S, approved

#2924 Add doc for "Controlling Disruption", document `SafeToEvict`
  build/includes/website.mk
  site/content/en/docs/Advanced/controlling-disruption.md
  site/content/en/docs/Advanced/scheduling-and-autoscaling.md
  site/layouts/shortcodes/alpha.html
  site/layouts/shortcodes/beta.html
  site/static/diagrams/eviction-decision.dot
  site/static/diagrams/eviction-decision.dot.png
Labels: size/L, approved

#2944 Fix Typo in Rust Doc
  site/content/en/docs/Guides/Client SDKs/rust.md
Labels: lgtm, size/XS, approved

#2910 Use containerd runtime based Windows image
  install/terraform/modules/gke/cluster.tf
  site/content/en/docs/Installation/Creating Cluster/gke.md
Labels: size/XS, approved

#2947 Add e2e test for Extensions
  build/Makefile
  test/e2e/extensions/high_availability_test.go
  test/e2e/extensions/main_test.go
Labels: lgtm, size/L

#2948 Remove apiHooks singleton
  cmd/controller/main.go
  cmd/extensions/main.go
  pkg/apis/agones/v1/apihooks.go
  pkg/apis/agones/v1/apihooks_test.go
  pkg/apis/agones/v1/apihooksfake.go
  pkg/apis/agones/v1/common.go
  pkg/apis/agones/v1/fleet.go
  pkg/apis/agones/v1/fleet_test.go
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/agones/v1/gameserver_test.go
  pkg/apis/agones/v1/gameserverset.go
  pkg/apis/agones/v1/gameserverset_test.go
  pkg/cloudproduct/cloudproduct.go
  pkg/cloudproduct/generic/generic.go
  pkg/cloudproduct/generic/generic_test.go
  pkg/cloudproduct/gke/gke.go
  pkg/fleets/controller.go
  pkg/fleets/controller_test.go
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  pkg/gameservers/gameservers_test.go
  pkg/gameservers/health.go
  pkg/gameservers/health_test.go
  pkg/gameservers/migration.go
  pkg/gameservers/migration_test.go
  pkg/gameservers/missing_test.go
  pkg/gameserversets/controller.go
  pkg/gameserversets/controller_test.go
  test/e2e/gameserver_test.go
Labels: lgtm, size/XL, approved

#2957 Update examples to use the Dynamic port policy instead of Static
  examples/crd-client/Makefile
  examples/crd-client/create-gs.yaml
  examples/crd-client/main.go
  examples/gameserver.yaml
Labels: lgtm, size/S, approved

#2956 Fix the broken example yaml
  examples/fleet.yaml
  examples/gameserverallocation.yaml
Labels: lgtm, size/XS

#2940 Add types for nodejs sdk
  sdks/nodejs/src/agonesSDK.d.ts
  sdks/nodejs/src/alpha.d.ts
  sdks/nodejs/src/index.d.ts
Labels: lgtm, size/L, approved

#2959 Do not install Consul in e2e test cluster
  build/includes/google-cloud.mk
  build/terraform/e2e/gke-standard/module.tf
Labels: size/M

#2949 Move the e2e test steps to a child Cloud Build
  .gcloudignore
  cloudbuild.yaml
  e2e-test-cloudbuild.yaml
Labels: size/L

#2946 Arbitrary Counts and Lists Feature/CRD
  build/Makefile
  examples/gameserver.yaml
  install/helm/agones/defaultfeaturegates.yaml
  install/helm/agones/templates/crds/_gameserverspecschema.yaml
  install/helm/agones/templates/crds/_gameserverstatus.yaml
  install/helm/agones/templates/crds/fleet.yaml
  install/helm/agones/templates/crds/gameserver.yaml
  install/helm/agones/templates/crds/gameserverset.yaml
  pkg/util/runtime/features.go
Labels: lgtm, size/L

#2955 Allow occasional flakes in SDK conformance tests
  build/includes/sdk.mk
Labels: size/XS, approved

#2950 Graduate `SafeToEvict` to Beta
  build/Makefile
  cloudbuild.yaml
  install/helm/agones/defaultfeaturegates.yaml
  install/yaml/install.yaml
  pkg/apis/agones/v1/gameserver_test.go
  pkg/util/runtime/features.go
  site/content/en/docs/Advanced/controlling-disruption.md
  site/content/en/docs/Advanced/scheduling-and-autoscaling.md
  site/content/en/docs/Guides/feature-stages.md
Labels: lgtm, size/L, approved

#2945 Run `build-release` within build image
  build/includes/release.mk
Labels: size/XS, approved

#2962 Create e2e test clusters with multiple k8s versions
  build/terraform/e2e/module.tf
Labels: size/S

#2963 Update the apiserver request dashboard
  build/grafana/dashboard-apiserver-requests.yaml
Labels: lgtm, size/XL, approved

#2967 Pre-Alpha Feature Gate: FleetAllocationOverflow
  build/Makefile
  cloudbuild.yaml
  install/helm/agones/defaultfeaturegates.yaml
  pkg/util/runtime/features.go
Labels: kind/feature, lgtm, size/S, approved

#2961 Add documentation for SplitControllerAndExtensions
  site/content/en/docs/Advanced/high-availability-agones.md
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: lgtm, size/L, approved

#2968 Run e2e tests on multiple clusters with different versions
  cloudbuild.yaml
  test/e2e/gameserver_test.go
Labels: size/M, lgtm, approved

#2969 Create e2e test clusters in different regions to mitigate quota limit issue
  build/terraform/e2e/gke-autopilot/module.tf
  build/terraform/e2e/gke-standard/module.tf
  build/terraform/e2e/module.tf
  install/terraform/modules/gke/cluster.tf
Labels: size/M, approved

#2971 Fix for `make gen-crd-client`
  pkg/apis/agones/v1/apihooksfake.go
  pkg/apis/agones/v1/fleet_test.go
  pkg/apis/agones/v1/gameserver_test.go
  pkg/apis/agones/v1/gameserverset_test.go
  pkg/gameservers/controller_test.go
  pkg/gameservers/gameservers_test.go
  pkg/gameservers/health_test.go
  pkg/gameservers/migration_test.go
  pkg/gameservers/missing_test.go
  pkg/testing/apihooks.go
  test/e2e/gameserver_test.go
Labels: kind/bug, area/build-tools, lgtm, size/L, approved

#2965 Updates counters lists schema status CRDs for gameservers fleets
  examples/gameserver.yaml
  install/helm/agones/templates/crds/_gameserverspecschema.yaml
  install/helm/agones/templates/crds/_gameserverstatus.yaml
  install/helm/agones/templates/crds/fleet.yaml
  install/helm/agones/templates/crds/gameserverset.yaml
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/agones/v1/gameserver_test.go
  pkg/apis/agones/v1/zz_generated.deepcopy.go
  site/content/en/docs/Reference/agones_crd_api_reference.html
Labels: kind/feature, area/user-experience, size/XXL, lgtm

#2974 More "packed" behavior when reducing GameServerSet replicas.
  pkg/gameserversets/gameserversets.go
  pkg/gameserversets/gameserversets_test.go
Labels: size/S

#2964 Add error callback to testSDKClient
  test/sdk/nodejs/testSDKClient.js
Labels: lgtm, size/XS, approved

#2984 Fix label_values for Google Managed Prometheus
  build/grafana/dashboard-autoscalers.yaml
  build/grafana/dashboard-gameservers.yaml
Labels: lgtm, size/S

#2986 Make up{} work with Google Managed Prometheus
  build/grafana/dashboard-status.yaml
Labels: lgtm, size/XS

#2977 Fix HandleWatchMessage
  sdks/unreal/Agones/Source/Agones/Private/AgonesComponent.cpp
  sdks/unreal/Agones/Source/Agones/Public/AgonesComponent.h
Labels: size/S, approved

#2988 Added back metrics support for extensions
  cmd/extensions/main.go
  install/helm/agones/templates/extensions-deployment.yaml
Labels: lgtm, size/L

#2982 Make Alpha & Beta CRD declaration consistent.
  install/helm/agones/templates/crds/_gameserverspecschema.yaml
  install/helm/agones/templates/crds/_gameserverstatus.yaml
  install/helm/agones/templates/crds/gameserver.yaml
  install/yaml/install.yaml
  pkg/apis/agones/v1/apihooks.go
  pkg/apis/agones/v1/apihooksfake.go
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/agones/v1/gameserver_test.go
  pkg/apis/agones/v1/zz_generated.deepcopy.go
  pkg/cloudproduct/generic/generic.go
  pkg/cloudproduct/generic/generic_test.go
  pkg/cloudproduct/gke/gke.go
  pkg/cloudproduct/gke/gke_test.go
  pkg/testing/apihooks.go
  site/content/en/docs/Reference/agones_crd_api_reference.html
Labels: kind/cleanup, size/L, approved

#2993 Add Extensions Resource Dashboard
  build/grafana/dashboard-extensions-usage.yaml
Labels: lgtm, size/XL, approved

#2980 Kubernetes Update template, Release template, and site content change for multiple k8s version support
  .github/ISSUE_TEMPLATE/kubernetes_update.md
  CONTRIBUTING.md
  docs/governance/templates/release_issue.md
  site/config.toml
  site/content/en/docs/Advanced/limiting-resources.md
  site/content/en/docs/FAQ/_index.md
  site/content/en/docs/Installation/Creating Cluster/aks.md
  site/content/en/docs/Installation/Creating Cluster/eks.md
  site/content/en/docs/Installation/Creating Cluster/gke.md
  site/content/en/docs/Installation/Creating Cluster/minikube.md
  site/content/en/docs/Installation/_index.md
  site/content/en/docs/Reference/fleet.md
  site/content/en/docs/Reference/fleetautoscaler.md
  site/content/en/docs/Reference/gameserver.md
  site/layouts/shortcodes/aks-example-cluster-version.html
  site/layouts/shortcodes/aks-k8s-minor-version.html
  site/layouts/shortcodes/eks-example-cluster-version.html
  site/layouts/shortcodes/gke-example-cluster-version.html
  site/layouts/shortcodes/k8s-api-version.html
  site/layouts/shortcodes/k8s-version.html
  site/layouts/shortcodes/minikube-example-cluster-version.html
  site/layouts/shortcodes/minikube-k8s-minor-version.html
Labels: lgtm, size/L, approved

#2979 CRDs for AllocationOverflow
  install/helm/agones/templates/crds/fleet.yaml
  install/helm/agones/templates/crds/gameserverset.yaml
  install/yaml/install.yaml
  pkg/apis/agones/v1/common.go
  pkg/apis/agones/v1/common_test.go
  pkg/apis/agones/v1/fleet.go
  pkg/apis/agones/v1/fleet_test.go
  pkg/apis/agones/v1/gameserverset.go
  pkg/apis/agones/v1/zz_generated.deepcopy.go
  site/content/en/docs/Reference/agones_crd_api_reference.html
Labels: kind/feature, size/XL, approved

#2989 Test Example Images Exist - Release Automation
  build/includes/examples.mk
  build/release/cloudbuild.yaml
  docs/governance/templates/release_issue.md
Labels: kind/cleanup, size/M, approved

#2990 Add integration guide for Google Cloud Managed Service for Prometheus
  build/grafana-frontend.yaml
  build/prometheus-google-managed.yaml
  site/content/en/docs/Guides/metrics.md
Labels: size/L, approved

#2995 Flaky: TestControllerSyncGameServerCreatingState
  pkg/gameservers/controller_test.go
Labels: kind/cleanup, area/tests, size/S, approved

#2996 Add more time and logging to extensions test
  test/e2e/extensions/high_availability_test.go
Labels: size/M, lgtm

#2998 Add variable to go-client request dashboard
  build/grafana/dashboard-goclient-requests.yaml
Labels: size/L

#2983 Adds default values for Counters and Lists fields
  examples/gameserver.yaml
  install/helm/agones/templates/crds/_gameserverspecschema.yaml
  install/helm/agones/templates/crds/_gameserverstatus.yaml
  install/helm/agones/templates/crds/fleet.yaml
  install/helm/agones/templates/crds/gameserver.yaml
  install/helm/agones/templates/crds/gameserverset.yaml
  install/yaml/install.yaml
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/agones/v1/gameserver_test.go
  pkg/apis/agones/v1/zz_generated.deepcopy.go
  site/content/en/docs/Reference/agones_crd_api_reference.html
Labels: kind/feature, area/user-experience, size/L, approved

#3000 Add extensions status dash and dash name change
  build/grafana/dashboard-extensions-status.yaml
  build/grafana/dashboard-extensions-usage.yaml
Labels: size/XL
