Repository googleforgames/agones, pull requests merged in 2023-05, with the labels that each got.

#3132 Move make release-deploy-site into pre-build-release
  build/includes/website.mk
  build/release/pre_cloudbuild.yaml
  docs/governance/templates/release_issue.md
Labels: kind/feature, lgtm, size/S, approved

#3129 Quilkin added in third-party-content/examples
  site/content/en/docs/Third Party Content/examples.md
Labels: good first issue, lgtm, size/XS, approved

#3136 Docs: Fix some bugs in the feature gate page
  site/content/en/docs/Guides/feature-stages.md
Labels: kind/bug, kind/documentation, lgtm, size/S, approved

#3137 Upgrade to Golang version 1.20.4
  build/build-image/Dockerfile
  build/build-sdk-images/go/Dockerfile
  build/build-sdk-images/restapi/Dockerfile
  build/e2e-image/Dockerfile
  build/report/cloudbuild.yaml
  build/scripts/previousversion/go.mod
  examples/allocation-endpoint/Makefile
  examples/allocation-endpoint/client/go.mod
  examples/allocation-endpoint/client/go.sum
  examples/allocation-endpoint/server/Dockerfile
  examples/allocation-endpoint/server/go.mod
  examples/autoscaler-webhook/Dockerfile
  examples/autoscaler-webhook/Makefile
  examples/crd-client/Dockerfile
  examples/crd-client/Makefile
  examples/simple-game-server/Dockerfile
  examples/simple-game-server/Makefile
  examples/simple-game-server/go.mod
  examples/supertuxkart/Dockerfile
  examples/supertuxkart/Makefile
  examples/supertuxkart/go.mod
  examples/xonotic/Dockerfile
  examples/xonotic/Dockerfile.windows
  examples/xonotic/Makefile
  examples/xonotic/go.mod
  examples/xonotic/go.sum
  go.mod
  site/go.mod
  test/terraform/go.mod
  test/terraform/go.sum
Labels: size/XXL, lgtm

#3138 Bump example image versions
  build/Makefile
  build/includes/examples.mk
  build/includes/sdk.mk
  examples/allocation-endpoint/terraform/variable.tf
  examples/autoscaler-webhook/autoscaler-service-tls.yaml
  examples/autoscaler-webhook/autoscaler-service.yaml
  examples/crd-client/create-gs.yaml
  examples/fleet.yaml
  examples/gameserver.yaml
  examples/simple-game-server/dev-gameserver.yaml
  examples/simple-game-server/fleet-distributed.yaml
  examples/simple-game-server/fleet-tcp.yaml
  examples/simple-game-server/fleet.yaml
  examples/simple-game-server/gameserver-passthrough.yaml
  examples/simple-game-server/gameserver-windows.yaml
  examples/simple-game-server/gameserver.yaml
  examples/supertuxkart/fleet.yaml
  examples/supertuxkart/gameserver.yaml
  examples/xonotic/fleet.yaml
  install/helm/agones/templates/tests/test-runner.yaml
  pkg/util/webhooks/webhooks_test.go
  site/config.toml
  test/e2e/fleetautoscaler_test.go
  test/e2e/framework/framework.go
  test/e2e/gameserver_test.go
  test/load/allocation/fleet.yaml
  test/load/allocation/scenario-fleet.yaml
Labels: lgtm, size/L

#3139 Fix an invalid xonotic-example image path
  examples/xonotic/gameserver.yaml
Labels: lgtm, size/XS

#3125 Added labels to the agones.allocator
  install/helm/agones/templates/service/allocation.yaml
  install/helm/agones/values.yaml
  site/content/en/docs/Guides/metrics.md
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: lgtm, size/S, approved

#3105 Add a more graceful termination to Allocator
  build/Makefile
  cmd/allocator/main.go
  install/helm/agones/templates/service/allocation.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  pkg/util/signals/signals.go
  test/e2e/allocator/main_test.go
  test/e2e/allocator/pod_termination_test.go
  test/e2e/allocator_test.go
  test/e2e/allochelper/helper_func.go
Labels: lgtm, size/XL

#3142 Add allocator readiness configurations doc
  build/README.md
  site/content/en/docs/Installation/Install Agones/helm.md
  test/e2e/allocator/pod_termination_test.go
Labels: lgtm, size/S

#3117 GameServerAllocation Actions for Counters and Lists
  pkg/apis/agones/v1/common.go
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/agones/v1/gameserver_test.go
  pkg/apis/allocation/v1/gameserverallocation.go
  pkg/apis/allocation/v1/gameserverallocation_test.go
  pkg/apis/allocation/v1/zz_generated.deepcopy.go
  pkg/gameserverallocations/allocator.go
  pkg/gameserverallocations/allocator_test.go
  site/content/en/docs/Reference/agones_crd_api_reference.html
Labels: size/XXL

#3146 Graduate SafeToEvict to GA
  cloudbuild.yaml
  install/helm/agones/defaultfeaturegates.yaml
  install/helm/agones/templates/pdb.yaml
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/agones/v1/gameserver_test.go
  pkg/cloudproduct/generic/generic.go
  pkg/cloudproduct/generic/generic_test.go
  pkg/cloudproduct/gke/gke.go
  pkg/cloudproduct/gke/gke_test.go
  pkg/gameservers/controller_test.go
  pkg/util/runtime/features.go
  site/content/en/docs/Advanced/controlling-disruption.md
  site/content/en/docs/Advanced/scheduling-and-autoscaling.md
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Reference/agones_crd_api_reference.html
Labels: size/XXL

#3147 Update stale.yaml
  .github/workflows/stale.yaml
Labels: lgtm, size/XS

#3158 ignore twitter link in tests
  site/htmltest.yaml
Labels: lgtm, size/XS

#3154 Move ResetMetricsOnDelete to Beta
  build/Makefile
  cloudbuild.yaml
  install/helm/agones/defaultfeaturegates.yaml
  pkg/util/runtime/features.go
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Guides/metrics.md
Labels: size/S

#3149 [Release Automation] Update Helm/SDK/Install Packages Version Numbers
  build/scripts/version-update/main.go
  docs/governance/templates/release_issue.md
Labels: size/L

#3157 sdkserver: When waitForConnection fails, container should restart quickly
  cmd/sdk-server/main.go
  pkg/sdkserver/sdkserver.go
  pkg/sdkserver/sdkserver_test.go
Labels: size/L

#3150 Allocation.proto Updates for Counts and Lists
  pkg/allocation/converters/converter.go
  pkg/allocation/converters/converter_test.go
  pkg/allocation/go/allocation.pb.go
  pkg/allocation/go/allocation.swagger.json
  proto/allocation/allocation.proto
Labels: size/XXL

#3160 Move back to FailureThreshold failures of /gshealthz
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
Labels: size/S

#3111 Add parametric host address
  sdks/rust/Cargo.toml
  sdks/rust/src/sdk.rs
Labels: size/M, lgtm

#3153 Update values yaml file for `SplitControllerAndExtensions`
  install/helm/agones/values.yaml
Labels: size/M, lgtm, approved

#3162 Always pull development images when running `make install`.
  build/Makefile
Labels: size/XS, approved

#3163 Add fix for one issue with TestFleetRecreateGameServers test
  test/e2e/fleet_test.go
Labels: lgtm, size/S

#3152 Add Cloud Best Practices guide, add guide on Release Channels
  site/content/en/docs/Advanced/controlling-disruption.md
  site/content/en/docs/Guides/Best Practices/_index.md
  site/content/en/docs/Guides/Best Practices/gke.md
  site/content/en/docs/Installation/Creating Cluster/gke.md
  site/content/en/docs/Installation/_index.md
Labels: lgtm, size/L, approved

#3164 Suppress full e2e logs so the per-configuration links are obvious
  cloudbuild.yaml
Labels: lgtm, size/XS

#3167 Strengthen the warning about reusing certificates in the yaml installation.
  site/content/en/docs/Installation/Install Agones/_index.md
  site/content/en/docs/Installation/Install Agones/yaml.md
Labels: kind/documentation, size/M, approved

#3148 Allow setting a static NodePort for the ping service
  install/helm/agones/templates/ping.yaml
  install/helm/agones/values.yaml
Labels: size/XS

#3165 Promote SplitControllerAndExtensions to beta
  build/Makefile
  cloudbuild.yaml
  install/helm/agones/defaultfeaturegates.yaml
  install/yaml/install.yaml
  pkg/util/runtime/features.go
  site/content/en/docs/Advanced/high-availability-agones.md
  site/content/en/docs/Guides/feature-stages.md
Labels: lgtm, size/L, approved

#3173 Add docs for #3148
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: lgtm, size/S, approved

#3179 Agones Release v1.32.0
  CHANGELOG.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/unity/package.json
  site/config.toml
  site/content/en/blog/releases/1.31.0.md
  site/content/en/blog/releases/1.32.0.md
  site/content/en/docs/Advanced/controlling-disruption.md
  site/content/en/docs/Advanced/high-availability-agones.md
  site/content/en/docs/Advanced/scheduling-and-autoscaling.md
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Guides/fleet-updates.md
  site/content/en/docs/Installation/Install Agones/helm.md
  site/content/en/docs/Installation/_index.md
  site/layouts/partials/navbar.html
Labels: kind/release, lgtm, size/L, approved

#3181 Preparation for next release v1.33.0
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/unity/package.json
  site/content/en/blog/releases/1.32.0.md
Labels: kind/release, size/M, lgtm, approved

#3182 Run e2e test on regional standard clusters
  cloudbuild.yaml
Labels: lgtm, size/XS, approved

#3174 Cloud Build config to trigger a build if no build is running
  build/always/always-be-building.yaml
Labels: size/M

#3186 Remove zonal test clusters, and create regional clusters with release channel
  build/terraform/e2e/gke-standard/module.tf
  build/terraform/e2e/module.tf
Labels: lgtm, size/S, approved

#3191 Update GKE installation instructions now that `SplitControllerAndExtensions` has been enabled by default.
  site/content/en/docs/Installation/Creating Cluster/gke.md
Labels: kind/documentation, size/M, lgtm, approved

#3187 build: add ltsc2022 target for windows builds
  build/Makefile
  examples/simple-game-server/Makefile
Labels: lgtm, size/XS
