Repository googleforgames/agones, pull requests merged in 2023-12, with the labels that each got.

#3524 Adds Go Conformance Tests for Lists
  build/includes/sdk.mk
  pkg/sdkserver/localsdk.go
  pkg/sdkserver/localsdk_test.go
  test/sdk/go/sdk-client-test.go
Labels: kind/feature, size/M, lgtm

#3525 Remove warning on C# SDK Docs
  site/content/en/docs/Guides/Client SDKs/csharp.md
Labels: kind/cleanup, lgtm, size/XS, approved

#3522 Ensure ci/save_cache and ci/restore_cache images don't get deleted by cleanup policy
  build/build-image/cache/Dockerfile-base
  build/build-image/cache/Dockerfile-restore
  build/build-image/cache/Dockerfile-save
  build/build-image/cache/README.md
  build/build-image/cache/checksum
  build/build-image/cache/cloudbuild.yaml
  build/build-image/cache/restore_cache
  build/build-image/cache/save_cache
Labels: lgtm, size/XL, approved, kind/other

#3520 Prevent Redundant Windows SDK Builds
  build/Makefile
Labels: kind/bug, do-not-merge/work-in-progress, size/XS

#3523 Move SplitControllerAndExtensions to Stable
  cloudbuild.yaml
  cmd/controller/main.go
  install/helm/agones/defaultfeaturegates.yaml
  install/helm/agones/templates/controller.yaml
  install/helm/agones/templates/extensions-deployment.yaml
  install/helm/agones/templates/extensions-metrics-service.yaml
  install/helm/agones/templates/service.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  pkg/util/runtime/features.go
  site/content/en/docs/Advanced/high-availability-agones.md
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Installation/Creating Cluster/gke.md
  site/content/en/docs/Installation/Install Agones/helm.md
  test/e2e/controller/crash_test.go
  test/e2e/extensions/high_availability_test.go
Labels: kind/feature, size/L

#3532 GH Action: Size label for PRs
  .github/workflows/labeler.yml
Labels: kind/cleanup, area/build-tools

#3534 Flake: TestControllerWatchGameServers
  pkg/gameserversets/controller_test.go
Labels: kind/cleanup, area/tests, size/XS

#3387 GKE Autopilot: Add support for Extended Duration pods
  install/helm/agones/defaultfeaturegates.yaml
  pkg/cloudproduct/eviction/eviction.go
  pkg/cloudproduct/eviction/eviction_test.go
  pkg/cloudproduct/generic/generic.go
  pkg/cloudproduct/generic/generic_test.go
  pkg/cloudproduct/gke/gke.go
  pkg/cloudproduct/gke/gke_test.go
  pkg/util/runtime/features.go
Labels: size/M, size/L, kind/other

#3528 Counter and List Aggregate Fleet Metrics
  pkg/metrics/controller.go
  pkg/metrics/controller_metrics.go
  pkg/metrics/controller_test.go
  pkg/metrics/util.go
Labels: kind/feature, size/M, do-not-merge/work-in-progress, size/S

#3536 Go CRD Comment Updates for Counters and Lists
  pkg/apis/agones/v1/common.go
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/allocation/v1/gameserverallocation.go
  site/content/en/docs/Reference/agones_crd_api_reference.html
Labels: kind/documentation, size/XL

#3537 CountsAndLists: SDK Reference
  site/content/en/docs/Guides/Client SDKs/_index.md
Labels: size/S, kind/other

#3531 Simple Game Server Example: Upgrade Docker to 24.0.6
  examples/simple-game-server/Makefile
  examples/simple-game-server/cloudbuild.yaml
  examples/simple-game-server/dev-gameserver.yaml
  examples/simple-game-server/fleet-distributed.yaml
  examples/simple-game-server/fleet-tcp.yaml
  examples/simple-game-server/fleet.yaml
  examples/simple-game-server/gameserver-passthrough.yaml
  examples/simple-game-server/gameserver-windows.yaml
  examples/simple-game-server/gameserver.yaml
Labels: do-not-merge/work-in-progress, size/S, kind/other

#3542 CI: Fix 404 on CI link testing
  site/config.toml
  site/htmltest.yaml
Labels: kind/cleanup, size/S

#3538 Xonotic Example: Docker 24.0.6
  examples/xonotic/Makefile
  examples/xonotic/cloudbuild.yaml
  examples/xonotic/fleet.yaml
  examples/xonotic/gameserver.yaml
  test/e2e/examples_test.go
Labels: kind/cleanup, size/S

#3543 Bumps simple-game-server to 0.23
  build/Makefile
  examples/crd-client/create-gs.yaml
  examples/fleet.yaml
  examples/gameserver.yaml
  install/helm/agones/templates/tests/test-runner.yaml
  pkg/util/webhooks/webhooks_test.go
  site/config.toml
  site/content/en/docs/Guides/fleet-updates.md
  test/e2e/framework/framework.go
  test/e2e/gameserver_test.go
  test/load/allocation/fleet.yaml
  test/load/allocation/performance-test-fleet-template.yaml
  test/load/allocation/scenario-fleet.yaml
Labels: size/S, kind/other

#3541 Tweaks to Client SDK reference
  site/content/en/docs/Guides/Client SDKs/_index.md
Labels: kind/documentation, size/M

#3544 Updates to Counter and List Alpha.proto Methods
  build/build-sdk-images/restapi/gen.sh
  pkg/sdk/alpha/alpha.pb.go
  pkg/sdk/alpha/alpha.pb.gw.go
  proto/sdk/alpha/alpha.proto
  sdks/csharp/proto/sdk/alpha/alpha.proto
  sdks/rust/proto/sdk/alpha/alpha.proto
  sdks/swagger/alpha.swagger.json
  test/sdk/restapi/alpha/swagger/api_sdk.go
  test/sdk/restapi/alpha/swagger/model_lists_nameadd_value_body.go
  test/sdk/restapi/alpha/swagger/model_lists_nameremove_value_body.go
Labels: kind/cleanup, size/M

#3545 Docs: SDK implementation matrixes
  site/content/en/docs/Guides/Client SDKs/go.md
  site/content/en/docs/Guides/Client SDKs/rust.md
  site/content/en/docs/Guides/Client SDKs/unity.md
  site/content/en/docs/Guides/Client SDKs/unreal.md
Labels: kind/documentation, size/S

#3468 Disable deletion protection for Autopilot test clusters
  build/terraform/e2e/gke-autopilot/module.tf
  build/terraform/e2e/gke-standard/module.tf
  install/terraform/modules/gke-autopilot/cluster.tf
  install/terraform/modules/gke-autopilot/variables.tf
  install/terraform/modules/gke/cluster.tf
  install/terraform/modules/gke/variables.tf
Labels: kind/cleanup, size/M, size/S, kind/other

#3546 Adds Counters and Lists REST API Conformance Tests
  build/includes/sdk.mk
  pkg/sdkserver/localsdk.go
  pkg/sdkserver/localsdk_test.go
  pkg/sdkserver/sdkserver.go
  pkg/sdkserver/sdkserver_test.go
  test/sdk/restapi/http-api-test.go
Labels: kind/feature, size/M

#3552 CountsAndLists: Yaml Examples And References
  examples/counterfleetautoscaler.yaml
  examples/gameserver.yaml
  examples/gameserverallocation.yaml
  examples/listfleetautoscaler.yaml
  site/content/en/docs/Reference/fleet.md
  site/content/en/docs/Reference/fleetautoscaler.md
  site/content/en/docs/Reference/gameserver.md
  site/content/en/docs/Reference/gameserverallocation.md
Labels: kind/feature, size/L

#3549 Delete the performance test fleet and fleetautoscaler after each test
  build/performance-test.sh
Labels: kind/bug, size/XS

#3548 SDK Matrices for NodeJS, C#, CPP, REST
  site/content/en/docs/Guides/Client SDKs/cpp.md
  site/content/en/docs/Guides/Client SDKs/csharp.md
  site/content/en/docs/Guides/Client SDKs/nodejs.md
  site/content/en/docs/Guides/Client SDKs/rest.md
Labels: kind/feature, size/M, size/S

#3557 Release v1.37.0
  CHANGELOG.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/rust/Cargo.toml
  sdks/unity/package.json
  site/config.toml
  site/content/en/blog/releases/1.36.0.md
  site/content/en/blog/releases/1.37.0.md
  site/content/en/docs/Advanced/high-availability-agones.md
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Guides/fleet-updates.md
  site/content/en/docs/Guides/metrics.md
  site/content/en/docs/Installation/Creating Cluster/gke.md
  site/content/en/docs/Installation/Install Agones/helm.md
  site/content/en/docs/Installation/_index.md
  site/content/en/docs/Reference/fleet.md
  site/content/en/docs/Reference/fleetautoscaler.md
  site/content/en/docs/Reference/gameserver.md
  site/content/en/docs/Reference/gameserverallocation.md
  site/layouts/partials/navbar.html
Labels: kind/release, size/L

#3558 Prep for release v1.38.0
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/rust/Cargo.toml
  sdks/unity/package.json
Labels: kind/release, size/S

#3559 Increase performance test cluster size
  build/terraform/performance/module.tf
Labels: kind/hotfix, size/XS
