Repository googleforgames/agones, pull requests merged in 2023-07, with the labels that each got.

#3247 Release v1.33.0
  CHANGELOG.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/unity/package.json
  site/config.toml
  site/content/en/blog/releases/1.32.0.md
  site/content/en/blog/releases/1.33.0.md
  site/content/en/docs/Installation/Install Agones/helm.md
  site/content/en/docs/Installation/_index.md
  site/layouts/partials/navbar.html
Labels: kind/release, size/L, approved

#3248 Preparation for 1.34.0
  build/Makefile
  docs/governance/templates/release_issue.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/unity/package.json
Labels: kind/release, size/M, lgtm, approved

#3241 fix: Label PR Warning
  .github/workflows/label-pr.yml
Labels: lgtm, size/XS, kind/other

#3250 Put e2e Cloud Build logs in public bucket
  ci/e2e-test-cloudbuild.yaml
Labels: kind/cleanup, lgtm, size/XS, approved

#3235 Graduate CustomFasSyncInterval To Stable
  cloudbuild.yaml
  examples/fleetautoscaler.yaml
  install/helm/agones/defaultfeaturegates.yaml
  pkg/apis/autoscaling/v1/fleetautoscaler.go
  pkg/apis/autoscaling/v1/fleetautoscaler_test.go
  pkg/fleetautoscalers/controller.go
  pkg/fleetautoscalers/controller_test.go
  pkg/util/runtime/features.go
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Guides/troubleshooting.md
  site/content/en/docs/Reference/agones_crd_api_reference.html
  site/content/en/docs/Reference/fleetautoscaler.md
  test/e2e/fleetautoscaler_test.go
Labels: kind/feature, lgtm, size/L

#3239 refactor: Throwing error messages with field.
  pkg/apis/agones/v1/common.go
  pkg/apis/agones/v1/common_test.go
  pkg/apis/agones/v1/fleet.go
  pkg/apis/agones/v1/fleet_test.go
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/agones/v1/gameserver_test.go
  pkg/apis/agones/v1/gameserverset.go
  pkg/apis/agones/v1/gameserverset_test.go
  pkg/fleets/controller.go
  pkg/gameservers/controller.go
  pkg/gameserversets/controller.go
  pkg/gameserversets/controller_test.go
  test/e2e/fleet_test.go
  test/e2e/gameserver_test.go
  test/e2e/gameserverallocation_test.go
Labels: kind/breaking, size/XL, approved

#3242 fix: Enabling SplitControllerAndExtensions leads to incomplete metrics availability
  install/helm/agones/templates/controller-metrics-service.yaml
  install/helm/agones/templates/extensions-metrics-service.yaml
  install/helm/agones/templates/service-monitor.yaml
  install/yaml/install.yaml
Labels: kind/bug, size/L, approved

#3256 cleanup: Add agones-extensions Image
  cloudbuild.yaml
Labels: kind/cleanup, lgtm, size/XS, approved

#3255 refactor: apihook ValidateGameServerSpec and ValidateScheduling use field.ErrorList
  cmd/controller/main.go
  pkg/apis/agones/v1/apihooks.go
  pkg/apis/agones/v1/apihooksfake.go
  pkg/apis/agones/v1/fleet.go
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/agones/v1/gameserver_test.go
  pkg/apis/agones/v1/gameserverset.go
  pkg/cloudproduct/generic/generic.go
  pkg/cloudproduct/gke/gke.go
  pkg/cloudproduct/gke/gke_test.go
  pkg/testing/apihooks.go
  test/e2e/fleet_test.go
  test/e2e/gameserver_test.go
Labels: kind/breaking, size/L, approved

#3260 Race Flake in TestControllerSyncFleetAutoscaler()
  pkg/fleetautoscalers/controller_test.go
Labels: kind/bug, area/tests, lgtm, size/XS, approved

#3258 Release Checklist Cleanup
  build/scripts/sdk-update-version/main.go
  build/scripts/site-config-update-version/main.go
  docs/governance/templates/release_issue.md
Labels: kind/documentation, size/M, approved

#3257 Cleanup Labeler
  .github/pull_request_template.md
  .github/workflows/label-pr.yml
Labels: kind/cleanup, size/XS, approved

#3259 refactor(allocation): Reimplement the Validate method using "field.ErrorList"
  examples/crd-client/main.go
  pkg/apis/allocation/v1/gameserverallocation.go
  pkg/apis/allocation/v1/gameserverallocation_test.go
  pkg/gameserverallocations/allocator.go
  pkg/gameserverallocations/allocator_test.go
  pkg/gameserverallocations/find_test.go
  test/e2e/gameserverallocation_test.go
Labels: kind/breaking, size/XL, approved

#3265 fix: info to debug level
  pkg/gameservers/controller.go
Labels: kind/cleanup, lgtm, size/XS, kind/other

#3263 refactor: Switch Helm Cleanup job to use bitnami/kubectl image
  install/helm/agones/templates/hooks/pre_delete_hook.yaml
Labels: kind/cleanup, size/XS, kind/other

#3253 Use maintenance exclusion to prevent auto-upgrade, add 1.27 test clusters
  build/terraform/e2e/module.tf
  install/terraform/modules/gke-autopilot/cluster.tf
  install/terraform/modules/gke/cluster.tf
Labels: kind/bug, size/M

#3267 Remove e2e cluster with oldest supported K8s version
  .github/ISSUE_TEMPLATE/kubernetes_update.md
  build/terraform/e2e/module.tf
Labels: kind/cleanup, lgtm, size/XS

#3264 Flake: TestControllerAllocator
  pkg/cloudproduct/gke/gke_test.go
  pkg/gameserverallocations/controller_test.go
Labels: kind/cleanup, area/tests, size/S, approved

#3270 Alpine ➡️ Distroless as Agones base image
  cmd/allocator/Dockerfile
  cmd/controller/Dockerfile
  cmd/extensions/Dockerfile
  cmd/ping/Dockerfile
  cmd/sdk-server/Dockerfile
  install/helm/agones/templates/controller.yaml
  install/helm/agones/templates/extensions-deployment.yaml
  install/yaml/install.yaml
Labels: kind/feature, area/security, size/M, lgtm, approved

#3272 refactor: FleetAutoscaler Validate use field.ErrorList
  pkg/apis/autoscaling/v1/fleetautoscaler.go
  pkg/apis/autoscaling/v1/fleetautoscaler_test.go
  pkg/fleetautoscalers/controller.go
Labels: kind/breaking, lgtm, size/L, approved, kind/other

#3268 Upgrade Version of Rust
  build/build-sdk-images/rust/Dockerfile
Labels: kind/cleanup, size/XS, approved

#3275 Some copy edits to the most recent release blog post.
  site/content/en/blog/releases/1.33.0.md
Labels: kind/cleanup, lgtm, size/S, approved

#3269 Fix Dependabot Vulnerability
  sdks/nodejs/package-lock.json
Labels: kind/cleanup, size/M, approved

#3278 Upgrade site to Google Analytics 4
  site/config.toml
  site/layouts/partials/head.html
  site/themes/docsy/layouts/partials/head.html
Labels: kind/cleanup, area/site, size/XS, approved

#3211 Adds Counts and Lists AutoScale Policies
  cmd/controller/main.go
  examples/fleet.yaml
  install/helm/agones/templates/crds/fleet.yaml
  install/helm/agones/templates/crds/gameserverset.yaml
  install/yaml/install.yaml
  pkg/allocation/converters/converter.go
  pkg/allocation/converters/converter_test.go
  pkg/allocation/go/allocation.pb.go
  pkg/allocation/go/allocation.swagger.json
  pkg/allocation/go/allocation_grpc.pb.go
  pkg/apis/agones/v1/common.go
  pkg/apis/agones/v1/fleet.go
  pkg/apis/agones/v1/fleet_test.go
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/agones/v1/gameserverset.go
  pkg/apis/agones/v1/zz_generated.deepcopy.go
  pkg/apis/allocation/v1/gameserverallocation.go
  pkg/apis/allocation/v1/gameserverallocation_test.go
  pkg/apis/allocation/v1/zz_generated.deepcopy.go
  pkg/apis/autoscaling/v1/fleetautoscaler.go
  pkg/fleetautoscalers/controller.go
  pkg/fleetautoscalers/controller_test.go
  pkg/fleetautoscalers/fleetautoscalers.go
  pkg/fleetautoscalers/fleetautoscalers_test.go
  pkg/fleets/controller.go
  pkg/fleets/controller_test.go
  pkg/gameserverallocations/allocation_cache.go
  pkg/gameserverallocations/allocation_cache_test.go
  pkg/gameserversets/allocation_overflow.go
  pkg/gameserversets/controller.go
  pkg/gameserversets/controller_test.go
  pkg/gameserversets/gameserversets.go
  pkg/gameserversets/gameserversets_test.go
  pkg/sdk/alpha/alpha.pb.go
  pkg/sdk/alpha/alpha_grpc.pb.go
  pkg/sdk/beta/beta.pb.go
  pkg/sdk/beta/beta_grpc.pb.go
  pkg/sdk/sdk.pb.go
  pkg/sdk/sdk_grpc.pb.go
  proto/allocation/allocation.proto
  site/content/en/docs/Reference/agones_crd_api_reference.html
Labels: kind/feature, size/XXL, lgtm, approved

#3280 Flaky: TestAllocatorAllocatePriority
  pkg/gameserverallocations/allocator_test.go
Labels: kind/cleanup, area/tests, size/S, approved

#3279 Move simple-game-server to Distroless base
  build/Makefile
  examples/crd-client/create-gs.yaml
  examples/fleet.yaml
  examples/gameserver.yaml
  examples/simple-game-server/Dockerfile
  examples/simple-game-server/Makefile
  examples/simple-game-server/dev-gameserver.yaml
  examples/simple-game-server/fleet-distributed.yaml
  examples/simple-game-server/fleet-tcp.yaml
  examples/simple-game-server/fleet.yaml
  examples/simple-game-server/gameserver-passthrough.yaml
  examples/simple-game-server/gameserver-windows.yaml
  examples/simple-game-server/gameserver.yaml
  examples/simple-game-server/go.mod
  examples/simple-game-server/go.sum
  install/helm/agones/templates/tests/test-runner.yaml
  pkg/util/webhooks/webhooks_test.go
  site/config.toml
  test/e2e/framework/framework.go
  test/e2e/gameserver_test.go
  test/load/allocation/fleet.yaml
  test/load/allocation/scenario-fleet.yaml
Labels: kind/cleanup, area/build-tools, area/examples, size/M, lgtm, approved

#3283 TestAllocatorAllocateOnGameServerUpdateError
  pkg/gameserverallocations/allocator_test.go
Labels: kind/cleanup, area/tests, size/S, approved

#3276 Switching autoscaler-webhook to utilize distroless as base Image
  examples/autoscaler-webhook/Dockerfile
  examples/autoscaler-webhook/Makefile
  examples/autoscaler-webhook/autoscaler-service-tls.yaml
  examples/autoscaler-webhook/autoscaler-service.yaml
  examples/autoscaler-webhook/go.mod
  examples/autoscaler-webhook/go.sum
  test/e2e/fleetautoscaler_test.go
Labels: kind/cleanup, size/L, approved

#3271 SDK WatchGameServer logs error on shutdown
  sdks/go/sdk.go
Labels: kind/bug, lgtm, size/S

#3277 Distroless base image for crd-client
  examples/crd-client/Dockerfile
  examples/crd-client/Makefile
  examples/crd-client/create-gs.yaml
  examples/crd-client/go.mod
  examples/crd-client/go.sum
  install/helm/agones/templates/tests/test-runner.yaml
Labels: kind/cleanup, size/XL, approved

#3252 More Local Dev Server Support
  cmd/sdk-server/main.go
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  site/content/en/docs/Advanced/out-of-cluster-dev-server.md
  site/content/en/docs/Guides/Client SDKs/local.md
  site/content/en/docs/Guides/local-game-server.md
  site/content/en/docs/Integration Patterns/allocation-from-fleet.md
  site/content/en/docs/Reference/gameserverallocation.md
  test/e2e/gameserver_test.go
Labels: kind/feature, size/L, approved

#3282 GameServerAllocation to sort Priorities by Allocated Capacity
  go.mod
  go.sum
  pkg/apis/allocation/v1/gameserverallocation.go
  pkg/apis/allocation/v1/gameserverallocation_test.go
  pkg/gameserverallocations/allocation_cache.go
  pkg/gameserverallocations/allocation_cache_test.go
  pkg/gameserverallocations/allocator.go
  pkg/gameserverallocations/allocator_test.go
  site/content/en/docs/Reference/agones_crd_api_reference.html
  vendor/github.com/mitchellh/hashstructure/v2/LICENSE
  vendor/github.com/mitchellh/hashstructure/v2/README.md
  vendor/github.com/mitchellh/hashstructure/v2/errors.go
  vendor/github.com/mitchellh/hashstructure/v2/hashstructure.go
  vendor/github.com/mitchellh/hashstructure/v2/include.go
  vendor/modules.txt
Labels: kind/feature, size/XXL, approved

#3295 Flake TestAllocatorAllocateOnGameServerUpdateError
  pkg/gameserverallocations/allocator_test.go
Labels: kind/cleanup, lgtm, size/S, approved

#3293 Updates for Terraform
  build/build-image/Dockerfile
  install/terraform/modules/gke/cluster.tf
Labels: kind/cleanup, area/operations, size/M, approved
