Repository googleforgames/agones, pull requests merged in 2023-09, with the labels that each got.

#3334 Update release checklist
  build/Makefile
  build/install-release.sh
  docs/governance/templates/release_issue.md
Labels: kind/cleanup, size/M, approved

#3359 Add Octops Fleet Garbage Collector project to third party docs
  site/content/en/docs/Third Party Content/libraries-tools.md
Labels: kind/documentation, size/XS, approved

#3360 Updates to GKE Terraform docs
  site/content/en/docs/Installation/Terraform/gke.md
Labels: kind/documentation, size/XS, approved

#3364 Fix unaccurate progress description of HA Agones
  site/content/en/docs/Advanced/high-availability-agones.md
Labels: kind/documentation, size/XS, approved

#3355 Bump GitHub workflow actions to latest versions
  .github/workflows/close.yaml
  .github/workflows/label-pr.yml
  .github/workflows/obsolete.yaml
  .github/workflows/stale.yaml
Labels: lgtm, size/S, kind/other

#3322 Implements GetCounter and UpdateCounter on the SDK Server
  pkg/sdk/alpha/alpha.pb.go
  pkg/sdk/alpha/alpha.pb.gw.go
  pkg/sdk/alpha/alpha_grpc.pb.go
  pkg/sdk/beta/beta.pb.go
  pkg/sdk/beta/beta_grpc.pb.go
  pkg/sdk/sdk.pb.go
  pkg/sdk/sdk_grpc.pb.go
  pkg/sdkserver/localsdk.go
  pkg/sdkserver/localsdk_test.go
  pkg/sdkserver/sdkserver.go
  pkg/sdkserver/sdkserver_test.go
  proto/sdk/alpha/alpha.proto
  sdks/csharp/sdk/generated/Alpha.cs
  sdks/csharp/sdk/generated/AlphaGrpc.cs
  sdks/nodejs/lib/alpha/alpha_grpc_pb.js
  sdks/nodejs/lib/alpha/alpha_pb.js
  sdks/rust/proto/sdk/alpha/alpha.proto
  sdks/swagger/alpha.swagger.json
  test/e2e/gameserver_test.go
  test/sdk/restapi/alpha/swagger/api_sdk.go
  test/sdk/restapi/alpha/swagger/model_alpha_counter_update_request.go
  test/sdk/restapi/alpha/swagger/model_the_requested_update_to_make_to_the_counter.go
Labels: kind/feature, size/XXL, approved

#3373 Fixes TestGameServerResourceValidation flake
  test/e2e/gameserver_test.go
Labels: kind/bug, lgtm, size/XS, approved

#3372 Adds Go SDK client Counter functions
  sdks/go/alpha.go
  sdks/go/alpha_test.go
Labels: kind/feature, size/L, approved

#3368 Update: Allocation Overflow Documentation
  examples/fleet.yaml
  site/content/en/docs/Guides/fleet-updates.md
  site/content/en/docs/Reference/fleet.md
Labels: kind/documentation, size/S, approved

#3378 Update Go simple-game-server to have commands for Counter SDK methods
  examples/simple-game-server/Makefile
  examples/simple-game-server/go.mod
  examples/simple-game-server/go.sum
  examples/simple-game-server/main.go
Labels: kind/feature, lgtm, size/L

#3369 Upgrade Hugo
  build/build-image/Dockerfile
  site/config.toml
  site/layouts/partials/community_links.html
  site/layouts/partials/head.html
  site/layouts/partials/page-meta-links.html
  site/themes/docsy/assets/vendor/bootstrap/config.yml
  site/themes/docsy/assets/vendor/bootstrap/site/layouts/_default/docs.html
  site/themes/docsy/layouts/404.html
  site/themes/docsy/layouts/partials/head.html
  site/themes/docsy/layouts/partials/page-meta-links.html
  site/themes/docsy/layouts/partials/scripts.html
Labels: kind/cleanup, size/M, lgtm, approved

#3381 Adds GameServer e2e tests for Counters
  cloudbuild.yaml
  test/e2e/gameserver_test.go
Labels: kind/feature, lgtm, size/L

#3383 Add more items to .gcloudignore
  .gcloudignore
Labels: kind/cleanup, area/examples, size/S, approved

#3385 Get the gs state correctly in error message
  pkg/sdkserver/sdkserver.go
Labels: kind/bug, lgtm, size/XS, approved

#3393 Don't log when a pod can't be found on startup
  pkg/gameservers/controller.go
Labels: kind/cleanup, area/operations, lgtm, size/XS, approved

#3394 Reduce controller memory footprint considerably
  pkg/gameservers/controller.go
  pkg/gameservers/health.go
  pkg/gameservers/health_test.go
  pkg/gameservers/migration.go
  pkg/gameservers/migration_test.go
  pkg/gameservers/missing.go
  pkg/gameservers/missing_test.go
Labels: kind/bug, area/user-experience, area/operations, size/M, approved

#3392 Add conformance test implementation for C# SDK
  build/build-sdk-images/csharp/Dockerfile
  build/build-sdk-images/csharp/sdktest.sh
  build/includes/sdk.mk
  test/sdk/csharp/Program.cs
  test/sdk/csharp/csharp.csproj
Labels: kind/feature, size/L, approved

#3398 Fix typo in examples/simple-game-server/README.md
  examples/simple-game-server/README.md
Labels: kind/documentation, kind/cleanup, size/XS, approved

#3399 Adds fleet e2e test for Counter
  test/e2e/fleet_test.go
Labels: kind/feature, size/M, lgtm

#3404 pre release: use clones source
  build/includes/release.mk
  build/release/pre_cloudbuild.yaml
Labels: kind/bug, lgtm, size/S, approved

#3402 Release v1.35.0
  .gcloudignore
  CHANGELOG.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/unity/package.json
  site/config.toml
  site/content/en/blog/releases/1.34.0.md
  site/content/en/blog/releases/1.35.0.md
  site/content/en/docs/Installation/_index.md
  site/layouts/partials/navbar.html
Labels: kind/release, lgtm, size/L, approved

#3406 Prep for release v1.36.0
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/rust/Cargo.toml
  sdks/unity/package.json
Labels: kind/release, size/M, lgtm, approved

#3397 Change to use grpc-dotnet instead of Grpc.Core in C# SDK
  build/build-sdk-images/csharp/Dockerfile
  build/build-sdk-images/csharp/gen.sh
  sdks/csharp/proto/googleapis/google/api/annotations.proto
  sdks/csharp/proto/googleapis/google/api/client.proto
  sdks/csharp/proto/googleapis/google/api/field_behavior.proto
  sdks/csharp/proto/googleapis/google/api/http.proto
  sdks/csharp/proto/googleapis/google/api/launch_stage.proto
  sdks/csharp/proto/googleapis/google/api/resource.proto
  sdks/csharp/proto/sdk/alpha/alpha.proto
  sdks/csharp/proto/sdk/beta/beta.proto
  sdks/csharp/proto/sdk/sdk.proto
  sdks/csharp/sdk/AgonesSDK.cs
  sdks/csharp/sdk/Alpha.cs
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/csharp/sdk/generated/Alpha.cs
  sdks/csharp/sdk/generated/AlphaGrpc.cs
  sdks/csharp/sdk/generated/Sdk.cs
  sdks/csharp/sdk/generated/SdkGrpc.cs
  sdks/csharp/test/AgonesAlphaSDKClientTests.cs
  sdks/csharp/test/AgonesSDKClientTests.cs
  sdks/csharp/test/csharp-sdk-test.csproj
Labels: kind/cleanup, size/XXL, approved, kind/other

#3390 Docs for running docker-compose locally with SDK and server
  site/content/en/docs/Guides/Client SDKs/local.md
Labels: size/M, approved, kind/other

#3408 Post release: use clone source and update release process
  build/includes/release.mk
  build/includes/website.mk
  build/release/post_cloudbuild.yaml
  build/scripts/sdk-update-version/main.go
  build/scripts/sdks-rust-cargo-version-update/main.go
  docs/governance/templates/release_issue.md
Labels: kind/bug, lgtm, size/L, approved
