Repository googleforgames/agones, pull requests merged in 2023-03, with the labels that each got.

#3007 Release 1.30.0 - GKE Autopilot and Multiple Kubernetes version support
  CHANGELOG.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/unity/package.json
  site/config.toml
  site/content/en/blog/releases/1.29.0.md
  site/content/en/blog/releases/1.30.0.md
  site/content/en/docs/Advanced/controlling-disruption.md
  site/content/en/docs/Advanced/scheduling-and-autoscaling.md
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Guides/metrics.md
  site/content/en/docs/Installation/Creating Cluster/gke.md
  site/content/en/docs/Installation/Install Agones/helm.md
  site/content/en/docs/Installation/Terraform/gke.md
  site/content/en/docs/Installation/_index.md
  site/layouts/partials/navbar.html
Labels: kind/release, lgtm, size/L, approved

#3006 Add CI step to cancel previous running build for the same branch
  ci/cancelot.sh
  ci/e2e-test-cloudbuild.yaml
  cloudbuild.yaml
Labels: size/M, lgtm

#3013 Prep for 1.31.0 release
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/unity/package.json
Labels: kind/release, size/M, approved

#3014 Ensure the state bucket exists before creating e2e test clusters
  build/includes/google-cloud.mk
Labels: size/S

#3015 Clarify instructions for Managed Prometheus
  site/content/en/docs/Guides/metrics.md
Labels: size/XS, approved

#3017 Delete unused e2e test cluster
  build/terraform/e2e/module.tf
Labels: lgtm, size/XS

#3004 Add autopilot instructions to doc as Alpha
  site/content/en/docs/Installation/Creating Cluster/gke.md
Labels: size/L

#3011 Add Sigterm handler and readiness probe to extensions
  cmd/extensions/main.go
  install/helm/agones/templates/extensions-deployment.yaml
  install/helm/agones/values.yaml
  pkg/util/signals/signals.go
  test/e2e/extensions/high_availability_test.go
  test/e2e/extensions/main_test.go
  test/e2e/framework/framework.go
Labels: lgtm, size/L

#3021 Removing dzlier-gcp from approvers list.
  OWNERS
Labels: lgtm, size/XS, approved

#3027 Fix Dependabot vulnerabilites
  examples/allocation-endpoint/Makefile
  examples/allocation-endpoint/client/go.mod
  examples/allocation-endpoint/server/go.mod
  examples/simple-game-server/Makefile
  examples/simple-game-server/go.mod
  examples/supertuxkart/Makefile
  examples/supertuxkart/go.mod
  examples/xonotic/Makefile
  examples/xonotic/go.mod
  go.mod
  go.sum
  test/terraform/go.mod
  vendor/github.com/emicklei/go-restful/.gitignore
  vendor/github.com/emicklei/go-restful/CHANGES.md
  vendor/github.com/emicklei/go-restful/Makefile
  vendor/github.com/emicklei/go-restful/README.md
  vendor/github.com/emicklei/go-restful/container.go
  vendor/github.com/emicklei/go-restful/cors_filter.go
  vendor/github.com/emicklei/go-restful/curly.go
  vendor/github.com/emicklei/go-restful/custom_verb.go
  vendor/github.com/emicklei/go-restful/jsr311.go
  vendor/github.com/emicklei/go-restful/parameter.go
  vendor/github.com/emicklei/go-restful/path_processor.go
  vendor/github.com/emicklei/go-restful/request.go
  vendor/github.com/emicklei/go-restful/response.go
  vendor/github.com/emicklei/go-restful/route.go
  vendor/github.com/emicklei/go-restful/route_builder.go
  vendor/github.com/emicklei/go-restful/route_reader.go
  vendor/github.com/emicklei/go-restful/service_error.go
  vendor/github.com/emicklei/go-restful/web_service.go
  vendor/modules.txt
Labels: kind/cleanup, lgtm, size/XL

#3032 Fix GKE Autopilot auto-detection for 1.26
  pkg/cloudproduct/gke/gke.go
Labels: lgtm, size/S

#3035 Use actually distinct webhook for Autopilot
  pkg/cloudproduct/gke/gke.go
Labels: lgtm, size/XS

#3002 Adds Counter to SDK alpha.proto
  build/build-sdk-images/node/gen.sh
  go.mod
  go.sum
  pkg/sdk/alpha/alpha.pb.go
  pkg/sdk/alpha/alpha.pb.gw.go
  pkg/sdk/alpha/alpha_grpc.pb.go
  pkg/sdk/sdk.pb.go
  pkg/sdk/sdk.pb.gw.go
  pkg/sdkserver/localsdk.go
  pkg/sdkserver/localsdk_test.go
  pkg/sdkserver/sdk.go
  pkg/sdkserver/sdkserver.go
  proto/googleapis/google/api/client.proto
  proto/googleapis/google/api/field_behavior.proto
  proto/googleapis/google/api/launch_stage.proto
  proto/googleapis/google/api/resource.proto
  proto/sdk/alpha/alpha.proto
  proto/sdk/sdk.proto
  sdks/go/alpha_test.go
  sdks/swagger/alpha.swagger.json
  sdks/swagger/sdk.swagger.json
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/github.com/mennanov/fmutils/.gitignore
  vendor/github.com/mennanov/fmutils/LICENSE
  vendor/github.com/mennanov/fmutils/README.md
  vendor/github.com/mennanov/fmutils/fmutils.go
  vendor/google.golang.org/protobuf/internal/msgfmt/format.go
  vendor/google.golang.org/protobuf/testing/protocmp/reflect.go
  vendor/google.golang.org/protobuf/testing/protocmp/util.go
  vendor/google.golang.org/protobuf/testing/protocmp/xform.go
  vendor/modules.txt
Labels: size/XXL

#3040 Changes to resolve error in creating gcloud-e2e-test-cluster
  build/includes/google-cloud.mk
Labels: size/XS

#3038 Fix doc for multiple k8s version support
  site/content/en/docs/Installation/upgrading.md
Labels: size/XS, approved

#3052 Helm test instruction cleanup in Agones doc
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: kind/cleanup, lgtm, size/S, approved

#3039 Adds List to SDK alpha.proto
  go.mod
  pkg/sdk/alpha/alpha.pb.go
  pkg/sdk/alpha/alpha.pb.gw.go
  pkg/sdk/alpha/alpha_grpc.pb.go
  pkg/sdk/sdk.pb.go
  pkg/sdkserver/localsdk.go
  pkg/sdkserver/localsdk_test.go
  pkg/sdkserver/sdk.go
  pkg/sdkserver/sdk_test.go
  pkg/sdkserver/sdkserver.go
  proto/sdk/alpha/alpha.proto
  proto/sdk/sdk.proto
  sdks/go/alpha_test.go
  sdks/swagger/alpha.swagger.json
  sdks/swagger/sdk.swagger.json
  vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
  vendor/modules.txt
Labels: size/XXL, lgtm

#3055 Add licence to cancelot.sh
  ci/cancelot.sh
Labels: kind/cleanup, lgtm, size/S, approved

#3022 Generate release notes and Changelog using Github
  .github/release.yml
  docs/governance/templates/release_issue.md
Labels: kind/cleanup, size/L, approved
