Repository googleforgames/agones, pull requests merged in 2023-11, with the labels that each got.

#3477 Cmake: Ensure find_dependency is on rebuild
  sdks/cpp/CMakeLists.txt
Labels: kind/bug, area/tests, lgtm, size/XS, approved

#3445 Implements UpdateList, AddListValue, and RemoveListValue in the SDK Server
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/agones/v1/gameserver_test.go
  pkg/apis/allocation/v1/gameserverallocation_test.go
  pkg/gameserverallocations/allocator_test.go
  pkg/sdkserver/localsdk.go
  pkg/sdkserver/sdkserver.go
  pkg/sdkserver/sdkserver_test.go
  pkg/util/apiserver/apiserver.go
Labels: kind/feature, lgtm, size/XL, approved

#3483 Updates to gRPC generation
  .github/ISSUE_TEMPLATE/kubernetes_update.md
  build/includes/allocation.mk
Labels: kind/cleanup, area/build-tools, size/S, approved, kind/other

#3484 Adds Go SDK Client List Functions
  sdks/go/alpha.go
  sdks/go/alpha_test.go
Labels: kind/feature, lgtm, size/L, approved

#3487 Updates LocalSDK UpdateCounter method
  pkg/sdkserver/localsdk.go
  pkg/sdkserver/localsdk_test.go
  pkg/sdkserver/sdkserver.go
Labels: kind/feature, lgtm, size/L

#3492 Release v1.36.0
  CHANGELOG.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/rust/Cargo.toml
  sdks/unity/package.json
  site/config.toml
  site/content/en/blog/releases/1.35.0.md
  site/content/en/blog/releases/1.36.0.md
  site/content/en/docs/Installation/Install Agones/helm.md
  site/content/en/docs/Installation/_index.md
  site/layouts/partials/navbar.html
Labels: kind/release, lgtm, size/L, approved

#3493 Prep for release v1.37.0
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/rust/Cargo.toml
  sdks/unity/package.json
Labels: kind/release, size/M, lgtm

#3488 Adds Counter conformance test
  build/includes/sdk.mk
  pkg/sdkserver/localsdk.go
  test/sdk/go/sdk-client-test.go
Labels: kind/feature, lgtm, size/L, approved

#3495 Xonotic: gLibc incompatibility
  examples/xonotic/Dockerfile
  examples/xonotic/Makefile
  examples/xonotic/fleet.yaml
  examples/xonotic/gameserver.yaml
Labels: kind/bug, area/examples, size/S, approved

#3496 Test SuperTuxKart Image
  test/e2e/examples_test.go
Labels: kind/cleanup, size/M, lgtm, approved

#3499 Test Rust Image
  test/e2e/examples_test.go
Labels: kind/cleanup, size/M, lgtm, approved

#3497 Test cpp-simple image
  test/e2e/examples_test.go
Labels: kind/cleanup, size/M, lgtm

#3500 Adds List SDK methods to simple-game-server
  examples/simple-game-server/Makefile
  examples/simple-game-server/README.md
  examples/simple-game-server/dev-gameserver.yaml
  examples/simple-game-server/fleet-distributed.yaml
  examples/simple-game-server/fleet-tcp.yaml
  examples/simple-game-server/fleet.yaml
  examples/simple-game-server/gameserver-passthrough.yaml
  examples/simple-game-server/gameserver-windows.yaml
  examples/simple-game-server/gameserver.yaml
  examples/simple-game-server/go.mod
  examples/simple-game-server/main.go
  sdks/go/alpha.go
Labels: kind/feature, lgtm, size/L, approved

#3501 Add steps to update performance test clusters when upgrading k8s version
  .github/ISSUE_TEMPLATE/kubernetes_update.md
  build/terraform/performance/module.tf
Labels: kind/documentation, size/S, approved

#3498 Test NodeJS image
  examples/nodejs-simple/gameserver.yaml
  test/e2e/examples_test.go
Labels: kind/cleanup, size/M

#3504 Bumps simple-game-server version to 0.22
  build/Makefile
  examples/crd-client/create-gs.yaml
  examples/fleet.yaml
  examples/gameserver.yaml
  install/helm/agones/templates/tests/test-runner.yaml
  pkg/util/webhooks/webhooks_test.go
  site/config.toml
  site/content/en/docs/Guides/fleet-updates.md
  test/e2e/framework/framework.go
  test/e2e/gameserver_test.go
  test/load/allocation/fleet.yaml
  test/load/allocation/performance-test-fleet-template.yaml
  test/load/allocation/scenario-fleet.yaml
Labels: kind/cleanup, size/S, approved

#3505 Fixes occasional data race flake with TestSDKServerAddListValue
  pkg/sdkserver/sdkserver.go
Labels: kind/bug, size/XS, approved

#3375 handle static port policy
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  test/e2e/framework/framework.go
  test/e2e/gameserver_test.go
Labels: size/L, approved, kind/other

#3494 xonotic image test
  examples/xonotic/fleet.yaml
  examples/xonotic/gameserver.yaml
  test/e2e/examples_test.go
Labels: kind/cleanup, size/M, approved

#3506 Bump helm install timeout to 10m
  build/Makefile
Labels: size/XS, approved, kind/other

#3502 Support appProtocol
  install/helm/agones/templates/service/allocation.yaml
  install/helm/agones/values.yaml
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: size/M, approved, kind/other

#3507 Adds gameserver e2e test for Lists
  test/e2e/gameserver_test.go
Labels: kind/feature, lgtm, size/L, approved

#3510 Adds fleet e2e test for lists
  test/e2e/fleet_test.go
Labels: kind/feature, size/M, lgtm

#3508 Disable resync on SDK Server
  build/Makefile
  cloudbuild.yaml
  install/helm/agones/defaultfeaturegates.yaml
  pkg/sdkserver/sdkserver.go
  pkg/util/runtime/features.go
  site/content/en/docs/Guides/feature-stages.md
Labels: size/M, approved, kind/other

#3517 Move PodHostName to Stable
  cloudbuild.yaml
  install/helm/agones/defaultfeaturegates.yaml
  pkg/util/runtime/features.go
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Reference/gameserver.md
Labels: kind/feature, lgtm, size/S, approved

#3516 Adds gameserverallocation e2e tests for Lists
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/allocation/v1/gameserverallocation_test.go
  test/e2e/gameserverallocation_test.go
Labels: kind/feature, size/L, approved

#3515 Move FleetAllocationOverflow to Beta
  build/Makefile
  cloudbuild.yaml
  examples/fleet.yaml
  install/helm/agones/defaultfeaturegates.yaml
  pkg/apis/agones/v1/fleet.go
  pkg/apis/agones/v1/gameserverset.go
  pkg/util/runtime/features.go
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Guides/fleet-updates.md
  site/content/en/docs/Reference/agones_crd_api_reference.html
  site/content/en/docs/Reference/fleet.md
Labels: size/XXL, lgtm, kind/other

#3518 Move ResetMetricsOnDelete to Stable
  cloudbuild.yaml
  install/helm/agones/defaultfeaturegates.yaml
  pkg/metrics/controller.go
  pkg/metrics/controller_test.go
  pkg/util/runtime/features.go
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Guides/metrics.md
Labels: lgtm, size/L, kind/other

#3519 Adds fleetauotscaler e2e test for Lists
  pkg/fleetautoscalers/fleetautoscalers_test.go
  test/e2e/fleetautoscaler_test.go
Labels: kind/feature, lgtm, size/L, approved

#3503 Add Shulker to the Agones adopters list
  site/content/en/docs/Third Party Content/examples.md
Labels: kind/documentation, size/S, approved

#3521 Another List fleet autoscaler e2e test
  test/e2e/fleetautoscaler_test.go
Labels: kind/feature, lgtm, size/L, approved
