Repository googleforgames/agones, pull requests merged in 2023-04, with the labels that each got.

#3063 Fixed example images
  examples/allocation-endpoint/server/go.mod
  examples/allocation-endpoint/server/go.sum
  examples/supertuxkart/go.mod
  examples/supertuxkart/go.sum
Labels: kind/cleanup, size/XL, approved

#3060 Replaces functionality and types to make plugin cross-compilable between UE4 and UE5
  sdks/unreal/Agones/Source/Agones/Private/AgonesComponent.cpp
Labels: size/M

#3046 Rework game server health initial delay handling
  cloudbuild.yaml
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  pkg/sdkserver/sdkserver.go
  pkg/sdkserver/sdkserver_test.go
  test/e2e/gameserver_test.go
Labels: kind/bug, size/L, approved

#3050 Fix simple-game-server to use context substitute for the infinite loop
  examples/simple-game-server/main.go
Labels: size/S, approved

#3064 Link to Global Scale Demo from Agones Examples page
  site/content/en/docs/Examples/_index.md
  site/content/en/docs/FAQ/_index.md
  site/content/en/docs/Installation/Creating Cluster/gke.md
  site/content/en/docs/Third Party Content/examples.md
Labels: kind/feature, kind/cleanup, lgtm, size/S, approved

#3068 Revert "Rework game server health initial delay handling (#3046)"
  cloudbuild.yaml
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  pkg/sdkserver/sdkserver.go
  pkg/sdkserver/sdkserver_test.go
  test/e2e/gameserver_test.go
Labels: lgtm, size/L

#3069 Added -buildvcs=false in build/Makefile
  build/Makefile
Labels: kind/bug, size/XS, approved

#3070 Add timeout to SDK k8s client
  cmd/sdk-server/main.go
Labels: size/XS, approved

#3053 Document missing Allocation Service helm variables
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: kind/cleanup, size/XS, approved

#3056 Remove unnecessary intermediate variables.
  pkg/util/signals/signals.go
Labels: kind/cleanup, size/XS, approved

#3049 Add description on when to upgrade supported Kubernetes version
  CONTRIBUTING.md
  site/content/en/docs/Installation/_index.md
Labels: size/XS

#3051 Add helm setting for leader election
  cmd/controller/main.go
  install/helm/agones/templates/controller.yaml
  install/helm/agones/templates/serviceaccounts/controller.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: size/M

#3062 Have TestPlayerConnectWithCapacityZero use framework to wait
  test/e2e/gameserver_test.go
Labels: size/S

#3071 Fix release tag on Unity SDK installation document page (#2622)
  site/content/en/docs/Guides/Client SDKs/unity.md
Labels: lgtm, size/XS, approved

#3073 Retry build cancellation if it fails
  cloudbuild.yaml
Labels: lgtm, size/XS

#3072 Rework game server health initial delay handling
  cloudbuild.yaml
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  pkg/sdkserver/sdkserver.go
  pkg/sdkserver/sdkserver_test.go
  test/e2e/gameserver_test.go
Labels: size/L, approved

#3074 Add tags for cluster, location, commit to e2e-test builds
  build/Makefile
  ci/e2e-test-cloudbuild.yaml
  cloudbuild.yaml
Labels: lgtm, size/S

#3077 Update examples images to latest version on agones-images
  examples/allocation-endpoint/terraform/variable.tf
  examples/supertuxkart/fleet.yaml
  examples/supertuxkart/gameserver.yaml
  examples/xonotic/fleet.yaml
  examples/xonotic/go.mod
  examples/xonotic/go.sum
Labels: size/M, lgtm, approved

#3075 GitHub action for stale issues
  .github/workflows/close.yaml
  .github/workflows/obsolete.yaml
  .github/workflows/stale.yaml
Labels: size/L, approved

#3065 GameServer Allocation Filtering for Counts and Lists
  pkg/apis/allocation/v1/gameserverallocation.go
  pkg/apis/allocation/v1/gameserverallocation_test.go
  pkg/apis/allocation/v1/zz_generated.deepcopy.go
  site/content/en/docs/Reference/agones_crd_api_reference.html
Labels: size/XXL, lgtm, approved

#3080 Tag CI build with commit, tag e2e with parent build ID
  ci/e2e-test-cloudbuild.yaml
  cloudbuild.yaml
Labels: size/XS

#3066 Automation: Update Approved Auto-Merge PR's to latest main
  .github/workflows/pr_update.yml
Labels: kind/feature, size/M, approved

#3076 Add e2e test for leader election
  test/e2e/controller/crash_test.go
Labels: size/M

#3081 Renamed action-secret
  .github/workflows/pr_update.yml
Labels: kind/cleanup, lgtm, size/XS, approved

#3078 simple-game-server with latest version 0.15
  build/Makefile
  examples/crd-client/create-gs.yaml
  examples/fleet.yaml
  examples/gameserver.yaml
  examples/simple-game-server/dev-gameserver.yaml
  examples/simple-game-server/fleet-distributed.yaml
  examples/simple-game-server/fleet-tcp.yaml
  examples/simple-game-server/fleet.yaml
  examples/simple-game-server/gameserver-passthrough.yaml
  examples/simple-game-server/gameserver-windows.yaml
  examples/simple-game-server/gameserver.yaml
  install/helm/agones/templates/tests/test-runner.yaml
  pkg/util/webhooks/webhooks_test.go
  site/config.toml
  test/e2e/framework/framework.go
  test/e2e/gameserver_test.go
  test/load/allocation/fleet.yaml
  test/load/allocation/scenario-fleet.yaml
Labels: kind/cleanup, size/M, approved

#3079 Remove changelog generation from release/cloudbuild.yaml
  build/release/cloudbuild.yaml
Labels: kind/cleanup, size/M, approved

#3082 Remove 1.23 e2e test cluster
  build/terraform/e2e/module.tf
Labels: size/XS, approved

#3086 Preparation for 1.32.0
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/unity/package.json
  site/content/en/blog/releases/1.31.0.md
Labels: kind/release, size/M, lgtm

#3083 Add to SplitControllerAndExtensions documentation for leader election
  site/content/en/docs/Advanced/high-availability-agones.md
Labels: lgtm, size/XS

#3088 Update docs for Stable Network ID
  site/content/en/docs/Reference/gameserver.md
Labels: kind/documentation, kind/cleanup, lgtm, size/XS, approved

#3092 Drop log level of worker queue to Trace
  pkg/util/workerqueue/workerqueue.go
Labels: size/XS, approved

#3102 refactor: type and constant definitions are in the same area.
  pkg/apis/agones/v1/gameserver.go
Labels: size/M, lgtm

#3104 Remove consul install
  build/e2e-image/Dockerfile
Labels: lgtm, size/S, approved

#3090 Release Automation: Push images on cloud
  build/includes/release.mk
  build/release/post_cloudbuild.yaml
  build/release/pre_cloudbuild.yaml
  docs/governance/templates/release_issue.md
Labels: size/L, approved

#3109 Specify the machine type for agones-metrics nodepool since the default one doesn't meet resource requirement
  site/content/en/docs/Guides/metrics.md
  site/content/en/docs/Installation/Creating Cluster/gke.md
Labels: lgtm, size/XS

#3091 Sort By Counters or Lists during GameServerAllocation 2716
  pkg/apis/allocation/v1/gameserverallocation.go
  pkg/apis/allocation/v1/gameserverallocation_test.go
  pkg/apis/allocation/v1/zz_generated.deepcopy.go
  pkg/gameserverallocations/allocation_cache.go
  pkg/gameserverallocations/allocation_cache_test.go
  pkg/gameserverallocations/allocator.go
  pkg/gameserverallocations/find_test.go
  site/content/en/docs/Reference/agones_crd_api_reference.html
Labels: size/XXL, lgtm, approved

#3101 Allocated GameServers updated on Fleet update
  examples/fleet.yaml
  pkg/apis/agones/v1/fleet.go
  pkg/gameserversets/allocation_overflow.go
  pkg/gameserversets/allocation_overflow_test.go
  pkg/gameserversets/controller.go
  pkg/gameserversets/gameserversets.go
  pkg/util/runtime/features.go
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Reference/agones_crd_api_reference.html
  site/content/en/docs/Reference/fleet.md
  test/e2e/fleet_test.go
  test/e2e/framework/framework.go
Labels: size/XXL, approved

#3124 require.NoError in fleet tests instead of continuing
  test/e2e/fleet_test.go
Labels: size/L

#3119 Clone Agones for release targets
  build/release/post_cloudbuild.yaml
  build/release/pre_cloudbuild.yaml
Labels: kind/cleanup, size/S

#3118 Move PodHostName to Beta
  build/Makefile
  cloudbuild.yaml
  install/helm/agones/defaultfeaturegates.yaml
  pkg/util/runtime/features.go
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Reference/gameserver.md
Labels: kind/feature, kind/cleanup, size/M

#3120 Move PushChart into releaseFile
  build/Makefile
  build/includes/release.mk
Labels: kind/cleanup, size/S

#3103 Refactor: Modify logger implementation and log level
  pkg/fleetautoscalers/controller.go
  pkg/fleets/controller.go
Labels: size/S

#3126 Remove unused target for generating change log
  build/includes/release.mk
Labels: lgtm, size/S, approved

#3127 Creating a branch for release
  build/includes/release.mk
  docs/governance/templates/release_issue.md
Labels: kind/feature, kind/cleanup, lgtm, size/S, approved

#3130 Docs: Remove contributing warning about bug.
  site/content/en/docs/Contribute/_index.md
Labels: kind/documentation, kind/cleanup, lgtm, size/XS, approved

#3131 Documentation: Allocated GameServer Overflow
  site/content/en/docs/Guides/fleet-updates.md
Labels: kind/feature, kind/documentation, size/M, approved
