Repository googleforgames/agones, pull requests merged in 2023-01, with the labels that each got.

#2885 Set seccompProfile of `Unconfined` on Autopilot unless overidden by user
  pkg/cloudproduct/gke/gke.go
  pkg/cloudproduct/gke/gke_test.go
Labels: size/M, lgtm, approved

#2883 Updates allocation load testing documentation
  site/content/en/docs/Advanced/allocator-service.md
  test/load/allocation/README.md
  test/load/allocation/autoscaler.yaml
  test/load/allocation/scenario-fleet.yaml
  test/load/allocation/variable.txt
Labels: lgtm, size/L, approved

#2857 SafeToEvict: Implement Eviction API, add SetEviction cloud product hook
  install/helm/agones/templates/crds/_gameserverspecschema.yaml
  install/helm/agones/templates/crds/_gameserverstatus.yaml
  pkg/apis/agones/v1/apihooks.go
  pkg/apis/agones/v1/apihooks_test.go
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/agones/v1/gameserver_test.go
  pkg/cloudproduct/gke/gke.go
  pkg/cloudproduct/gke/gke_test.go
  site/content/en/docs/Reference/agones_crd_api_reference.html
Labels: size/XXL, lgtm, approved

#2862 Update metrics documentation for Cloud Monitoring/Stackdriver
  site/content/en/docs/Guides/metrics.md
Labels: size/M, approved

#2886 e2e: Add --cloud-product flag, add SkipOnCloudProduct
  test/e2e/framework/framework.go
  test/e2e/gameserver_test.go
Labels: lgtm, size/S

#2889 Don't run cloud product GameServerSpec validation on development GameServers
  pkg/apis/agones/v1/gameserver.go
  test/e2e/fleet_test.go
Labels: size/S

#2896 Fix the json5 vulnerabilities
  sdks/nodejs/package-lock.json
Labels: lgtm, size/S

#2893 e2e framework: Allow variable timing based on cloud product
  pkg/apis/agones/v1/gameserver.go
  test/e2e/framework/framework.go
Labels: feature-freeze-do-not-merge, size/M

#2911 Preparation for 1.29.0
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/unity/package.json
Labels: kind/release, size/M, lgtm, approved

#2902 flaky/TestFleetRollingUpdate
  build/Makefile
  test/e2e/fleet_test.go
Labels: kind/bug, area/tests, size/S, approved

#2904 e2e: Use gotestsum for CI e2e runs, change e2e ARGS handling
  build/Makefile
  build/build-image/Dockerfile
  build/e2e-image/Dockerfile
  build/e2e-image/e2e.sh
Labels: size/M, lgtm, approved

#2901 Wait on free ports on GKE Autopilot
  pkg/cloudproduct/cloudproduct.go
  pkg/cloudproduct/generic/generic.go
  pkg/cloudproduct/gke/gke.go
  pkg/gameservers/health.go
  pkg/gameservers/health_test.go
  test/e2e/framework/framework.go
  test/e2e/gameserver_test.go
Labels: size/M, approved

#2908 Fix: Updates README.md by removing dead links
  README.md
Labels: size/XS

#2900 controller/extensions: Add explicit requests/limits for ephemeral storage
  install/helm/agones/templates/controller.yaml
  install/helm/agones/templates/extensions-deployment.yaml
  install/yaml/install.yaml
Labels: size/S, approved

#2916 Move pooneh-m to emeritus approvers
  OWNERS
Labels: area/meta, lgtm, size/XS, approved

#2892 Validate the .scheduling field in the fleet and gameserverset
  pkg/apis/agones/v1/apihooks.go
  pkg/apis/agones/v1/fleet.go
  pkg/apis/agones/v1/gameserverset.go
  pkg/cloudproduct/gke/gke.go
  pkg/cloudproduct/gke/gke_test.go
  test/e2e/fleet_test.go
  test/e2e/gameserverallocation_test.go
Labels: size/M, lgtm, approved

#2898 Removes explicit versions of Prometheus and Grafana
  build/Makefile
  build/README.md
  build/build-image/Dockerfile
  build/grafana/dashboard-allocations.yaml
  build/grafana/dashboard-gameservers.yaml
  site/content/en/docs/Guides/metrics.md
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: size/L

#2891 Trim down `agones-extensions` and add flag to `agones-controller`
  cmd/controller/main.go
  cmd/extensions/main.go
  cmd/extensions/main_test.go
  install/helm/agones/templates/extensions-deployment.yaml
  install/helm/agones/templates/service.yaml
  install/helm/agones/values.yaml
  pkg/fleetautoscalers/controller.go
  pkg/fleetautoscalers/controller_test.go
  pkg/fleets/controller.go
  pkg/fleets/controller_test.go
  pkg/gameserverallocations/controller.go
  pkg/gameserverallocations/controller_test.go
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  pkg/gameserversets/controller.go
  pkg/gameserversets/controller_test.go
Labels: lgtm, size/XL, approved

#2922 Allow 30m more to acquire consul lock
  build/e2e-image/entrypoint.sh
  cloudbuild.yaml
Labels: lgtm, size/XS, approved

#2927 Bump the cloud build expiration time, we can no longer retry
  cloudbuild.yaml
  pkg/metrics/controller_test.go
Labels: lgtm, size/XS, approved

#2925 Omit namespace from cluster scopped resources in helm install
  install/helm/agones/templates/hooks/sa.yaml
  install/helm/agones/templates/service/allocation.yaml
  install/helm/agones/templates/serviceaccounts/controller.yaml
  install/helm/agones/templates/serviceaccounts/sdk.yaml
  install/yaml/install.yaml
Labels: lgtm, size/S

#2928 Added GKE Workload Identity flag to GKE Terraform modules
  install/terraform/modules/gke/cluster.tf
  install/terraform/modules/gke/variables.tf
Labels: size/XS

#2919 Remove release candidate steps from the docs
  docs/governance/release_process.md
  docs/governance/templates/release.md
  docs/governance/templates/release_issue.md
Labels: kind/cleanup, area/meta, size/M, approved

#2930 Actually bump consul timeout
  build/e2e-image/entrypoint.sh
Labels: lgtm, size/XS, approved

#2932 Run e2es in fair order, eliminate need for consul
  cloudbuild.yaml
Labels: size/M, lgtm, approved

#2929 Remove rc from the includes
  build/includes/release.mk
Labels: kind/cleanup, area/meta, lgtm, size/XS, approved

#2933 Allocation Endpoint: Fix Makefile to correctly call docker build
  examples/allocation-endpoint/Makefile
  examples/allocation-endpoint/terraform/variable.tf
Labels: size/S, approved

#2936 Use Server Side Apply to mitigate the 'metadata.annotations: Too long: must have at most 262144 bytes' error
  site/content/en/docs/Installation/Install Agones/yaml.md
Labels: size/XS, approved

#2934 Disable consul locking if consul is not present
  build/e2e-image/entrypoint.sh
Labels: size/S

#2923 Enable SplitControllerAndExtensions for e2e testing and changed value…
  build/Makefile
  build/e2e-image/e2e.sh
  cloudbuild.yaml
  install/helm/agones/defaultfeaturegates.yaml
  install/helm/agones/templates/controller.yaml
  install/helm/agones/templates/extensions-deployment.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  pkg/util/runtime/features.go
Labels: lgtm, size/L

#2941 Block on Autopilot in CI
  cloudbuild.yaml
Labels: lgtm, size/XS, approved
