Repository googleforgames/agones, pull requests merged in 2024-09, with the labels that each got.

#3934 Adds schedule and chain policy to fleetautoscaler documentation
  site/content/en/docs/Reference/fleetautoscaler.md
Labels: kind/documentation, size/M

#3948 Improve documentation to run performance script
  build/README.md
Labels: kind/documentation, size/S

#3975 Preparation for Release v1.44.0
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/rust/Cargo.toml
  sdks/unity/package.json
Labels: kind/release, size/S

#3935 Unreal SDK - Added counters to unreal sdk
  sdks/unreal/Agones/Source/Agones/Classes/Classes.h
  sdks/unreal/Agones/Source/Agones/Private/AgonesComponent.cpp
  sdks/unreal/Agones/Source/Agones/Public/AgonesComponent.h
  site/content/en/docs/Guides/Client SDKs/unreal.md
Labels: kind/feature, size/M

#3965 Add instructions for running Agones on Minikube with the Windows Docker driver
  site/content/en/docs/Installation/Creating Cluster/minikube.md
Labels: kind/documentation, size/S

#3964 Use Markdown when use k8s-api-version variable
  site/content/en/docs/Reference/gameserver.md
  site/content/en/docs/Reference/gameserverallocation.md
Labels: size/XS, kind/other

#3932 Unreal SDK - Add Support for GameServer Status Addresses
  sdks/unreal/Agones/Source/Agones/Classes/Classes.h
Labels: kind/feature, size/S

#3981 fix: remove bad character from metrics markdown
  site/content/en/docs/Guides/metrics.md
Labels: kind/bug, size/XS

#3958 Refactor Terraform
  build/Makefile
  build/includes/google-cloud.mk
  build/includes/terraform.mk
Labels: size/M, kind/other

#3899 Updating UpdateList to update the values on a list
  pkg/sdkserver/sdkserver.go
  pkg/sdkserver/sdkserver_test.go
  site/content/en/docs/Guides/Client SDKs/rest.md
Labels: kind/bug, size/M, size/S

#3973 Cleanup Patch Sidecar Logging
  pkg/gameservers/controller.go
  pkg/gameservers/health.go
  pkg/gameservers/migration.go
  pkg/sdkserver/sdkserver.go
  pkg/util/workerqueue/workerqueue.go
  pkg/util/workerqueue/workerqueue_test.go
Labels: kind/bug, area/operations, size/S

#3986 Created performance cluster 1.29
  build/terraform/e2e/module.tf
  build/terraform/performance/module.tf
  ci/perf-test-cloudbuild.yaml
Labels: kind/cleanup, size/XS

#3982 Updates upgrade test to install multiple versions of Agones on a cluster in succession
  test/upgrade/Dockerfile
  test/upgrade/main.go
  test/upgrade/permissions.yaml
  test/upgrade/upgradeTest.yaml
  test/upgrade/versionMap.yaml
Labels: kind/feature, size/L, size/XL

#3987 Adds game server template with containerized sdk-client-test
  test/sdk/go/Dockerfile
  test/sdk/go/Makefile
  test/sdk/go/cloudbuild.yaml
  test/upgrade/Dockerfile
  test/upgrade/gameserverTemplate.yaml
  test/upgrade/go.mod
  test/upgrade/go.sum
  test/upgrade/main.go
  test/upgrade/upgradeTest.yaml
  test/upgrade/versionMap.yaml
Labels: kind/feature, size/L

#3912 Adding missing documentation about: add option for extensions components to use host network and configure ports
  site/content/en/docs/Installation/Creating Cluster/eks.md
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: kind/documentation, size/S

#3989 Refactor metrics registry exporter
  cmd/allocator/main.go
  cmd/allocator/metrics.go
  cmd/controller/main.go
  cmd/extensions/main.go
  pkg/metrics/exporter.go
Labels: kind/bug, size/M, size/S

#3991 Test in place upgrades run tests
  .gitignore
  test/sdk/go/Makefile
  test/sdk/go/sdk-client-test.go
  test/upgrade/Dockerfile
  test/upgrade/Makefile
  test/upgrade/gameserverTemplate.yaml
  test/upgrade/main.go
  test/upgrade/permissions.yaml
  test/upgrade/upgradeTest.yaml
  test/upgrade/versionMap.yaml
Labels: kind/feature, size/M

#3999 fix: correct misspelled metric in docs
  site/content/en/docs/Guides/metrics.md
Labels: kind/documentation, size/XS

#4005 Add finalizer name change to create gameserver example
  site/content/en/docs/Getting Started/create-gameserver.md
Labels: kind/cleanup, size/XS

#4000 Formatting code with gofmt
  cmd/controller/pprof.go
  cmd/extensions/pprof.go
Labels: size/XS, kind/other
