Repository googleforgames/agones, pull requests merged in 2024-02, with the labels that each got.

#3627 Flake: List Add/Delete Unit Tests
  pkg/sdkserver/sdkserver_test.go
Labels: kind/cleanup, area/tests, size/S

#3615 fix(SdkList): fix list delete values panic
  pkg/sdkserver/sdkserver.go
Labels: kind/bug, size/S, kind/other

#3632 More description on fleetautoscaler.md
  site/content/en/docs/Reference/fleetautoscaler.md
Labels: kind/feature, kind/documentation, size/M

#3621 Breaking: Remove Cmake gRPC install when not found
  .github/ISSUE_TEMPLATE/kubernetes_update.md
  build/build-sdk-images/cpp/build-sdk-test.sh
  build/build-sdk-images/restapi/Dockerfile
  build/build-sdk-images/tool/base/Dockerfile
  build/includes/sdk.mk
  build/release/post_cloudbuild.yaml
  cloudbuild.yaml
  examples/cpp-simple/CMakeLists.txt
  examples/cpp-simple/Dockerfile
  examples/cpp-simple/Makefile
  sdks/cpp/CMakeLists.txt
  sdks/cpp/cmake/clang-verify.in
  sdks/cpp/cmake/prerequisites.cmake
  site/content/en/docs/Guides/Client SDKs/cpp.md
  test/sdk/cpp/CMakeLists.txt
Labels: area/user-experience, kind/breaking, size/L

#3626 Script to bump example images
  build/includes/website.mk
  build/scripts/bump-image/main.go
  examples/cpp-simple/fleet.yaml
  examples/cpp-simple/gameserver.yaml
  install/helm/agones/templates/tests/test-runner.yaml
  test/e2e/examples_test.go
Labels: size/M, kind/other

#3638 Linting: need `git ... --add safe.directory`
  build/Makefile
  build/includes/website.mk
Labels: kind/cleanup, size/XS

#3639 Migrate to https://github.com/gomodules/jsonpatch
  go.mod
  go.sum
  pkg/apis/agones/v1/gameserver.go
  pkg/fleetautoscalers/controller.go
  pkg/fleetautoscalers/controller_test.go
  pkg/fleets/controller.go
  pkg/fleets/controller_test.go
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  vendor/github.com/mattbaird/jsonpatch/.gitignore
  vendor/github.com/mattbaird/jsonpatch/README.md
  vendor/github.com/mattbaird/jsonpatch/jsonpatch.go
  vendor/gomodules.xyz/jsonpatch/v2/LICENSE
  vendor/gomodules.xyz/jsonpatch/v2/jsonpatch.go
  vendor/modules.txt
Labels: kind/cleanup, size/L

#3637 Docs: Default Counter Capacity as 1000
  examples/gameserver.yaml
  site/content/en/docs/Guides/Client SDKs/_index.md
  site/content/en/docs/Reference/gameserver.md
Labels: kind/cleanup, size/XS, size/S

#3643 Build: Replace godoc with pkgsite
  build/Makefile
  build/README.md
  build/build-image/Dockerfile
Labels: kind/cleanup, area/build-tools, size/S

#3658 fix: typo
  site/content/en/docs/Advanced/out-of-cluster-dev-server.md
Labels: kind/documentation, size/XS

#3657 Switch to debian:bookworm
  build/build-image/Dockerfile
Labels: size/S, kind/other

#3631 Define SDKServer LogLevel early
  cmd/sdk-server/main.go
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  pkg/sdkserver/sdkserver.go
  pkg/sdkserver/sdkserver_test.go
Labels: size/S, kind/other

#3666 Downscale performance test cluster
  build/terraform/performance/module.tf
Labels: kind/cleanup, size/XS

#3667 Info log level on Performance tests
  build/performance-test.sh
Labels: kind/cleanup, area/performance, size/XS

#3668 Fix the handling of removing disconnected streams to avoid a panic when multiple streams disconnect from the sdkserver
  pkg/sdkserver/sdkserver.go
  pkg/sdkserver/sdkserver_test.go
Labels: kind/bug, size/S

#3673 fix: minor typos for simple-genai-server endpoints and readme
  examples/simple-genai-server/README.md
  examples/simple-genai-server/main.go
Labels: kind/documentation, size/XS
