Repository googleforgames/agones, pull requests merged in 2024-05, with the labels that each got.

#3809 Passthrough autopilot - Adds an AutopilotPassthroughPort Feature Gate and new pod label
  install/helm/agones/defaultfeaturegates.yaml
  pkg/apis/agones/v1/gameserver.go
  pkg/cloudproduct/gke/gke.go
  pkg/cloudproduct/gke/gke_test.go
  pkg/util/runtime/features.go
Labels: kind/feature, size/M, size/S

#3773 Helm Param Update: Default to agones.controller if agones.extensions is Missing
  install/helm/agones/templates/extensions.yaml
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: size/M, size/S, kind/other

#3808 fix: typo
  site/content/en/docs/Guides/fleet-updates.md
Labels: kind/cleanup, size/XS

#3802 Helm Config: Add httpUnallocatedStatusCode in Allocator Service
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: kind/documentation, size/S

#3762 fix: rollout strategy issues
  build/Makefile
  cloudbuild.yaml
  install/helm/agones/defaultfeaturegates.yaml
  pkg/fleets/controller.go
  pkg/fleets/controller_rollingupdatefix.go
  pkg/fleets/controller_test.go
  pkg/util/runtime/features.go
  site/content/en/docs/Guides/feature-stages.md
  test/e2e/fleet_test.go
Labels: kind/bug, size/M, size/S

#3747 feat: support multiple port ranges
  build/Makefile
  cloudbuild.yaml
  cmd/controller/main.go
  cmd/controller/main_test.go
  examples/gameserver.yaml
  go.mod
  install/helm/agones/defaultfeaturegates.yaml
  install/helm/agones/templates/controller.yaml
  install/helm/agones/templates/crds/_gameserverspecschema.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/agones/v1/gameserver_test.go
  pkg/cloudproduct/cloudproduct.go
  pkg/cloudproduct/generic/generic.go
  pkg/cloudproduct/gke/gke.go
  pkg/cloudproduct/gke/gke_test.go
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  pkg/portallocator/portallocator.go
  pkg/portallocator/portallocator_test.go
  pkg/util/runtime/features.go
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Installation/Creating Cluster/gke.md
  site/content/en/docs/Installation/Install Agones/helm.md
  site/content/en/docs/Reference/agones_crd_api_reference.html
  site/content/en/docs/Reference/gameserver.md
Labels: kind/feature, size/XL

#3810 Update Docs: CountersAndLists to Beta
  examples/fleet.yaml
  examples/gameserver.yaml
  examples/gameserverallocation.yaml
  site/content/en/docs/Guides/Client SDKs/_index.md
  site/content/en/docs/Guides/Client SDKs/csharp.md
  site/content/en/docs/Guides/Client SDKs/rest.md
  site/content/en/docs/Guides/counters-and-lists.md
  site/content/en/docs/Guides/player-tracking.md
  site/content/en/docs/Integration Patterns/player-capacity.md
  site/content/en/docs/Reference/gameserver.md
  site/content/en/docs/Reference/gameserverallocation.md
Labels: size/L, size/XL, kind/other

#3803 Changes `sdk-server` to Patch instead of Update
  install/helm/agones/templates/serviceaccounts/sdk.yaml
  install/yaml/install.yaml
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/agones/v1/gameserver_test.go
  pkg/sdkserver/sdkserver.go
  pkg/sdkserver/sdkserver_test.go
  sdks/go/beta.go
  sdks/go/beta_test.go
  test/e2e/gameserver_test.go
Labels: kind/feature, size/M, size/L

#3749 Set Minimum Buffer Size to 1
  pkg/fleetautoscalers/fleetautoscalers.go
  pkg/fleetautoscalers/fleetautoscalers_test.go
Labels: kind/bug, size/S

#3815 Disable Dev feature FeatureAutopilotPassthroughPort
  install/helm/agones/defaultfeaturegates.yaml
Labels: kind/hotfix, size/XS

#3816 Disable FeatureAutopilotPassthroughPort in features.go
  pkg/util/runtime/features.go
Labels: size/XS, kind/other

#3774 SDK proto compatibility guarantees and deprecation policies documentation
  site/content/en/docs/Installation/upgrading.md
Labels: kind/documentation, size/M, size/S

#3827 Fix dangling "as of"
  site/content/en/docs/Installation/upgrading.md
Labels: size/XS, kind/other

#3829 Pin ltsc2019 to older SHA
  build/Makefile
  cmd/sdk-server/Dockerfile.windows
Labels: size/XS, kind/other

#3814 Steps to Promote SDK Features from Alpha to Beta
  pkg/util/runtime/features.go
Labels: size/XS, size/S, kind/other

#3825 Generate grpc for nodejs from alpha to beta
  build/build-sdk-images/node/gen.sh
  sdks/nodejs/lib/beta/beta_grpc_pb.js
  sdks/nodejs/lib/beta/beta_pb.js
  sdks/nodejs/lib/beta/google/api/annotations_pb.js
  sdks/nodejs/lib/beta/google/api/client_pb.js
  sdks/nodejs/lib/beta/google/api/field_behavior_pb.js
  sdks/nodejs/lib/beta/google/api/http_pb.js
  sdks/nodejs/lib/beta/google/api/launch_stage_pb.js
  sdks/nodejs/lib/beta/google/api/resource_pb.js
  sdks/nodejs/lib/beta/protoc-gen-openapiv2/options/annotations_pb.js
  sdks/nodejs/lib/beta/protoc-gen-openapiv2/options/openapiv2_pb.js
Labels: kind/feature, size/XL

#3824 Update CountsAndLists from Alpha to Beta
  examples/counterfleetautoscaler.yaml
  examples/fleet.yaml
  examples/listfleetautoscaler.yaml
  pkg/allocation/go/allocation.pb.go
  pkg/allocation/go/allocation.swagger.json
  pkg/apis/agones/v1/fleet.go
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/agones/v1/gameserver_test.go
  pkg/apis/agones/v1/gameserverset.go
  pkg/apis/allocation/v1/gameserverallocation.go
  pkg/apis/autoscaling/v1/fleetautoscaler.go
  pkg/util/runtime/features.go
  proto/allocation/allocation.proto
  sdks/rust/proto/allocation/allocation.proto
  site/content/en/docs/Reference/agones_crd_api_reference.html
  site/content/en/docs/Reference/fleet.md
Labels: size/XL, kind/other

#3807 feat(gameserver): New DirectToGameServer PortPolicy allows direct traffic to a GameServer
  build/Makefile
  cloudbuild.yaml
  examples/gameserver.yaml
  examples/simple-game-server/gameserver-none.yaml
  install/helm/agones/defaultfeaturegates.yaml
  install/helm/agones/templates/crds/_gameserverspecschema.yaml
  install/yaml/install.yaml
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/agones/v1/gameserver_test.go
  pkg/client/applyconfiguration/agones/v1/gameserverport.go
  pkg/cloudproduct/gke/gke.go
  pkg/cloudproduct/gke/gke_test.go
  pkg/gameservers/gameservers_test.go
  pkg/util/runtime/features.go
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Reference/agones_crd_api_reference.html
  site/content/en/docs/Reference/gameserver.md
  test/e2e/gameserver_test.go
Labels: kind/feature, size/M, size/L, size/XL

#3822 Adds comment for help troubleshooting issues with terraform tfstate
  build/terraform/e2e/state-bucket/main.tf
Labels: kind/documentation, size/XS, size/S

#3831 TestGameServerAllocationDuringMultipleAllocationClients: Readdress flake
  test/e2e/gameserverallocation_test.go
Labels: size/S, kind/other

#3818 docs: improve counter and list example comments
  examples/fleet.yaml
  examples/gameserver.yaml
  site/content/en/docs/Guides/counters-and-lists.md
  site/content/en/docs/Reference/fleet.md
  site/content/en/docs/Reference/gameserver.md
Labels: kind/documentation, size/M, size/S

#3838 Skip /tmp/ on yamllint
  .yamllint
Labels: size/XS, kind/other

#3837 TestAllocatorAfterDeleteReplica: More logging
  test/e2e/allocator/pod_termination_test.go
Labels: size/XS, kind/other

#3839 agones-{extensions,allocator}: Be more defensive about draining
  install/helm/agones/templates/extensions-deployment.yaml
  install/helm/agones/templates/service/allocation.yaml
  install/yaml/install.yaml
  test/e2e/allocator/pod_termination_test.go
  test/e2e/extensions/high_availability_test.go
Labels: size/S, kind/other

#3819 Instructions for upgrading golang version
  .github/ISSUE_TEMPLATE/golang_version_upgrade.md
Labels: kind/documentation, size/S

#3833 Passthrough autopilot - Adds mutating webhook
  install/helm/agones/templates/extensions.yaml
  install/yaml/install.yaml
  pkg/cloudproduct/gke/gke.go
  pkg/cloudproduct/gke/gke_test.go
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  pkg/util/webhooks/webhooks.go
Labels: kind/feature, size/M

#3841 Remove unused function FindGameServerContainer
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/agones/v1/gameserver_test.go
Labels: size/S, kind/other

#3843 agones-{extensions,allocator}: Pause after cancelling context
  cmd/allocator/main.go
  cmd/extensions/main.go
  install/helm/agones/templates/extensions-deployment.yaml
  install/helm/agones/templates/service/allocation.yaml
  install/yaml/install.yaml
  test/e2e/allocator/pod_termination_test.go
  test/e2e/extensions/high_availability_test.go
Labels: size/S, kind/other

#3844 Change the line to modify in Quickstart: Edit a Game Server
  site/content/en/docs/Getting Started/edit-first-gameserver-go.md
Labels: kind/bug, kind/documentation, area/examples, size/XS, kind/other

#3847 Adds Unreal to the List of URL Links to Not Check
  site/htmltest.yaml
Labels: kind/hotfix, size/XS

#3842 Passthrough autopilot - added ports array case and updated unit tests
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/agones/v1/gameserver_test.go
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
Labels: kind/feature, size/M
