Repository googleforgames/agones, pull requests merged in 2024-04, with the labels that each got.

#3692 fix: #3607 Metrics data loss in K8S controller
  pkg/metrics/controller.go
  pkg/metrics/controller_test.go
  pkg/metrics/gameservers_count.go
Labels: size/M, size/S, kind/other

#3743 Docs: Make hitting <enter> on connection explicit
  site/content/en/docs/Getting Started/create-gameserver.md
Labels: kind/documentation, size/S

#3581 Adds Counters and Lists to CSharp SDK
  build/includes/sdk.mk
  sdks/csharp/sdk/Alpha.cs
  sdks/csharp/sdk/IAgonesAlphaSDK.cs
  sdks/csharp/test/AgonesAlphaSDKClientTests.cs
  site/content/en/docs/Guides/Client SDKs/csharp.md
  test/sdk/csharp/Program.cs
Labels: kind/feature, size/M, size/L, size/S, size/XL

#3734 Feat/counter and list defaulting order to ascending
  install/helm/agones/templates/crds/fleet.yaml
  install/yaml/install.yaml
  pkg/apis/agones/v1/common.go
  pkg/apis/allocation/v1/gameserverallocation.go
  pkg/apis/allocation/v1/gameserverallocation_test.go
  site/content/en/docs/Reference/agones_crd_api_reference.html
Labels: kind/feature, size/M, size/L, size/XS, size/S

#3745 CI: Don't check Unreal Link
  site/content/en/docs/Guides/Client SDKs/unreal.md
  site/content/en/docs/Prerequisite Knowledge/_index.md
Labels: kind/cleanup, size/S

#3744 New recommendation for multi-cluster allocation
  site/content/en/docs/Advanced/multi-cluster-allocation.md
Labels: kind/documentation, size/S

#3739 Add handling for StatusAddresses in GameServerStatus for the Unity SDK
  sdks/unity/model/GameServerStatus.cs
  sdks/unity/model/StatusAddresses.cs
  sdks/unity/model/StatusAddresses.cs.meta
Labels: kind/feature, size/M

#3725 Custom Controller Example Page on Agones Website
  examples/custom-controller/README.md
  site/content/en/docs/Examples/custom-controller.md
Labels: size/M, size/S, kind/other

#3753 Add Nitrado logo
  site/content/en/_index.html
  site/static/images/nitrado.svg
Labels: kind/documentation, size/XS, size/S

#3754 Remove unnecessary args from e2e-test-cloudbuild
  ci/e2e-test-cloudbuild.yaml
Labels: size/XS, kind/other

#3750 Deflake GameServerAllocationDuringMultipleAllocationClients by allowing errors
  test/e2e/gameserverallocation_test.go
Labels: size/S, kind/other

#3761 Update Allocation from Fleet Documentation
  site/content/en/docs/Integration Patterns/allocation-from-fleet.md
Labels: size/XS, kind/other

#3760 Update Canary Testing Documentation
  site/content/en/docs/Integration Patterns/canary-testing.md
Labels: size/XS, size/S, kind/other

#3728 Supertuxkart Example on Agones Site
  examples/supertuxkart/README.md
  site/content/en/docs/Examples/supertuxkart.md
  site/static/images/supertuxkart-AI-players.png
  site/static/images/supertuxkart-enter-ip-port.png
  site/static/images/supertuxkart-race-start.png
Labels: size/M, size/S, kind/other

#3742 Xonotic Example on Agones Site
  examples/xonotic/README.md
  site/content/en/docs/Examples/xonotic.md
  site/static/images/xonotic-front-page.png
  site/static/images/xonotic-ip-port.png
  site/static/images/xonotic-join-game.png
Labels: size/M, size/S, kind/other

#3770 nit documentation fix in kind cluster section when building Agones
  build/README.md
Labels: kind/documentation, size/XS

#3768 Merged steps inside documentation about webhook certificate creation
  examples/webhookfleetautoscalertls.yaml
  site/content/en/docs/Getting Started/create-webhook-fleetautoscaler.md
Labels: kind/documentation, size/S

#3764 Feat(gameservers): Shared pod IPs with GameServer Addresses
  pkg/apis/agones/v1/gameserver.go
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  pkg/gameservers/gameservers.go
  pkg/gameservers/gameservers_test.go
  site/content/en/docs/Reference/gameserver.md
  test/e2e/gameserver_test.go
Labels: kind/feature, size/S

#3781 Optimise GameServer Sub-Controller Queues
  pkg/gameservers/gameservers.go
  pkg/gameservers/health.go
  pkg/gameservers/migration.go
  pkg/gameservers/migration_test.go
  pkg/gameservers/missing.go
  pkg/gameservers/missing_test.go
Labels: kind/bug, area/performance, area/operations, size/M

#3738 Counters and Lists: Remove Bool Returns
  build/Makefile
  build/scripts/bump-image/main.go
  examples/crd-client/create-gs.yaml
  examples/fleet.yaml
  examples/gameserver.yaml
  examples/simple-game-server/Makefile
  examples/simple-game-server/dev-gameserver.yaml
  examples/simple-game-server/fleet-distributed.yaml
  examples/simple-game-server/fleet-tcp.yaml
  examples/simple-game-server/fleet.yaml
  examples/simple-game-server/gameserver-passthrough.yaml
  examples/simple-game-server/gameserver-windows.yaml
  examples/simple-game-server/gameserver.yaml
  examples/simple-game-server/main.go
  install/helm/agones/templates/tests/test-runner.yaml
  pkg/util/webhooks/webhooks_test.go
  sdks/go/alpha.go
  sdks/go/alpha_test.go
  site/config.toml
  test/e2e/fleet_test.go
  test/e2e/framework/framework.go
  test/e2e/gameserver_test.go
  test/load/allocation/fleet.yaml
  test/load/allocation/performance-test-fleet-template.yaml
  test/load/allocation/scenario-fleet.yaml
  test/sdk/go/sdk-client-test.go
Labels: size/M, size/S, kind/other

#3796 Example Images: Increment Tags
  build/Makefile
  examples/allocation-endpoint/terraform/variable.tf
  examples/autoscaler-webhook/autoscaler-service-tls.yaml
  examples/autoscaler-webhook/autoscaler-service.yaml
  examples/crd-client/create-gs.yaml
  examples/custom-controller/deployment.yaml
  examples/fleet.yaml
  examples/gameserver.yaml
  examples/simple-game-server/dev-gameserver.yaml
  examples/simple-game-server/fleet-distributed.yaml
  examples/simple-game-server/fleet-tcp.yaml
  examples/simple-game-server/fleet.yaml
  examples/simple-game-server/gameserver-passthrough.yaml
  examples/simple-game-server/gameserver-windows.yaml
  examples/simple-game-server/gameserver.yaml
  examples/supertuxkart/fleet.yaml
  examples/supertuxkart/gameserver.yaml
  examples/xonotic/fleet.yaml
  examples/xonotic/gameserver.yaml
  install/helm/agones/templates/tests/test-runner.yaml
  pkg/util/webhooks/webhooks_test.go
  site/config.toml
  test/e2e/examples_test.go
  test/e2e/fleetautoscaler_test.go
  test/e2e/framework/framework.go
  test/e2e/gameserver_test.go
  test/load/allocation/fleet.yaml
  test/load/allocation/performance-test-fleet-template.yaml
  test/load/allocation/scenario-fleet.yaml
Labels: size/S, kind/other

#3776 Update simple game server example documentation
  site/content/en/docs/Getting Started/edit-first-gameserver-go.md
Labels: kind/documentation, size/S

#3797 Flake: TestFleetUpdates
  test/e2e/fleet_test.go
Labels: kind/cleanup, area/tests, size/S

#3799 Release v1.40.0
  CHANGELOG.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/rust/Cargo.toml
  sdks/unity/package.json
  site/config.toml
  site/content/en/blog/releases/1.39.0.md
  site/content/en/blog/releases/1.40.0.md
  site/content/en/docs/Guides/Client SDKs/csharp.md
  site/content/en/docs/Guides/counters-and-lists.md
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Guides/fleet-updates.md
  site/content/en/docs/Installation/_index.md
  site/content/en/docs/Reference/fleet.md
  site/layouts/partials/navbar.html
Labels: kind/release, size/XL, kind/other

#3800 Prep for Release v1.41.0
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/rust/Cargo.toml
  sdks/unity/package.json
  site/content/en/blog/releases/1.40.0.md
Labels: kind/release, size/S

#3782 Configure Allocator Status Code
  cmd/allocator/main.go
  install/helm/agones/templates/service/allocation.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  pkg/allocation/converters/converter.go
  pkg/allocation/converters/converter_test.go
Labels: size/M, size/S, kind/other

#3769 Update site documentation to reflect firewall prefix and default to Autopilot cluster creation for Agones
  site/content/en/docs/Installation/Creating Cluster/gke.md
  site/layouts/shortcodes/gs-prerequisites.html
Labels: kind/documentation, size/S

#3792 Add a System Diagram and overview page
  build/includes/website.mk
  site/content/en/docs/Advanced/system-diagram.md
  site/static/diagrams/allocation-player-capacity.puml
  site/static/diagrams/allocation-player-capacity.puml.png
  site/static/diagrams/canary-testing.puml
  site/static/diagrams/canary-testing.puml.png
  site/static/diagrams/eviction-decision.dot
  site/static/diagrams/gameserver-lifecycle.puml
  site/static/diagrams/gameserver-lifecycle.puml.png
  site/static/diagrams/gameserver-reserved.puml
  site/static/diagrams/gameserver-reserved.puml.png
  site/static/diagrams/gameserver-states.dot
  site/static/diagrams/gameserver-states.dot.png
  site/static/diagrams/high-density.puml
  site/static/diagrams/high-density.puml.png
  site/static/diagrams/reusing-gameservers.puml
  site/static/diagrams/reusing-gameservers.puml.png
  site/static/diagrams/system-diagram.dot
  site/static/diagrams/system-diagram.dot.png
Labels: size/M, kind/other

#3805 Update Side Menu: Preserve and Restore Scroll Position
  site/layouts/partials/hooks/body-end.html
Labels: size/S, kind/other

#3801 Graduate Counters and Lists to Beta
  build/Makefile
  build/includes/sdk.mk
  cloudbuild.yaml
  install/helm/agones/defaultfeaturegates.yaml
  pkg/gameserversets/controller_test.go
  pkg/util/runtime/features.go
  site/content/en/docs/Guides/feature-stages.md
Labels: kind/feature, size/S
