Repository googleforgames/agones, pull requests merged in 2024-10, with the labels that each got.

#3995 Add 'Trace' to LogLevel in GameServer.Spec.SdkServer
  examples/fleet.yaml
  examples/gameserver.yaml
  install/helm/agones/templates/crds/_gameserverspecschema.yaml
  install/yaml/install.yaml
  pkg/apis/agones/v1/gameserver.go
  site/content/en/docs/Reference/gameserver.md
Labels: kind/cleanup, size/S

#4006 Move Feature GKEAutopilotExtendedDurationPods To Beta
  build/Makefile
  cloudbuild.yaml
  install/helm/agones/defaultfeaturegates.yaml
  pkg/util/runtime/features.go
  site/content/en/docs/Guides/feature-stages.md
Labels: kind/feature, size/S

#4009 Fix the build-e2e error
  build/e2e-image/Dockerfile
Labels: size/XS, kind/other

#4010 Add a flag to sdkserver to avoid a collision on port 8080
  cmd/sdk-server/main.go
  pkg/sdkserver/sdkserver.go
  pkg/sdkserver/sdkserver_test.go
Labels: kind/bug, size/S

#4011 Update the go version upgrade template
  .github/ISSUE_TEMPLATE/golang_version_upgrade.md
Labels: kind/documentation, size/S

#3913 Adds instructions for adding and removing field from a CRD
  README.md
  install/helm/agones/README.md
Labels: kind/documentation, size/S

#4013 Release v1.44.0
  CHANGELOG.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/rust/Cargo.toml
  sdks/unity/package.json
  site/config.toml
  site/content/en/blog/releases/1.43.0.md
  site/content/en/blog/releases/1.44.0.md
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Installation/_index.md
  site/layouts/partials/navbar.html
Labels: kind/release, size/M

#4014 Preparation for Release v1.45.0
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/rust/Cargo.toml
  sdks/unity/package.json
Labels: kind/release, size/S

#4008 Update all Rust SDK dependencies to latest versions
  build/build-sdk-images/rust/Dockerfile
  sdks/rust/Cargo.toml
  sdks/rust/build.rs
Labels: kind/cleanup, size/S

#4016 Allowing list based fleet autoscaler to scale up from 0 replicas
  pkg/fleetautoscalers/fleetautoscalers.go
  pkg/fleetautoscalers/fleetautoscalers_test.go
  pkg/gameserversets/controller.go
  pkg/gameserversets/controller_test.go
  test/e2e/fleet_test.go
  test/e2e/fleetautoscaler_test.go
Labels: kind/bug, size/M
