Repository googleforgames/agones, pull requests merged in 2024-01, with the labels that each got.

#3562 fix: typo
  site/content/en/docs/Advanced/allocator-service.md
Labels: kind/documentation, size/XS

#3565 Docs: Link to SDK Service Account
  site/content/en/docs/Advanced/service-accounts.md
Labels: kind/documentation, kind/cleanup, size/XS

#3561 Add Feature Template for Issues Created from Agones Website
  site/layouts/partials/page-meta-links.html
Labels: kind/feature, kind/documentation, size/XS, size/S, kind/other

#3568 Docs: gomod go 1.21
  site/go.mod
Labels: kind/cleanup, size/XS

#3566 ci/cache project root cloudbuild.yaml fix
  build/build-image/cache/cloudbuild.yaml
Labels: kind/bug, size/S

#3567 Upgrade Docker to 24.0.6
  build/Makefile
  cloudbuild.yaml
Labels: kind/cleanup, size/XS, size/S

#3571 Upgrade from Debian Bullseye to Bookworm for Rust
  examples/rust-simple/Dockerfile
  examples/rust-simple/Makefile
Labels: kind/cleanup, size/XS

#3577 Update /cmd: Switch from debian11 to debian12
  cmd/allocator/Dockerfile
  cmd/controller/Dockerfile
  cmd/extensions/Dockerfile
  cmd/ping/Dockerfile
  cmd/sdk-server/Dockerfile
Labels: size/S, kind/other

#3572 Upgrade from Debian Bullseye to Bookworm for NodeJS
  examples/nodejs-simple/Dockerfile
  examples/nodejs-simple/Makefile
  examples/nodejs-simple/gameserver.yaml
Labels: kind/cleanup, size/XS

#3575 Update autoscaler-webhook: Switch from debian11 to debian12
  examples/autoscaler-webhook/Dockerfile
  examples/autoscaler-webhook/Makefile
  examples/autoscaler-webhook/autoscaler-service-tls.yaml
  examples/autoscaler-webhook/autoscaler-service.yaml
  examples/autoscaler-webhook/go.mod
  examples/autoscaler-webhook/go.sum
Labels: kind/cleanup, size/S

#3585 Fix Lint Warning
  .github/workflows/labeler.yml
  build/build-image/cache/cloudbuild.yaml
  examples/nodejs-simple/gameserver.yaml
  examples/xonotic/gameserver.yaml
Labels: kind/cleanup, size/S

#3576 Update simple-game-server: Switch from debian11 to debian12
  examples/simple-game-server/Dockerfile
  examples/simple-game-server/Makefile
  examples/simple-game-server/dev-gameserver.yaml
  examples/simple-game-server/fleet-distributed.yaml
  examples/simple-game-server/fleet-tcp.yaml
  examples/simple-game-server/fleet.yaml
  examples/simple-game-server/gameserver-passthrough.yaml
  examples/simple-game-server/gameserver-windows.yaml
  examples/simple-game-server/gameserver.yaml
  examples/simple-game-server/go.mod
  examples/simple-game-server/go.sum
Labels: kind/cleanup, size/S

#3588 Bump simple-game-server to 0.24
  build/Makefile
  examples/crd-client/create-gs.yaml
  examples/fleet.yaml
  examples/gameserver.yaml
  install/helm/agones/templates/tests/test-runner.yaml
  pkg/util/webhooks/webhooks_test.go
  site/config.toml
  site/content/en/docs/Guides/fleet-updates.md
  test/e2e/framework/framework.go
  test/e2e/gameserver_test.go
  test/load/allocation/fleet.yaml
  test/load/allocation/performance-test-fleet-template.yaml
  test/load/allocation/scenario-fleet.yaml
Labels: size/S, kind/other

#3587 Bump Example Images: Rust, Crd-client, NodeJS, Autoscaler-webhook
  examples/nodejs-simple/README.md
  examples/rust-simple/README.md
  examples/rust-simple/gameserver.yaml
  install/helm/agones/templates/tests/test-runner.yaml
  test/e2e/examples_test.go
  test/e2e/fleetautoscaler_test.go
Labels: kind/cleanup, size/S

#3592 Use Docker 24.0.6 for performanace test
  ci/perf-test-cloudbuild.yaml
Labels: kind/hotfix, size/XS

#3489 controller refresh certificate
  cmd/extensions/main.go
  pkg/util/https/server.go
Labels: kind/feature, size/M, do-not-merge/work-in-progress, size/S

#3596 GKEAutopilotExtendedDurationPods: Fix embarassing typo preventing use
  install/helm/agones/defaultfeaturegates.yaml
Labels: size/XS, kind/other

#3595 Update Site Go Version
  site/app.yaml
Labels: kind/cleanup, size/XS

#3560 Docs: Lifecycle Management of Counters and Lists in REST
  site/content/en/docs/Guides/Client SDKs/local.md
  site/content/en/docs/Guides/Client SDKs/rest.md
Labels: kind/documentation, size/M, size/S

#3598 Local SDK: Refactor List and Count keys for default GameServer
  pkg/sdkserver/localsdk.go
  test/sdk/go/sdk-client-test.go
  test/sdk/restapi/http-api-test.go
Labels: kind/cleanup, size/S

#3583 Docs: Game Server Allocation Details
  site/content/en/docs/Reference/gameserverallocation.md
Labels: kind/documentation, size/XS

#3605 Prevent Int64 Overflow
  pkg/apis/agones/v1/common.go
  pkg/fleets/controller.go
  pkg/fleets/controller_test.go
  pkg/gameserversets/controller.go
  pkg/gameserversets/controller_test.go
Labels: kind/bug, size/S

#3569 Counts and Lists: Improvements to SDK docs
  site/content/en/docs/Guides/Client SDKs/_index.md
Labels: kind/documentation, size/S

#3602 Upgrade Golang Version to 1.21.6
  build/build-image/Dockerfile
  build/build-sdk-images/go/Dockerfile
  build/build-sdk-images/restapi/Dockerfile
  build/e2e-image/Dockerfile
  build/report/cloudbuild.yaml
  build/scripts/k8s-export-openapi/go.mod
  build/scripts/previousversion/go.mod
  examples/allocation-endpoint/client/go.mod
  examples/allocation-endpoint/client/go.sum
  examples/allocation-endpoint/server/go.mod
  examples/allocation-endpoint/server/go.sum
  examples/autoscaler-webhook/Dockerfile
  examples/autoscaler-webhook/Makefile
  examples/autoscaler-webhook/autoscaler-service-tls.yaml
  examples/autoscaler-webhook/autoscaler-service.yaml
  examples/autoscaler-webhook/go.mod
  examples/autoscaler-webhook/go.sum
  examples/crd-client/Dockerfile
  examples/crd-client/Makefile
  examples/crd-client/create-gs.yaml
  examples/crd-client/go.mod
  examples/crd-client/go.sum
  examples/simple-game-server/Dockerfile
  examples/simple-game-server/Dockerfile.windows
  examples/simple-game-server/Makefile
  examples/simple-game-server/dev-gameserver.yaml
  examples/simple-game-server/fleet-distributed.yaml
  examples/simple-game-server/fleet-tcp.yaml
  examples/simple-game-server/fleet.yaml
  examples/simple-game-server/gameserver-passthrough.yaml
  examples/simple-game-server/gameserver-windows.yaml
  examples/simple-game-server/gameserver.yaml
  examples/simple-game-server/go.mod
  examples/simple-game-server/go.sum
  examples/supertuxkart/Dockerfile
  examples/supertuxkart/Makefile
  examples/supertuxkart/fleet.yaml
  examples/supertuxkart/gameserver.yaml
  examples/supertuxkart/go.mod
  examples/supertuxkart/go.sum
  examples/xonotic/Dockerfile
  examples/xonotic/Dockerfile.windows
  examples/xonotic/Makefile
  examples/xonotic/fleet.yaml
  examples/xonotic/gameserver.yaml
  examples/xonotic/go.mod
  examples/xonotic/go.sum
  go.mod
  go.sum
Labels: kind/cleanup, size/M, size/S

#3584 Kubernetes Config Update: Prioritize InClusterConfig function
  cmd/controller/main.go
  cmd/extensions/main.go
  cmd/sdk-server/main.go
  pkg/fleets/controller_test.go
  pkg/util/runtime/runtime.go
  test/e2e/framework/framework.go
  test/eviction/evictpod.go
Labels: kind/feature, size/M, size/S

#3612 Nodepool upgrades on GKE Terraform apply
  install/terraform/modules/gke/cluster.tf
Labels: kind/bug, kind/breaking, area/operations, size/M

#3613 Example Images with Updated Tags
  build/Makefile
  examples/autoscaler-webhook/go.mod
  examples/autoscaler-webhook/go.sum
  examples/crd-client/create-gs.yaml
  examples/fleet.yaml
  examples/gameserver.yaml
  install/helm/agones/templates/tests/test-runner.yaml
  pkg/util/webhooks/webhooks_test.go
  site/config.toml
  site/content/en/docs/Guides/fleet-updates.md
  test/e2e/examples_test.go
  test/e2e/fleetautoscaler_test.go
  test/e2e/framework/framework.go
  test/e2e/gameserver_test.go
  test/load/allocation/fleet.yaml
  test/load/allocation/performance-test-fleet-template.yaml
  test/load/allocation/scenario-fleet.yaml
Labels: kind/cleanup, size/S

#3606 SDK server not clearing lists on update
  pkg/sdkserver/sdkserver.go
  pkg/sdkserver/sdkserver_test.go
Labels: kind/bug, size/M, size/XS

#3591 Support topologySpreadConstraints
  install/helm/agones/templates/controller.yaml
  install/helm/agones/templates/extensions-deployment.yaml
  install/helm/agones/templates/ping.yaml
  install/helm/agones/templates/service/allocation.yaml
  install/helm/agones/values.yaml
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: size/M, size/S, kind/other

#3619 Release v1.38.0
  CHANGELOG.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/rust/Cargo.toml
  sdks/unity/package.json
  site/config.toml
  site/content/en/blog/releases/1.37.0.md
  site/content/en/blog/releases/1.38.0.md
  site/content/en/docs/Installation/Install Agones/helm.md
  site/content/en/docs/Installation/_index.md
  site/layouts/partials/navbar.html
Labels: kind/release, size/M

#3620 Prep for release v1.39.0
  build/Makefile
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/rust/Cargo.toml
  sdks/unity/package.json
  site/content/en/blog/releases/1.38.0.md
Labels: kind/release, size/S
