Repository googleforgames/agones, pull requests merged in 2024-08, with the labels that each got.

#3923 Rewrite agones-bot, commit to Agones repo
  CONTRIBUTING.md
  build/agones-bot/Dockerfile
  build/agones-bot/Makefile
  build/agones-bot/README.md
  build/agones-bot/agones-bot-pr-commenter.yaml
  build/agones-bot/cloudbuild.yaml
  build/agones-bot/go.mod
  build/agones-bot/go.sum
  build/agones-bot/main.go
Labels: size/XL, kind/other

#3929 feat: Adds autoscaling logic for new Chain and Schedule policies
  pkg/apis/autoscaling/v1/fleetautoscaler.go
  pkg/apis/autoscaling/v1/fleetautoscaler_test.go
  pkg/fleetautoscalers/controller.go
  pkg/fleetautoscalers/fleetautoscalers.go
  pkg/fleetautoscalers/fleetautoscalers_test.go
Labels: kind/feature, size/M, size/L

#3944 Small cleanup of incorrect comment in features.go file
  pkg/util/runtime/features.go
Labels: kind/cleanup, size/XS

#3959 remove ctx within the condition func
  test/e2e/allocator/pod_termination_test.go
Labels: size/S, kind/other

#3956 Adds basic framework for the in place Agones upgrades test controller
  test/upgrade/Dockerfile
  test/upgrade/Makefile
  test/upgrade/go.mod
  test/upgrade/go.sum
  test/upgrade/main.go
  test/upgrade/permissions.yaml
  test/upgrade/upgradeTest.yaml
  test/upgrade/versionMap.yaml
Labels: kind/feature, size/L

#3927 [Performance] - Added a new metric inside the allocator to track the success retry rate inside the retry loop
  pkg/gameserverallocations/allocator.go
  pkg/gameserverallocations/metrics.go
  pkg/gameserversets/controller.go
  pkg/gameserversets/metrics.go
  pkg/metrics/controller.go
  pkg/metrics/kubernetes_client.go
  pkg/metrics/util.go
  site/content/en/docs/Guides/metrics.md
Labels: kind/feature, size/M, size/S

#3962 change kubernetes API version to fix broken CI
  site/content/en/docs/Reference/gameserver.md
  site/content/en/docs/Reference/gameserverallocation.md
Labels: size/XS, kind/other

#3938 docs(godot): add Agones x Godot third party example
  site/content/en/docs/Third Party Content/examples.md
Labels: kind/documentation, size/XS

#3937 Link Unity Netcode for Gameobjects example in documentation
  site/content/en/docs/Third Party Content/examples.md
Labels: size/XS, kind/other

#3963 Docs: Use k8s-api-version for links
  site/content/en/docs/Reference/gameserver.md
  site/content/en/docs/Reference/gameserverallocation.md
Labels: kind/cleanup, size/XS

#3950 Make the parameters that limits the number of GameServers to add configurable
  cmd/controller/main.go
  install/helm/agones/templates/controller.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  pkg/gameserversets/controller.go
  pkg/gameserversets/controller_test.go
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: kind/feature, size/M, size/L

#3946 feat: Adds e2e tests for chain/schedule policy and bump ScheduledAutoscaler to Alpha
  build/Makefile
  cloudbuild.yaml
  install/helm/agones/defaultfeaturegates.yaml
  pkg/fleetautoscalers/fleetautoscalers_test.go
  pkg/util/runtime/features.go
  site/content/en/docs/Guides/feature-stages.md
  test/e2e/fleetautoscaler_test.go
Labels: kind/feature, size/M, size/L, size/XL, kind/other

#3883 Implement CountsAndLists for Unity SDK + Tests
  sdks/unity/AgonesBetaSdk.cs
  sdks/unity/AgonesBetaSdk.cs.meta
  sdks/unity/AgonesSdk.cs
  sdks/unity/Tests/Runtime/PlayMode/AgonesSdkIntegrationTests.cs
  sdks/unity/Tests/Runtime/PlayMode/AgonesSdkIntegrationTests.cs.meta
  test/sdk/unity/Packages/manifest.json
  test/sdk/unity/Packages/packages-lock.json
  test/sdk/unity/README.md
Labels: kind/feature, size/L, size/XL

#3971 update cpp-simple example tag to 0.18
  examples/cpp-simple/fleet.yaml
  examples/cpp-simple/gameserver.yaml
Labels: kind/cleanup, size/XS

#3972 Release v1.43.0
  CHANGELOG.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/rust/Cargo.toml
  sdks/unity/package.json
  site/config.toml
  site/content/en/blog/releases/1.42.0.md
  site/content/en/blog/releases/1.43.0.md
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Guides/metrics.md
  site/content/en/docs/Installation/Install Agones/helm.md
  site/content/en/docs/Installation/_index.md
  site/layouts/partials/navbar.html
Labels: kind/release, size/M

#3974 Update the note at the top of the player tracking docs
  site/content/en/docs/Guides/player-tracking.md
Labels: kind/cleanup, size/XS
