Repository googleforgames/agones, pull requests merged in 2025-09, with the labels that each got.

#4251 e2e: add webhook autoscaler test with fleet metadata
  examples/autoscaler-webhook/Makefile
  examples/autoscaler-webhook/autoscaler-service-tls.yaml
  examples/autoscaler-webhook/autoscaler-service.yaml
  examples/autoscaler-webhook/main.go
  test/e2e/fleetautoscaler_test.go
Labels: kind/cleanup, size/M

#4252 Updates the upgrade test to print any fatal error messages to the job pod termination log
  build/e2e_upgrade_test.sh
  cloudbuild.yaml
  test/upgrade/go.mod
  test/upgrade/go.sum
  test/upgrade/main.go
  test/upgrade/upgradeTest.yaml
Labels: kind/cleanup, size/M

#4268 Replace bitname/kubectl with alpine/kubectl
  install/helm/agones/templates/hooks/pre_delete_hook.yaml
Labels: kind/cleanup, size/XS

#4269 flaky: TestControllerAllocator
  pkg/gameserverallocations/controller_test.go
Labels: kind/cleanup, size/S

#4273 Preparation for Release v1.53.0
  build/Makefile
  cloudbuild.yaml
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/rust/Cargo.toml
  sdks/unity/package.json
  test/sdk/go/Makefile
  test/upgrade/Makefile
Labels: kind/release, size/M

#4247 Feat: implement rust sdk (counter and list)
  build/build-sdk-images/rust/test.sh
  sdks/rust/build.rs
  sdks/rust/src/alpha.rs
  sdks/rust/src/beta.rs
  sdks/rust/src/lib.rs
  sdks/rust/src/sdk.rs
  site/content/en/docs/Guides/Client SDKs/rust.md
  test/sdk/rust/src/main.rs
Labels: kind/feature, size/L

#4278 Prepend sidecars to existing init containers
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/agones/v1/gameserver_test.go
Labels: kind/bug, size/S

#4277 Fleet autoscaler threads maintain state
  pkg/fleetautoscalers/controller.go
  pkg/fleetautoscalers/controller_test.go
  pkg/fleetautoscalers/fleetautoscalers.go
  pkg/fleetautoscalers/fleetautoscalers_test.go
Labels: kind/feature, size/M, size/S

#4270 fix: broken websocket connection after upgrading github.com/grpc-ecosystem/grpc-gateway/v2
  build/includes/sdk.mk
  cmd/sdk-server/main.go
  go.mod
  go.sum
  vendor/github.com/tmc/grpc-websocket-proxy/wsproxy/websocket_proxy.go
  vendor/modules.txt
Labels: kind/bug, size/XS, size/S, kind/other

#4288 Fix: update link to quilkin
  site/content/en/docs/Advanced/system-diagram.md
  site/content/en/docs/Third Party Content/examples.md
Labels: kind/bug, size/XS
