Repository googleforgames/agones, pull requests merged in 2025-07, with the labels that each got.

#4221 Feat: Add dev feature flag for Processor Allocator
  install/helm/agones/defaultfeaturegates.yaml
  pkg/util/runtime/features.go
Labels: kind/feature, size/XS

#4165 Add logs reporting to submit-upgrade-test-cloud-build for better visibility
  build/e2e_upgrade_test.sh
  cloudbuild.yaml
Labels: kind/cleanup, size/M, size/S

#4226 feat: promote ScheduledAutoscaler to beta
  build/Makefile
  cloudbuild.yaml
  install/helm/agones/defaultfeaturegates.yaml
  install/yaml/install.yaml
  pkg/apis/autoscaling/v1/fleetautoscaler.go
  pkg/util/runtime/features.go
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Reference/agones_crd_api_reference.html
  test/upgrade/versionMap.yaml
Labels: kind/feature, size/M, size/S

#4216 Adds support for lists in the Unreal SDK #4029
  sdks/unreal/Agones/Source/Agones/Classes/Classes.h
  sdks/unreal/Agones/Source/Agones/Private/AgonesComponent.cpp
  sdks/unreal/Agones/Source/Agones/Public/AgonesComponent.h
  site/content/en/docs/Guides/Client SDKs/unreal.md
Labels: kind/feature, size/M

#4228 Remove former agones collaborator from github action
  .github/workflows/update_dependencies.yaml
Labels: kind/bug, size/XS

#4234 Preparation for Release v1.52.0
  build/Makefile
  cloudbuild.yaml
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/rust/Cargo.toml
  sdks/unity/package.json
  test/sdk/go/Makefile
  test/upgrade/Makefile
  test/upgrade/versionMap.yaml
Labels: kind/release, size/M
