Repository googleforgames/agones, pull requests merged in 2025-01, with the labels that each got.

#4078 Unblocks Agones release PR by waiting for either the Agones dev version or release version
  site/content/en/docs/Guides/Client SDKs/rest.md
  test/upgrade/main.go
Labels: kind/hotfix, size/XS, size/S

#4077 Release v1.46.0
  CHANGELOG.md
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/rust/Cargo.toml
  sdks/unity/package.json
  site/config.toml
  site/content/en/blog/releases/1.45.0.md
  site/content/en/blog/releases/1.46.0.md
  site/content/en/docs/Installation/Install Agones/helm.md
  site/content/en/docs/Installation/_index.md
  site/content/en/docs/Installation/upgrading.md
  site/layouts/partials/navbar.html
Labels: kind/release, size/M

#4082 Update `.golangci.yml` config to resolve deprecation warnings
  .golangci.yml
  pkg/allocation/converters/converter.go
  pkg/allocation/converters/converter_test.go
  pkg/gameserverallocations/allocation_cache_test.go
  pkg/sdkserver/localsdk.go
  pkg/sdkserver/localsdk_test.go
  test/e2e/fleet_test.go
  test/e2e/gameserverallocation_test.go
Labels: size/S, kind/other

#4086 Docs: Update Player Tracking to use Lists
  build/includes/website.mk
  site/content/en/docs/Integration Patterns/player-capacity.md
  site/static/diagrams/allocation-player-capacity-list.puml
  site/static/diagrams/allocation-player-capacity-list.puml.png
  site/static/diagrams/allocation-player-capacity-tracking.puml
  site/static/diagrams/allocation-player-capacity-tracking.puml.png
Labels: kind/feature, kind/documentation, size/M

#4085 Docs: Counters with High Density
  build/includes/website.mk
  site/content/en/docs/Integration Patterns/high-density-gameservers.md
  site/static/diagrams/high-density-counters.puml
  site/static/diagrams/high-density-counters.puml.png
  site/static/diagrams/high-density-label-lock.puml
  site/static/diagrams/high-density-label-lock.puml.png
Labels: kind/feature, kind/documentation, size/M

#4083 Add ability to change externalTrafficPolicy for agones-ping services (http&udp)
  install/helm/agones/templates/ping.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  site/content/en/docs/Installation/Install Agones/helm.md
Labels: kind/feature, size/S

#4084 Initialise FCounterResponse members
  sdks/unreal/Agones/Source/Agones/Classes/Classes.h
Labels: kind/cleanup, size/XS

#4096 Changes upgrade game server template to use safe-to-evict: Always
  test/upgrade/gameserverTemplate.yaml
Labels: kind/bug, size/XS

#4091 Added OKE steps in K8S version upgrade template
  .github/ISSUE_TEMPLATE/kubernetes_update.md
Labels: kind/documentation, size/XS
