Repository googleforgames/agones, pull requests merged in 2025-04, with the labels that each got.

#4061 Add AFP features and update documentation
  .github/ISSUE_TEMPLATE/feature_request.md
  .yamllint
  docs/proposals/NNNN-afp-template/README.md
  docs/proposals/NNNN-afp-template/afp.yaml
  docs/proposals/README.md
  site/content/en/docs/Contribute/_index.md
  site/content/en/docs/Contribute/agones-feature-proposal.md
  site/content/en/docs/Contribute/documentation-editing-contribution.md
  site/htmltest.yaml
Labels: kind/feature, kind/documentation, kind/breaking, size/XL

#4139 Updated doc for adding support of Extended Duration Pods on GKE Autopilot
  site/content/en/docs/Advanced/controlling-disruption.md
Labels: kind/documentation

#4143 Various e2e test improvements
  test/e2e/allocator_test.go
  test/e2e/examples_test.go
  test/e2e/framework/framework.go
  test/e2e/gameserver_test.go
Labels: kind/cleanup, area/tests

#4144 Promote PortPolicyNone to Beta
  build/Makefile
  cloudbuild.yaml
  install/helm/agones/defaultfeaturegates.yaml
  pkg/util/runtime/features.go
  site/content/en/docs/Guides/feature-stages.md
Labels: kind/feature

#4147 Promote PortRanges to Beta
  build/Makefile
  cloudbuild.yaml
  install/helm/agones/defaultfeaturegates.yaml
  pkg/util/runtime/features.go
  site/content/en/docs/Guides/feature-stages.md
Labels: kind/feature

#4149 load test client make concurrent requests
  test/load/allocation/allocationload/allocationload.go
Labels: kind/other

#4148 Adds permissions in the agones-system namespace for the upgrade tests
  test/upgrade/permissions.yaml
Labels: kind/cleanup

#4152 Fix CRD API docs generation script
  build/build-image/Dockerfile
  site/content/en/docs/Reference/agones_crd_api_reference.html
  site/gen-api-docs.sh
Labels: kind/bug, kind/cleanup

#4098 fix: ensure fleet autoscaler policy are namespaced
  pkg/fleetautoscalers/controller.go
  pkg/fleetautoscalers/fleetautoscalers.go
  pkg/fleetautoscalers/fleetautoscalers_test.go
  pkg/fleets/controller.go
  pkg/fleets/controller_test.go
  pkg/fleets/fleets.go
  pkg/fleets/fleets_test.go
  pkg/metrics/controller.go
  test/e2e/fleetautoscaler_test.go
Labels: kind/bug, size/M

#4161 Adds explicit permissions for github workflows
  .github/workflows/labeler.yml
  .github/workflows/pr_update.yml
Labels: kind/hotfix

#4164 chore: update Nitrado GameFabric branding
  site/content/en/_index.html
  site/static/images/gamefabric-nitrado.png
  site/static/images/nitrado.svg
Labels: kind/documentation

#4155 Adds instructions to update dependencies as part of upgrading Golang
  .github/ISSUE_TEMPLATE/golang_version_upgrade.md
  .github/workflows/update_dependencies.yaml
Labels: kind/cleanup

#4156 Fix feature stages page to show expected content
  examples/gameserver.yaml
  examples/simple-game-server/gameserver-none.yaml
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Reference/gameserver.md
  test/upgrade/versionMap.yaml
Labels: kind/bug, area/site

#4168 Fix: Remove Kubernetes 1.29 from Agones 1.39.0 compatibility matrix
  site/content/en/docs/Installation/_index.md
Labels: kind/cleanup

#4159 Allocation: Re-cache allocated `GameServer`
  pkg/gameserverallocations/allocator.go
  pkg/gameserverallocations/allocator_test.go
  pkg/gameserverallocations/cache.go
  pkg/gameserverallocations/cache_test.go
Labels: kind/bug, area/performance

#4146 Adoption of Sidecar Containers
  build/Makefile
  cloudbuild.yaml
  cmd/sdk-server/main.go
  install/helm/agones/defaultfeaturegates.yaml
  pkg/apis/agones/v1/gameserver.go
  pkg/apis/agones/v1/gameserver_test.go
  pkg/gameservers/controller.go
  pkg/gameservers/controller_test.go
  pkg/gameservers/health.go
  pkg/gameservers/health_test.go
  pkg/util/runtime/features.go
  test/e2e/gameserver_test.go
Labels: kind/breaking
