Repository googleforgames/agones, pull requests merged in 2025-06, with the labels that each got.

#4195 Updated goimports formatting
  pkg/fleetautoscalers/controller_test.go
  pkg/fleetautoscalers/fleetautoscalers_test.go
  pkg/metrics/util_test.go
Labels: kind/cleanup, size/S

#4196 Specify exit code in simple-game-server CRASH
  examples/simple-game-server/Makefile
  examples/simple-game-server/handlers.go
Labels: kind/feature, area/examples, size/S

#4205 Promote FeatureRollingUpdateFix to Beta
  build/Makefile
  cloudbuild.yaml
  install/helm/agones/defaultfeaturegates.yaml
  pkg/fleets/controller_test.go
  pkg/util/runtime/features.go
  site/content/en/docs/Guides/feature-stages.md
  test/upgrade/versionMap.yaml
Labels: kind/feature, size/S

#4208 Release v1.50.0
  CHANGELOG.md
  build/build-image/Dockerfile
  build/includes/website.mk
  install/helm/agones/Chart.yaml
  install/helm/agones/values.yaml
  install/yaml/install.yaml
  sdks/csharp/sdk/AgonesSDK.nuspec
  sdks/csharp/sdk/csharp-sdk.csproj
  sdks/nodejs/package-lock.json
  sdks/nodejs/package.json
  sdks/rust/Cargo.toml
  sdks/unity/package.json
  site/config.toml
  site/content/en/blog/releases/1.49.0.md
  site/content/en/blog/releases/1.50.0.md
  site/content/en/docs/Guides/feature-stages.md
  site/content/en/docs/Installation/_index.md
  site/layouts/partials/navbar.html
Labels: kind/release, size/M

#4201 Controller for Pod in Succeeded state.
  pkg/gameservers/controller.go
  pkg/gameservers/succeeded.go
  pkg/gameservers/succeeded_test.go
  test/e2e/gameserver_test.go
Labels: kind/bug, size/M, size/L
